/* OCEANUM — Corpo integrado: peso, altura e exame de bioimpedância completo; alongamentos (com fotos e rotina guiada);
   e a ligação entre treino, dieta e corrida (gasto do exercício, meta do dia ajustada, recomendações e visão do corpo). */
(() => {
'use strict';
const U = OS.U, UI = OS.UI, esc = U.esc, A = OS.act, S = OS.S, C = OS.C, L = OS.L, V = OS.views;
const F = (k, l, t = 'text', x = {}) => Object.assign({ k, l, t }, x);
const n = v => U.num(v) || 0;
const BX = OS.BodyX = {};

/* ================= medições e bioimpedância ================= */
const H = (k, t) => F(k, '', 'custom', { wide: 1, render: () => `<div class="fsec">${t}</div>` });
const N = (k, l, unit, h) => F(k, l, 'num', { unit, h });
S.body = { label: 'Medição / bioimpedância', title: r => U.fmtD(r.date) + (r.bio ? ' · bioimpedância' : ''), fields: [
  F('date', 'Data', 'date', { req: 1 }), F('weight', 'Peso', 'num', { unit: 'kg', req: 1 }), F('bio', 'Exame de bioimpedância completo', 'bool', { re: 1 }),
  H('h1', 'Composição corporal'), F('bf', 'Gordura corporal', 'pct'), N('fatKg', 'Massa gorda', 'kg'), N('muscleKg', 'Massa muscular esquelética', 'kg', 'SMM na InBody'), N('leanKg', 'Massa magra (sem gordura)', 'kg', 'FFM / LBM'),
  F('water', 'Água corporal', 'pct'), N('waterL', 'Água corporal total', 'L'), F('protein', 'Proteína', 'pct'), N('bone', 'Massa óssea / minerais', 'kg'),
  N('visceral', 'Gordura visceral', 'nível', '1–59 (InBody: área em nível)'), F('subq', 'Gordura subcutânea', 'pct'), N('bmr', 'Metabolismo basal', 'kcal'), N('metAge', 'Idade metabólica', 'anos'),
  ...[['h2', 'Análise segmentar · massa magra (kg)', 'l'], ['h3', 'Análise segmentar · gordura (%)', 'g']].flatMap(([h, t, p]) => [Object.assign(H(h, t), { show: r => r.bio }), ...[['ArmL', 'Braço esquerdo'], ['ArmR', 'Braço direito'], ['Trunk', 'Tronco'], ['LegL', 'Perna esquerda'], ['LegR', 'Perna direita']].map(([k, l]) => Object.assign(N(p + k, l, p === 'l' ? 'kg' : '%'), { show: r => r.bio }))]),
  Object.assign(H('h4', 'Avançado'), { show: r => r.bio }), Object.assign(N('ecw', 'Rácio água extracelular (ECW/TBW)', '', 'normal 0,360–0,390'), { show: r => r.bio }), Object.assign(N('phase', 'Ângulo de fase', '°'), { show: r => r.bio }), Object.assign(N('score', 'Pontuação do aparelho', 'pts'), { show: r => r.bio }), Object.assign(F('device', 'Aparelho / local'), { show: r => r.bio }),
  H('h5', 'Perímetros (fita métrica)'), N('neck', 'Pescoço', 'cm'), N('chest', 'Peito', 'cm'), N('waist', 'Cintura', 'cm'), N('abdomen', 'Abdómen (umbigo)', 'cm'), N('hip', 'Anca', 'cm'), N('armLc', 'Braço esq. (contraído)', 'cm'), N('armRc', 'Braço dir. (contraído)', 'cm'), N('thighL', 'Coxa esquerda', 'cm'), N('thighR', 'Coxa direita', 'cm'), N('calf', 'Gémeo', 'cm'),
  F('notes', 'Notas', 'area', { rows: 2 })
], defaults: () => ({ date: U.today() }) };
const B = () => U.sortBy(OS.all('body'), b => b.date);
const lastW = () => { const b = B().filter(x => n(x.weight)); return b.length ? n(b[b.length - 1].weight) : 0; };
const lastBio = () => B().filter(x => x.bio || n(x.bf) || n(x.muscleKg)).pop();
BX.height = () => n(OS.one('diet').h);
BX.weight = lastW;
BX.lean = () => { const b = lastBio(); if (!b) return 0; return n(b.leanKg) || (n(b.weight) && n(b.bf) ? n(b.weight) * (1 - n(b.bf) / 100) : 0); };
BX.bmrMeasured = () => { const b = B().filter(x => n(x.bmr)).pop(); return b && U.diff(U.today(), b.date) <= 120 ? n(b.bmr) : 0; };
const sex = () => OS.one('diet').sex === 'F' ? 'F' : 'M';
// faixas de referência [limites, rótulos/tons]
const RANGES = {
  bmi: { l: 'IMC', u: '', min: 15, max: 40, cuts: [18.5, 25, 30], names: ['Abaixo', 'Normal', 'Excesso de peso', 'Obesidade'], tones: ['warn', 'pos', 'warn', 'neg'] },
  bf: { l: 'Gordura corporal', u: '%', min: 3, max: 45, cuts: () => sex() === 'F' ? [14, 21, 25, 32] : [6, 14, 18, 25], names: ['Essencial', 'Atleta', 'Em forma', 'Média', 'Elevada'], tones: ['warn', 'pos', 'pos', '', 'neg'] },
  water: { l: 'Água corporal', u: '%', min: 35, max: 75, cuts: () => sex() === 'F' ? [45, 60] : [50, 65], names: ['Baixa', 'Normal', 'Alta'], tones: ['warn', 'pos', ''] },
  visceral: { l: 'Gordura visceral', u: '', min: 1, max: 20, cuts: [10, 15], names: ['Saudável', 'Alta', 'Muito alta'], tones: ['pos', 'warn', 'neg'] },
  protein: { l: 'Proteína', u: '%', min: 10, max: 25, cuts: [16, 20], names: ['Baixa', 'Normal', 'Alta'], tones: ['warn', 'pos', 'pos'] },
  ffmi: { l: 'Índice de massa magra (FFMI)', u: '', min: 14, max: 28, cuts: [18, 20, 22, 25], names: ['Baixo', 'Médio', 'Acima da média', 'Excelente', 'Elite'], tones: ['warn', '', 'pos', 'pos', 'pos'] },
  whr: { l: 'Cintura / anca', u: '', min: .65, max: 1.15, cuts: () => sex() === 'F' ? [.8, .85] : [.9, 1], names: ['Baixo risco', 'Moderado', 'Alto risco'], tones: ['pos', 'warn', 'neg'] },
  whtr: { l: 'Cintura / altura', u: '', min: .35, max: .7, cuts: [.4, .5, .6], names: ['Magro', 'Saudável', 'Atenção', 'Risco'], tones: ['warn', 'pos', 'warn', 'neg'] },
  ecw: { l: 'Água extracelular (ECW/TBW)', u: '', min: .33, max: .42, cuts: [.36, .39], names: ['Baixa', 'Normal', 'Edema / inflamação'], tones: ['', 'pos', 'neg'] },
  phase: { l: 'Ângulo de fase', u: '°', min: 3, max: 10, cuts: () => sex() === 'F' ? [4.5, 5.5] : [5, 6], names: ['Baixo', 'Normal', 'Bom (células saudáveis)'], tones: ['warn', '', 'pos'] }
};
const gauge = (k, v, dec = 1) => { const R = RANGES[k]; if (!v && v !== 0) return ''; const cuts = typeof R.cuts === 'function' ? R.cuts() : R.cuts, i = cuts.filter(c => v >= c).length, pos = U.clamp((v - R.min) / (R.max - R.min), 0, 1);
  const segs = [R.min, ...cuts, R.max].map((c, j, a) => j < a.length - 1 ? `<i class="${R.tones[j]}" style="width:${(a[j + 1] - c) / (R.max - R.min) * 100}%"></i>` : '').join('');
  return `<div class="gz"><div class="gz-h"><span>${R.l}</span><b class="mono">${U.nf(v, dec)}${R.u}</b><span class="bdg ${R.tones[i]}">${R.names[i]}</span></div><div class="gz-b">${segs}<em style="left:${pos * 100}%"></em></div></div>`; };
BX.metrics = b => { const h = BX.height() / 100, w = n(b.weight) || lastW(), bf = n(b.bf), lean = n(b.leanKg) || (w && bf ? w * (1 - bf / 100) : 0), fat = n(b.fatKg) || (w && bf ? w * bf / 100 : 0);
  return { w, bf, lean, fat, bmi: h && w ? w / (h * h) : 0, ffmi: h && lean ? lean / (h * h) + 6.1 * (1.8 - h) : 0, whr: n(b.waist) && n(b.hip) ? n(b.waist) / n(b.hip) : 0, whtr: n(b.waist) && h ? n(b.waist) / (h * 100) : 0 }; };
const delta = (a, b, k, u = '', dec = 1, goodDown = false) => { if (!a || !b || !n(a[k]) || !n(b[k])) return ''; const d = n(a[k]) - n(b[k]); if (Math.abs(d) < .05) return `<small class="mut">=</small>`; const good = goodDown ? d < 0 : d > 0; return `<small class="${good ? 'pos' : 'neg'}">${d > 0 ? '+' : ''}${U.nf(d, dec)}${u}</small>`; };
V.treinoPeso = () => { const all = B(), last = all[all.length - 1], bio = all.filter(x => x.bio || n(x.bf) || n(x.muscleKg)), lb = bio[bio.length - 1], pb = bio[bio.length - 2], o = OS.one('diet');
  const m = lb ? BX.metrics(lb) : last ? BX.metrics(last) : null, wts = all.filter(x => n(x.weight)), w30 = wts.filter(x => x.date >= U.addDays(U.today(), -30))[0], lw = wts[wts.length - 1];
  const seg = lb && ['ArmL', 'ArmR', 'Trunk', 'LegL', 'LegR'].some(k => n(lb['l' + k]) || n(lb['g' + k]));
  const segBox = (k, l) => `<div class="sg sg-${k}"><small>${l}</small><b class="mono">${n(lb['l' + k]) ? U.nf(lb['l' + k], 1) + ' kg' : '—'}</b><span class="mut mono">${n(lb['g' + k]) ? U.nf(lb['g' + k], 1) + '%' : ''}</span></div>`;
  const meas = [['neck', 'Pescoço'], ['chest', 'Peito'], ['waist', 'Cintura'], ['abdomen', 'Abdómen'], ['hip', 'Anca'], ['armLc', 'Braço esq.'], ['armRc', 'Braço dir.'], ['thighL', 'Coxa esq.'], ['thighR', 'Coxa dir.'], ['calf', 'Gémeo']];
  const lastM = k => { const r = all.filter(x => n(x[k])); return [r[r.length - 1], r[r.length - 2]]; };
  return `<div class="pn bx-me"><div class="fgrid"><div class="fld"><label for="bx_h">Altura</label><div class="inp-wrap"><input id="bx_h" type="number" inputmode="decimal" step="any" data-bind="diet.h" value="${esc(o.h ?? '')}" placeholder="ex.: 178"><span>cm</span></div></div><div class="fld"><label for="bx_a">Idade</label><div class="inp-wrap"><input id="bx_a" type="number" inputmode="numeric" data-bind="diet.age" value="${esc(o.age ?? '')}"><span>anos</span></div></div><div class="fld"><label for="bx_s">Sexo</label><select id="bx_s" data-bind="diet.sex"><option value="M"${o.sex !== 'F' ? ' selected' : ''}>Masculino</option><option value="F"${o.sex === 'F' ? ' selected' : ''}>Feminino</option></select></div>
    <div class="fld bx-btns"><button class="btn pri" data-act="bioExam">${UI.ic('zap')}<span>Fazer exame com IA</span></button>${UI.addBtn('body', 'Registar peso', null, 'ghost')}<button class="btn ghost" data-act="bioScan">${UI.ic('camera')}<span>Ler exame em papel</span></button>${UI.addBtn('body', 'Escrever exame', { bio: true }, 'ghost')}</div></div><small class="mut">A altura, a idade e o sexo servem para o IMC, o metabolismo, as metas da dieta e as faixas de referência.</small></div>
  <div class="kpis">${UI.kpi('Peso atual', lw ? U.nf(lw.weight, 1) + ' kg' : '—', lw ? U.fmtDS(lw.date) : '')}${UI.kpi('Variação 30 dias', lw && w30 ? (n(lw.weight) - n(w30.weight) > 0 ? '+' : '') + U.nf(n(lw.weight) - n(w30.weight), 1) + ' kg' : '—')}${UI.kpi('IMC', m && m.bmi ? U.nf(m.bmi, 1) : '—', BX.height() ? '' : 'falta a altura')}${UI.kpi('Gordura corporal', m && m.bf ? U.nf(m.bf, 1) + '%' : '—', lb ? U.fmtDS(lb.date) : '')}${UI.kpi('Massa muscular', lb && n(lb.muscleKg) ? U.nf(lb.muscleKg, 1) + ' kg' : '—')}${UI.kpi('Massa magra', m && m.lean ? U.nf(m.lean, 1) + ' kg' : '—')}</div>
  ${lb ? `${OS.BioAI ? OS.BioAI.panel(lb, pb) : ''}<div class="g g2"><div class="pn"><div class="pn-h"><h3>${lb.src === 'ia' ? 'Resultado do exame da IA' : 'Bioimpedância'} · ${U.fmtD(lb.date)}</h3>${pb ? `<span class="mut" style="font-size:12px">vs ${U.fmtD(pb.date)}</span>` : ''}</div>
    <div class="bx-comp">${[['Peso', 'weight', 'kg', false], ['Gordura', 'bf', '%', true], ['Massa gorda', 'fatKg', 'kg', true], ['Músculo esq.', 'muscleKg', 'kg', false], ['Massa magra', 'leanKg', 'kg', false], ['Água', 'water', '%', false], ['Proteína', 'protein', '%', false], ['Ossos', 'bone', 'kg', false], ['Visceral', 'visceral', '', true], ['Metab. basal', 'bmr', ' kcal', false], ['Idade metab.', 'metAge', ' anos', true]].filter(([, k]) => n(lb[k])).map(([l, k, u, gd]) => `<div><small>${l}</small><b class="mono">${U.nf(lb[k], k === 'bmr' || k === 'metAge' || k === 'visceral' ? 0 : 1)}${u}</b>${delta(lb, pb, k, u.trim(), 1, gd)}</div>`).join('')}</div>
    ${seg ? `<div class="eyebrow" style="margin:14px 0 6px">Análise segmentar · massa magra e gordura</div><div class="bx-seg">${segBox('ArmR', 'Braço dir.')}${segBox('Trunk', 'Tronco')}${segBox('ArmL', 'Braço esq.')}${segBox('LegR', 'Perna dir.')}<div class="sg-fig">${UI.ic('users')}</div>${segBox('LegL', 'Perna esq.')}</div>${n(lb.lArmL) && n(lb.lArmR) && Math.abs(n(lb.lArmL) - n(lb.lArmR)) / Math.max(n(lb.lArmL), n(lb.lArmR)) > .06 ? `<p class="note">Diferença entre braços acima de 6%: inclui exercícios unilaterais.</p>` : ''}${n(lb.lLegL) && n(lb.lLegR) && Math.abs(n(lb.lLegL) - n(lb.lLegR)) / Math.max(n(lb.lLegL), n(lb.lLegR)) > .06 ? `<p class="note">Diferença entre pernas acima de 6%: afundos e búlgaros ajudam a equilibrar.</p>` : ''}` : ''}
    ${lb.src === 'ia' ? `<p class="note">Estimativa feita pela IA a partir de ${esc(lb.method || 'medidas')}. Não mede como um aparelho de bioimpedância, mas é ótima para acompanhar a evolução: repete nas mesmas condições (de manhã, em jejum).${lb.look ? `<br>Músculo: <b>${esc(lb.look.musc)}</b>${lb.look.fortes.length ? ` · mais desenvolvido: ${esc(lb.look.fortes.join(', '))}` : ''}${lb.look.fracas.length ? ` · a desenvolver: <b>${esc(lb.look.fracas.join(', '))}</b>` : ''}${lb.look.gord ? ` · gordura acumula-se em: ${esc(lb.look.gord)}` : ''}${lb.look.post ? ` · postura: ${esc(lb.look.post)}` : ''}` : ''}</p>` : ''}<button class="btn ghost sm" data-edit="body:${lb.id}" style="margin-top:10px">${UI.ic('edit')}Ver / editar exame</button></div>
    <div class="pn"><div class="pn-h"><h3>Faixas de referência</h3></div>${gauge('bmi', m.bmi)}${gauge('bf', n(lb.bf))}${gauge('ffmi', m.ffmi)}${gauge('visceral', n(lb.visceral), 0)}${gauge('water', n(lb.water))}${gauge('protein', n(lb.protein))}${gauge('whr', m.whr, 2)}${gauge('whtr', m.whtr, 2)}${gauge('ecw', n(lb.ecw), 3)}${gauge('phase', n(lb.phase))}
      <p class="note">Valores de referência gerais para adultos${sex() === 'F' ? ' (mulher)' : ' (homem)'}. Compara sempre exames feitos no mesmo aparelho, à mesma hora e em jejum.</p></div></div>`
    : `<div class="pn bx-cta"><div>${UI.ic('scale')}</div><div><b>Exame de bioimpedância</b><p class="mut">A IA faz o teu exame de composição corporal: só precisas do peso, de uma fita métrica (cintura e pescoço) e, se quiseres, de 3 fotos do corpo. Recebes a gordura, o músculo, a água, a gordura visceral, o metabolismo e a idade metabólica, e a IA diz-te onde tens de melhorar no treino, na dieta e na corrida.</p><div class="row gap8" style="flex-wrap:wrap"><button class="btn pri" data-act="bioExam">${UI.ic('zap')}<span>Fazer exame com IA</span></button><button class="btn ghost" data-act="bioScan">${UI.ic('camera')}<span>Já tenho um exame em papel</span></button></div></div></div>`}
  <div class="g g2"><div class="pn"><div class="pn-h"><h3>Peso</h3></div>${C.mount({ type: 'line', labels: wts.map(b => U.fmtDS(b.date)), series: [{ name: 'Peso (kg)', data: wts.map(b => n(b.weight)) }], min0: false, fmt: v => U.nf(v, 1), empty: 'Regista o peso para ver a curva.' }, 220)}</div>
  <div class="pn"><div class="pn-h"><h3>Gordura e músculo</h3></div>${C.mount({ type: 'line', labels: bio.map(b => U.fmtDS(b.date)), series: [{ name: 'Gordura (%)', data: bio.map(b => n(b.bf) || null), color: '#F2A65A' }, { name: 'Músculo (kg)', data: bio.map(b => n(b.muscleKg) || null), color: 'var(--c6)' }], min0: false, fmt: v => U.nf(v, 1), empty: 'Precisas de pelo menos um exame.' }, 220)}</div></div>
  ${meas.some(([k]) => lastM(k)[0]) ? `<div class="pn"><div class="pn-h"><h3>Perímetros</h3></div><div class="bx-comp">${meas.map(([k, l]) => { const [a, b] = lastM(k); return a ? `<div><small>${l}</small><b class="mono">${U.nf(a[k], 1)} cm</b>${delta(a, b, k, ' cm', 1, ['waist', 'abdomen', 'hip'].includes(k))}</div>` : ''; }).join('')}</div></div>` : ''}
  ${UI.table({ key: 'body', coll: 'body', rows: all.slice().reverse(), limit: 30, cols: [{ l: 'Data', v: b => U.fmtD(b.date), s: b => b.date }, { l: 'Peso', cls: 'r', v: b => n(b.weight) ? U.nf(b.weight, 1) + ' kg' : '—' }, { l: 'Gordura', cls: 'r', v: b => n(b.bf) ? U.nf(b.bf, 1) + '%' : '—' }, { l: 'Músculo', cls: 'r', v: b => n(b.muscleKg) ? U.nf(b.muscleKg, 1) + ' kg' : '—' }, { l: 'Cintura', cls: 'r', v: b => n(b.waist) ? b.waist + ' cm' : '—' }, { l: '', v: b => b.bio ? UI.badge('bioimpedância', 'pos') : '' }] })}`; };

/* ================= gasto do exercício e meta do dia ================= */
const kg = () => lastW() || 75;
BX.wkKcal = w => { const mins = n(w.dur) || Math.max(20, OS.Fit.sets(w) * 2.5); return Math.round(5 * kg() * mins / 60); };
BX.runKcal = r => Math.round(kg() * n(r.km) * 1.03);
BX.stKcal = s => Math.round(2.3 * kg() * n(s.mins) / 60);
BX.burn = d => U.sum(OS.all('workouts').filter(w => w.date === d), BX.wkKcal) + U.sum(OS.all('runs').filter(r => r.date === d), BX.runKcal) + U.sum(OS.all('stretches').filter(s => s.date === d), BX.stKcal);
BX.avgBurn = () => { const days = U.lastN(28).slice(0, 27); return U.sum(days, BX.burn) / days.length; };
BX.bmr = () => BX.bmrMeasured() || (OS.Diet ? OS.Diet.bmr() : 0);
BX.tdee = d => { const b = BX.bmr(); return b ? Math.round(b * 1.25 + BX.burn(d)) : 0; };
// meta de hoje: a meta base da dieta + (gasto de hoje − gasto médio). A média da semana fica igual; dias de treino têm mais hidratos.
BX.target = d => { const o = OS.one('diet'), base = { kcal: n(o.kcal), p: n(o.p), c: n(o.c), f: n(o.f) }; if (o.adapt === false || o.adapt === 'off') return Object.assign(base, { adj: 0 });
  const adj = Math.round((BX.burn(d) - BX.avgBurn()) / 10) * 10, lim = U.clamp(adj, -400, 700); return { kcal: base.kcal + lim, p: base.p, c: Math.max(0, Math.round(base.c + lim / 4)), f: base.f, adj: lim }; };
const plannedSplit = d => { const s = OS.one('fit').split[String(U.parse(d).getDay())]; return s && !['Descanso', 'Corrida', 'Mobilidade'].includes(s) ? s : ''; };
const plannedRun = d => OS.all('runplan').filter(r => r.active && String(r.wday) === String(U.parse(d).getDay()))[0];
BX.strip = () => { const d = U.today(), wk = OS.all('workouts').filter(w => w.date === d), rn = OS.all('runs').filter(r => r.date === d), st = OS.all('stretches').filter(s => s.date === d), x = OS.Diet ? OS.Diet.day(d) : { kcal: 0, p: 0 }, tg = BX.target(d), sp = plannedSplit(d), pr = plannedRun(d), w = lastW();
  const wts = B().filter(b => n(b.weight)), w7 = wts.filter(b => b.date >= U.addDays(d, -7))[0];
  const tile = (href, ic, l, v, s, tone) => `<a class="bxs ${tone || ''}" href="#${href}"><span class="bxs-i">${UI.ic(ic)}</span><span><small>${l}</small><b>${v}</b><em>${s}</em></span></a>`;
  return `<div class="bx-strip" aria-label="Hoje no corpo">
    ${tile('treino', 'dumbbell', 'Treino', wk.length ? 'Feito' : sp ? 'Planeado' : 'Descanso', wk.length ? `${esc(wk[0].title || '')} · ${BX.wkKcal(wk[0])} kcal` : sp ? esc(sp) : 'recupera bem', wk.length ? 'pos' : sp ? 'warn' : '')}
    ${tile('corrida', 'run', 'Corrida', rn.length ? U.nf(U.sum(rn, r => r.km), 1) + ' km' : pr ? 'Planeada' : '—', rn.length ? BX.runKcal(rn[0]) + ' kcal' : pr ? esc(pr.type) + (n(pr.km) ? ' ' + pr.km + ' km' : '') : 'sem corrida hoje', rn.length ? 'pos' : pr ? 'warn' : '')}
    ${tile('corrida.alongamentos', 'wave', 'Alongamentos', st.length ? U.sum(st, s => s.mins) + ' min' : '—', st.length ? 'feito' : wk.length || rn.length ? 'faz agora (5–10 min)' : 'mobilidade diária', st.length ? 'pos' : wk.length || rn.length ? 'warn' : '')}
    ${tile('dieta', 'apple', 'Calorias', `${U.nf(x.kcal)} / ${U.nf(tg.kcal)}`, tg.adj ? `meta ${tg.adj > 0 ? '+' : ''}${tg.adj} pelo exercício` : 'kcal hoje', tg.kcal && x.kcal > tg.kcal * 1.1 ? 'neg' : tg.kcal && x.kcal >= tg.kcal * .9 ? 'pos' : '')}
    ${tile('dieta', 'bolt', 'Proteína', `${U.nf(x.p)} / ${U.nf(tg.p)} g`, tg.p && x.p >= tg.p * .9 ? 'meta batida' : `faltam ${U.nf(Math.max(0, tg.p - x.p))} g`, tg.p && x.p >= tg.p * .9 ? 'pos' : '')}
    ${tile('corpo.peso', 'scale', 'Peso', w ? U.nf(w, 1) + ' kg' : '—', w && w7 && wts[wts.length - 1] !== w7 ? `${n(wts[wts.length - 1].weight) - n(w7.weight) > 0 ? '+' : ''}${U.nf(n(wts[wts.length - 1].weight) - n(w7.weight), 1)} kg em 7 dias` : 'regista o peso', '')}
  </div>`; };
BX.afterWorkout = w => { const d = w.date, x = OS.Diet ? OS.Diet.day(d) : { p: 0 }, tg = BX.target(d), ms = [...new Set((w.items || []).map(it => (OS.get('exercises', it.ex) || {}).muscle).filter(Boolean))];
  return `<div class="bx-after"><div>${UI.ic('flame')}<span>Gastaste cerca de <b>${BX.wkKcal(w)} kcal</b>. ${tg.adj > 0 ? `A tua meta de hoje subiu para <b>${U.nf(tg.kcal)} kcal</b> (mais hidratos).` : ''}</span></div>
  <div>${UI.ic('apple')}<span>Come <b>30–40 g de proteína</b> nas próximas 2 horas${tg.p ? ` (faltam ${U.nf(Math.max(0, tg.p - x.p))} g hoje)` : ''}.</span></div>
  ${ms.length ? `<div>${UI.ic('wave')}<span>Alonga o que treinaste: ${ms.map(esc).join(', ')}.</span></div><button class="btn sm" data-act="stPlay" data-kind="musc" data-m="${esc(ms.join('|'))}" data-mclose>${UI.ic('play')}Alongamentos (5 min)</button>` : ''}</div>`; };

/* ================= alongamentos ================= */
OS.SHARD.stretches = 200;
S.stretches = { label: 'Alongamentos', title: r => r.kind || 'Alongamentos', fields: [F('date', 'Data', 'date', { req: 1 }), F('kind', 'Tipo', 'sel', { o: ['Antes da corrida', 'Depois da corrida', 'Depois do treino', 'Mobilidade', 'Rolo'] }), F('mins', 'Duração', 'num', { unit: 'min', req: 1 }), F('notes', 'Notas')], defaults: () => ({ date: U.today(), kind: 'Mobilidade', mins: 10 }) };
const ST = (OS.ExLib ? OS.ExLib.ST : []).map(s => ({ id: s[0], name: s[1], ph: s[2], run: s[3], sec: s[4], sides: s[5], how: s[6], muscle: s[7] }));
BX.ST = ST;
const PH = { din: 'Antes (dinâmico)', est: 'Depois (estático)', rolo: 'Rolo / libertação' };
const MUS2 = { 'Quadríceps': ['Quadríceps'], 'Isquiotibiais': ['Isquiotibiais'], 'Glúteos': ['Glúteos'], 'Gémeos': ['Gémeos'], 'Peito': ['Peito', 'Ombros'], 'Ombros': ['Ombros', 'Peito'], 'Dorsais': ['Dorsais', 'Lombar'], 'Trapézio': ['Trapézio', 'Ombros'], 'Bíceps': ['Bíceps', 'Peito'], 'Tríceps': ['Tríceps', 'Dorsais'], 'Antebraços': ['Antebraços'], 'Lombar': ['Lombar', 'Glúteos'], 'Abdómen': ['Abdómen', 'Lombar'], 'Oblíquos': ['Abdómen', 'Lombar'] };
const stMus = s => ({ hamstrings: 'Isquiotibiais' }[s.muscle] || s.muscle);
const stCard = s => `<article class="st-c"><button class="st-ci" data-act="stOne" data-id="${s.id}">${OS.Ex.thumb({ lib: s.id }, 'md')}</button><div><b>${esc(s.name)}</b><small>${PH[s.ph]} · ${s.sec} s${s.sides > 1 ? ' cada lado' : ''}${s.run ? ' · essencial para corrida' : ''}</small><p>${esc(s.how)}</p></div></article>`;
V.corridaAlong = () => { const f = OS.ui.stF || 'din', mf = OS.ui.stM || '', list = ST.filter(s => (f === 'todos' || s.ph === f) && (!mf || stMus(s) === mf)), mus = [...new Set(ST.map(stMus))].filter(Boolean), log = U.sortBy(OS.all('stretches'), s => s.date, -1), wk = OS.all('stretches').filter(s => s.date >= U.addDays(U.today(), -6));
  const routine = (k, ic, t, sub) => { const it = BX.routine(k); return `<button class="st-r" data-act="stPlay" data-kind="${k}">${UI.ic(ic)}<span><b>${t}</b><small>${sub} · ${it.length} alongamentos · ~${Math.round(U.sum(it, s => s.sec * s.sides) / 60 + it.length * .1)} min</small></span>${UI.ic('play')}</button>`; };
  return `${BX.strip()}<div class="kpis">${UI.kpi('Esta semana', wk.length + ' sessões', U.sum(wk, s => s.mins) + ' min')}${UI.kpi('Recomendado', 'antes e depois', 'de cada corrida')}${UI.kpi('Última vez', log[0] ? U.rel(log[0].date) : '—')}</div>
  <div class="sech"><div><h2>Rotinas guiadas</h2><p>Com temporizador, foto de cada movimento e aviso para trocar de lado.</p></div></div>
  <div class="st-rs">${routine('pre', 'zap', 'Aquecimento antes de correr', 'dinâmico, 6–8 min')}${routine('post', 'wave', 'Depois de correr', 'estático, 30 s cada')}${routine('rolo', 'repeat', 'Rolo para corredores', 'libertação miofascial')}${routine('mob', 'heart', 'Mobilidade diária', 'corpo todo')}</div>
  <div class="note" style="margin:10px 0 4px"><b>Antes</b> de correr: alongamentos <b>dinâmicos</b> (movimento), para aquecer sem perder força. <b>Depois</b>: <b>estáticos</b> (30 s parado em cada um), para relaxar e recuperar. O rolo ajuda nos gémeos, banda iliotibial e glúteos, as zonas que mais sofrem na corrida.</div>
  <div class="sech"><div><h2>Todos os alongamentos</h2></div></div>
  ${UI.seg('stF', [['din', 'Antes (dinâmico)'], ['est', 'Depois (estático)'], ['rolo', 'Rolo'], ['todos', 'Todos']], f)}
  <div class="wk-chips" style="margin:10px 0">${mus.map(m => UI.chip(m, 'stM', mf === m, `data-v="${m}"`)).join('')}</div>
  <div class="st-list">${list.map(stCard).join('') || UI.empty('Nada com este filtro.')}</div>
  <div class="row gap8" style="margin-top:14px">${UI.addBtn('stretches', 'Registar alongamentos', null, 'ghost')}</div>`; };
A.stM = b => OS.setUI('stM', OS.ui.stM === b.dataset.v ? '' : b.dataset.v);
BX.routine = (k, ms = []) => { const pick = ids => ids.map(id => ST.find(s => s.id === id)).filter(Boolean);
  if (k === 'pre') return pick(['Ankle_Circles', 'Standing_Hip_Circles', 'Front_Leg_Raises', 'Side_Leg_Raises', 'Double_Leg_Butt_Kick', 'Fast_Skipping', 'Groiners', 'Worlds_Greatest_Stretch', 'Inchworm']);
  if (k === 'post') return pick(['Standing_Hamstring_and_Calf_Stretch', 'Quad_Stretch', 'Kneeling_Hip_Flexor', 'Calf_Stretch_Hands_Against_Wall', 'Standing_Soleus_And_Achilles_Stretch', 'Lying_Glute', 'IT_Band_and_Glute_Stretch', 'Adductor', 'Childs_Pose']);
  if (k === 'rolo') return pick(['Calves-SMR', 'Iliotibial_Tract-SMR', 'Quadriceps-SMR', 'Hamstring-SMR', 'Piriformis-SMR', 'Foot-SMR']);
  if (k === 'mob') return pick(['Cat_Stretch', 'Worlds_Greatest_Stretch', 'Kneeling_Hip_Flexor', 'Lying_Glute', 'Chest_And_Front_Of_Shoulder_Stretch', 'Overhead_Lat', 'Spinal_Stretch', 'Standing_Hamstring_and_Calf_Stretch', 'Childs_Pose']);
  const want = new Set(ms.flatMap(m => MUS2[m] || [m])); const out = ST.filter(s => s.ph === 'est' && want.has(stMus(s))); const by = {}; out.forEach(s => { (by[stMus(s)] = by[stMus(s)] || []).push(s); });
  return Object.values(by).flatMap(a => a.slice(0, 2)).slice(0, 8); };
// leitor guiado
let PL = null;
const plHost = () => { let h = document.getElementById('stPlay'); if (!h) { h = document.createElement('div'); h.id = 'stPlay'; h.hidden = true; document.body.appendChild(h); h.addEventListener('click', e => { const b = e.target.closest('[data-pl]'); if (!b || !PL) return; const a = b.dataset.pl;
  if (a === 'x') { if (PL.i > 0 && !PL.logged) logPL(); stopPL(); return; } if (a === 'pause') PL.pause = !PL.pause; if (a === 'vid') { PL.vid = !PL.vid; if (PL.vid) PL.pause = true; } if (a === 'next') nextPL(); if (a === 'prev') { PL.i = Math.max(0, PL.i - 1); PL.left = PL.list[PL.i].sec * PL.list[PL.i].sides; } if (a === 'done') { logPL(); stopPL(); return; } drawPL(); }); } return h; };
const KIND = { pre: 'Antes da corrida', post: 'Depois da corrida', rolo: 'Rolo', mob: 'Mobilidade', musc: 'Depois do treino', one: 'Mobilidade' };
A.stPlay = b => { const k = b.dataset.kind, list = BX.routine(k, (b.dataset.m || '').split('|').filter(Boolean)); if (!list.length) { UI.toast('Sem alongamentos para estes músculos', 'warn'); return; } UI.closeModal(); PL = { k, list, i: 0, left: list[0].sec * list[0].sides, pause: false, t0: Date.now() }; plHost().hidden = false; document.body.classList.add('noscroll'); drawPL(); clearInterval(PL.tm); PL.tm = setInterval(tickPL, 1000); };
A.stOne = b => { const s = ST.find(x => x.id === b.dataset.id); if (!s) return; PL = { k: 'one', list: [s], i: 0, left: s.sec * s.sides, pause: true, t0: Date.now() }; plHost().hidden = false; document.body.classList.add('noscroll'); drawPL(); clearInterval(PL.tm); PL.tm = setInterval(tickPL, 1000); };
const beep = (f = 660) => { try { const a = BX._ac = BX._ac || new (window.AudioContext || window.webkitAudioContext)(), o = a.createOscillator(), g = a.createGain(); o.frequency.value = f; g.gain.value = .12; o.connect(g); g.connect(a.destination); o.start(); o.stop(a.currentTime + .18); } catch (e) { } try { navigator.vibrate && navigator.vibrate(120); } catch (e) { } };
const tickPL = () => { if (!PL || PL.pause) return; PL.left--; const s = PL.list[PL.i];
  if (s.sides > 1 && PL.left === s.sec) { beep(520); UI.toast('Troca de lado'); }
  if (PL.left <= 0) { beep(); nextPL(); return; } const el = document.querySelector('#stPlay [data-left]'); if (el) el.textContent = PL.left; const bar = document.querySelector('#stPlay .pl-bar i'); if (bar) bar.style.width = (100 - PL.left / (s.sec * s.sides) * 100) + '%'; };
const nextPL = () => { PL.vid = false; if (PL.i >= PL.list.length - 1) { PL.end = true; clearInterval(PL.tm); drawPL(); return; } PL.i++; PL.left = PL.list[PL.i].sec * PL.list[PL.i].sides; drawPL(); };
const logPL = () => { if (!PL || PL.logged || PL.k === 'one') return; PL.logged = true; const mins = Math.max(1, Math.round((Date.now() - PL.t0) / 60000)); OS.add('stretches', { date: U.today(), kind: KIND[PL.k], mins, n: PL.i + 1 }); UI.toast(`Alongamentos registados · ${mins} min`, 'pos'); };
const stopPL = () => { if (PL) clearInterval(PL.tm); PL = null; plHost().hidden = true; document.body.classList.remove('noscroll'); OS.request(); };
const drawPL = () => { const s = PL.list[PL.i], tot = s.sec * s.sides, side = s.sides > 1 ? (PL.left > s.sec ? 'Lado direito' : 'Lado esquerdo') : '';
  plHost().innerHTML = `<div class="pl" role="dialog" aria-modal="true" aria-label="Alongamentos"><header class="wk-top"><button class="icon-btn" data-pl="x" aria-label="Fechar">${UI.ic('x')}</button><b class="wk-ttl">${PL.end ? 'Concluído' : `${PL.i + 1} de ${PL.list.length}`}</b><span></span></header>
  ${PL.end ? `<div class="pl-end">${UI.ic('check')}<h3>Muito bem!</h3><p class="mut">${PL.list.length} alongamentos feitos. O teu corpo agradece.</p><button class="btn pri" data-pl="done">Registar e fechar</button></div>`
    : `<div class="pl-b">${PL.vid ? `<div class="pl-v">${OS.Ex.player(s.id, s.name)}</div>` : OS.Ex.thumb({ lib: s.id }, 'xl')}${OS.Ex.vid(s.id) ? `<button class="btn ghost sm" data-pl="vid">${UI.ic(PL.vid ? 'repeat' : 'play')}${PL.vid ? 'Ver a foto' : 'Ver vídeo'}</button>` : ''}<h3>${esc(s.name)}</h3>${side ? `<span class="bdg">${side}</span>` : ''}<p>${esc(s.how)}</p><div class="pl-t mono" data-left>${PL.left}</div><div class="pl-bar"><i style="width:${100 - PL.left / tot * 100}%"></i></div>
    <div class="pl-c"><button class="icon-btn" data-pl="prev" aria-label="Anterior">${UI.ic('left')}</button><button class="btn pri lg" data-pl="pause">${UI.ic(PL.pause ? 'play' : 'pause')}<span>${PL.pause ? 'Começar' : 'Pausa'}</span></button><button class="icon-btn" data-pl="next" aria-label="Seguinte">${UI.ic('right')}</button></div>
    ${PL.list[PL.i + 1] ? `<small class="mut">A seguir: ${esc(PL.list[PL.i + 1].name)}</small>` : ''}</div>`}</div>`; };

/* ================= visão do corpo (tudo ligado) ================= */
const GOALS = { cut: 'Perder gordura', keep: 'Manter', bulk: 'Ganhar massa' };
BX.recs = () => { const t = U.today(), o = OS.one('diet'), out = [], x = OS.Diet ? OS.Diet.day(t) : { kcal: 0, p: 0 }, tg = BX.target(t), wts = B().filter(b => n(b.weight)), d28 = wts.filter(b => b.date >= U.addDays(t, -28)), goal = o.goal || 'keep';
  const rate = d28.length >= 2 ? (n(d28[d28.length - 1].weight) - n(d28[0].weight)) / Math.max(1, U.diff(d28[d28.length - 1].date, d28[0].date)) * 7 : null;
  const tom = U.addDays(t, 1), sp = plannedSplit(tom), pr = plannedRun(tom);
  if (!BX.height()) out.push(['warn', 'scale', 'Regista a tua altura', 'Em Corpo → Peso e medidas. Serve para o IMC, metabolismo e metas.', 'corpo.peso']);
  if (!wts.length || U.diff(t, wts[wts.length - 1].date) > 7) out.push(['warn', 'scale', 'Pesa-te esta semana', 'De manhã, em jejum, depois da casa de banho. Uma vez por semana chega.', 'corpo.peso']);
  if (rate != null && wts.length >= 3) { const w = n(wts[wts.length - 1].weight), pct = rate / w * 100;
    if (goal === 'cut' && pct > -.2) out.push(['warn', 'trend', 'O peso não está a descer', `Nas últimas 4 semanas: ${rate > 0 ? '+' : ''}${U.nf(rate, 2)} kg/semana. Para perder gordura, tira 150–200 kcal por dia ou junta 1 corrida leve por semana.`, 'dieta.metas']);
    else if (goal === 'cut' && pct < -1) out.push(['warn', 'trend', 'Estás a perder peso depressa demais', `${U.nf(rate, 2)} kg/semana (mais de 1%). Arriscas perder músculo: sobe 150 kcal e mantém a proteína alta.`, 'dieta.metas']);
    else if (goal === 'bulk' && pct < .1) out.push(['warn', 'trend', 'O peso não está a subir', `${rate > 0 ? '+' : ''}${U.nf(rate, 2)} kg/semana. Para ganhar massa, junta ~200 kcal por dia (sobretudo hidratos à volta do treino).`, 'dieta.metas']);
    else if (goal === 'bulk' && pct > .6) out.push(['warn', 'trend', 'Estás a ganhar peso depressa', `+${U.nf(rate, 2)} kg/semana: parte disso é gordura. Ideal: 0,25–0,5% do peso por semana.`, 'dieta.metas']);
    else out.push(['pos', 'trend', 'Peso dentro do objetivo', `${rate > 0 ? '+' : ''}${U.nf(rate, 2)} kg/semana, ao ritmo certo para "${GOALS[goal]}".`, 'corpo.peso']); }
  if (tg.p && x.p < tg.p * .6 && new Date().getHours() >= 15) out.push(['warn', 'bolt', 'Proteína atrasada hoje', `Tens ${U.nf(x.p)} g de ${U.nf(tg.p)} g. Ex.: 200 g de frango (≈60 g) ou um iogurte proteico + whey (≈35 g).`, 'dieta']);
  if (sp || pr) out.push(['', 'cal', 'Amanhã: ' + [sp && 'treino de ' + sp, pr && 'corrida ' + pr.type + (n(pr.km) ? ' ' + pr.km + ' km' : '')].filter(Boolean).join(' + '), pr && /longa|intervalado|limiar/i.test(pr.type) ? 'Come hidratos ao jantar de hoje (arroz, massa, batata) para teres energia. Dorme 7–8 h.' : 'Dorme bem e bebe 2,5–3 L de água. Leva o alongamento dinâmico antes.', pr ? 'corrida.plano' : 'treino']);
  const legs = OS.all('workouts').filter(w => w.date >= U.addDays(t, -1)).some(w => (w.items || []).some(it => ['Quadríceps', 'Isquiotibiais', 'Glúteos'].includes((OS.get('exercises', it.ex) || {}).muscle)));
  if (legs && pr) out.push(['warn', 'run', 'Pernas cansadas antes de correr', 'Treinaste pernas nas últimas 24 h. Amanhã faz a corrida mais leve ou troca-a com um dia de descanso.', 'corrida.plano']);
  const runs7 = OS.all('runs').filter(r => r.date >= U.addDays(t, -6)).length, st7 = OS.all('stretches').filter(s => s.date >= U.addDays(t, -6)).length;
  if (runs7 >= 2 && st7 < runs7) out.push(['warn', 'wave', 'Alonga depois de correr', `${runs7} corridas e ${st7} sessões de alongamento esta semana. 6 minutos depois de cada corrida reduzem dores e lesões.`, 'corrida.alongamentos']);
  const lean = BX.lean(); if (lean && n(o.p) && n(o.p) < lean * 2) out.push(['', 'bolt', 'Proteína pela massa magra', `Com ${U.nf(lean, 1)} kg de massa magra, o ideal é ${Math.round(lean * 2.2)}–${Math.round(lean * 2.6)} g/dia. A tua meta é ${n(o.p)} g.`, 'dieta.metas']);
  if (BX.bmrMeasured() && OS.Diet && OS.Diet.bmr() && Math.abs(BX.bmrMeasured() - OS.Diet.bmr()) > 120) out.push(['', 'zap', 'Metabolismo medido na bioimpedância', `O teu exame dá ${U.nf(BX.bmrMeasured())} kcal de metabolismo basal (a fórmula dava ${U.nf(OS.Diet.bmr())}). As metas usam o valor medido.`, 'dieta.metas']);
  return out; };
V.corpo = () => { const t = U.today(), days = U.lastN(14), o = OS.one('diet'), wk = U.range(U.monday(t), U.addDays(U.monday(t), 6)), lb = lastBio();
  const cell = (ok, plan, past) => `<i class="${ok ? 'on' : plan ? (past ? 'miss' : 'plan') : ''}"></i>`;
  const rows = [['Treino', d => OS.all('workouts').some(w => w.date === d), d => !!plannedSplit(d)], ['Corrida', d => OS.all('runs').some(r => r.date === d), d => !!plannedRun(d)], ['Alongamentos', d => OS.all('stretches').some(s => s.date === d), () => false], ['Calorias na meta', d => { const x = OS.Diet.day(d), tg = BX.target(d); return x.n && tg.kcal && x.kcal >= tg.kcal * .9 && x.kcal <= tg.kcal * 1.1; }, () => false], ['Proteína', d => { const x = OS.Diet.day(d), tg = BX.target(d); return x.n && tg.p && x.p >= tg.p * .9; }, () => false]];
  const recs = BX.recs();
  return UI.head('Corpo', 'Treino, dieta e corrida ligados: o que gastas, o que comes e como o corpo responde.', `${UI.addBtn('body', 'Registar peso', null, 'ghost')}<button class="btn pri" data-act="wkStart">${UI.ic('dumbbell')}<span>Treinar</span></button>`, 'Corpo') + BX.strip() + `
  <div class="g g2"><div class="pn"><div class="pn-h"><h3>Objetivo: ${GOALS[o.goal || 'keep']}</h3><a class="more" href="#dieta.metas">Mudar ${UI.ic('right')}</a></div>
    <div class="bx-comp">${[['Peso', lastW() ? U.nf(lastW(), 1) + ' kg' : '—'], ['Altura', BX.height() ? BX.height() + ' cm' : '—'], ['Gordura', lb && n(lb.bf) ? U.nf(lb.bf, 1) + '%' : '—'], ['Massa magra', BX.lean() ? U.nf(BX.lean(), 1) + ' kg' : '—'], ['Metabolismo basal', BX.bmr() ? U.nf(BX.bmr()) + ' kcal' : '—'], ['Gasto hoje', BX.tdee(t) ? U.nf(BX.tdee(t)) + ' kcal' : '—']].map(([l, v]) => `<div><small>${l}</small><b class="mono">${v}</b></div>`).join('')}</div>
    <div class="fld" style="margin-top:12px"><label class="switch"><input type="checkbox" data-bind="diet.adapt"${o.adapt === false ? '' : ' checked'}><span></span>Ajustar a meta de calorias ao treino e à corrida de cada dia</label><small class="mut">Em dias de treino comes mais (sobretudo hidratos); em dias de descanso um pouco menos. A média da semana fica igual à tua meta.</small></div></div>
  <div class="pn"><div class="pn-h"><h3>Esta semana</h3></div><div class="bx-week"><div></div>${wk.map(d => `<b class="${d === t ? 'today' : ''}">${U.WDS[U.parse(d).getDay()]}</b>`).join('')}${rows.map(([l, f, p]) => `<span>${l}</span>${wk.map(d => d > t ? cell(false, p(d)) : cell(f(d), p(d), d < t)).join('')}`).join('')}</div><div class="mut" style="font-size:12px;margin-top:8px"><i class="bx-k on"></i> feito <i class="bx-k plan"></i> planeado <i class="bx-k miss"></i> falhado</div></div></div>
  ${recs.length ? `<div class="sech"><div><h2>O que fazer agora</h2><p>Recomendações a partir do teu treino, dieta, corrida e peso.</p></div></div><div class="bx-recs">${recs.map(([tone, ic, tt, tx, href]) => `<a class="bx-rec ${tone}" href="#${href}"><span>${UI.ic(ic)}</span><div><b>${tt}</b><p>${tx}</p></div></a>`).join('')}</div>` : ''}
  <div class="pn"><div class="pn-h"><h3>Energia · comido vs gasto (14 dias)</h3></div>${C.mount({ type: 'bar', labels: days.map(d => U.fmtDS(d)), series: [{ name: 'Comido', data: days.map(d => OS.Diet.day(d).kcal), color: 'var(--accent)' }, { name: 'Gasto estimado', data: days.map(d => BX.tdee(d)), color: '#F2A65A' }], fmt: v => U.nf(v), empty: 'Regista refeições e o teu peso para ver o balanço.' }, 230)}<div class="note">Gasto = metabolismo basal × 1,25 + exercício (treino ≈ 5 kcal/kg/h, corrida ≈ 1 kcal/kg/km). É uma estimativa: o que conta é a tendência do peso.</div></div>`; };
})();
