/* OCEANUM — Dieta completa: base de alimentos (TACO + comuns) com fotos, pesquisa e quantidades em gramas ou porções,
   refeições fixas, refeições do dia por secção, reconhecimento de comida por foto (IA) e metas ligadas ao treino. */
(() => {
'use strict';
const U = OS.U, UI = OS.UI, esc = U.esc, A = OS.act, S = OS.S, Diet = OS.Diet, T = Diet.T;
const F = (k, l, t = 'text', x = {}) => Object.assign({ k, l, t }, x);
const n = v => U.num(v) || 0;
const MEALS = ['Pequeno-almoço', 'Almoço', 'Lanche', 'Jantar', 'Ceia', 'Snack'];
const nowMeal = () => { const h = new Date().getHours(); return h < 11 ? 'Pequeno-almoço' : h < 15 ? 'Almoço' : h < 18.5 ? 'Lanche' : h < 22 ? 'Jantar' : 'Ceia'; };
const norm = s => String(s || '').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');

/* ================= base de alimentos e fotos ================= */
const DB = (OS.FoodDB || []).filter(r => r[1] || r[2] || r[3] || r[4] || /agua|cafe|cha\b|creatina|zero|sal\b|adocante/.test(norm(r[0]))).map((r, i) => ({ id: 'db' + i, name: r[0], kcal: r[1], p: r[2], c: r[3], f: r[4], fib: r[5], cat: r[6], por: r[7] || null, nn: norm(r[0]) }));
Diet.DB = DB;
/* ================= país (as marcas mudam conforme o país) ================= */
const COUNTRIES = [['PT', 'Portugal', 'portugal', 'pt'], ['BR', 'Brasil', 'brazil', 'br'], ['ES', 'Espanha', 'spain', 'es'], ['FR', 'França', 'france', 'fr'], ['IT', 'Itália', 'italy', 'it'], ['DE', 'Alemanha', 'germany', 'de'], ['GB', 'Reino Unido', 'united-kingdom', 'uk'], ['IE', 'Irlanda', 'ireland', 'ie'], ['CH', 'Suíça', 'switzerland', 'ch'], ['BE', 'Bélgica', 'belgium', 'be'], ['NL', 'Países Baixos', 'netherlands', 'nl'], ['LU', 'Luxemburgo', 'luxembourg', 'lu'], ['US', 'Estados Unidos', 'united-states', 'us'], ['CA', 'Canadá', 'canada', 'ca'], ['MX', 'México', 'mexico', 'mx'], ['AR', 'Argentina', 'argentina', 'ar'], ['AO', 'Angola', 'angola', 'world'], ['MZ', 'Moçambique', 'mozambique', 'world'], ['CV', 'Cabo Verde', 'cape-verde', 'world']];
const CTY = OS.Country = { list: COUNTRIES, code: () => OS.one('profile').country || 'PT' };
CTY.get = () => COUNTRIES.find(c => c[0] === CTY.code()) || COUNTRIES[0];
CTY.btn = (cls = '') => `<button class="ctry ${cls}" data-act="countryPick" title="Mudar de país">${UI.ic('map')}<span>${esc(CTY.get()[1])}</span>${UI.ic('down')}</button>`;
A.countryPick = () => UI.modal(`<div class="row" style="justify-content:space-between;align-items:center"><h3>Em que país estás?</h3><button class="icon-btn" data-mclose aria-label="Fechar">${UI.ic('x')}</button></div><p>As marcas e os fast foods da dieta e os simuladores de dinheiro (moeda, taxas, impostos e regras dos créditos) passam a ser os deste país. O que já registaste fica igual.</p><div class="ctry-l">${COUNTRIES.map(c => `<button class="${c[0] === CTY.code() ? 'on' : ''}" data-act="countrySet" data-v="${c[0]}"><b>${c[0]}</b><span>${esc(c[1])}</span></button>`).join('')}</div>`, 'bio-m');
A.countrySet = b => { const c = COUNTRIES.find(x => x[0] === b.dataset.v); if (!c) return; OS.setOne('profile', { country: c[0] }); UI.closeModal(); UI.toast(`País: ${c[1]}. Marcas e simuladores atualizados.`, 'pos'); if (FS) fDraw(); };
OS.on('ready', () => { const V = OS.views, pv = V.visao; if (pv && !pv._cty) { V.visao = sub => { const h = pv(sub), i = h.indexOf('</header>'), bar = `<div class="ctry-bar">${CTY.btn()}<small class="mut">as marcas da dieta e os simuladores seguem este país</small></div>`; return i > 0 ? h.slice(0, i + 9) + bar + h.slice(i + 9) : bar + h; }; V.visao._cty = 1; } });
const BR = (OS.FoodBrands || []).map((r, i) => ({ id: 'br' + i, name: r[0], brand: r[1], kcal: r[2], p: r[3], c: r[4], f: r[5], fib: r[6], cat: 'Marcas', por: r[7] ? ['porção', r[7]] : null, pic: r[8], cc: r[9] || 'PT', nn: norm(r[0] + ' ' + r[1]) }));
const FF = (OS.FastFood || []).map((r, i) => ({ id: 'ff' + i, name: r[1], brand: r[0], kcal: Math.round(r[2] / r[6] * 100), p: U.r1(r[3] / r[6] * 100), c: U.r1(r[4] / r[6] * 100), f: U.r1(r[5] / r[6] * 100), fib: 0, cat: 'Fast food', por: ['unidade', r[6]], cc: r[7], nn: norm(r[1] + ' ' + r[0]) }));
const here = x => x.cc === '*' || String(x.cc).split(',').includes(CTY.code());
const brHere = () => BR.filter(here), ffHere = () => FF.filter(here);
Diet.FF = FF;
Diet.BR = BR;
const OFFC = {}; // produtos encontrados online nesta sessão
const PIC = 'https://www.themealdb.com/images/ingredients/';
// fotos reais: pratos e alimentos (Wikimedia Commons) e ingredientes (TheMealDB); marcas: foto da embalagem (Open Food Facts)
const PK = [[/zinger|frango original|hot wings|popcorn chicken|nuggets|sanduiche de frango|mcchicken|chicken royale|long chicken|crispy/, 'nuggets'], [/whopper|big mac|cheeseburger|hamburguer|burger|cbo|big tasty|quarteirao|mcroyal|dave|big bob|h3/, 'hamburguer'], [/batatas? fritas/, 'batatafrita'], [/mcflurry|sundae|milk-shake|frappuccino/, 'gelado'], [/macchiato|latte|cappuccino/, 'cafe'], [/esfiha|bib/, 'pastel'], [/taco crocante|burrito/, 'burrito'], [/subway|teriyaki|b\.m\.t|bocadillo|peito de peru 15|atum 15|cachorro|hot dog/, 'sandes'], [/almondegas/, 'esparguete_bol'], [/fatia margherita|fatia pepperoni|fatia barbecue|pao de alho/, 'pizza'], [/muffin|donut glaceado/, 'donut'], [/bloomin/, 'batatafrita'], [/brutos|massa com frango|burrito bowl|prato/, 'marmita'], [/francesinha/, 'francesinha'], [/feijoada/, 'feijoada'], [/pastel de nata/, 'nata'], [/bacalhau a bras/, 'brasbacalhau'], [/caldo verde/, 'caldoverde'], [/cozido a portuguesa/, 'cozido'], [/bitoque/, 'bitoque'], [/kebab|durum/, 'kebab'], [/burrito/, 'burrito'], [/tosta/, 'tosta'], [/sandes/, 'sandes'], [/pizza/, 'pizza'], [/sushi/, 'sushi'], [/hamburguer no pao|big mac/, 'hamburguer'], [/nuggets/, 'nuggets'], [/coxinha/, 'coxinha'], [/pao de queijo/, 'paodequeijo'], [/tapioca/, 'tapioca'], [/acai/, 'acai'], [/estrogonofe/, 'estrogonofe'], [/yakisoba/, 'yakisoba'], [/lasanha/, 'lasanha'], [/esparguete a bolonhesa|macarrao, molho bolognesa/, 'esparguete_bol'], [/arroz de frango|arroz de pato|arroz carreteiro|baiao/, 'arrozfrango'], [/marmita/, 'marmita'], [/panqueca proteica/, 'panquecaprot'], [/panqueca/, 'panqueca'], [/croissant/, 'croissant'], [/bola de berlim/, 'berlim'], [/donut/, 'donut'], [/quindim/, 'quindim'], [/empada/, 'empada'], [/croquete/, 'croquete'], [/rissol/, 'rissol'], [/pastel/, 'pastel'], [/brigadeiro/, 'brigadeiro'], [/pudim/, 'pudim'], [/farofa/, 'farofa'], [/sopa|caldo de|creme de abobora/, 'sopa'], [/salada/, 'salada'],
  [/whey|caseina|proteina vegetal|hipercalorico|isolada/, 'whey'], [/barra proteica|barra de cereal/, 'barra'], [/pipoca/, 'pipoca'], [/gelado|sorvete/, 'gelado'], [/gomas/, 'gomas'], [/bolo/, 'bolo'], [/bolacha|biscoito|cookie/, 'bolacha'], [/doce de leite/, 'doceleite'],
  [/bebida energetica/, 'energetica'], [/refrigerante|coca|guarana|tonica/, 'refrigerante'], [/sumo|suco|nectar/, 'sumo'], [/kefir/, 'kefir'], [/kombucha|isoton/, 'refrigerante'],
  [/arroz integral/, 'arrozint'], [/arroz|risoto/, 'arroz'], [/cuscuz/, 'cuscuz'], [/quinoa/, 'arroz'], [/feijao|baiao|guandu/, 'feijao'], [/grao-de-bico|grao de bico/, 'grao'], [/lentilha/, 'lentilha'], [/tremoco/, 'tremoco'], [/edamame|soja, grao/, 'edamame'], [/humus/, 'humus'], [/tofu/, 'tofu'],
  [/aveia|mingau|papas/, 'aveia'], [/granola|muesli/, 'granola'], [/cereal|cornflakes|flocos/, 'cereais'], [/bagel/, 'bagel'], [/tortilha|wrap/, 'wrap'], [/pao de forma|pao, trigo, forma|pao, aveia|pao, de soja|pao, glúten|pao, milho/, 'paoforma'], [/pao|torrada|papo-seco|carcaca/, 'pao'],
  [/iogurte|skyr|leite fermentado|petit suisse/, 'iogurte'], [/requeijao|queijo creme|philadelphia/, 'requeijao'], [/queijo/, 'queijo'], [/manteiga de amendoim/, 'mantamendoim'], [/manteiga|margarina/, 'manteiga'], [/leite de coco|coco/, 'coco'], [/leite|bebida de|bebida lactea|natas|creme de leite|chantilly|achocolatado/, 'leite'],
  [/amendoim|pacoca/, 'amendoim'], [/pistacio/, 'pistacio'], [/mix de frutos|frutos secos/, 'frutossecos'], [/sementes|chia|linhaca|gergelim/, 'sementes'], [/farinha|polvilho|fecula|amido|fuba/, 'farinha'], [/massa|macarrao|esparguete|espaguete|nhoque/, 'massa'],
  [/lula|polvo/, 'lula'], [/peito de peru|fiambre de peru|peru/, 'peru'], [/milho|curau|pamonha/, 'milho'], [/chourico|salsicha|linguica|salame|mortadela/, 'salsicha'], [/acucar|rapadura|melado|glicose/, 'acucar'], [/mel\b|mel,|^mel/, 'mel'], [/melancia/, 'melancia'], [/melao/, 'melao'], [/uva/, 'uva'], [/cereja/, 'cereja'], [/mamao|papaia/, 'papaia'], [/goiaba/, 'goiaba'], [/maracuja/, 'maracuja'],
  [/ovos mexidos/, 'ovomexido'], [/omelete/, 'omelete'], [/chocolate/, 'chocolate'], [/cafe|expresso|bica|galao|cappuccino/, 'cafe'], [/cerveja/, 'cerveja'], [/vinho/, 'vinho'], [/cha\b|cha,/, 'cha'], [/agua/, 'agua'], [/batata-doce|batata doce/, 'batatadoce'], [/batata frita|batata, inglesa, frita|chips/, 'batatafrita'], [/mandioca|aipim/, 'mandioca']];
const PICS = [[/frango.*assad|frango assado|frango, inteiro/, 'Chicken'], [/frango|galinha/, 'Chicken Thighs'], [/carne picada|moido|moida|almondega|hamburguer/, 'Minced Beef'], [/bife|picanha|alcatra|patinho|maminha|contra-file|fraldinha|file mignon/, 'Sirloin steak'], [/carne|vaca|bovina|cupim/, 'Beef'],
  [/bacon|toucinho/, 'Bacon'], [/fiambre|presunto|apresuntado/, 'Ham'], [/porco|lombo|entrecosto|pernil|bisteca/, 'Pork Chops'], [/salmao/, 'Salmon'], [/atum/, 'Tuna'], [/sardinha/, 'Sardines'], [/bacalhau/, 'Cod'], [/camarao|gambas/, 'Shrimp'], [/pescada|merluza|peixe|dourada|robalo|abadejo|cacao|tilapia|corvina/, 'White Fish'],
  [/clara/, 'Egg White'], [/ovo/, 'Eggs'], [/mozarela|mozzarella/, 'Mozzarella Balls'], [/azeite/, 'Olive Oil'], [/oleo/, 'Vegetable Oil'], [/maionese/, 'Mayonnaise'], [/ketchup/, 'Tomato Ketchup'], [/mostarda/, 'Mustard'], [/molho de soja|shoyu/, 'Soy Sauce'],
  [/banana/, 'Banana'], [/maca/, 'Apples'], [/laranja|tangerina|mexerica|clementina/, 'Orange'], [/limao/, 'Lemon'], [/morango/, 'Strawberries'], [/mirtilo/, 'Blueberries'], [/framboesa/, 'Raspberries'], [/pera/, 'Pears'], [/pessego/, 'Peaches'], [/abacate/, 'Avocado'], [/manga/, 'Mango'], [/abacaxi|ananas/, 'Pineapple'], [/kiwi/, 'Kiwi'], [/tamara/, 'Medjool Dates'], [/passa/, 'Raisins'], [/figo/, 'Figs'], [/ameixa/, 'Prunes'], [/roma/, 'Pomegranate'], [/damasco/, 'Apricot'],
  [/brocol/, 'Broccoli'], [/cenoura/, 'Carrots'], [/tomate/, 'Tomatoes'], [/cebola/, 'Onions'], [/alho/, 'Garlic'], [/alface|rucula|agriao|chicoria/, 'Lettuce'], [/espinafre/, 'Spinach'], [/couve/, 'Kale'], [/repolho/, 'Cabbage'], [/pepino/, 'Cucumber'], [/pimentao/, 'Red Pepper'], [/abobrinha|courgette/, 'Zucchini'], [/abobora/, 'Pumpkin'], [/berinjela/, 'Aubergine'], [/cogumelo|champignon/, 'Mushrooms'], [/espargo/, 'Asparagus'], [/beterraba/, 'Beetroot'], [/vagem/, 'Green Beans'],
  [/amendoa/, 'Almonds'], [/noz|nozes/, 'Walnuts'], [/caju/, 'Cashew Nuts'], [/avela/, 'Hazlenuts'], [/batata/, 'Potatoes']];
const CATK = { 'Cereais e pães': 'pao', 'Legumes e verduras': 'legumes', 'Frutas': 'fruta', 'Gorduras e óleos': 'azeite', 'Peixe e marisco': 'peixe', 'Carne': 'bife', 'Lácteos': 'leite', 'Bebidas': 'agua', 'Ovos': 'ovo', 'Doces': 'doce', 'Outros': 'molho', 'Pratos prontos': 'marmita', 'Leguminosas': 'feijao', 'Frutos secos e sementes': 'frutossecos', 'Suplementos': 'whey' };
const FP = OS.FoodPics || {};
const picCache = {};
const FPN = {}; Object.entries(OS.FoodPhoto || {}).forEach(([k, v]) => { FPN[norm(k)] = v; });
/* ================= catálogo: cada alimento uma vez, com as variantes (cru, cozido, grelhado…) lá dentro ================= */
const GR = [], byName = {}, dupes = {}; DB.forEach(x => { if (!byName[x.name]) byName[x.name] = x; else (dupes[x.name] = dupes[x.name] || []).push(x); });
(OS.FoodCat || []).forEach((r, i) => { const vars = r[4].map(([l, nm]) => ({ l, x: byName[nm] })).filter(v => v.x); if (!vars.length) return;
  const d = vars[0].x, g = { id: 'g' + i, name: r[0], desc: r[1], pic: r[2], bk: r[3], cat: d.cat, vars, def: d, kcal: d.kcal, p: d.p, c: d.c, f: d.f, fib: d.fib, por: d.por, nn: norm(r[0] + ' ' + vars.map(v => v.l + ' ' + v.x.name).join(' ')) };
  vars.forEach(v => (dupes[v.x.name] || []).forEach(d => { d.g = g; d.vl = v.l; if (g.pic) d.pic = g.pic; }));
  vars.forEach(v => { v.x.g = g; v.x.vl = v.l; if (g.pic) { v.x.pic = g.pic; FPN[norm(v.x.name)] = g.pic; } }); if (g.pic) { FPN[norm(g.name)] = g.pic; vars.forEach(v => { FPN[norm(g.name + ' · ' + v.l)] = g.pic; }); } GR.push(g); });
Diet.GR = GR;
const gName = (x, brand) => (x.g ? x.g.name + (x.g.vars.length > 1 ? ' · ' + x.vl.toLowerCase() : '') : x.name.replace(/ \(unidade média\)/, '')) + (brand ? ` (${brand})` : '');
Diet.gName = gName;
Diet.pic = (name, cat) => { const k = norm(name); if (picCache[k] !== undefined) return picCache[k]; let r = FPN[k] && FPN[k] !== 'W' ? { u: FPN[k], c: /themealdb/.test(FPN[k]) ? 1 : 0 } : null; if (r) return picCache[k] = r;
  for (const [rx, key] of PK) if (rx.test(k) && FP[key]) { r = { u: FP[key], c: /themealdb/.test(FP[key]) ? 1 : 0 }; break; }
  if (!r) for (const [rx, ing] of PICS) if (rx.test(k)) { r = { u: PIC + encodeURIComponent(ing) + '-Small.png', c: 1 }; break; }
  if (!r) { const d = DB.find(x => x.nn === k), key = CATK[cat || (d && d.cat)] || 'marmita'; r = FP[key] ? { u: FP[key] } : { u: '' }; }
  return picCache[k] = r; };
// foto própria de cada alimento: procurada na Wikipédia em português a partir deste aparelho, guardada e sincronizada
OS.ONE_DEF.foodpics = { m: {} };
const STW = new Set('cru crua crus cruas cozido cozida cozidos cozidas grelhado grelhada frito frita fritos fritas assado assada refogado refogada congelado congelada com sem de da do dos das e tipo para pre pronto pronta unidade media inteiro inteira posta file capa gordura pele sal oleo soja enlatado enlatada drenado drenada conserva em calda industrializado industrializada sabor'.split(' '));
Diet.picQuery = name => { let w = norm(name).replace(/[(),%/.0-9]/g, ' ').split(/\s+/).filter(x => x.length > 2 && !STW.has(x)); if (w[0] === 'carne' && w[1] === 'bovina') w = w.slice(2).concat('carne'); return w.slice(0, 4).join(' '); };
const DBN = new Set(DB.map(x => x.nn));
OS.ONE_DEF.foodpics = OS.ONE_DEF.foodpics || { m: {} };
Diet.img = (name, cat, cls = '', pic) => { if (!pic && FPN[norm(name)] && FPN[norm(name)] !== 'W') pic = FPN[norm(name)];
  const p = pic ? { u: pic } : Diet.pic(name, cat); return p.u ? `<span class="fdi ${cls}${p.c && !pic ? ' cut' : ''}${pic && /openfoodfacts/.test(pic) ? ' brand' : ''}"><img src="${esc(p.u)}" alt="" loading="lazy" decoding="async" referrerpolicy="no-referrer" onerror="this.parentNode.classList.add('noimg');this.remove()"></span>` : `<span class="fdi ${cls} noimg" aria-hidden="true"></span>`; };
/* ================= procurar ================= */
const userFoods = () => OS.all('foods').map(f => ({ id: 'u' + f.id, name: f.name, kcal: n(f.kcal), p: n(f.p), c: n(f.c), f: n(f.f), fib: n(f.fib), cat: 'Os meus', por: [f.portion || '1 porção', 0], per: 'portion', nn: norm(f.name), uid: f.id }));
Diet.search = (q, lim = 40) => { const w = norm(q).split(/\s+/).filter(Boolean); if (!w.length) return [];
  const score = x => { let s = 0; w.forEach(t => { const i = x.nn.indexOf(t); if (i < 0) s -= 1e3; else s += (i === 0 ? 30 : x.nn[i - 1] === ' ' || x.nn[i - 1] === ',' ? 15 : 3); }); if (x.uid) s += 25; s -= (x.vars ? norm(x.name).length : x.nn.length) / 20; if (x.vars) s -= (+x.id.slice(1)) * .004 + (x.cat === 'Pratos prontos' ? 4 : 0); if (!x.vars && /\bcru|crua\b/.test(x.nn) && !w.some(t => t.startsWith('cru'))) s -= 6; if (/coracao|figado|moela|lingua|bucho|orelha|rabo|toucinho|dobradinha|sarapatel/.test(x.nn) && !w.some(t => /coracao|figado|moela|lingua|bucho|orelha|rabo/.test(t))) s -= 12; return s; };
  const seen = new Set(); return [...userFoods(), ...brHere(), ...ffHere(), ...GR, ...DB.filter(x => !x.g)].map(x => [score(x) + (x.vars ? 8 : 0), x]).filter(([s]) => s > -1e3 / 2).sort((a, b) => b[0] - a[0]).map(x => x[1]).filter(x => !seen.has(x.id) && seen.add(x.id)).slice(0, lim); };
Diet.searchGroups = (q, lim = 80) => Diet.search(q, 200).filter(x => x.vars).slice(0, lim);
const recents = () => { const seen = new Set(), out = []; U.sortBy(OS.all('meals'), m => m.date + (m.created || ''), -1).forEach(m => { const k = norm(m.food); if (!k || seen.has(k) || out.length >= 30) return; seen.add(k); out.push(m); }); return out; };
const macrosFor = (x, g, units) => { if (x.per === 'portion') { const q = units || 1; return { kcal: Math.round(x.kcal * q), p: U.r1(x.p * q), c: U.r1(x.c * q), f: U.r1(x.f * q), fib: U.r1((x.fib || 0) * q) }; } const k = g / 100; return { kcal: Math.round(x.kcal * k), p: U.r1(x.p * k), c: U.r1(x.c * k), f: U.r1(x.f * k), fib: U.r1((x.fib || 0) * k) }; };

/* ================= janela "adicionar alimento" ================= */
let FS = null; // { meal, date, tab, q, sel, unit, amt, tpl: [] | null (construtor de refeição fixa), added }
const fh = () => { let h = document.getElementById('fdAdd'); if (!h) { h = document.createElement('div'); h.id = 'fdAdd'; h.hidden = true; document.body.appendChild(h); h.addEventListener('click', fClick); h.addEventListener('input', fInput); h.addEventListener('change', fInput); } return h; };
Diet.add = (opt = {}) => { FS = { meal: opt.meal || nowMeal(), date: opt.date || Diet.dayNow(), tab: opt.tab || 'procurar', q: '', sel: null, unit: 'g', amt: 100, tpl: opt.tpl || null, tplName: opt.tplName || '', tplId: opt.tplId || '', added: 0 }; fh().hidden = false; document.body.classList.add('noscroll'); fDraw(); if (FS.tab === 'procurar') setTimeout(() => { const i = fh().querySelector('[data-fq]'); i && matchMedia('(min-width:700px)').matches && i.focus(); }, 60); if (FS.tab === 'foto') setTimeout(() => { const i = fh().querySelector('#fdCam'); i && i.click(); }, 80); };
const fClose = () => { FS = null; fh().hidden = true; fh().innerHTML = ''; document.body.classList.remove('noscroll'); OS.request(); };
const fRow = (x, extra = '') => x.vars ? `<button class="fd-r" data-fa="pick" data-id="${x.id}">${Diet.img(x.name, x.cat, '', x.pic)}<span><b>${esc(x.name)}</b><small>${U.nf(x.kcal)} kcal <em>/100 g ${x.vars.length > 1 ? esc(x.def.vl.toLowerCase()) : ''}</em>${x.vars.length > 1 ? ` · ${x.vars.length} opções` : ''} · <em class="fd-dsc">${esc(x.desc)}</em></small></span>${UI.ic('right')}</button>` : `<button class="fd-r" data-fa="pick" data-id="${x.id}">${Diet.img(x.name, x.cat, '', x.pic)}<span><b>${esc(x.name)}${x.brand ? ` <em class="fd-br">${esc(x.brand)}</em>` : ''}</b><small>${x.per === 'portion' ? `${esc(x.por[0])} · ${U.nf(x.kcal)} kcal` : `${U.nf(x.kcal)} kcal · P ${U.nf(x.p, 1)} · H ${U.nf(x.c, 1)} · G ${U.nf(x.f, 1)} <em>/100 g</em>`}${extra}</small></span>${UI.ic('plus')}</button>`;
const findX = id => id.startsWith('ff') ? FF.find(x => x.id === id) : id.startsWith('br') ? BR.find(x => x.id === id) : id.startsWith('off:') || id.startsWith('bp:') ? OFFC[id] : id.startsWith('u') ? userFoods().find(x => x.id === id) : id.startsWith('r:') ? (() => { const m = OS.get('meals', id.slice(2)); if (!m) return null; const g = n(m.g), q = n(m.qty) || 1; return g ? { id, pic: m.pic || '', name: m.food, kcal: n(m.kcal) / g * 100, p: n(m.p) / g * 100, c: n(m.c) / g * 100, f: n(m.f) / g * 100, fib: n(m.fib) / g * 100, nn: norm(m.food), lastG: g } : { id, name: m.food, kcal: n(m.kcal) / q, p: n(m.p) / q, c: n(m.c) / q, f: n(m.f) / q, fib: n(m.fib) / q, per: 'portion', por: ['porção', 0], pic: m.pic || '', nn: norm(m.food) }; })() : id.startsWith('g') ? GR.find(x => x.id === id) : DB.find(x => x.id === id);
const selMac = () => { const x = FS.sel; return x.per === 'portion' ? macrosFor(x, 0, n(FS.amt) || 0) : FS.unit === 'u' ? macrosFor(x, n(FS.amt) * x.por[1]) : macrosFor(x, n(FS.amt)); };
const macHTML = () => { const mm = selMac(); return `<div class="fd-mac"><div><b class="mono">${U.nf(mm.kcal)}</b><small>kcal</small></div><div><b class="mono">${U.nf(mm.p, 1)}</b><small>proteína</small></div><div><b class="mono">${U.nf(mm.c, 1)}</b><small>hidratos</small></div><div><b class="mono">${U.nf(mm.f, 1)}</b><small>gordura</small></div><div><b class="mono">${U.nf(mm.fib, 1)}</b><small>fibra</small></div></div>`; };
const COUNT = /^(ovo|clara|unidade|fatia|pao|wrap|scoop|barra|bolacha|quadrado|copo|lata|imperial|iogurte|chavena|6 unidades|meio|colher de sopa|medida|porcao)$/;
const fDraw = () => { const h = fh(); if (!FS) return; const s = FS, sel = s.sel;
  const tabs = [['procurar', 'Procurar'], ['marcas', 'Marcas'], ['recentes', 'Recentes'], ['fixas', 'Refeições fixas'], ['foto', 'Foto (IA)']].filter(([k]) => !(s.tpl && (k === 'fixas' || k === 'foto')));
  let body = '';
  if (sel) { const x = sel, g = s.grp, opts = x.per === 'portion' ? [['p', x.por[0]]] : [['g', 'gramas'], ...(x.por ? [['u', `${x.por[0]} (${x.por[1]} g)`]] : [])], prod = x !== s.base && s.base;
    body = `<div class="fd-sel">${Diet.img(g && !prod ? g.name : x.name, x.cat, 'lg', x.pic || (g && g.pic))}<h3>${esc(g && !prod ? g.name : x.name)}</h3>${prod && x.brand ? `<p class="fd-br">${esc(x.brand)}</p>` : s.brand ? `<p class="fd-br">${esc(s.brand)}</p>` : ''}${g && !prod ? `<p class="fd-desc">${esc(g.desc)}</p>` : ''}
      ${g && g.vars.length > 1 ? `<div class="fd-lab">Escolhe</div><div class="fd-vars">${g.vars.map((v, k) => `<button class="chip ${s.base === v.x ? 'on' : ''}" data-fa="var" data-k="${k}">${esc(v.l)}</button>`).join('')}</div>` : ''}
      ${s.base ? `<div class="fd-brands"><div class="fd-bh"><div class="fd-lab">Marca</div>${CTY.btn('sm')}</div><div class="fd-bl">${brandCards()}</div></div>` : ''}
      <p class="mut fd-per">${x.per === 'portion' ? 'por ' + esc(x.por[0]) : 'valores por 100 g: ' + U.nf(x.kcal) + ' kcal'}${s.brand && !prod ? ' · valores médios' : ''}</p>
      <div class="fd-q"><input class="field" type="text" inputmode="decimal" data-famt value="${esc(s.amt)}" aria-label="Quantidade"><select class="field" data-funit aria-label="Unidade">${opts.map(([v, l]) => `<option value="${v}"${s.unit === v ? ' selected' : ''}>${esc(l)}</option>`).join('')}</select></div>
      ${x.per !== 'portion' ? `<div class="fd-chips">${(s.unit === 'u' ? [.5, 1, 2, 3] : [50, 100, 150, 200, 250]).map(v => `<button class="chip ${+s.amt === v ? 'on' : ''}" data-fa="amt" data-v="${v}">${s.unit === 'u' ? U.nf(v, v % 1 ? 1 : 0) : v + ' g'}</button>`).join('')}</div>` : ''}
      ${macHTML()}
      <div class="row gap8"><button class="btn ghost" data-fa="back">${UI.ic('left')}Voltar</button><button class="btn pri grow" data-fa="add">${UI.ic('plus')}${s.tpl ? 'Juntar à refeição fixa' : 'Adicionar a ' + esc(s.meal)}</button></div></div>`; }
  else if (s.tab === 'procurar') { const r = Diet.search(s.q); body = `<input type="search" class="field fd-s" data-fq value="${esc(s.q)}" placeholder="Procurar entre ${DB.length} alimentos (ex.: frango, arroz, iogurte)" aria-label="Procurar alimento">
      <div class="fd-list">${s.q ? (r.map(x => fRow(x)).join('') || `<p class="mut fd-p">Sem resultados. Tenta outra palavra ou cria o alimento.</p>`) : `<p class="mut fd-p">Escreve o nome do alimento. Também podes ver os <b>Recentes</b> ou tirar uma <b>Foto</b>.</p>${recents().slice(0, 8).map(m => fRow({ id: 'r:' + m.id, name: m.food, pic: m.pic || '', kcal: n(m.kcal), p: n(m.p), c: n(m.c), f: n(m.f), per: 'portion', por: [n(m.g) ? U.nf(m.g) + ' g' : 'porção', 0] }, '')).join('')}`}</div>
      <button class="btn ghost sm" data-fa="new">${UI.ic('plus')}Criar alimento</button>`; }
  else if (s.tab === 'marcas') { const chains = [...new Set(ffHere().map(x => x.brand))], ch = s.chain || '', loc = s.bq ? Diet.search(s.bq, 60).filter(x => x.cat === 'Marcas' || x.cat === 'Fast food') : ch ? ffHere().filter(x => x.brand === ch) : brHere().slice(0, 30), on = (OFFQ[offKey(s.bq || '')] || {});
    body = `<div class="fd-bh">${CTY.btn('sm')}<small class="mut">marcas e fast food de ${esc(CTY.get()[1])}</small></div><div class="wk-chips">${chains.map(c => `<button class="chip ${ch === c ? 'on' : ''}" data-fa="chain" data-v="${esc(c)}">${esc(c)}</button>`).join('')}</div><form class="fd-bq" data-fbq-form><input type="search" class="field" data-fbq value="${esc(s.bq || '')}" placeholder="Marca ou produto (ex.: Skyr Pingo Doce, Mimosa, Danone)" aria-label="Procurar marca"><button class="btn pri" data-fa="bqgo">${UI.ic('search')}</button></form>
      <div class="fd-list">${loc.map(x => fRow(x)).join('')}${on.busy ? `<div class="fd-spin"></div>` : ''}${(on.items || []).map(x => fRow(x)).join('')}${on.err ? `<p class="mut fd-p">${esc(on.err)}</p>` : ''}${!s.bq ? `<p class="mut fd-p">Escreve uma marca ou produto (ex.: Milaneza, Mimosa, Continente) e toca na lupa: procuro nos produtos vendidos no país escolhido. Ou escolhe uma cadeia de fast food acima.</p>` : !on.busy && on.items && !on.items.length && !loc.length ? `<p class="mut fd-p">Sem resultados. Tenta outro nome.</p>` : ''}</div>`; }
  else if (s.tab === 'recentes') { const r = recents(); body = `<div class="fd-list">${r.map(m => fRow({ id: 'r:' + m.id, name: m.food, pic: m.pic || '', kcal: n(m.kcal), p: n(m.p), c: n(m.c), f: n(m.f), per: 'portion', por: [n(m.g) ? U.nf(m.g) + ' g' : `× ${U.nf(n(m.qty) || 1, 1)}`, 0] })).join('') || `<p class="mut fd-p">Ainda não registaste nada.</p>`}</div>`; }
  else if (s.tab === 'fixas') { const R = OS.all('mealtpl'); body = `<div class="fd-list">${R.map(t => `<button class="fd-r" data-fa="tpl" data-id="${t.id}">${Diet.img((t.items[0] || {}).food || t.name, '', '', (t.items[0] || {}).pic)}<span><b>${esc(t.name)}</b><small>${t.items.length} alimentos · ${U.nf(U.sum(t.items, i => i.kcal))} kcal · P ${U.nf(U.sum(t.items, i => i.p))} g</small></span>${UI.ic('plus')}</button>`).join('') || `<p class="mut fd-p">Ainda não tens refeições fixas. Cria-as em Dieta → Refeições fixas, ou guarda uma refeição do dia com "Guardar como fixa".</p>`}</div>`; }
  else if (s.tab === 'foto') body = photoBody();
  h.innerHTML = `<div class="fd" role="dialog" aria-modal="true" aria-label="Adicionar alimento"><header class="wk-top"><button class="icon-btn" data-fa="x" aria-label="Fechar">${UI.ic('x')}</button><b class="wk-ttl">${s.tpl ? 'Refeição fixa' : ''}${s.tpl ? '' : `<select class="fd-meal" data-fmeal aria-label="Refeição">${MEALS.map(m => `<option${m === s.meal ? ' selected' : ''}>${m}</option>`).join('')}</select>`}</b>${s.tpl ? `<button class="btn pri sm" data-fa="tplsave">Guardar</button>` : s.added ? `<button class="btn pri sm" data-fa="x">Concluir (${s.added})</button>` : '<span></span>'}</header>
    ${s.tpl ? `<div class="fd-tpl"><input class="field" data-ftn value="${esc(s.tplName)}" placeholder="Nome (ex.: Pequeno-almoço de sempre)" aria-label="Nome da refeição fixa"><select class="field" data-ftm aria-label="Refeição">${MEALS.map(m => `<option${m === s.meal ? ' selected' : ''}>${m}</option>`).join('')}</select>
      <div class="fd-ti">${s.tpl.map((i, k) => `<div>${Diet.img(i.food, '', '', i.pic)}<span><b>${esc(i.food)}</b><small>${n(i.g) ? U.nf(i.g) + ' g · ' : ''}${U.nf(i.kcal)} kcal · P ${U.nf(i.p)} g</small></span><button class="icon-btn" data-fa="tdel" data-k="${k}" aria-label="Tirar">${UI.ic('x')}</button></div>`).join('') || '<small class="mut">Procura e junta os alimentos desta refeição.</small>'}</div>${s.tpl.length ? `<small class="mono mut">Total: ${U.nf(U.sum(s.tpl, i => i.kcal))} kcal · P ${U.nf(U.sum(s.tpl, i => i.p))} · H ${U.nf(U.sum(s.tpl, i => i.c))} · G ${U.nf(U.sum(s.tpl, i => i.f))}</small>` : ''}</div>` : ''}
    ${sel ? '' : `<nav class="tabs fd-tabs">${tabs.map(([k, l]) => `<a href="#" class="${s.tab === k ? 'on' : ''}" data-fa="tab" data-v="${k}">${l}</a>`).join('')}</nav>`}<div class="fd-b">${body}</div></div>`;
  const fq = h.querySelector('[data-fq]'); if (fq && document.activeElement !== fq && FS._focusQ) { fq.focus(); fq.setSelectionRange(fq.value.length, fq.value.length); } };
const listOnly = () => { const h = fh(), l = h.querySelector('.fd-list'); if (!l) return fDraw(); const r = Diet.search(FS.q); l.innerHTML = FS.q ? (r.map(x => fRow(x)).join('') || `<p class="mut fd-p">Sem resultados. Tenta outra palavra ou cria o alimento.</p>`) : `<p class="mut fd-p">Escreve o nome do alimento.</p>`; };
const deb = U.deb(listOnly, 140);
function fInput(e) { const t = e.target; if (!FS) return;
  if (t.dataset.fq != null) { FS.q = t.value; deb(); return; }
  if (t.dataset.fbq != null) { FS.bq = t.value; return; }
  if (t.dataset.famt != null) { FS.amt = t.value.replace(',', '.'); const m = fh().querySelector('.fd-mac'); if (m) m.outerHTML = macHTML(); fh().querySelectorAll('[data-fa=amt]').forEach(c => c.classList.toggle('on', +c.dataset.v === n(FS.amt))); return; }
  if (t.dataset.funit != null) { FS.unit = t.value; FS.amt = t.value === 'u' ? 1 : (FS.sel.lastG || 100); fDraw(); return; }
  if (t.dataset.fmeal != null) { FS.meal = t.value; return; }
  if (t.dataset.ftn != null) { FS.tplName = t.value; return; }
  if (t.dataset.ftm != null) { FS.meal = t.value; return; } }
function fClick(e) { const b = e.target.closest('[data-fa]'); if (!b || !FS) return; e.preventDefault(); const a = b.dataset.fa;
  if (a === 'x') return fClose();
  if (a === 'tab') { FS.tab = b.dataset.v; fDraw(); if (FS.tab === 'foto') setTimeout(() => { const i = fh().querySelector('#fdCam'); if (i && !PH.items) i.click(); }, 50); return; }
  if (a === 'pick') { let x = findX(b.dataset.id); if (!x) return; FS.brand = ''; FS.grp = x.vars ? x : x.g || null; if (x.vars) x = x.def; FS.sel = x; FS.base = /^db/.test(x.id) ? x : null; if (FS.base) brandData(brandsRefresh); FS.unit = x.per === 'portion' ? 'p' : x.por && !x.lastG && COUNT.test(norm(x.por[0])) ? 'u' : 'g'; FS.amt = x.per === 'portion' ? 1 : FS.unit === 'u' ? 1 : (x.lastG || 100); fDraw(); return; }
  if (a === 'back') { FS.sel = null; FS.base = null; FS.grp = null; FS.brand = ''; fDraw(); return; }
  if (a === 'var') { const v = FS.grp && FS.grp.vars[+b.dataset.k]; if (!v) return; const keepU = FS.unit === 'u' && v.x.por; FS.sel = FS.base = v.x; if (!keepU && FS.unit === 'u') { FS.unit = 'g'; FS.amt = 100; } fDraw(); return; }
  if (a === 'bname') { FS.brand = FS.brand === b.dataset.v ? '' : b.dataset.v; FS.sel = FS.base; fDraw(); return; }
  if (a === 'brand') { const id = b.dataset.id, x = id === 'gen' ? FS.base : findX(id) || OFFC[id]; if (!x) return; FS.brand = ''; const wasU = FS.unit === 'u'; FS.sel = x; if (wasU && !x.por) { FS.unit = 'g'; FS.amt = 100; } if (FS.unit === 'u' && x.por) FS.amt = FS.amt || 1; fDraw(); return; }
  if (a === 'amt') { FS.amt = +b.dataset.v; fDraw(); return; }
  if (a === 'add') { const x = FS.sel, g = x.per === 'portion' ? 0 : FS.unit === 'u' ? n(FS.amt) * x.por[1] : n(FS.amt); if (x.per !== 'portion' && !g) { UI.toast('Indica a quantidade', 'warn'); return; }
    const m = x.per === 'portion' ? macrosFor(x, 0, n(FS.amt) || 1) : macrosFor(x, g), rec = { food: x.brand ? `${FS.grp && x.gg && !norm(x.name).includes(norm(FS.grp.name).split(/[ (]/)[0]) ? FS.grp.name + ' — ' : ''}${x.name} (${x.brand})` : gName(x, FS.brand), pic: x.pic || (x.g && x.g.pic) || '', g: g || '', qty: x.per === 'portion' ? n(FS.amt) || 1 : 1, kcal: m.kcal, p: m.p, c: m.c, f: m.f, fib: m.fib };
    if (FS.tpl) { FS.tpl.push(rec); FS.sel = null; UI.toast('Junto: ' + rec.food, 'pos'); fDraw(); return; }
    OS.add('meals', Object.assign({ date: FS.date, meal: FS.meal }, rec)); FS.added++; FS.sel = null; UI.toast(`${rec.food} · ${U.nf(rec.kcal)} kcal`, 'pos'); fDraw(); return; }
  if (a === 'tpl') { const t = OS.get('mealtpl', b.dataset.id); if (!t) return; Diet.applyTpl(t, FS.date, FS.meal); FS.added += t.items.length; fDraw(); return; }
  if (a === 'new') { const nm = FS.q; fClose(); UI.openForm('foods', null, { name: nm }); return; }
  if (a === 'tdel') { FS.tpl.splice(+b.dataset.k, 1); fDraw(); return; }
  if (a === 'tplsave') { const name = (FS.tplName || '').trim(); if (!name) { UI.toast('Dá um nome à refeição fixa', 'warn'); fh().querySelector('[data-ftn]').focus(); return; } if (!FS.tpl.length) { UI.toast('Junta pelo menos um alimento', 'warn'); return; }
    const o = { name, meal: FS.meal, items: FS.tpl }; if (FS.tplId && OS.get('mealtpl', FS.tplId)) OS.upd('mealtpl', FS.tplId, o); else OS.add('mealtpl', o); UI.toast('Refeição fixa guardada', 'pos'); fClose(); return; }
  if (a === 'chain') { FS.chain = FS.chain === b.dataset.v ? '' : b.dataset.v; FS.bq = ''; fDraw(); return; }
  if (a === 'bqgo') { const i = fh().querySelector('[data-fbq]'); FS.bq = i ? i.value.trim() : ''; fDraw(); offSearch(FS.bq); return; }
  if (a === 'phgo') return photoRun();
  if (a === 'phtoggle') { const it = PH.items[+b.dataset.k]; it.off = !it.off; fDraw(); return; }
  if (a === 'phadd') { const its = PH.items.filter(i => !i.off); its.forEach(i => OS.add('meals', { date: FS.date, meal: FS.meal, food: i.nome, g: n(i.gramas) || '', qty: 1, kcal: Math.round(n(i.kcal)), p: U.r1(n(i.proteina)), c: U.r1(n(i.hidratos)), f: U.r1(n(i.gordura)), fib: U.r1(n(i.fibra)), src: 'foto' })); UI.toast(`${its.length} alimentos registados`, 'pos'); FS.added += its.length; PH.items = null; PH.img = ''; fClose(); return; }
  if (a === 'phagain') { PH.items = null; PH.img = ''; PH.err = ''; fDraw(); setTimeout(() => { const i = fh().querySelector('#fdCam'); i && i.click(); }, 50); return; }
  if (a === 'phkey') { const v = (fh().querySelector('[data-phkey]') || {}).value || ''; if (v.trim().length < 20) { UI.toast('Esta chave parece incompleta', 'warn'); return; } OS.setOne('diet', { aiKey: v.trim() }); UI.toast('Chave guardada', 'pos'); fDraw(); return; } }
// alterar gramas de um item da foto reescala as macros
document.addEventListener('change', e => { const t = e.target; if (!t.dataset || t.dataset.phg == null || !PH.items) return; const it = PH.items[+t.dataset.phg], g = n(t.value); if (!it || !g) return; const k = g / (n(it.gramas) || g); ['kcal', 'proteina', 'hidratos', 'gordura', 'fibra'].forEach(f => it[f] = n(it[f]) * k); it.gramas = g; setTimeout(fDraw, 0); });

/* ================= marcas online (Open Food Facts) ================= */
const OFFQ = {};
const offKey = q => CTY.code() + '|' + norm(q);
// procura produtos de marca no Open Food Facts, só os vendidos no país escolhido (guardado para não repetir)
const offSearch = async (q, onDone) => { const k = offKey(q); if (!norm(q) || norm(q).length < 2 || (OFFQ[k] && !OFFQ[k].err)) { onDone && onDone(); return; }
  const c = CTY.get(); OFFQ[k] = { busy: true }; onDone ? onDone() : FS && FS.tab === 'marcas' && fDraw();
  const params = new URLSearchParams({ search_terms: q, search_simple: 1, action: 'process', json: 1, page_size: 40, sort_by: 'unique_scans_n', tagtype_0: 'countries', tag_contains_0: 'contains', tag_0: c[2], fields: 'code,product_name,product_name_pt,product_name_' + c[3] + ',brands,image_front_small_url,nutriments,serving_quantity' });
  try { let r = await fetch(`https://${c[3]}.openfoodfacts.org/cgi/search.pl?` + params).catch(() => null); if (!r || !r.ok) r = await fetch('https://world.openfoodfacts.org/cgi/search.pl?' + params);
    if (!r.ok) throw new Error('Open Food Facts ocupado (' + r.status + '). Tenta daqui a um minuto.'); const j = await r.json(), seen = new Set();
    OFFQ[k] = { items: (j.products || []).map(p => { const nu = p.nutriments || {}, kc = U.num(nu['energy-kcal_100g']); const nm = String(p['product_name_' + c[3]] || p.product_name_pt || p.product_name || '').trim(); if (!nm || !isFinite(kc) || kc > 900 || nu['energy-kcal_100g'] == null || !p.image_front_small_url) return null;
      const brand = String(p.brands || '').split(',')[0].trim().slice(0, 28), key = norm(nm + brand); if (seen.has(key)) return null; seen.add(key);
      const sq = U.num(p.serving_quantity), x = { id: 'off:' + p.code, name: nm.slice(0, 70), brand, kcal: Math.round(kc), p: U.r1(n(nu.proteins_100g)), c: U.r1(n(nu.carbohydrates_100g)), f: U.r1(n(nu.fat_100g)), fib: U.r1(n(nu.fiber_100g)), cat: 'Marcas', por: sq > 0 && sq < 1000 ? ['porção', sq] : null, pic: p.image_front_small_url, cc: c[0], nn: norm(nm + ' ' + brand) }; OFFC[x.id] = x; return x; }).filter(Boolean) }; }
  catch (e) { OFFQ[k] = { err: /fetch|network|load/i.test(e.message) ? 'Sem internet: mostro só as marcas guardadas.' : e.message }; }
  onDone ? onDone() : FS && FS.tab === 'marcas' && fDraw(); };
Diet.offSearch = offSearch;
// escolha de marca para o alimento selecionado
const brandQ = x => { const g = x.g; return g ? norm(g.name).replace(/\(.*?\)|\/.*$/g, ' ').split(/\s+/).filter(Boolean).slice(0, 2).join(' ') : Diet.picQuery(x.name).split(' ').slice(0, 2).join(' '); };
const brandNames = g => { const L = OS.BrandLists || {}, c = CTY.code(), k = g && g.bk, own = k && L[k] ? (L[k][c] || L[k]['*'] || []) : g ? ['Caseiro', 'Restaurante / take-away'] : []; return [...new Set([...own, ...((L.STORE || {})[c] || [])])]; };
Diet.brandNames = brandNames;
// marcas e produtos reais de cada alimento, por país (Open Food Facts, filtrados por categoria, nome e calorias): vendor/brands/XX.json
const BD = {}, BDW = {}, IMGP = 'https://images.openfoodfacts.org/images/products/';
const brandData = (cb) => { const c = CTY.code(); if (BD[c]) return BD[c]; if (!BDW[c]) { BDW[c] = fetch(new URL('vendor/brands/' + c + '.json', document.baseURI)).then(r => r.ok ? r.json() : {}).catch(() => ({})).then(j => { BD[c] = j; BDW[c] = null; cb && cb(); }); } else if (cb) BDW[c].then(() => cb()); return null; };
Diet.brandData = brandData;
const prodOf = (r, g) => { const id = 'bp:' + r[8]; if (OFFC[id]) return OFFC[id]; const x = { id, name: r[1], brand: r[0], kcal: r[2], p: r[3], c: r[4], f: r[5], fib: r[6], cat: 'Marcas', pic: r[7] ? (/^https?:/.test(r[7]) ? r[7] : IMGP + r[7]) : '', por: r[9] > 0 ? ['porção', r[9]] : null, nn: norm(r[1] + ' ' + r[0]), cc: CTY.code(), gg: g }; OFFC[id] = x; return x; };
// fast food das cadeias do país dentro de cada alimento
const FFM = { 'Batata frita (fast food)': /batatas? fritas|fries|onion rings/, 'Hambúrguer no pão': /mac|whopper|burger|hamburguer|cheeseburger|quarteirao|quarter pounder|big tasty|cbo|dave|big bob|big king|stacker|royal cheese|mcmelt|giant|baconator|famous star|double-double|shackburger|mccrispy|crispy chicken|chicken royale|long chicken|zinger|fillet burger|mcchicken|sanduiche de frango|brutus|filet-o-fish/,
  'Nuggets de frango': /nugget|popcorn chicken|tenders|strips|chicken fries/, 'Pizza': /pizza|fatia/, 'Sandes de fiambre e queijo': /sandes|sandwich|sanduiche|bocadillo|15 cm|30 cm|montadito|panino|misto|beirute|bifana|prego|bmt|steak & cheese/, 'Tosta mista': /tosta|misto quente|mixto|croque-/,
  'Kebab': /kebab|durum/, 'Burrito': /burrito|taco|crunchwrap|quesadilla|nachos/, 'Salada César com frango': /salada|salad/, 'Salada mista': /salada/, 'Gelado': /mcflurry|sundae|casquinha|frosty|milkshake|king fusion|shake/, 'Donut': /donut|kreme/, 'Bola de Berlim': /berlim/,
  'Café': /americano|expresso|cafe com leite|double-double \(medio\)/, 'Cappuccino': /cappuccino/, 'Galão / café com leite': /galao|latte|macchiato|mocha|cafe com leite/, 'Chá': /chai/, 'Sushi': /nigiri|uramaki|hot roll|sushi/, 'Coxinha': /coxinha/, 'Pastel de nata': /pastel de nata/, 'Croissant': /croissant/,
  'Bolacha de chocolate (cookie)': /cookie/, 'Bolo de chocolate': /muffin de chocolate|brownie|cheesecake/, 'Refrigerante de cola': /coca-cola/, 'Frango inteiro': /1\/4 de frango|peca de frango|balde|frango original/, 'Asa de frango': /asas|wings|hot wings/, 'Esparguete à bolonhesa': /massa/, 'Lasanha à bolonhesa': /lasanha/,
  'Quibe': /kibe|quibe/, 'Croquete de carne': /croquete/, 'Pão de queijo': /pao de queijo/, 'Arroz de frango': /prato de frango|frango.*arroz/, 'Frango com arroz e legumes': /prato de frango|chicken box/, 'Sopa de legumes': /sopa/, 'Sumo de laranja': /sumo natural/, 'Bitoque': /h3|prato/, 'Yakisoba': /yakisoba|xadrez|orange chicken/ };
const brandCards = () => { const base = FS.base, g = FS.grp; if (!base) return ''; const d = brandData(brandsRefresh);
  if (!d) return `<div class="fd-bwait"><div class="fd-spin"></div><small>A carregar as marcas de ${esc(CTY.get()[1])}…</small></div>`;
  const fr = g && FFM[g.name];
  const rows = g ? (d[g.id.slice(1)] || []) : [], prods = (fr ? ffHere().filter(x => fr.test(norm(x.name + ' ' + x.brand))) : []).concat(rows.map(r => prodOf(r, g))), have = new Set(prods.map(x => norm(x.brand)));
  const others = brandNames(g).filter(nm => !have.has(norm(nm)));
  const card = x => `<button class="fd-bc ${FS.sel === x ? 'on' : ''}" data-fa="brand" data-id="${x.id}">${Diet.img(x.name, x.cat, '', x.pic || (g && g.pic))}<b>${esc(x.brand)}</b><small>${esc(x.name)}</small><em class="mono">${U.nf(x.kcal)} kcal/100 g</em></button>`;
  return `<div class="fd-bns"><button class="chip ${!FS.brand && FS.sel === base ? 'on' : ''}" data-fa="brand" data-id="gen">Sem marca (valores médios)</button></div>`
    + (prods.length ? `<div class="fd-lab sm">${prods.length} marcas, cadeias e produtos com os valores reais (${esc(CTY.get()[1])})</div><div class="fd-bp">${prods.map(card).join('')}</div>` : '')
    + (others.length ? `<div class="fd-lab sm">${prods.length ? 'Outras marcas' : 'Marcas'} à venda em ${esc(CTY.get()[1])} (valores médios)</div><div class="fd-bns">${others.map(nm => `<button class="chip ${FS.brand === nm && FS.sel === base ? 'on' : ''}" data-fa="bname" data-v="${esc(nm)}">${esc(nm)}</button>`).join('')}</div>` : ''); };
const brandsRefresh = () => { const el = fh().querySelector('.fd-bl'); if (el && FS && FS.base) el.innerHTML = brandCards(); };
document.addEventListener('submit', e => { if (!e.target.matches('[data-fbq-form]')) return; e.preventDefault(); e.stopPropagation(); if (!FS) return; const v = e.target.querySelector('[data-fbq]').value.trim(); FS.bq = v; fDraw(); offSearch(v); }, true);

/* ================= foto com IA ================= */
const PH = { items: null, img: '', busy: false, err: '' };
const photoBody = () => { const key = OS.one('diet').aiKey;
  if (!key) return `<div class="fd-ai"><div class="fd-aic">${UI.ic('camera')}</div><h3>Reconhecer comida pela foto</h3><p>Tiras uma foto ao prato e a IA identifica os alimentos, estima as gramas, as calorias e as macros. Depois confirmas ou corriges antes de guardar.</p>
    <p>Para ligar (grátis, 2 minutos):</p><ol><li>Abre <a href="https://aistudio.google.com/apikey" target="_blank" rel="noopener">aistudio.google.com/apikey</a> com a tua conta Google.</li><li>Toca em <b>Create API key</b> (Criar chave) e copia a chave.</li><li>Cola-a aqui e toca em Guardar.</li></ol>
    <div class="row gap8"><input class="field grow" data-phkey placeholder="Cola aqui a chave (começa por AIza…)" autocomplete="off"><button class="btn pri" data-fa="phkey">Guardar</button></div><small class="mut">A chave fica só na tua conta Oceanum (e no teu Google Drive pela sincronização). Não a partilhes.</small></div>`;
  if (PH.busy) return `<div class="fd-ai">${PH.img ? `<img class="fd-ph" src="${PH.img}" alt="Foto da refeição">` : ''}<div class="fd-spin"></div><p class="mut">A identificar os alimentos…</p></div>`;
  if (PH.items) return `<div class="fd-ai">${PH.img ? `<img class="fd-ph" src="${PH.img}" alt="Foto da refeição">` : ''}${PH.note ? `<p class="mut">${esc(PH.note)}</p>` : ''}<div class="fd-phl">${PH.items.map((i, k) => `<div class="${i.off ? 'off' : ''}"><button class="fd-ck" data-fa="phtoggle" data-k="${k}" aria-label="Incluir">${UI.ic(i.off ? 'x' : 'check')}</button>${Diet.img(i.nome)}<span><b>${esc(i.nome)}</b><small class="mono">${U.nf(n(i.kcal))} kcal · P ${U.nf(n(i.proteina), 1)} · H ${U.nf(n(i.hidratos), 1)} · G ${U.nf(n(i.gordura), 1)}</small></span><label class="fd-g"><input type="text" inputmode="decimal" data-phg="${k}" value="${U.nf(n(i.gramas))}" aria-label="Gramas"><small>g</small></label></div>`).join('')}</div>
    <small class="mut">Confere as quantidades: muda as gramas e as calorias ajustam-se. É uma estimativa.</small><div class="row gap8"><button class="btn ghost" data-fa="phagain">${UI.ic('camera')}Outra foto</button><button class="btn pri grow" data-fa="phadd">${UI.ic('check')}Registar ${PH.items.filter(i => !i.off).length} em ${esc(FS.meal)}</button></div></div>`;
  return `<div class="fd-ai"><label class="fd-cam" for="fdCam">${UI.ic('camera')}<b>Tirar foto ou escolher da galeria</b><small>Fotografa o prato de cima, com boa luz.</small></label><input id="fdCam" type="file" accept="image/*" capture="environment" hidden>${PH.err ? `<p class="neg">${esc(PH.err)}</p>` : ''}</div>`; };
document.addEventListener('change', e => { if (e.target.id !== 'fdCam') return; const f = e.target.files && e.target.files[0]; if (!f) return; shrink(f).then(d => { PH.img = d; photoRun(); }).catch(() => { PH.err = 'Não consegui abrir esta imagem.'; fDraw(); }); });
const shrink = file => new Promise((ok, ko) => { const r = new FileReader(); r.onerror = ko; r.onload = () => { const im = new Image(); im.onerror = ko; im.onload = () => { const m = 896, k = Math.min(1, m / Math.max(im.width, im.height)), c = document.createElement('canvas'); c.width = Math.round(im.width * k); c.height = Math.round(im.height * k); c.getContext('2d').drawImage(im, 0, 0, c.width, c.height); ok(c.toDataURL('image/jpeg', .82)); }; im.src = r.result; }; r.readAsDataURL(file); });
const PROMPT = 'És um nutricionista. Identifica TODOS os alimentos e bebidas visíveis nesta foto. Para cada um, estima a quantidade em gramas (ou ml para bebidas) com base no tamanho do prato e das porções, e calcula as calorias e macronutrientes para essa quantidade. Usa nomes simples em português (ex.: "Arroz branco cozido", "Peito de frango grelhado", "Coca-Cola"). Se não houver comida na foto, devolve itens vazio. Responde APENAS com JSON neste formato: {"itens":[{"nome":"","gramas":0,"kcal":0,"proteina":0,"hidratos":0,"gordura":0,"fibra":0}],"nota":"frase curta opcional"}';
const MODELS = ['gemini-flash-latest', 'gemini-2.5-flash', 'gemini-2.0-flash'];
Diet.vision = async (dataUrl, key) => { let last = '';
  for (const m of MODELS) { try { const r = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${m}:generateContent?key=${encodeURIComponent(key)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ contents: [{ parts: [{ text: PROMPT }, { inline_data: { mime_type: 'image/jpeg', data: dataUrl.split(',')[1] } }] }], generationConfig: { responseMimeType: 'application/json', temperature: .2 } }) });
      const j = await r.json().catch(() => ({})); if (r.status === 404) { last = 'modelo indisponível'; continue; }
      if (!r.ok) { const msg = (j.error && j.error.message) || ''; if (/API key not valid|API_KEY_INVALID/i.test(msg)) throw Object.assign(new Error('A chave da IA não é válida. Volta a copiá-la em aistudio.google.com/apikey.'), { fatal: 1 }); if (r.status === 429) throw Object.assign(new Error('Limite gratuito atingido por agora. Tenta daqui a um minuto.'), { fatal: 1 }); last = msg || 'erro ' + r.status; continue; }
      const txt = (((j.candidates || [])[0] || {}).content || {}).parts ? j.candidates[0].content.parts.map(p => p.text || '').join('') : ''; const o = JSON.parse(txt.replace(/^```(json)?|```$/g, '').trim()); return { itens: (o.itens || o.items || []).filter(i => i && i.nome), nota: o.nota || '' }; }
    catch (e) { if (e.fatal) throw e; last = e.message; } }
  throw new Error('Não consegui analisar a foto (' + last + '). Verifica a internet e tenta de novo.'); };
const photoRun = async () => { const key = OS.one('diet').aiKey; if (!key || !PH.img) return; PH.busy = true; PH.err = ''; fDraw();
  try { const r = await Diet.vision(PH.img, key); PH.items = r.itens.map(i => Object.assign({}, i, { nome: String(i.nome).trim() })); PH.note = r.nota; if (!PH.items.length) { PH.items = null; PH.err = 'Não encontrei comida nesta foto. Tenta outra, de cima e com boa luz.'; } }
  catch (e) { PH.err = e.message; PH.items = null; }
  PH.busy = false; if (FS) fDraw(); };

/* ================= refeições fixas ================= */
S.mealtpl = { label: 'Refeição fixa', title: r => r.name, fields: [F('name', 'Nome', 'text', { req: 1, wide: 1 }), F('meal', 'Refeição', 'sel', { o: MEALS })] };
Diet.applyTpl = (t, date, meal) => { (t.items || []).forEach(i => OS.add('meals', { date, meal: meal || t.meal || nowMeal(), food: i.food, pic: i.pic || '', g: i.g || '', qty: i.qty || 1, kcal: n(i.kcal), p: n(i.p), c: n(i.c), f: n(i.f), fib: n(i.fib), tpl: t.id })); UI.toast(`${t.name} · ${U.nf(U.sum(t.items, i => i.kcal))} kcal`, 'pos'); };
A.tplApply = b => { const t = OS.get('mealtpl', b.dataset.id); if (t) Diet.applyTpl(t, Diet.dayNow(), b.dataset.m || t.meal); };
A.tplEdit = b => { const t = OS.get('mealtpl', b.dataset.id); Diet.add({ tpl: t ? U.clone(t.items) : [], tplName: t ? t.name : '', tplId: t ? t.id : '', meal: t ? t.meal : nowMeal() }); };
A.tplDel = b => UI.ask('Apagar esta refeição fixa?', 'As refeições já registadas ficam.', 'Apagar', () => OS.del('mealtpl', b.dataset.id));
A.tplFromMeal = b => { const its = OS.all('meals').filter(m => m.date === Diet.dayNow() && m.meal === b.dataset.m); if (!its.length) return; Diet.add({ tpl: its.map(m => ({ food: m.food, pic: m.pic || '', g: m.g || '', qty: m.qty || 1, kcal: n(m.kcal), p: n(m.p), c: n(m.c), f: n(m.f), fib: n(m.fib) })), tplName: b.dataset.m + ' de sempre', meal: b.dataset.m }); };
A.dietAdd = b => Diet.add({ meal: b.dataset.m || nowMeal(), tab: b.dataset.tab });

/* ================= vistas ================= */
Diet.dayNow = () => OS.ui.dietDay && OS.ui.dietDay <= U.today() ? OS.ui.dietDay : U.today();
const ring = (v, t, col, l, u) => { const p = t ? Math.min(1, v / t) : 0, r = 30, c = 2 * Math.PI * r, over = t && v > t * 1.1;
  return `<div class="dt-ring"><svg viewBox="0 0 72 72"><circle cx="36" cy="36" r="${r}" class="bg"/><circle cx="36" cy="36" r="${r}" stroke="${over ? 'var(--neg)' : col}" stroke-dasharray="${(p * c).toFixed(1)} ${c.toFixed(1)}" transform="rotate(-90 36 36)"/></svg><div><b class="mono">${U.nf(v)}</b><small>/ ${U.nf(t)}${u}</small></div><span>${l}</span></div>`; };
T.hoje = () => { const d = Diet.dayNow(), x = Diet.day(d), o = OS.one('diet'), tg = OS.BodyX ? OS.BodyX.target(d) : { kcal: n(o.kcal), p: n(o.p), c: n(o.c), f: n(o.f), adj: 0 }, left = tg.kcal - x.kcal, fib = U.sum(x.m, m => n(m.fib)), burn = OS.BodyX ? OS.BodyX.burn(d) : 0;
  const cups = Math.ceil(n(o.water) / 250), got = Math.round(x.water / 250), tpls = OS.all('mealtpl');
  return `${OS.BodyX ? OS.BodyX.strip() : ''}<div class="dt-day"><button class="icon-btn" data-act="dietDay" data-d="-1" aria-label="Dia anterior">${UI.ic('left')}</button><b>${d === U.today() ? 'Hoje' : d === U.addDays(U.today(), -1) ? 'Ontem' : U.fmtD(d)}</b><button class="icon-btn" data-act="dietDay" data-d="1" aria-label="Dia seguinte" ${d >= U.today() ? 'disabled' : ''}>${UI.ic('right')}</button></div>
  <section class="dt-sum2"><div class="dt-left"><span class="mut">${left >= 0 ? 'Faltam' : 'Passaste'}</span><b class="mono">${U.nf(Math.abs(left))}</b><span class="mut">kcal</span><small class="mut">${U.nf(tg.kcal)} meta${tg.adj ? ` (${tg.adj > 0 ? '+' : ''}${tg.adj} exercício)` : ''} − ${U.nf(x.kcal)} comido${burn ? ` · ${U.nf(burn)} kcal gastas a treinar` : ''}</small></div>
    <div class="dt-rings">${ring(x.kcal, tg.kcal, 'var(--accent)', 'Calorias', '')}${ring(x.p, tg.p, '#5FB3E8', 'Proteína', ' g')}${ring(x.c, tg.c, '#E8B75F', 'Hidratos', ' g')}${ring(x.f, tg.f, '#C98AE0', 'Gordura', ' g')}${ring(fib, n(o.fib) || 30, '#6FCF97', 'Fibra', ' g')}</div></section>
  <div class="dt-acts"><button class="btn pri" data-act="dietAdd">${UI.ic('search')}<span>Adicionar alimento</span></button><button class="btn" data-act="dietAdd" data-tab="foto">${UI.ic('camera')}<span>Foto da refeição</span></button>${tpls.length ? `<button class="btn ghost" data-act="dietAdd" data-tab="fixas">${UI.ic('repeat')}<span>Refeição fixa</span></button>` : ''}</div>
  ${MEALS.slice(0, 5).concat(x.m.some(r => r.meal === 'Snack') ? ['Snack'] : []).map(m => { const it = x.m.filter(r => r.meal === m), ft = tpls.filter(t => t.meal === m).slice(0, 3);
    return `<section class="dt-meal"><div class="dt-mt"><b>${m}</b><span class="mut mono">${it.length ? `${U.nf(U.sum(it, r => n(r.kcal)))} kcal · ${U.nf(U.sum(it, r => n(r.p)))} g prot` : ''}</span></div>
    ${it.map(r => `<div class="li dt-it" data-edit="meals:${r.id}" style="cursor:pointer">${Diet.img(r.food, '', '', r.pic)}<div class="li-t"><b>${esc(r.food)}${n(r.g) ? ` <span class="mut">${U.nf(r.g)} g</span>` : n(r.qty) && n(r.qty) !== 1 ? ` <span class="mut">× ${U.nf(r.qty, 1)}</span>` : ''}${r.src === 'foto' ? ` <span class="mut" title="registado por foto">${UI.ic('camera')}</span>` : ''}</b><small class="mono">P ${U.nf(n(r.p))} · H ${U.nf(n(r.c))} · G ${U.nf(n(r.f))}</small></div><span class="mono">${U.nf(n(r.kcal))}</span><button class="icon-btn" data-act="dietDel" data-id="${r.id}" aria-label="Apagar">${UI.ic('x')}</button></div>`).join('')}
    <div class="dt-madd"><button class="btn ghost sm" data-act="dietAdd" data-m="${m}">${UI.ic('plus')}Adicionar</button>${ft.map(t => `<button class="chip" data-act="tplApply" data-id="${t.id}" data-m="${m}">+ ${esc(t.name)}</button>`).join('')}${it.length > 1 ? `<button class="btn ghost sm" data-act="tplFromMeal" data-m="${m}" title="Guardar como refeição fixa">${UI.ic('note')}Guardar como fixa</button>` : ''}</div></section>`; }).join('')}
  <section class="dt-water"><div><b>${UI.ic('drop')}Água</b><span class="mut mono">${U.nf(x.water / 1000, 2)} / ${U.nf(n(o.water) / 1000, 1)} L</span></div><div class="dt-cups">${Array.from({ length: cups }, (_, i) => `<i class="${i < got ? 'on' : ''}"></i>`).join('')}</div><div class="dt-wb"><button class="btn ghost sm" data-act="dietWater" data-v="-250">−</button><button class="btn sm" data-act="dietWater" data-v="250">+ 250 ml</button><button class="btn ghost sm" data-act="dietWater" data-v="500">+ 500 ml</button></div></section>
  ${UI.toggle('Registo manual (escrever as calorias)', `<form class="dt-add" data-form="dietQuick" autocomplete="off"><select class="field" name="meal" aria-label="Refeição">${MEALS.map(m => `<option${m === nowMeal() ? ' selected' : ''}>${m}</option>`).join('')}</select><input class="field" name="food" placeholder="O que comeste?" aria-label="Alimento" required><input class="field" name="qty" type="number" step="any" inputmode="decimal" placeholder="porções" aria-label="Porções" value="1"><input class="field" name="kcal" type="number" step="any" inputmode="decimal" placeholder="kcal" aria-label="Calorias"><input class="field" name="p" type="number" step="any" inputmode="decimal" placeholder="prot g" aria-label="Proteína"><button class="btn pri">${UI.ic('plus')}<span>Registar</span></button></form>`, 'dtquick', 'edit')}`; };
T.fixas = () => { const R = U.sortBy(OS.all('mealtpl'), t => MEALS.indexOf(t.meal) * 1000 + (t.name || '').charCodeAt(0));
  return `<div class="row gap8" style="margin-bottom:12px"><button class="btn pri" data-act="tplEdit">${UI.ic('plus')}<span>Nova refeição fixa</span></button><span class="mut" style="font-size:12.5px">Para o que comes sempre: regista tudo de uma vez com um toque.</span></div>
  ${R.length ? `<div class="tp-g">${R.map(t => `<article class="tp-c"><div class="tp-h"><div><b>${esc(t.name)}</b><small>${esc(t.meal || '')} · ${U.nf(U.sum(t.items, i => i.kcal))} kcal · P ${U.nf(U.sum(t.items, i => i.p))} · H ${U.nf(U.sum(t.items, i => i.c))} · G ${U.nf(U.sum(t.items, i => i.f))}</small></div><button class="icon-btn" data-act="tplEdit" data-id="${t.id}" aria-label="Editar">${UI.ic('edit')}</button><button class="icon-btn" data-act="tplDel" data-id="${t.id}" aria-label="Apagar">${UI.ic('trash')}</button></div>
    <div class="tp-i">${t.items.map(i => `<div>${Diet.img(i.food, '', '', i.pic)}<span>${esc(i.food)}</span><small class="mono">${n(i.g) ? U.nf(i.g) + ' g' : ''}</small></div>`).join('')}</div><button class="btn sm pri" data-act="tplApply" data-id="${t.id}">${UI.ic('plus')}Adicionar a ${Diet.dayNow() === U.today() ? 'hoje' : U.fmtDS(Diet.dayNow())}</button></article>`).join('')}</div>`
    : UI.empty('Sem refeições fixas. Ex.: "Pequeno-almoço de sempre" = aveia 50 g + whey 30 g + banana.', `<button class="btn pri" data-act="tplEdit">${UI.ic('plus')}Criar a primeira</button>`)}`; };
T.alimentos = () => { const q = (OS.ui.fdb || {}).q || '', cat = OS.ui.fdCat || '', cats = ['Marcas', ...new Set(DB.map(x => x.cat))], my = OS.all('foods');
  const src = cat === 'Marcas' ? brHere() : GR.filter(x => !cat || x.cat === cat), list = q ? (cat === 'Marcas' ? Diet.search(q, 80).filter(x => x.cat === 'Marcas') : Diet.searchGroups(q, 80)) : src.slice(0, OS.ui.more_fdb ? 1e9 : 60);
  return `<div class="wk-pf pg"><input type="search" class="field" data-uif="fdb.q" value="${esc(q)}" placeholder="Procurar entre ${GR.length} alimentos…" aria-label="Procurar alimento"><div class="wk-chips">${cats.map(c => UI.chip(c, 'fdCat', cat === c, `data-v="${esc(c)}"`)).join('')}</div></div>
  <div class="fd-grid">${list.map(x => `<button class="fd-gi" data-act="dietAddFood" data-id="${x.id}">${Diet.img(x.name, x.cat, 'md', x.pic)}<b>${esc(x.name)}${x.brand ? ` · ${esc(x.brand)}` : ''}</b>${x.desc ? `<span class="fd-gd">${esc(x.desc)}</span>` : ''}<small class="mono">${U.nf(x.kcal)} kcal · P ${U.nf(x.p, 1)} · H ${U.nf(x.c, 1)} · G ${U.nf(x.f, 1)}</small><em>por 100 g${x.vars && x.vars.length > 1 ? ' · ' + esc(x.def.vl.toLowerCase()) + ' · ' + x.vars.length + ' opções' : ''}</em></button>`).join('')}</div>
  ${!q && src.length > list.length ? `<button class="btn ghost" data-more="fdb" style="margin-top:10px">Mostrar todos</button>` : ''}
  <div class="sech"><div><h2>Os meus alimentos</h2><p>Alimentos e produtos que criaste (ex.: marcas que usas sempre).</p></div>${UI.addBtn('foods', 'Novo alimento', null, 'sm')}</div>
  ${UI.table({ key: 'foods', coll: 'foods', rows: U.sortBy(my, f => f.name.toLowerCase()), limit: 100, empty: 'Ainda não criaste alimentos. Os que estão acima já estão todos guardados.', cols: [{ l: 'Alimento', v: f => `<b>${esc(f.name)}</b>`, s: f => f.name }, { l: 'Porção', v: f => esc(f.portion || '') }, { l: 'kcal', cls: 'r', v: f => `<span class="mono">${U.nf(n(f.kcal))}</span>`, s: f => n(f.kcal) }, { l: 'P', cls: 'r', v: f => `<span class="mono">${U.nf(n(f.p), 1)}</span>` }, { l: 'H', cls: 'r', v: f => `<span class="mono">${U.nf(n(f.c), 1)}</span>` }, { l: 'G', cls: 'r', v: f => `<span class="mono">${U.nf(n(f.f), 1)}</span>` }] })}
  <p class="note">Valores por 100 g da Tabela Brasileira de Composição de Alimentos (TACO, NEPA/UNICAMP), médias de rótulos e produtos de marca do Open Food Facts. Fotos dos alimentos: Pinterest; produtos de marca: Open Food Facts.</p>`; };
A.fdCat = b => OS.setUI('fdCat', OS.ui.fdCat === b.dataset.v ? '' : b.dataset.v);
A.dietAddFood = b => { Diet.add({}); const id = b.dataset.id; if (!findX(id) && !BR.find(y => y.id === id)) return; fClick({ target: { closest: () => ({ dataset: { fa: 'pick', id } }) }, preventDefault() { } }); };
// meta de fibra e opções da IA nas metas
const prevMetas = T.metas;
T.metas = () => prevMetas() + `<div class="pn"><div class="pn-h"><h3>Mais</h3></div><div class="form-grid"><div class="fld"><label for="dg_fib">Fibra</label><div class="inp-wrap"><input id="dg_fib" type="number" inputmode="decimal" data-bind="diet.fib" value="${esc(OS.one('diet').fib ?? 30)}"><span>g</span></div></div></div>
  <div class="fld" style="margin-top:10px"><label class="switch"><input type="checkbox" data-bind="diet.adapt"${OS.one('diet').adapt === false ? '' : ' checked'}><span></span>Ajustar as calorias de cada dia ao treino e à corrida</label></div>
  <div class="fld" style="margin-top:10px"><label>Foto com IA</label>${OS.one('diet').aiKey ? `<div class="row gap8"><span class="bdg pos">ligada</span><button class="btn ghost sm" data-act="dietAiOff">Remover chave</button></div>` : `<small class="mut">Desligada. Liga em Dieta → Hoje → Foto da refeição.</small>`}</div></div>`;
A.dietAiOff = () => UI.ask('Remover a chave da IA?', 'Deixas de poder registar refeições por foto até voltares a colar uma chave.', 'Remover', () => OS.setOne('diet', { aiKey: '' }));
S.meals.fields.splice(4, 0, F('g', 'Gramas', 'num', { unit: 'g', h: 'opcional' }));
S.foods.fields.push(F('fib', 'Fibra', 'num', { unit: 'g' }));
})();
