/* OCEANUM — Análise de empresas: escreves o nome e recebes tudo o que precisas para decidir.
   O que faz · quem manda e quem é dono · demonstrações financeiras (resultados, balanço, fluxos de caixa) · múltiplos ·
   dividendos · analistas · calendário · checklists dos mestres (Graham, Buffett, Lynch, Bazin, Fisher) · Piotroski · Altman Z ·
   preço justo de Graham e preço-teto de Bazin · notícias · relatório completo da IA (com pesquisa web e verificação).
   Dados: Yahoo Finance através do teu script Google. */
(() => {
'use strict';
const U = OS.U, UI = OS.UI, C = OS.C, A = OS.act, esc = U.esc, IX = OS.InvX, T = IX.T;
const v = x => x == null ? null : typeof x === 'object' ? (x.raw != null ? x.raw : null) : x;
const big = (x, cur = '') => { if (x == null || !isFinite(x)) return '—'; const a = Math.abs(x), g = x < 0 ? '−' : '', s = cur ? (({ USD: 'US$ ', EUR: '€ ', BRL: 'R$ ', GBP: '£ ' })[cur] || cur + ' ') : ''; return a >= 1e12 ? g + s + U.nf(a / 1e12, 2) + ' bi' : a >= 1e9 ? g + s + U.nf(a / 1e9, 2) + ' mM' : a >= 1e6 ? g + s + U.nf(a / 1e6, 1) + ' M' : g + s + U.nf(a, 0); };
const pct = (x, d = 1) => x == null || !isFinite(x) ? '—' : U.pct(x, d);
const nx = (x, d = 2) => x == null || !isFinite(x) ? '—' : U.nf(x, d);
const tone = x => x == null ? '' : x > 0 ? 'pos' : x < 0 ? 'neg' : '';
const ST = { q: '', busy: false, res: null, err: '' }, CO = {}, TR = {}, REP = U.ls.get('oc_corep', {}) || {};

/* ---------- dados ---------- */
const load = s => { if (CO[s]) return CO[s]; CO[s] = { busy: true }; IX.fund(s).then(f => { CO[s] = { f }; OS.request(); }).catch(e => { CO[s] = { err: IX.st.script === 'old' ? 'O teu script Google precisa da versão nova (Cotações → Copiar código novo).' : 'Não consegui obter os dados: ' + e.message }; OS.request(); }); return CO[s]; };
const years = (f, key, n = 5) => { const a = (f.ts['annual' + key] || []).slice(-n); return a; };
const series = (f, key) => { const m = {}; (f.ts['annual' + key] || []).forEach(([d, x]) => m[d.slice(0, 4)] = x); return m; };
IX.coModel = f => { const S = f.sum || {}, ap = S.assetProfile || {}, sd = S.summaryDetail || {}, fd = S.financialData || {}, ks = S.defaultKeyStatistics || {}, pr = S.price || {};
  const yrs = [...new Set(Object.keys(f.ts).filter(k => k.startsWith('annual')).flatMap(k => f.ts[k].map(x => x[0].slice(0, 4))))].sort().slice(-5);
  const g = k => { const m = series(f, k); return yrs.map(y => m[y] != null ? m[y] : null); };
  const rev = g('TotalRevenue'), ni = g('NetIncome'), gp = g('GrossProfit'), op = g('OperatingIncome'), ebitda = g('EBITDA'), ebit = g('EBIT'), ocf = g('OperatingCashFlow'), capex = g('CapitalExpenditure'), fcf = g('FreeCashFlow'), div = g('CashDividendsPaid'), buy = g('RepurchaseOfCapitalStock'), ta = g('TotalAssets'), tl = g('TotalLiabilitiesNetMinorityInterest'), eq = g('StockholdersEquity'), debt = g('TotalDebt'), cash = g('CashCashEquivalentsAndShortTermInvestments'), nd = g('NetDebt'), ca = g('CurrentAssets'), cl = g('CurrentLiabilities'), re = g('RetainedEarnings'), wc = g('WorkingCapital'), sh = g('OrdinarySharesNumber'), eps = g('DilutedEPS'), rnd = g('ResearchAndDevelopment');
  const cur = (f.ts.annualTotalRevenue && f.ts.annualTotalRevenue[0] && f.ts.annualTotalRevenue[0][2]) || pr.financialCurrency || fd.financialCurrency || pr.currency;
  const L = a => { for (let i = a.length - 1; i >= 0; i--) if (a[i] != null) return a[i]; return null; }, P = a => { let k = 0; for (let i = a.length - 1; i >= 0; i--) if (a[i] != null) { if (k++) return a[i]; } return null; };
  const price = v(pr.regularMarketPrice), mcap = v(pr.marketCap) || v(sd.marketCap), pe = v(sd.trailingPE), pb = v(ks.priceToBook), epsT = v(ks.trailingEps), bvps = v(ks.bookValue), dyR = v(sd.dividendRate) || v(sd.trailingAnnualDividendRate), dy = v(sd.dividendYield) != null ? v(sd.dividendYield) : v(sd.trailingAnnualDividendYield), eg = v(fd.earningsGrowth);
  const peg = v(ks.pegRatio) || (pe && eg > 0 ? pe / (eg * 100) : null), de = v(fd.debtToEquity) != null ? v(fd.debtToEquity) / 100 : (L(debt) != null && L(eq) ? L(debt) / L(eq) : null);
  const cagr = a => { const xs = a.map((x, i) => [x, i]).filter(x => x[0] > 0); if (xs.length < 2) return null; const [x0, i0] = xs[0], [x1, i1] = xs[xs.length - 1]; return Math.pow(x1 / x0, 1 / (i1 - i0)) - 1; };
  // Piotroski (9 pontos, últimos 2 anos)
  const pio = (() => { const i = yrs.length - 1; if (i < 1) return null; const roa = (k) => ni[k] != null && ta[k] ? ni[k] / ta[k] : null, crr = k => ca[k] != null && cl[k] ? ca[k] / cl[k] : null, gm = k => gp[k] != null && rev[k] ? gp[k] / rev[k] : null, at = k => rev[k] != null && ta[k] ? rev[k] / ta[k] : null, lev = k => debt[k] != null && ta[k] ? debt[k] / ta[k] : null;
    const t = [['Lucro positivo', roa(i) != null ? roa(i) > 0 : null], ['Fluxo de caixa operacional positivo', ocf[i] != null ? ocf[i] > 0 : null], ['Rentabilidade dos ativos a subir', roa(i) != null && roa(i - 1) != null ? roa(i) > roa(i - 1) : null], ['Caixa operacional maior que o lucro (qualidade)', ocf[i] != null && ni[i] != null ? ocf[i] > ni[i] : null],
      ['Endividamento a descer', lev(i) != null && lev(i - 1) != null ? lev(i) <= lev(i - 1) : null], ['Liquidez corrente a subir', crr(i) != null && crr(i - 1) != null ? crr(i) > crr(i - 1) : null], ['Sem emissão de novas ações', sh[i] != null && sh[i - 1] != null ? sh[i] <= sh[i - 1] * 1.005 : null], ['Margem bruta a subir', gm(i) != null && gm(i - 1) != null ? gm(i) > gm(i - 1) : null], ['Eficiência (vendas/ativos) a subir', at(i) != null && at(i - 1) != null ? at(i) > at(i - 1) : null]];
    const known = t.filter(x => x[1] != null); return { t, score: known.filter(x => x[1]).length, of: known.length }; })();
  // Altman Z (não se aplica a bancos e seguradoras)
  const fin = /bank|insurance|financial|capital markets|credit/i.test((ap.industry || '') + ' ' + (ap.sector || ''));
  const alt = (() => { const i = yrs.length - 1, TA = ta[i], TL = tl[i]; if (fin || !TA || !TL || mcap == null) return null; const z = 1.2 * ((wc[i] != null ? wc[i] : (ca[i] || 0) - (cl[i] || 0)) / TA) + 1.4 * ((re[i] || 0) / TA) + 3.3 * ((ebit[i] != null ? ebit[i] : op[i] || 0) / TA) + .6 * (mcap * (cur && pr.currency && cur !== pr.currency ? 1 : 1) / TL) + 1.0 * ((rev[i] || 0) / TA); return { z, zona: z > 2.99 ? 'segura' : z > 1.81 ? 'cinzenta' : 'de risco' }; })();
  const graham = epsT > 0 && bvps > 0 ? Math.sqrt(22.5 * epsT * bvps) : null, bazin = dyR ? dyR / .06 : null;
  const ndE = L(nd) != null ? L(nd) : (L(debt) != null && L(cash) != null ? L(debt) - L(cash) : null), ndEb = ndE != null && L(ebitda) ? ndE / L(ebitda) : null;
  const grow = cagr(rev), growNI = cagr(ni), roe = v(fd.returnOnEquity), nm = v(fd.profitMargins), gmL = v(fd.grossMargins), curR = v(fd.currentRatio), payout = v(sd.payoutRatio);
  const allPos = a => a.filter(x => x != null).length >= 3 && a.filter(x => x != null).every(x => x > 0);
  const up = a => { const xs = a.filter(x => x != null); if (xs.length < 3) return null; let u = 0; for (let i = 1; i < xs.length; i++) if (xs[i] >= xs[i - 1]) u++; return u >= xs.length - 2; };
  const ck = (t, ok, val) => ({ t, ok, val });
  const lists = {
    'Warren Buffett': [ck('ROE acima de 15%', roe == null ? null : roe > .15, pct(roe)), ck('Margem líquida acima de 10%', nm == null ? null : nm > .1, pct(nm)), ck('Dívida líquida < 3× EBITDA', ndEb == null ? null : ndEb < 3, ndEb == null ? '—' : nx(ndEb, 1) + '×'), ck('Lucros a crescer de forma consistente', up(ni), growNI == null ? '—' : pct(growNI) + '/ano'), ck('Fluxo de caixa livre positivo todos os anos', allPos(fcf) ? true : fcf.some(x => x != null) ? false : null, big(L(fcf), cur))],
    'Benjamin Graham': [ck('P/L abaixo de 15', pe == null ? null : pe < 15, nx(pe, 1)), ck('P/L × P/VP abaixo de 22,5', pe && pb ? pe * pb < 22.5 : null, pe && pb ? nx(pe * pb, 1) : '—'), ck('Liquidez corrente acima de 1,5', curR == null ? null : curR > 1.5, nx(curR, 2)), ck('Lucro positivo em todos os anos', allPos(ni) ? true : ni.some(x => x != null) ? false : null, ni.filter(x => x != null).length + ' anos'), ck('Paga dividendos', dyR == null ? null : dyR > 0, pct(dy, 2)), ck('Preço abaixo do número de Graham', graham && price ? price < graham : null, graham ? nx(graham) : '—')],
    'Peter Lynch': [ck('PEG abaixo de 1', peg == null ? null : peg < 1, nx(peg, 2)), ck('Crescimento do lucro entre 10% e 25%/ano', growNI == null ? null : growNI >= .1 && growNI <= .25, pct(growNI)), ck('Dívida/património abaixo de 50%', de == null ? null : de < .5, pct(de, 0))],
    'Décio Bazin': [ck('Dividend yield ≥ 6%', dy == null ? null : dy >= .06, pct(dy, 2)), ck('Preço abaixo do preço-teto (DY 6%)', bazin && price ? price <= bazin : null, bazin ? nx(bazin) : '—'), ck('Endividamento baixo (dívida/património < 50%)', de == null ? null : de < .5, pct(de, 0)), ck('Payout sustentável (< 80%)', payout == null ? null : payout < .8, pct(payout, 0))],
    'Philip Fisher (qualidade)': [ck('Receita a crescer acima de 5%/ano', grow == null ? null : grow > .05, pct(grow)), ck('Margem bruta acima de 40%', gmL == null ? null : gmL > .4, pct(gmL)), ck('Investe em I&D', rnd.some(x => x > 0) ? true : rnd.some(x => x != null) ? false : null, big(L(rnd), cur))] };
  return { S, ap, sd, fd, ks, pr, yrs, rev, ni, gp, op, ebitda, ocf, capex, fcf, div, buy, ta, tl, eq, debt, cash, nd, eps, cur, price, mcap, pe, pb, peg, dy, dyR, de, roe, nm, gmL, grow, growNI, ndEb, graham, bazin, pio, alt, lists, payout, curR, L, P, fin }; };

/* ---------- ecrã ---------- */
A.invCo = b => { OS.setUI('invCo', b.dataset.s); location.hash = 'investimentos.empresas'; };
OS.forms.invCoSearch = async (f, val) => { const q = String(val('q') || '').trim(); if (!q) return; ST.q = q; ST.busy = true; ST.err = ''; ST.res = null; OS.request();
  try { const j = await IX.search(q); ST.res = (j.q || []).filter(x => /EQUITY|ETF|MUTUALFUND/i.test(x.t || '')); if (ST.res.length === 1) { OS.setUI('invCo', ST.res[0].s); ST.res = null; } } catch (e) { ST.err = IX.st.script === 'old' ? 'O teu script Google precisa da versão nova (Cotações).' : !IX.hasScript() ? 'Liga primeiro o script Google em Cotações.' : 'A pesquisa falhou: ' + e.message; }
  ST.busy = false; OS.request(); };
const head = () => `<div class="pn"><div class="pn-h"><h3>${UI.ic('search')}Analisar uma empresa</h3><span class="mut" style="font-size:12px">ações de todas as bolsas: EUA, Brasil, Portugal, Europa…</span></div>
  <form class="row gap8" data-form="invCoSearch"><input class="field grow" name="q" id="invCoQ" value="${esc(ST.q)}" placeholder="Nome ou ticker: Apple, Petrobras, EDP, Itaúsa, Nvidia, Galp…" autocomplete="off" aria-label="Empresa"><button class="btn pri">${ST.busy ? 'A procurar…' : 'Analisar'}</button></form>
  ${ST.err ? `<p class="neg">${esc(ST.err)}</p>` : ''}${ST.res ? (ST.res.length ? `<div class="list" style="margin-top:8px">${ST.res.map(r => `<div class="li click" data-act="invCo" data-s="${esc(r.s)}"><div class="li-t"><b>${esc(r.n)}</b><small>${esc(r.s)} · ${esc(r.ty || r.t || '')} · ${esc(r.ex || '')}</small></div><span class="acc">analisar →</span></div>`).join('')}</div>` : '<p class="mut">Nenhuma empresa encontrada.</p>') : ''}
  ${!IX.hasScript() ? `<div class="note" style="margin-top:8px">Precisa do script Google ligado (em <a class="acc" href="#investimentos.cotacoes">Cotações</a>): é ele que vai buscar os dados da empresa.</div>` : ''}</div>`;
T.empresas = () => { const s = OS.ui.invCo; if (!s) return head() + `<div class="pn"><p class="mut">Exemplos: ${['AAPL', 'MSFT', 'PETR4.SA', 'ITSA4.SA', 'EDP.LS', 'GALP.LS', 'ASML.AS', 'KO'].map(x => `<button class="chip" data-act="invCo" data-s="${x}">${x}</button>`).join(' ')}</p></div>`;
  IX.extra.add(s); const st = load(s); if (st.busy) return head() + `<div class="pn"><div class="sai-busy"><div class="fd-spin"></div><span>A recolher o perfil, os donos e as demonstrações financeiras de ${esc(s)}…</span></div></div>`;
  if (st.err) return head() + `<div class="pn"><p class="neg">${esc(st.err)}</p></div>`;
  const f = st.f; if (!f || (!f.sum && !Object.keys(f.ts || {}).length)) return head() + `<div class="pn"><p class="mut">Sem dados fundamentais para ${esc(s)} (pode ser um ETF, índice ou ativo sem relatórios).</p></div>`;
  const m = IX.coModel(f), q = IX.q(s), price = q ? q.p : m.price, cur = m.cur, pcur = (m.pr && m.pr.currency) || cur, ap = m.ap, held = OS.all('assets').find(a => a.sym === s), rep = REP[s];
  translate(s, ap.longBusinessSummary);
  const up = (tgt) => tgt && price ? tgt / price - 1 : null, tgt = v(m.fd.targetMeanPrice), rt = ((m.S.recommendationTrend || {}).trend || [])[0] || {}, rec = ['strongBuy', 'buy', 'hold', 'sell', 'strongSell'].map(k => rt[k] || 0), recT = U.sum(rec, x => x);
  const own = m.S.majorHoldersBreakdown || {}, inst = ((m.S.institutionOwnership || {}).ownershipList || []).slice(0, 8), funds = ((m.S.fundOwnership || {}).ownershipList || []).slice(0, 5), ins = ((m.S.insiderHolders || {}).holders || []).slice(0, 6), off = (ap.companyOfficers || []).slice(0, 6);
  const cal = m.S.calendarEvents || {}, ed = ((cal.earnings || {}).earningsDate || [])[0];
  const row = (l, a, fmt = x => big(x, cur), cls = '') => `<tr><th>${l}</th>${a.map(x => `<td class="r mono ${cls}">${fmt(x)}</td>`).join('')}</tr>`;
  const mg = (a, b) => a.map((x, i) => x != null && b[i] ? x / b[i] : null);
  const scoreAll = Object.values(m.lists).flat(), okN = scoreAll.filter(x => x.ok === true).length, knN = scoreAll.filter(x => x.ok != null).length;
  return head() + `<div class="pn co-h"><div class="row between gap12" style="align-items:flex-start;flex-wrap:wrap"><div><h2 style="margin:0">${esc(v(m.pr.longName) || m.pr.longName || m.pr.shortName || s)}</h2><span class="mut">${esc(s)} · ${esc(m.pr.exchangeName || (q && q.ex) || '')} · ${esc(ap.sector || '')}${ap.industry ? ' / ' + esc(ap.industry) : ''} · ${esc(ap.country || '')}</span>
      <div class="row gap8" style="margin-top:8px;flex-wrap:wrap">${ap.website ? `<a class="btn xs ghost" href="${esc(ap.website)}" target="_blank" rel="noopener">site oficial</a>` : ''}<button class="btn xs ghost" data-act="invOpen" data-s="${esc(s)}">gráfico e notícias</button>${held ? '<span class="bdg pos">na tua carteira</span>' : `<button class="btn xs" data-act="invAddAsset" data-s="${esc(s)}" data-n="${esc(m.pr.longName || s)}" data-t="EQUITY">+ Carteira</button>`}<button class="btn xs ghost" data-act="invWatch" data-s="${esc(s)}">☆ Acompanhar</button></div></div>
    <div class="inv-ap"><div class="big-num">${price != null ? `<span class="mono px" data-pxs="${esc(s)}" data-k="p">${U.nf(price, 2)}</span>` : '—'} <small class="mut">${esc(pcur || '')}</small></div>${q && q.pc ? `<span class="mono ${tone(q.p - q.pc)}" data-pxs="${esc(s)}" data-k="ch">${(q.p >= q.pc ? '+' : '') + U.pct(q.p / q.pc - 1, 2)}</span>` : ''}<div class="mut" style="font-size:12px">valor de mercado ${big(m.mcap, pcur)}</div></div></div></div>
  <div class="pn co-ai"><div class="sai-h"><span class="sai-ic">${UI.ic('zap')}</span><div><h3>Relatório completo da IA</h3><small class="mut">O que faz, vantagens competitivas, qualidade dos números, dívida, avaliação, riscos, o que diriam Buffett, Graham, Lynch, Fisher, Bazin e Barsi, e se cabe na TUA carteira. Com pesquisa web, fontes e verificação.</small></div><button class="btn sm pri" data-act="invCoAI" data-s="${esc(s)}" ${ST.ai ? 'disabled' : ''}>${rep ? 'Atualizar relatório' : 'Gerar relatório'}</button></div>
    ${ST.ai === s ? `<div class="sai-busy"><div class="fd-spin"></div><span>A pesquisar a empresa e a analisar os números…</span></div>` : ''}${ST.aiErr ? `<p class="neg">${esc(ST.aiErr)}</p>` : ''}${rep && OS.InvAI && OS.InvAI.render ? OS.InvAI.render(rep) : ''}</div>
  <div class="g g-main"><div class="pn"><div class="pn-h"><h3>O que faz</h3>${ap.fullTimeEmployees ? `<span class="mut" style="font-size:12px">${U.nf(ap.fullTimeEmployees)} funcionários</span>` : ''}</div>${TR[s] && TR[s] !== 'busy' ? `<p style="line-height:1.6;margin:0">${esc(TR[s])}</p>${UI.toggle('Descrição original (inglês)', `<p class="mut" style="font-size:13px;line-height:1.55">${esc(ap.longBusinessSummary || '')}</p>`, 'coOrig' + s)}` : `<p style="line-height:1.6;margin:0" class="${OS.AI && OS.AI.key() ? 'mut' : ''}">${esc(ap.longBusinessSummary || 'Sem descrição.')}</p>${TR[s] === 'busy' ? '<small class="mut">a traduzir…</small>' : ''}`}
      <dl class="kv" style="margin-top:10px">${ap.city ? `<dt>Sede</dt><dd>${esc([ap.city, ap.state, ap.country].filter(Boolean).join(', '))}</dd>` : ''}${ed ? `<dt>Próximos resultados</dt><dd>${esc(ed.fmt || '')}</dd>` : ''}${cal.exDividendDate ? `<dt>Data ex-dividendo</dt><dd>${esc(cal.exDividendDate.fmt || '')}</dd>` : ''}</dl></div>
    <div class="pn"><div class="pn-h"><h3>Nota dos mestres</h3><span class="mut" style="font-size:12px">${okN}/${knN} critérios cumpridos</span></div><div class="co-sc">
      <div><b>${m.pio ? m.pio.score + '/' + m.pio.of : '—'}</b><small>Piotroski F-score<br>${m.pio ? (m.pio.score >= 7 ? 'forte' : m.pio.score >= 4 ? 'médio' : 'fraco') : ''}</small></div>
      <div><b class="${m.alt ? (m.alt.zona === 'segura' ? 'pos' : m.alt.zona === 'cinzenta' ? 'warn' : 'neg') : ''}">${m.alt ? nx(m.alt.z, 2) : '—'}</b><small>Altman Z<br>${m.alt ? 'zona ' + m.alt.zona : m.fin ? 'não se aplica a bancos' : ''}</small></div>
      <div><b>${m.graham ? nx(m.graham, 2) : '—'}</b><small>Preço justo de Graham<br>${m.graham && price ? `<span class="${tone(m.graham - price)}">${(m.graham / price - 1 >= 0 ? '+' : '') + U.pct(m.graham / price - 1, 0)}</span>` : ''}</small></div>
      <div><b>${m.bazin ? nx(m.bazin, 2) : '—'}</b><small>Preço-teto de Bazin<br>${m.bazin && price ? `<span class="${tone(m.bazin - price)}">${(m.bazin / price - 1 >= 0 ? '+' : '') + U.pct(m.bazin / price - 1, 0)}</span>` : ''}</small></div></div>
      ${Object.entries(m.lists).map(([nm, l]) => `<div class="co-ck"><b>${esc(nm)}</b>${l.map(c => `<div class="${c.ok === true ? 'pos' : c.ok === false ? 'neg' : 'mut'}"><span>${c.ok === true ? '✓' : c.ok === false ? '✗' : '·'} ${esc(c.t)}</span><span class="mono">${esc(c.val)}</span></div>`).join('')}</div>`).join('')}
      <p class="mut" style="font-size:11.5px;margin:6px 0 0">Critérios clássicos de cada mestre aplicados aos números. Não substituem a análise: empresas de crescimento raramente passam no Graham, bancos não passam no Altman.</p></div></div>
  <div class="pn"><div class="pn-h"><h3>Múltiplos e rentabilidade</h3><span class="mut" style="font-size:12px">em ${esc(pcur || '')}</span></div><div class="co-m">${[['P/L', nx(m.pe, 1)], ['P/L futuro', nx(v(m.sd.forwardPE), 1)], ['P/VP', nx(m.pb, 2)], ['PEG', nx(m.peg, 2)], ['EV/EBITDA', nx(v(m.ks.enterpriseToEbitda), 1)], ['P/Vendas', nx(v(m.sd.priceToSalesTrailing12Months), 2)], ['Dividend yield', pct(m.dy, 2)], ['Payout', pct(m.payout, 0)], ['ROE', pct(m.roe)], ['ROA', pct(v(m.fd.returnOnAssets))], ['Margem bruta', pct(m.gmL)], ['Margem operacional', pct(v(m.fd.operatingMargins))], ['Margem líquida', pct(m.nm)], ['Cresc. receita (12m)', pct(v(m.fd.revenueGrowth))], ['Cresc. lucro (12m)', pct(v(m.fd.earningsGrowth))], ['Dívida/património', pct(m.de, 0)], ['Dívida líq./EBITDA', m.ndEb == null ? '—' : nx(m.ndEb, 1) + '×'], ['Liquidez corrente', nx(m.curR, 2)], ['Beta', nx(v(m.sd.beta) || v(m.ks.beta), 2)], ['LPA', nx(v(m.ks.trailingEps), 2)], ['VPA', nx(v(m.ks.bookValue), 2)], ['Mín. / máx. 52 sem.', v(m.sd.fiftyTwoWeekLow) ? nx(v(m.sd.fiftyTwoWeekLow)) + ' – ' + nx(v(m.sd.fiftyTwoWeekHigh)) : '—']].map(([l, x]) => `<div><small>${l}</small><b class="mono">${x}</b></div>`).join('')}</div></div>
  <div class="pn"><div class="pn-h"><h3>Demonstrações financeiras</h3><span class="mut" style="font-size:12px">anuais · ${esc(cur || '')} · Yahoo Finance</span></div>
    ${m.yrs.length ? `<div class="g g2" style="margin-bottom:10px"><div>${C.mount({ type: 'bar', labels: m.yrs, series: [{ name: 'Receita', data: m.rev, color: 'var(--accent)' }, { name: 'Lucro líquido', data: m.ni, color: 'var(--pos)' }, { name: 'Fluxo de caixa livre', data: m.fcf, color: '#f2a65a' }], fmt: x => big(x) }, 220)}</div><div>${C.mount({ type: 'line', labels: m.yrs, series: [{ name: 'Margem bruta', data: mg(m.gp, m.rev).map(x => x == null ? null : x * 100) }, { name: 'Margem operacional', data: mg(m.op, m.rev).map(x => x == null ? null : x * 100), color: '#a78bfa' }, { name: 'Margem líquida', data: mg(m.ni, m.rev).map(x => x == null ? null : x * 100), color: 'var(--pos)' }], fmt: x => U.nf(x, 0) + '%', min0: false, area: false }, 220)}</div></div>
    <div class="tblw"><table class="tbl co-t"><thead><tr><th></th>${m.yrs.map(y => `<th class="r">${y}</th>`).join('')}</tr></thead><tbody>
      <tr class="co-sec"><th colspan="${m.yrs.length + 1}">Demonstração de resultados</th></tr>${row('Receita', m.rev)}${row('Lucro bruto', m.gp)}${row('EBITDA', m.ebitda)}${row('Resultado operacional', m.op)}${row('Lucro líquido', m.ni)}${row('Margem líquida', mg(m.ni, m.rev), x => pct(x))}${row('Lucro por ação', m.eps, x => nx(x, 2))}
      <tr class="co-sec"><th colspan="${m.yrs.length + 1}">Balanço</th></tr>${row('Ativos totais', m.ta)}${row('Passivos totais', m.tl)}${row('Capital próprio', m.eq)}${row('Dívida total', m.debt)}${row('Caixa e aplicações', m.cash)}${row('Dívida líquida', m.nd)}${row('ROE', mg(m.ni, m.eq), x => pct(x))}
      <tr class="co-sec"><th colspan="${m.yrs.length + 1}">Fluxos de caixa</th></tr>${row('Caixa das operações', m.ocf)}${row('Investimento (capex)', m.capex)}${row('Fluxo de caixa livre', m.fcf)}${row('Dividendos pagos', m.div)}${row('Recompra de ações', m.buy)}
    </tbody></table></div>` : '<p class="mut">Sem demonstrações financeiras disponíveis para este ativo.</p>'}
    ${m.grow != null || m.growNI != null ? `<p class="mut" style="font-size:12.5px;margin:8px 0 0">Crescimento médio anual: receita ${pct(m.grow)}, lucro ${pct(m.growNI)} (${m.yrs[0]}–${m.yrs[m.yrs.length - 1]}).</p>` : ''}</div>
  <div class="g g-main"><div class="pn"><div class="pn-h"><h3>Quem é dono</h3></div><div class="co-own"><div><b>${pct(v(own.insidersPercentHeld))}</b><small>fundadores, gestores e insiders</small></div><div><b>${pct(v(own.institutionsPercentHeld))}</b><small>instituições (${U.nf(v(own.institutionsCount) || 0)})</small></div><div><b>${v(own.institutionsPercentHeld) != null ? pct(Math.max(0, 1 - (v(own.insidersPercentHeld) || 0) - v(own.institutionsPercentHeld))) : '—'}</b><small>pequenos investidores e outros</small></div></div>
      ${inst.length ? `<div class="tblw"><table class="tbl"><thead><tr><th>Maiores acionistas institucionais</th><th class="r">%</th><th class="r">Valor</th></tr></thead><tbody>${inst.map(x => `<tr><td>${esc(x.organization)}</td><td class="r mono">${pct(v(x.pctHeld), 2)}</td><td class="r mono">${big(v(x.value), pcur)}</td></tr>`).join('')}</tbody></table></div>` : ''}
      ${funds.length ? `<div class="tblw" style="margin-top:8px"><table class="tbl"><thead><tr><th>Maiores fundos</th><th class="r">%</th></tr></thead><tbody>${funds.map(x => `<tr><td>${esc(x.organization)}</td><td class="r mono">${pct(v(x.pctHeld), 2)}</td></tr>`).join('')}</tbody></table></div>` : ''}
      ${ins.length ? `<div class="tblw" style="margin-top:8px"><table class="tbl"><thead><tr><th>Insiders</th><th>Cargo</th><th class="r">Ações</th></tr></thead><tbody>${ins.map(x => `<tr><td>${esc(x.name)}</td><td class="mut">${esc(x.relation || '')}</td><td class="r mono">${U.nf(v(x.positionDirect) || 0)}</td></tr>`).join('')}</tbody></table></div>` : ''}</div>
    <div class="pn"><div class="pn-h"><h3>Quem manda</h3></div>${off.length ? `<div class="list">${off.map(o => `<div class="li"><div class="li-t"><b>${esc(o.name)}</b><small>${esc(o.title || '')}${o.age ? ' · ' + o.age + ' anos' : ''}</small></div>${v(o.totalPay) ? `<span class="mono mut" title="remuneração anual">${big(v(o.totalPay), pcur)}</span>` : ''}</div>`).join('')}</div>` : '<p class="mut">Sem dados da administração.</p>'}
      <div class="pn-h" style="margin-top:12px"><h3>Analistas</h3><span class="mut" style="font-size:12px">${v(m.fd.numberOfAnalystOpinions) || 0} opiniões</span></div>
      ${recT ? `<div class="co-rec">${['Compra forte', 'Compra', 'Manter', 'Venda', 'Venda forte'].map((l, i) => `<div><i style="height:${Math.max(4, rec[i] / recT * 70)}px" class="r${i}"></i><b>${rec[i]}</b><small>${l}</small></div>`).join('')}</div>` : '<p class="mut">Sem recomendações de analistas.</p>'}
      ${tgt ? `<dl class="kv"><dt>Preço-alvo médio</dt><dd class="mono">${nx(tgt)} <span class="${tone(up(tgt))}">(${(up(tgt) >= 0 ? '+' : '') + U.pct(up(tgt), 0)})</span></dd><dt>Intervalo dos alvos</dt><dd class="mono">${nx(v(m.fd.targetLowPrice))} – ${nx(v(m.fd.targetHighPrice))}</dd></dl><p class="mut" style="font-size:11.5px">Os analistas erram muito e costumam ser otimistas: usa como termómetro, não como decisão.</p>` : ''}</div></div>`; };

/* ---------- tradução automática do "o que faz" ---------- */
const translate = (s, txt) => { if (!txt || TR[s] || !(OS.AI && OS.AI.key())) return; const c = U.ls.get('oc_cotr_' + s, null); if (c) { TR[s] = c; return; } TR[s] = 'busy';
  OS.AI.json([{ text: 'Explica em português de Portugal, em no máximo 130 palavras e de forma simples, o que esta empresa faz e como ganha dinheiro (principais produtos, clientes e mercados). Usa só a informação do texto. Responde APENAS com JSON {"pt":"..."}. Texto: ' + txt.slice(0, 4000) }], .1)
    .then(o => { TR[s] = String(o.pt || '').slice(0, 1200) || null; if (TR[s]) U.ls.set('oc_cotr_' + s, TR[s]); OS.request(); }).catch(() => { TR[s] = null; }); };

/* ---------- relatório da IA ---------- */
const compact = (s, m) => ({ simbolo: s, nome: m.pr.longName || m.pr.shortName, setor: m.ap.sector, industria: m.ap.industry, pais: m.ap.country, funcionarios: m.ap.fullTimeEmployees, descricao: String(m.ap.longBusinessSummary || '').slice(0, 1800), moeda_contas: m.cur, moeda_cotacao: m.pr.currency, preco: m.price, valor_mercado: m.mcap,
  multiplos: { pl: m.pe, pl_futuro: v(m.sd.forwardPE), pvp: m.pb, peg: m.peg, ev_ebitda: v(m.ks.enterpriseToEbitda), dy: m.dy, payout: m.payout, roe: m.roe, margem_liquida: m.nm, margem_bruta: m.gmL, divida_pl: m.de, divida_liq_ebitda: m.ndEb, liquidez_corrente: m.curR, beta: v(m.sd.beta) },
  anos: m.yrs, receita: m.rev, lucro_liquido: m.ni, ebitda: m.ebitda, fluxo_caixa_livre: m.fcf, divida_total: m.debt, caixa: m.cash, capital_proprio: m.eq, dividendos_pagos: m.div, crescimento_receita_anual: m.grow, crescimento_lucro_anual: m.growNI,
  piotroski: m.pio ? m.pio.score + '/' + m.pio.of : null, altman_z: m.alt ? { z: m.alt.z, zona: m.alt.zona } : null, preco_justo_graham: m.graham, preco_teto_bazin: m.bazin,
  checklists: Object.fromEntries(Object.entries(m.lists).map(([k, l]) => [k, l.map(c => (c.ok === true ? 'OK ' : c.ok === false ? 'FALHA ' : 'SEM DADOS ') + c.t + ' (' + c.val + ')')])),
  donos: { insiders: v((m.S.majorHoldersBreakdown || {}).insidersPercentHeld), instituicoes: v((m.S.majorHoldersBreakdown || {}).institutionsPercentHeld), maiores: ((m.S.institutionOwnership || {}).ownershipList || []).slice(0, 5).map(x => x.organization + ' ' + ((x.pctHeld || {}).fmt || '')) },
  gestao: (m.ap.companyOfficers || []).slice(0, 4).map(o => o.name + ' — ' + o.title), analistas: { recomendacao: m.fd.recommendationKey, alvo_medio: v(m.fd.targetMeanPrice), n: v(m.fd.numberOfAnalystOpinions) } });
A.invCoAI = async b => { const s = b.dataset.s, st = CO[s]; if (!st || !st.f || ST.ai) return; if (!(OS.AI && OS.AI.key())) { location.hash = 'investimentos.ia'; UI.toast('Liga primeiro a IA (chave Gemini) no Assistente IA', 'warn'); return; }
  const m = IX.coModel(st.f), nm = m.pr.longName || s; ST.ai = s; ST.aiErr = ''; OS.request();
  try { const r = await OS.InvAI.ask(`Faz uma análise completa da empresa ${nm} (${s}) para eu decidir se invisto. Cobre: 1) o que faz e como ganha dinheiro; 2) vantagens competitivas (fosso) e posição no setor; 3) qualidade e evolução dos resultados, margens e fluxo de caixa; 4) endividamento e solidez (Altman, Piotroski); 5) avaliação: está cara ou barata face aos múltiplos, ao preço justo de Graham e ao preço-teto de Bazin; 6) dividendos e política de remuneração; 7) quem são os donos e a gestão; 8) principais riscos e o que vigiar; 9) o que diriam os mestres; 10) se faz sentido NA MINHA carteira, com que peso máximo e como entrar (aportes graduais, preço de entrada). Usa os números de empresa_em_analise.`, { web: true, asset: s, extra: { empresa_em_analise: compact(s, m) } });
    REP[s] = r; try { const keys = Object.keys(REP); if (keys.length > 15) delete REP[keys[0]]; U.ls.set('oc_corep', REP); } catch (e) { } }
  catch (e) { ST.aiErr = e.message || 'A IA não respondeu.'; }
  ST.ai = false; OS.request(); };
})();
