/* OCEANUM — Investimentos completos (ao estilo Kinvo / TradeMap):
   Visão · Carteira ao vivo · Rentabilidade vs referências · Proventos · Alocação e rebalanceamento · Mercado (pesquisa, índices, lista de acompanhamento, cripto)
   · Página de cada ativo (gráfico, estatísticas, notícias) · Movimentos com importação CSV · Impostos (PT e BR) · Cotações e ligações. */
(() => {
'use strict';
const U = OS.U, UI = OS.UI, C = OS.C, V = OS.views, A = OS.act, L = OS.L, esc = U.esc, Inv = OS.Inv, IX = OS.InvX;
const n = v => U.num(v) || 0;
const M = (v, o) => IX.M(v, o), MK = v => IX.MK(v);
const cfg = () => OS.one('invcfg');
const cc = () => (OS.Country ? OS.Country.code() : 'PT');
const pctS = (v, d = 2) => (v >= 0 ? '+' : '') + U.pct(v, d);
const tone = v => v > 0 ? 'pos' : v < 0 ? 'neg' : 'mut';
const TABS = [['', 'Visão'], ['carteira', 'Carteira'], ['rentabilidade', 'Rentabilidade'], ['risco', 'Risco'], ['proventos', 'Proventos'], ['alocacao', 'Alocação'], ['mercado', 'Mercado'], ['empresas', 'Análise de empresas'], ['comparar', 'Comparar'], ['ia', 'Assistente IA'], ['movimentos', 'Movimentos'], ['impostos', 'Impostos'], ['cotacoes', 'Cotações']];
const GROUP = c => ({ 'Opção': 'Derivados', Futuro: 'Derivados', CFD: 'Derivados', 'Caixa em moeda estrangeira': 'Caixa', 'Ação': 'Ações', BDR: 'Ações', ETF: 'ETFs', FII: 'Fundos imobiliários', REIT: 'Fundos imobiliários', Fundo: 'Fundos', PPR: 'Reforma (PPR / previdência)', 'Previdência': 'Reforma (PPR / previdência)', Cripto: 'Cripto', Commodity: 'Ouro e commodities', Ouro: 'Ouro e commodities', 'Imóvel': 'Imóveis', Outro: 'Outros' }[c] || (L.RFC.includes(c) || c === 'Obrigação' ? 'Renda fixa' : 'Outros'));
const GC = { Derivados: '#e879f9', Caixa: '#cbd5e1', 'Ações': '#5cc8e6', ETFs: '#7c8cf8', 'Fundos imobiliários': '#f2a65a', Fundos: '#a78bfa', 'Renda fixa': '#34d399', Cripto: '#f472b6', 'Ouro e commodities': '#fbbf24', 'Reforma (PPR / previdência)': '#60a5fa', 'Imóveis': '#fb7185', Outros: '#94a3b8' };
const pxCell = (s, v, d) => s ? `<span class="mono px" data-pxs="${esc(s)}" data-k="p">${U.nf(v, d)}</span>` : `<span class="mono">${U.nf(v, d)}</span>`;
const chCell = (s, c) => `<span class="mono ${tone(c)}" ${s ? `data-pxs="${esc(s)}" data-k="ch"` : ''}>${pctS(c)}</span>`;

/* ---------- estado ao vivo no topo ---------- */
const liveBadge = () => { const st = IX.st, has = IX.hasScript(), t = IX.lastTick ? new Date(IX.lastTick).toLocaleTimeString('pt-PT', { hour: '2-digit', minute: '2-digit', second: '2-digit' }) : '';
  const srcs = [has && st.script === 'ok' ? 'Yahoo Finance' : '', st.ws === 'ok' ? 'Binance' : '', st.fh === 'ok' ? 'Finnhub' : '', IX.fxRates ? 'BCE (câmbio)' : ''].filter(Boolean);
  if (has && st.script === 'old') return `<a class="inv-live off" href="#investimentos.cotacoes"><i></i>Atualiza o script para teres cotações ao vivo</a>`;
  if (!has) return `<a class="inv-live off" href="#investimentos.cotacoes"><i></i>Liga as cotações em tempo real</a>`;
  return `<span class="inv-live ${st.script === 'erro' ? 'warn' : ''}"><i></i>${st.script === 'erro' ? 'Sem ligação ao mercado agora' : 'Ao vivo'}${srcs.length ? ' · ' + srcs.join(', ') : ''}${t ? ' · ' + t : ''}</span>`; };
const viewSel = () => `<div class="seg inv-cur" role="group">${['EUR', 'BRL', 'USD'].map(c => `<button class="${IX.view() === c ? 'on' : ''}" data-act="invView" data-v="${c}">${c}</button>`).join('')}</div>`;
A.invView = b => { cfg().view = b.dataset.v; OS.touch('invcfg'); };

V.investimentos = sub => {
  const s = sub || '';
  const head = UI.head('Investimentos', 'A tua carteira completa, ao vivo: ações, ETFs, FII, fundos, renda fixa, Tesouro, CDB, Certificados, PPR, cripto, ouro e mais.', `${viewSel()}${UI.addBtn('invtx', 'Movimento')}${UI.addBtn('assets', 'Ativo', null, '')}`, 'Dinheiro')
    + `<div class="inv-top">${liveBadge()}</div>` + UI.tabs('investimentos', TABS, s === 'ativo' ? '' : s);
  const miss = Inv.fxMissing();
  const fxNote = miss.length ? `<div class="note"><b>Câmbio em falta:</b> ${miss.join(', ')}. Sem internet, define-o em Cotações.</div>` : '';
  IX.extra = new Set();
  const body = (T[s] || T[''])();
  setTimeout(() => { const miss = [...IX.extra].filter(x => !IX.q(x)); if (miss.length && Date.now() - (IX._qt || 0) > 4000) { IX._qt = Date.now(); IX.tick(true); } }, 60);
  return head + fxNote + `<div class="inv">${body}</div>`;
};
const T = IX.T = {};

/* ================= VISÃO ================= */
const ensureHist = () => { const k = OS.all('invtx').length + ':' + OS.all('assets').length; if (IX.hcache && IX.hcache.key === k && Date.now() - IX.hcache.at < 30 * 6e4) return IX.hcache; if (!IX._hb) { IX._hb = 1; IX.build().catch(() => null).finally(() => { IX._hb = 0; OS.request(); }); } return IX.hcache; };
T[''] = () => { const S = IX.summary(); if (!OS.all('assets').length) return onboarding();
  const h = ensureHist(), m = h ? IX.metrics(h) : null, H = IX.health(S);
  const movers = S.P.filter(p => p.live && p.live.pc).sort((a, b) => b.dayPct - a.dayPct);
  const groups = Object.entries(U.groupBy(S.P, p => GROUP(p.a.cls))).map(([k, arr]) => ({ l: k, v: U.sum(arr, p => p.value), c: GC[k] })).sort((a, b) => b.v - a.v);
  const ser = h ? thin(h) : null;
  return `<div class="kpis">${UI.kpi('Património investido', `<span data-live="val">${M(S.val)}</span>`, `aplicado ${M(S.cost, { dec: 0 })}`)}
    ${UI.kpi('Hoje', `<span data-live="day" class="${tone(S.day)}">${M(S.day, { sign: 1 })}</span>`, `<span class="${tone(S.dayPct)}">${pctS(S.dayPct)}</span> · variação do dia, ao vivo`)}
    ${UI.kpi('Lucro / prejuízo', `<span data-live="pl">${M(S.pl, { sign: 1 })}</span>`, S.cost ? pctS(S.ret, 1) + ' sobre o aplicado' : '', { tone: tone(S.pl) })}
    ${UI.kpi('Rentabilidade total', m ? pctS(m.tot, 1) : '—', m ? `${m.xirr != null ? 'TIR ' + pctS(m.xirr, 1) + '/ano · ' : ''}com proventos e vendas` : 'a calcular…', { tone: m ? tone(m.tot) : '' })}
    ${UI.kpi('Proventos 12 meses', M(S.divs12), S.val ? 'yield ' + U.pct(S.divs12 / S.val, 2) : '')}</div>
  <div class="g g-main"><div class="pn"><div class="pn-h"><h3>Património vs aplicado</h3><a class="acc" href="#investimentos.rentabilidade" style="font-size:12px">ver rentabilidade →</a></div>${ser ? C.mount({ type: 'line', labels: ser.l, series: [{ name: 'Património', data: ser.v }, { name: 'Aplicado', data: ser.c, color: 'var(--mut)', dash: 1 }], fmt: MK, min0: false }, 240) : `<div class="chart-empty" style="height:240px">${IX._hb ? 'A reconstruir o histórico com as cotações…' : 'Regista movimentos para ver a evolução.'}</div>`}</div>
    <div class="pn"><div class="pn-h"><h3>Por tipo de investimento</h3><a class="acc" href="#investimentos.alocacao" style="font-size:12px">alocação →</a></div>${C.mount({ type: 'donut', data: groups, label: 'Por tipo', fmt: MK, centerSub: 'investido', max: 8 }, 210)}</div></div>
  <div class="g g2"><div class="pn"><div class="pn-h"><h3>${UI.ic('trend')}Maiores altas e baixas de hoje</h3></div>${movers.length ? `<div class="list">${[...movers.slice(0, 3), ...movers.slice(-3).reverse()].filter((p, i, a) => a.indexOf(p) === i).map(p => `<div class="li click" data-act="invOpen" data-s="${esc(p.a.sym)}"><div class="li-t"><b>${esc(p.a.ticker || p.a.sym)}</b><small>${esc(p.a.name)}</small></div>${UI.spark(p.live.d || [], p.dayPct >= 0 ? 'var(--pos)' : 'var(--neg)')}${chCell(p.a.sym, p.dayPct)}</div>`).join('')}</div>` : UI.empty(IX.hasScript() ? 'Sem cotações de hoje ainda.' : 'Liga as cotações ao vivo para veres as variações.')}</div>
    <div class="pn inv-health"><div class="pn-h"><h3>${UI.ic('zap')}Saúde da carteira</h3><a class="acc" href="#investimentos.ia" style="font-size:12px">pedir análise à IA →</a></div><div class="ih-top"><div class="ih-score ${H.score >= 75 ? 'pos' : H.score >= 50 ? 'warn' : 'neg'}"><b>${H.score}</b><small>/100</small></div><div class="ih-l">${H.items.slice(0, 5).map(i => `<div class="${i.ok ? 'pos' : i.w ? 'warn' : 'neg'}">${i.ok ? '✓' : '!'} ${esc(i.t)}</div>`).join('')}</div></div></div></div>
  ${alerts(S)}`; };
const thin = h => { const k = Math.max(1, Math.ceil(h.dates.length / 160)), idx = h.dates.map((_, i) => i).filter(i => i % k === 0 || i === h.dates.length - 1); return { l: idx.map(i => U.fmtDS ? U.fmtDS(h.dates[i]) : h.dates[i]), v: idx.map(i => h.V[i]), c: idx.map(i => h.C[i]), i: idx }; };
const alerts = S => { const out = [], val = S.val || 1;
  S.P.forEach(p => { if (p.value / val > .25 && S.P.length > 2 && p.a.cls !== 'ETF') out.push(`<b>${esc(p.a.ticker || p.a.name)}</b> pesa ${U.pct(p.value / val)} da carteira (concentração alta).`); });
  OS.all('assets').filter(a => IX.isRF(a) && a.venc && a.venc >= U.today() && U.diff(a.venc, U.today()) <= 30).forEach(a => out.push(`<b>${esc(a.name)}</b> vence a ${U.fmtD(a.venc)}: decide onde reinvestir.`));
  const noSym = S.P.filter(p => !p.a.sym && !IX.isRF(p.a) && !['Imóvel', 'PPR', 'Previdência', 'Outro', 'Crowdlending/P2P'].includes(p.a.cls)); if (noSym.length) out.push(`${noSym.length} ativo(s) sem símbolo de cotação (${noSym.slice(0, 4).map(p => esc(p.a.ticker || p.a.name)).join(', ')}): <a class="acc" href="#investimentos.carteira">define o símbolo</a> para atualizarem sozinhos.`);
  const ev = IX.detected ? IX.detected() : []; if (ev.length) out.push(`${ev.length} evento(s) detetado(s) por registar (dividendos/desdobramentos): <a class="acc" href="#investimentos.proventos">ver e registar</a>.`);
  OS.all('assets').filter(a => a.cls === 'Opção' && a.venc && a.venc >= U.today() && U.diff(a.venc, U.today()) <= 7 && Inv.pos(a).qty).forEach(a => out.push(`Opção <b>${esc(a.ticker || a.name)}</b> vence a ${U.fmtD(a.venc)}.`));
  return out.length ? `<div class="pn"><div class="pn-h"><h3>Atenção</h3></div>${out.map(x => `<div class="note" style="margin:4px 0">${x}</div>`).join('')}</div>` : ''; };
const TYPES = [['Ação, ETF, FII, BDR, fundo', null, 'search'], ['CDB, LCI/LCA, debênture (BR)', { cls: 'CDB', idx: '% do CDI', rate: 100, currency: 'BRL', liq: 'Diária' }], ['Tesouro Direto', 'td'], ['Depósito a prazo / Certificados (PT)', { cls: 'Depósito a prazo', idx: 'Pré-fixado', rate: 2, currency: 'EUR' }], ['Obrigação (cotada em % do nominal)', { cls: 'Obrigação', mult: .01, currency: 'EUR' }], ['PPR / previdência', { cls: 'PPR', currency: 'EUR' }], ['Cripto', null, 'search'], ['Ouro / commodity', { cls: 'Ouro', sym: 'GC=F', currency: 'USD' }], ['Opção', { cls: 'Opção', mult: 100, currency: 'USD', optType: 'Call (compra)' }], ['Futuro / CFD (alavancado)', { cls: 'CFD', alav: 5, mult: 1, currency: 'EUR' }], ['Caixa em moeda estrangeira', { cls: 'Caixa em moeda estrangeira', name: 'Dólares na corretora', currency: 'USD' }], ['Imóvel', { cls: 'Imóvel', currency: 'EUR' }], ['Crowdlending / P2P', { cls: 'Crowdlending/P2P', idx: 'Pré-fixado', rate: 8, currency: 'EUR' }], ['Outro', { cls: 'Outro' }]];
const addTypes = () => `<div class="inv-types">${TYPES.map(([l, d, k]) => k === 'search' ? `<a class="chip" href="#investimentos.mercado">${esc(l)}</a>` : d === 'td' ? `<a class="chip" href="#investimentos.cotacoes">${esc(l)}</a>` : `<button class="chip" data-new="assets" data-defs='${esc(JSON.stringify(d))}'>${esc(l)}</button>`).join('')}</div>`;
const onboarding = () => `<div class="pn inv-on"><h3>Começa a tua carteira</h3><p class="mut">Pesquisa um ativo (ex.: <i>VWCE</i>, <i>Apple</i>, <i>PETR4</i>, <i>Bitcoin</i>) e adiciona-o, ou regista renda fixa (Tesouro, CDB, Certificados de Aforro, depósito a prazo) com a taxa: o Oceanum calcula o rendimento dia a dia.</p>
  <div class="row gap8" style="flex-wrap:wrap"><a class="btn pri" href="#investimentos.mercado">${UI.ic('search')}Pesquisar ativo</a><a class="btn ghost" href="#investimentos.movimentos">Importar CSV da corretora</a></div><b style="font-size:13px">Ou escolhe o tipo:</b>${addTypes()}
  ${IX.hasScript() ? '' : `<div class="note" style="margin-top:12px">Para cotações em tempo real de todas as bolsas, liga o script em <a class="acc" href="#investimentos.cotacoes">Cotações</a>. A cripto já atualiza sem nada.</div>`}</div>`;

/* ================= saúde da carteira (regras objetivas, sem IA) ================= */
IX.health = (S = IX.summary()) => { const items = [], val = S.val || 0, P = S.P; let score = 100;
  const add = (ok, t, pen, w) => { items.push({ ok, t, w }); if (!ok) score -= pen; };
  const Fin = OS.Fin, res = Fin.reserve ? Fin.reserve() : 0, exp = (Fin.avgMonthly && Fin.avgMonthly(3, 'exp')) || 0;
  add(!exp || res >= exp * 3, exp ? (res >= exp * 3 ? `Reserva de emergência cobre ${U.nf(res / exp, 1)} meses` : `Reserva cobre só ${U.nf(res / (exp || 1), 1)} meses de despesas (alvo: 3–6)`) : 'Reserva de emergência: regista despesas para avaliar', 20, res > 0);
  const debt = (Fin.cardDebt ? Fin.cardDebt() : 0) + (Fin.debtsTotal ? Fin.debtsTotal() : 0); add(!debt, debt ? `Tens ${M(debt, { dec: 0 })} em dívidas: pagar dívida cara rende mais que investir` : 'Sem dívidas registadas', 15, true);
  const top = P.length ? Math.max(...P.map(p => p.value)) / (val || 1) : 0; const topP = P.find(p => p.value / (val || 1) === top); add(top <= .2 || P.length <= 1 && val < 2000 || (topP && topP.a.cls === 'ETF' && top <= .8), top > .2 ? `Maior posição pesa ${U.pct(top)} (ideal < 20%, exceto ETFs globais)` : 'Sem concentração excessiva num ativo', P.length && /ETF/.test((P.find(p => p.value / val === top) || { a: {} }).a.cls) ? 3 : 12, true);
  const hhi = U.sum(P, p => Math.pow(p.value / (val || 1), 2)), eff = hhi ? 1 / hhi : 0, hasGlobalEtf = P.some(p => p.a.cls === 'ETF'); add(eff >= 5 || hasGlobalEtf, `Diversificação efetiva: ${U.nf(eff, 1)} ativos${hasGlobalEtf ? ' + ETF(s)' : ''}`, 10, true);
  const groups = new Set(P.map(p => GROUP(p.a.cls))); add(groups.size >= 2, `${groups.size} tipo(s) de investimento`, 8, true);
  const curs = {}; P.forEach(p => curs[p.a.currency || 'EUR'] = (curs[p.a.currency || 'EUR'] || 0) + p.value); const home = cc() === 'BR' ? 'BRL' : 'EUR', homeW = (curs[home] || 0) / (val || 1); add(homeW >= .3 || !val, `Moeda: ${U.pct(homeW)} em ${home}${homeW < .3 ? ' (muito exposto a câmbio para quem gasta em ' + home + ')' : ''}`, 6, true);
  const cryptoW = U.sum(P.filter(p => p.a.cls === 'Cripto'), p => p.value) / (val || 1); add(cryptoW <= .1, cryptoW > .1 ? `Cripto pesa ${U.pct(cryptoW)} (risco alto; costuma recomendar-se ≤ 5–10%)` : `Cripto: ${U.pct(cryptoW)}`, 8, true);
  const tg = cfg().tgt || {}, keys = Object.keys(tg).filter(k => n(tg[k]) > 0); if (keys.length) { const off = U.sum(keys, k => Math.abs(U.sum(P.filter(p => GROUP(p.a.cls) === k), p => p.value) / (val || 1) - n(tg[k]) / 100)); add(off <= .15, `Desvio face à alocação alvo: ${U.pct(off / 2)}`, 8, true); } else add(false, 'Sem alocação alvo definida (Alocação → metas)', 4, true);
  const stale = P.filter(p => p.stale && !p.rf).length; add(!stale, stale ? `${stale} cotação(ões) desatualizada(s)` : 'Cotações atualizadas', 3, true);
  const pf = cfg().perfil; add(!!pf, pf ? `Perfil de investidor: ${pf.nome}` : 'Perfil de investidor por definir (Assistente IA)', 4, true);
  return { score: Math.max(0, Math.round(score)), items: items.sort((a, b) => a.ok - b.ok), eff, top, cryptoW, homeW, curs }; };

/* ================= CARTEIRA ================= */
T.carteira = () => { const S = IX.summary(); if (!S.P.length) return onboarding(); const val = S.val || 1;
  const groups = Object.entries(U.groupBy(S.P, p => GROUP(p.a.cls))).sort((a, b) => U.sum(b[1], p => p.value) - U.sum(a[1], p => p.value));
  return `<div class="kpis">${UI.kpi('Património', `<span data-live="val">${M(S.val)}</span>`)}${UI.kpi('Hoje', `<span data-live="day" class="${tone(S.day)}">${M(S.day, { sign: 1 })}</span>`, pctS(S.dayPct))}${UI.kpi('Lucro / prejuízo', `<span data-live="pl">${M(S.pl, { sign: 1 })}</span>`, pctS(S.ret, 1), { tone: tone(S.pl) })}${UI.kpi('Ativos', S.P.length, groups.length + ' tipos')}</div>
  ${groups.map(([g, arr]) => { const gv = U.sum(arr, p => p.value), gc = U.sum(arr, p => p.cost), rf = g === 'Renda fixa';
    return `<section class="inv-g"><div class="inv-gh"><span class="dot" style="background:${GC[g] || 'var(--mut)'}"></span><h3>${esc(g)}</h3><span class="mut">${U.pct(gv / val, 1)}</span><b class="mono">${M(gv)}</b><span class="mono ${tone(gv - gc)}">${gc ? pctS((gv - gc) / gc, 1) : ''}</span></div>
    <div class="tblw"><table class="tbl inv-t"><thead><tr><th>Ativo</th>${rf ? '<th>Rende</th><th class="mh">Vencimento</th><th class="r mh">Aplicado</th><th class="r">Valor bruto</th><th class="r">Líquido (estim.)</th>' : '<th class="r mh">Qtd.</th><th class="r mh">Preço médio</th><th class="r">Preço</th><th class="r">Dia</th><th class="r">Valor</th>'}<th class="r mh">L/P</th><th class="r">Rent.</th><th class="r mh">Peso</th></tr></thead><tbody>
    ${U.sortBy(arr, p => p.value, -1).map(p => { const a = p.a, cur = a.currency || 'EUR';
      return `<tr class="click" ${a.sym ? `data-act="invOpen" data-s="${esc(a.sym)}"` : `data-edit="assets:${a.id}"`} tabindex="0"><td><b>${esc(a.ticker || a.sym || a.name)}</b>${p.live ? '<span class="lv-mini" title="cotação ao vivo"></span>' : ''}<div class="mut" style="font-size:12px">${esc(a.name)}${a.broker ? ' · ' + esc(a.broker) : ''}${p.short ? ' · <span class="bdg neg">vendido</span>' : ''}${p.lev ? ` · exposição ${M(p.exposure, { dec: 0 })} · ${U.nf(p.lev, 1)}×` : ''}${a.cls === 'Opção' ? ` · ${esc(a.optType || '')} ${a.strike ? 'strike ' + U.nf(n(a.strike), 2) : ''}${a.venc ? ' · vence ' + U.fmtD(a.venc) : ''}` : ''}${p.mam != null ? ` · <span title="na curva: ${M(p.curve)}">a mercado</span>` : ''}${IX.tdSym(a) ? ' · preço oficial do Tesouro' : ''}</div></td>
      ${rf ? `<td>${esc(a.idx || '')} ${a.idx === 'Poupança' ? '' : U.nf(n(a.rate), 2) + (a.idx === '% do CDI' ? '%' : '% a.a.')}</td><td class="mh">${a.venc ? U.fmtD(a.venc) + (p.matured ? ' <span class="bdg">vencido</span>' : '') : (a.liq || '—')}</td><td class="r mono mh">${M(p.cost)}</td><td class="r mono">${M(p.value)}</td><td class="r mono">${M(p.net != null ? p.net : p.value)}</td>`
      : `<td class="r mono mh">${U.nf(p.qty, p.qty % 1 ? 4 : 0)}</td><td class="r mono mh">${IX.Mc(p.avg, cur)}</td><td class="r">${p.hasPrice ? pxCell(a.sym, p.price != null ? p.price : n(a.price), 2) : '—'}${p.stale && !p.live ? ' <span class="warn" title="cotação antiga">•</span>' : ''}</td><td class="r">${p.live && p.live.pc ? chCell(a.sym, p.dayPct) : '—'}</td><td class="r mono">${M(p.value)}</td>`}
      <td class="r mono mh ${tone(p.pl)}">${M(p.pl, { sign: 1 })}</td><td class="r mono ${tone(p.ret)}">${pctS(p.ret, 1)}</td><td class="r mono mh">${U.pct(p.value / val, 1)}${n(a.target) ? `<div class="mut" style="font-size:11px">alvo ${a.target}%</div>` : ''}</td></tr>`; }).join('')}</tbody></table></div></section>`; }).join('')}
  ${UI.toggle('Adicionar outro tipo de investimento', addTypes(), 'invTypes', 'plus')}
  <p class="mut" style="font-size:12px">Toca num ativo para ver gráfico, estatísticas e notícias. Valores em ${IX.view()}${IX.view() !== 'EUR' ? ' (convertidos ao câmbio atual)' : ''}. Renda fixa: valor calculado com ${cc() === 'BR' ? 'CDI, Selic, IPCA e poupança do Banco Central' : 'a taxa indicada'}; o líquido desconta o imposto estimado.</p>`; };

/* ================= RENTABILIDADE ================= */
const PER = [['1m', '1M', 30], ['3m', '3M', 91], ['6m', '6M', 182], ['ytd', 'No ano', 0], ['1a', '12M', 365], ['2a', '2 anos', 730], ['tudo', 'Tudo', 1e5]];
T.rentabilidade = () => { const h = ensureHist(); if (!OS.all('invtx').length) return onboarding(); if (!h) return `<div class="pn"><div class="sai-busy"><div class="fd-spin"></div><span>A reconstruir a carteira dia a dia com as cotações históricas…</span></div></div>`;
  const per = OS.ui.invPer || 'tudo', P0 = PER.find(p => p[0] === per) || PER[6], start = per === 'ytd' ? U.today().slice(0, 4) + '-01-01' : U.addDays(U.today(), -P0[2]);
  let i0 = h.dates.findIndex(d => d >= start); if (i0 < 0) i0 = 0; i0 = Math.max(i0, h.V.findIndex(v => v > 0));
  const dates = h.dates.slice(i0), base = 1 + h.cum[i0], cum = h.cum.slice(i0).map(c => (1 + c) / base - 1), sub = { dates, V: h.V.slice(i0), F: h.F.slice(i0), D: h.D.slice(i0), C: h.C.slice(i0), R: [0, ...h.R.slice(i0 + 1)], cum };
  const m = IX.metrics(sub), sel = OS.ui.invBench || IX.BENCH(cc()).slice(0, 2).map(b => b[0]), B = IX.BENCH(cc());
  const bkey = sel.join(',') + '|' + dates[0] + '|' + dates.length; if (IX._bk !== bkey && !IX._bb) { IX._bb = 1; Promise.all(sel.map(k => IX.bench(k, dates).catch(() => null))).then(r => { IX._bs = r; IX._bk = bkey; }).finally(() => { IX._bb = 0; OS.request(); }); }
  const bs = IX._bk === bkey ? IX._bs || [] : [], k = Math.max(1, Math.ceil(dates.length / 160)), idx = dates.map((_, i) => i).filter(i => i % k === 0 || i === dates.length - 1);
  const pal = ['var(--mut)', '#f2a65a', '#a78bfa', '#34d399'];
  const series = [{ name: 'Carteira', data: idx.map(i => cum[i] * 100) }, ...sel.map((s, j) => bs[j] ? { name: (B.find(b => b[0] === s) || [s, s])[1], data: idx.map(i => bs[j][i] == null ? null : bs[j][i] * 100), color: pal[j % pal.length], dash: 1 } : null).filter(Boolean)];
  const years = {}; (m ? m.mret : []).forEach(([ym, r]) => { const y = ym.slice(0, 4); (years[y] = years[y] || {})[+ym.slice(5)] = r; });
  const allM = IX.metrics(h); const yearsAll = {}; (allM ? allM.mret : []).forEach(([ym, r]) => { const y = ym.slice(0, 4); (yearsAll[y] = yearsAll[y] || {})[+ym.slice(5)] = r; });
  const contrib = IX.positions().map(p => ({ l: p.a.ticker || p.a.name, v: p.pl + p.realized + p.divs })).filter(x => Math.abs(x.v) > .01).sort((a, b) => b.v - a.v);
  return `<div class="row gap8 inv-per">${PER.map(([k2, l]) => `<button class="chip ${per === k2 ? 'on' : ''}" data-ui="invPer" data-v="${k2}">${l}</button>`).join('')}</div>
  <div class="kpis">${m ? `${UI.kpi('Rentabilidade', pctS(m.tot, 2), P0[1] === 'Tudo' ? 'desde o início (TWR)' : P0[1], { tone: tone(m.tot) })}${UI.kpi('Ao ano', m.years >= .9 ? pctS(m.ann, 1) : '—', m.xirr != null ? 'TIR (dinheiro): ' + pctS(m.xirr, 1) : '')}${UI.kpi('Volatilidade', U.pct(m.vol, 1), 'anualizada')}${UI.kpi('Sharpe', m.sharpe == null ? '—' : U.nf(m.sharpe, 2), 'vs ' + U.pct(m.rf, 1) + ' sem risco; Sortino ' + (m.sortino == null ? '—' : U.nf(m.sortino, 2)))}${UI.kpi('Queda máxima', U.pct(m.mdd, 1), m.mddAt ? 'até ' + U.fmtD(m.mddAt) : '', { tone: 'neg' })}${UI.kpi('Meses positivos', m.pos + '/' + m.nm, m.best[0] ? 'melhor ' + U.fmtYM(m.best[0]) + ' ' + pctS(m.best[1], 1) : '')}` : UI.kpi('Rentabilidade', '—', 'poucos dados no período')}</div>
  <div class="pn"><div class="pn-h"><h3>Carteira vs referências</h3><div class="row gap6" style="flex-wrap:wrap">${B.map(([k2, l]) => `<button class="chip ${sel.includes(k2) ? 'on' : ''}" data-act="invBench" data-v="${esc(k2)}">${esc(l)}</button>`).join('')}</div></div>
    ${C.mount({ type: 'line', labels: idx.map(i => U.fmtDS ? U.fmtDS(dates[i]) : dates[i]), series, fmt: v => U.nf(v, 0) + '%', min0: false, area: false }, 290)}
    ${h.missing.length ? `<div class="note">Sem histórico de cotações para: ${h.missing.map(esc).join(', ')} (usado o preço médio até ao preço atual). ${IX.hasScript() ? 'Confirma o símbolo do ativo.' : 'Liga o script em Cotações para ter histórico de todas as bolsas.'}</div>` : ''}
    <p class="mut" style="font-size:12px;margin:6px 0 0">Rentabilidade por cotas (TWR): não é afetada pelos teus aportes e resgates, por isso compara-se diretamente com os índices. A TIR mostra o retorno do teu dinheiro tendo em conta quando aportaste.</p></div>
  <div class="g g-main"><div class="pn"><div class="pn-h"><h3>Rentabilidade mês a mês</h3></div>${heat(yearsAll)}</div>
  <div class="pn"><div class="pn-h"><h3>Quem mais contribuiu</h3><span class="mut" style="font-size:12px">ganho total (valorização + proventos + vendas)</span></div>${contrib.length ? `<div class="list">${contrib.slice(0, 10).map(c => `<div class="bar-row" style="grid-template-columns:90px 1fr 120px"><span class="l">${esc(c.l)}</span>${UI.bar(Math.abs(c.v) / Math.max(...contrib.map(x => Math.abs(x.v))), c.v >= 0 ? 'pos' : 'neg')}<span class="v ${tone(c.v)}">${M(c.v, { sign: 1, dec: 0 })}</span></div>`).join('')}</div>` : UI.empty('Sem dados.')}</div></div>
  <div class="pn"><div class="pn-h"><h3>Património e aportes</h3></div>${(() => { const t = thin(h); return C.mount({ type: 'line', labels: t.l, series: [{ name: 'Património', data: t.v }, { name: 'Aplicado (aportes − resgates)', data: t.c, color: 'var(--mut)', dash: 1 }], fmt: MK, min0: false }, 230); })()}</div>`; };
A.invBench = b => { const cur = OS.ui.invBench || IX.BENCH(cc()).slice(0, 2).map(x => x[0]), v = b.dataset.v; OS.setUI('invBench', cur.includes(v) ? cur.filter(x => x !== v) : [...cur, v].slice(-3)); };
const heat = Y => { const ys = Object.keys(Y).sort().reverse(); if (!ys.length) return UI.empty('Sem meses completos ainda.'); const MS = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'];
  const cell = r => r == null ? '<td></td>' : `<td class="hm" style="background:${r >= 0 ? `rgba(52,211,153,${Math.min(.85, .15 + Math.abs(r) * 9)})` : `rgba(248,113,113,${Math.min(.85, .15 + Math.abs(r) * 9)})`}">${(r * 100).toFixed(1)}</td>`;
  return `<div class="tblw"><table class="tbl hmt"><thead><tr><th></th>${MS.map(m => `<th>${m}</th>`).join('')}<th>Ano</th></tr></thead><tbody>${ys.map(y => { const yr = Object.values(Y[y]).reduce((g, r) => g * (1 + r), 1) - 1; return `<tr><th>${y}</th>${MS.map((_, i) => cell(Y[y][i + 1])).join('')}<td class="mono ${tone(yr)}"><b>${(yr * 100).toFixed(1)}%</b></td></tr>`; }).join('')}</tbody></table></div><p class="mut" style="font-size:11.5px;margin:4px 0 0">Valores em %. Verde = mês positivo.</p>`; };


/* ================= RISCO ================= */
const PMAX = { Conservador: 3, Moderado: 4, Arrojado: 5, Agressivo: 6 };
T.risco = () => { if (!OS.all('invtx').length) return onboarding(); const h = ensureHist(); if (!h) return `<div class="pn"><div class="sai-busy"><div class="fd-spin"></div><span>A calcular o risco com o histórico das cotações…</span></div></div>`;
  const bk = IX.BENCH(cc()).find(b => !/^dep:|^CDI|^IPCA/.test(b[0])) || ['^GSPC', 'S&P 500'], key = bk[0] + '|' + h.dates.length + '|' + h.at;
  if (IX._rbk !== key && !IX._rbb) { IX._rbb = 1; IX.bench(bk[0], h.dates).then(r => { IX._rb = r; IX._rbk = key; }).catch(() => { IX._rb = null; IX._rbk = key; }).finally(() => { IX._rbb = 0; OS.request(); }); }
  const r = IX.risk(h, IX._rbk === key ? IX._rb : null); if (!r) return UI.empty('Preciso de pelo menos um mês de histórico para medir o risco.');
  const pf = cfg().perfil, mx = pf ? PMAX[pf.nome] : null, ok = mx == null || r.sri <= mx, S = IX.summary();
  const k = Math.max(1, Math.ceil(h.dates.length / 160)), ix = h.dates.map((_, i) => i).filter(i => i % k === 0 || i === h.dates.length - 1);
  const top = r.assets.slice(0, 8), cidx = r.assets.slice(0, 8).map(x => r.names.indexOf(x.a.ticker || x.a.sym || x.a.name));
  return `<div class="pn rk-sri"><div class="rk-sri-h"><div><div class="eyebrow">Nota de risco da carteira</div><div class="rk-big">${r.sri}<small>/7</small></div></div>
    <div class="rk-scale">${[1, 2, 3, 4, 5, 6, 7].map(i => `<span class="${i === r.sri ? 'on' : ''} s${i}">${i}</span>`).join('')}<div class="rk-lab"><small>menor risco · menor retorno potencial</small><small>maior risco · maior retorno potencial</small></div></div>
    <div class="rk-pf ${ok ? 'pos' : 'warn'}">${pf ? (ok ? `✓ Adequado ao teu perfil ${esc(pf.nome)} (até ${mx})` : `! Acima do teu perfil ${esc(pf.nome)} (até ${mx}): a carteira oscila mais do que disseste aguentar`) : 'Define o perfil no Assistente IA para comparar'}</div></div>
    <p class="mut" style="margin:6px 0 0;font-size:12.5px">Escala europeia de risco (indicador SRI dos documentos KID), calculada com a volatilidade real da tua carteira nos últimos 12 meses (${U.pct(r.vol, 1)}/ano).</p></div>
  <div class="kpis">${UI.kpi('Volatilidade', U.pct(r.vol, 1) + '/ano', 'quanto a carteira oscila; ações globais ≈ 15%')}
    ${UI.kpi('VaR 95% · 1 mês', M(-r.var21e, { dec: 0 }), `num mês mau (1 em cada 20) podes perder até ${U.pct(r.var1 * Math.sqrt(21), 1)}`, { tone: 'neg' })}
    ${UI.kpi('CVaR · 1 mês', M(-r.cvar21e, { dec: 0 }), 'perda média nesses meses maus (pior cenário médio)', { tone: 'neg' })}
    ${UI.kpi('VaR 95% · 1 dia', M(-r.var1e, { dec: 0 }), U.pct(r.var1, 2) + ' · paramétrico ' + U.pct(r.varP, 2))}
    ${UI.kpi('Queda máxima', U.pct(r.mdd, 1), `agora ${U.pct(r.curDD, 1)} do máximo · maior período abaixo: ${r.maxUw} dias úteis`, { tone: 'neg' })}
    ${UI.kpi('Beta vs ' + bk[1], r.beta == null ? '…' : U.nf(r.beta, 2), r.corr == null ? 'a calcular' : `correlação ${U.nf(r.corr, 2)} · se o ${bk[1]} cair 10%, a carteira tende a cair ~${U.pct(Math.abs(r.beta * .1), 1)}`)}</div>
  <div class="g g-main"><div class="pn"><div class="pn-h"><h3>Distância ao máximo (drawdown)</h3><span class="mut" style="font-size:12px">quanto estavas abaixo do pico em cada dia</span></div>${C.mount({ type: 'line', labels: ix.map(i => U.fmtDS(h.dates[i])), series: [{ name: 'Abaixo do máximo', data: ix.map(i => r.dd[i] * 100), color: 'var(--neg)' }], fmt: v => U.nf(v, 0) + '%', min0: false }, 230)}</div>
    <div class="pn"><div class="pn-h"><h3>Diversificação e liquidez</h3></div><dl class="kv"><dt>Rácio de diversificação</dt><dd class="mono">${U.nf(r.divRatio, 2)}×</dd><dt>Diversificação efetiva</dt><dd class="mono">${U.nf(IX.health(S).eff, 1)} ativos</dd><dt>Liquidez imediata</dt><dd class="mono">${U.pct(r.liq)}</dd><dt>Em moeda estrangeira</dt><dd class="mono">${U.pct(1 - IX.health(S).homeW)}</dd><dt>Cripto</dt><dd class="mono">${U.pct(IX.health(S).cryptoW, 1)}</dd></dl><p class="mut" style="font-size:12px;margin:8px 0 0">Rácio de diversificação &gt; 1,3× = os ativos compensam-se bem uns aos outros. Liquidez = o que consegues vender em poucos dias.</p></div></div>
  <div class="pn"><div class="pn-h"><h3>${UI.ic('shield')}Testes de stress</h3><span class="mut" style="font-size:12px">quanto perderia a carteira de hoje se a história se repetisse</span></div><div class="tblw"><table class="tbl"><thead><tr><th>Cenário</th><th class="r">Perda</th><th class="r">%</th><th class="mh" style="width:160px"></th></tr></thead><tbody>${r.stress.map(x => `<tr><td style="white-space:normal"><b>${esc(x.nm)}</b><div class="mut" style="font-size:12px">${esc(x.ds)}</div></td><td class="r mono ${tone(x.loss)}">${M(x.loss, { sign: 1, dec: 0 })}</td><td class="r mono ${tone(x.pct)}">${pctS(x.pct, 1)}</td><td class="mh">${UI.bar(Math.min(1, Math.abs(x.pct) / .6), x.pct < -.25 ? 'neg' : x.pct < -.1 ? 'warn' : 'pos')}</td></tr>`).join('')}</tbody></table></div><p class="mut" style="font-size:12px;margin:6px 0 0">Choques históricos aproximados por tipo de ativo. A renda fixa levada até ao vencimento não perde valor nestes cenários.</p></div>
  <div class="g g-main"><div class="pn"><div class="pn-h"><h3>De onde vem o risco</h3><span class="mut" style="font-size:12px">peso no dinheiro vs peso no risco</span></div><div class="tblw"><table class="tbl"><thead><tr><th>Ativo</th><th class="r">Peso</th><th class="r">Volatilidade</th><th>Contribuição para o risco</th></tr></thead><tbody>${top.map(x => `<tr><td><b>${esc(x.a.ticker || x.a.sym || x.a.name)}</b></td><td class="r mono">${U.pct(x.w, 1)}</td><td class="r mono">${U.pct(x.vol, 1)}</td><td><div class="row gap8" style="align-items:center">${UI.bar(Math.max(0, x.rc), x.rc > x.w * 1.5 ? 'neg' : x.rc > x.w ? 'warn' : 'pos')}<span class="mono" style="min-width:52px;text-align:right">${U.pct(x.rc, 1)}</span></div></td></tr>`).join('')}</tbody></table></div><p class="mut" style="font-size:12px;margin:6px 0 0">Vermelho: o ativo traz muito mais risco do que dinheiro (ex.: 11% do dinheiro e 35% do risco).</p></div>
    <div class="pn"><div class="pn-h"><h3>Correlação entre ativos</h3><span class="mut" style="font-size:12px">1 = andam juntos · 0 = independentes</span></div>${cidx.length > 1 ? `<div class="tblw"><table class="tbl hmt rk-c"><thead><tr><th></th>${cidx.map(i => `<th>${esc(r.names[i])}</th>`).join('')}</tr></thead><tbody>${cidx.map(i => `<tr><th>${esc(r.names[i])}</th>${cidx.map(j => { const v = r.C[i][j]; return `<td class="hm" style="background:rgba(${v >= 0 ? '248,113,113' : '52,211,153'},${Math.min(.85, Math.abs(v) * .8)})">${U.nf(v, 2)}</td>`; }).join('')}</tr>`).join('')}</tbody></table></div>` : UI.empty('Precisas de pelo menos 2 ativos com histórico.')}</div></div>
  <p class="mut" style="font-size:12px">Como ler: a volatilidade e o VaR usam os retornos diários reais dos últimos ${r.n} dias úteis; o VaR diz o limite das perdas em 95% dos casos, o CVaR a perda média nos 5% piores. O passado não garante o futuro: crises novas podem ser maiores.</p>`; };

/* ================= PROVENTOS ================= */
T.proventos = () => { const INC = IX.INC, D = OS.all('invtx').filter(t => INC.has(t.type)), fxOf = t => Inv.fx((OS.get('assets', t.asset) || {}).currency), net = t => (n(t.amount) - n(t.tax) - n(t.fees)) * fxOf(t);
  const S = IX.summary(), ms = OS.Fin.months(24), TY = ['Dividendo', 'JCP', 'Rendimento', 'Juros', 'Aluguer'], TC = { Dividendo: 'var(--pos)', JCP: '#5cc8e6', Rendimento: '#f2a65a', Juros: '#a78bfa', Aluguer: '#f472b6' };
  const tot = U.sum(D, net), last12 = D.filter(t => t.date >= U.addDays(U.today(), -365)), y12 = U.sum(last12, net), tax12 = U.sum(last12, t => n(t.tax) * fxOf(t)), avg = y12 / 12, meta = n(cfg().meta);
  const byA = Object.entries(U.groupBy(D, t => t.asset)).map(([id, arr]) => { const a = OS.get('assets', id) || { name: '—' }, p = Inv.pos(a), d12 = U.sum(arr.filter(t => t.date >= U.addDays(U.today(), -365)), net), h = a.sym && DETC[a.sym]; return { a, p, tot: U.sum(arr, net), d12, dy: p.value ? d12 / p.value : 0, yoc: p.cost ? d12 / p.cost : 0, n: arr.length, last: U.sortBy(arr, t => t.date).pop(), g: h ? divGrowth(h) : null }; }).sort((x, y) => y.d12 - x.d12);
  const det = detected(), proj = projection(), cal = agenda(), recent = U.sortBy(D, t => t.date, -1).slice(0, 8);
  return `<div class="kpis">${UI.kpi('Recebido no total', M(tot), 'líquido de impostos')}${UI.kpi('Últimos 12 meses', M(y12), S.val ? 'dividend yield ' + U.pct(y12 / S.val, 2) : '')}${UI.kpi('Média por mês', M(avg), 'renda passiva atual')}${UI.kpi('Projeção 12 meses', M(proj.total), 'com a carteira de hoje')}${UI.kpi('Imposto retido (12m)', M(tax12), 'na fonte (JCP, EUA, PT…)')}${UI.kpi('Meta de renda passiva', meta ? U.pct(avg / meta) : '—', meta ? M(avg, { dec: 0 }) + ' de ' + M(meta, { dec: 0 }) + '/mês' : 'define abaixo')}</div>
  <div class="g g-main"><div class="pn"><div class="pn-h"><h3>Recebidos por mês</h3><span class="mut" style="font-size:12px">por tipo, líquido</span></div>${C.mount({ type: 'bar', stacked: true, labels: ms.map(U.fmtYM), series: TY.map(ty => ({ name: ty === 'Rendimento' ? 'Rendimentos (FII/REIT)' : ty === 'Juros' ? 'Juros e cupões' : ty === 'Aluguer' ? 'Aluguer de ações' : ty, data: ms.map(ym => U.sum(D.filter(t => t.type === ty && U.ym(t.date) === ym), net)), color: TC[ty] })).filter(se => se.data.some(Boolean)), fmt: MK, empty: 'Ainda sem proventos registados.' }, 230)}
      <div class="row gap8" style="margin-top:10px;align-items:center;flex-wrap:wrap"><label class="mut" for="invMeta">Meta de renda passiva por mês (€)</label><div class="inp-wrap" style="width:140px"><input id="invMeta" type="number" step="any" data-bind="invcfg.meta" data-fk="invMeta" value="${meta || ''}"><span>€</span></div>${meta && avg && S.val ? `<span class="mut">ao yield atual (${U.pct(y12 / S.val, 2)}) precisas de ~${M(meta * 12 / (y12 / S.val), { dec: 0 })} investidos</span>` : ''}</div></div>
    <div class="pn"><div class="pn-h"><h3>Próximos 12 meses (projeção)</h3><span class="mut" style="font-size:12px">pagamentos do último ano × as tuas quantidades</span></div>${C.mount({ type: 'bar', labels: proj.labels, series: [{ name: 'Projeção', data: proj.data, color: 'var(--pos)' }], fmt: MK, empty: IX.hasScript() ? 'A calcular com o histórico de dividendos…' : 'Liga o script em Cotações para projetar.' }, 230)}</div></div>
  <div class="pn"><div class="pn-h"><h3>${UI.ic('cal')}Agenda de dividendos</h3><span class="mut" style="font-size:12px">data-ex (tens de ter o ativo no dia anterior) e pagamento</span></div>${cal.length ? `<div class="tblw"><table class="tbl"><thead><tr><th>Ativo</th><th>Data-ex</th><th>Pagamento</th><th class="r">Por ano / unidade</th><th class="r">Estimativa para ti</th><th class="r">Yield</th></tr></thead><tbody>${cal.map(x => `<tr class="${x.ex >= U.today() ? '' : 'mut'}"><td><b>${esc(x.a.ticker || x.a.sym)}</b></td><td>${x.ex ? U.fmtD(x.ex) + (x.ex >= U.today() ? ` <span class="bdg acc">daqui a ${U.diff(x.ex, U.today())} d</span>` : '') : '—'}</td><td>${x.pay ? U.fmtD(x.pay) : '—'}</td><td class="r mono">${x.rate ? IX.Mc(x.rate, x.a.currency || 'EUR', 2) : '—'}</td><td class="r mono pos">${x.est ? M(x.est) : '—'}</td><td class="r mono">${x.dy ? U.pct(x.dy, 2) : '—'}</td></tr>`).join('')}</tbody></table></div>` : `<p class="mut">${IX.hasScript() ? 'A procurar as próximas datas…' : 'Liga o script em Cotações para veres a agenda.'}</p>`}</div>
  ${det.length ? `<div class="pn"><div class="pn-h"><h3>${UI.ic('info')}Eventos detetados que ainda não registaste</h3><button class="btn sm pri" data-act="invDivAll">Registar todos (${det.length})</button></div><div class="list">${det.slice(0, 12).map(d => `<div class="li"><div class="li-t"><b>${esc(d.a.ticker || d.a.sym)} · ${d.split ? (d.ratio >= 1 ? 'desdobramento 1→' + U.nf(d.ratio, 2) : 'grupamento ' + U.nf(1 / d.ratio, 2) + '→1') : 'dividendo'}</b><small>${U.fmtD(d.date)}${d.split ? '' : ' · ' + U.nf(d.qty, 4) + ' × ' + IX.Mc(d.per, d.a.currency || d.cur, 4)}</small></div>${d.split ? '' : `<span class="mono pos">${IX.Mc(d.amt, d.a.currency || d.cur)}</span>`}</div>`).join('')}</div><p class="mut" style="font-size:12px;margin:6px 0 0">Do histórico do Yahoo Finance × a quantidade que tinhas na data. Dividendos em valor bruto: acrescenta o imposto retido no extrato da corretora.</p></div>` : ''}
  ${recent.length ? `<div class="pn"><div class="pn-h"><h3>Últimos recebidos</h3><span class="mut" style="font-size:12px">reinvestir = comprar mais do mesmo ativo</span></div><div class="list">${recent.map(t => { const a = OS.get('assets', t.asset) || {}, q = IX.quoteFor(a), netv = n(t.amount) - n(t.tax) - n(t.fees); return `<div class="li"><span class="when">${U.fmtD(t.date)}</span><div class="li-t click" data-edit="invtx:${t.id}"><b>${esc(a.ticker || a.name || '—')} · ${esc(t.type)}</b><small>bruto ${IX.Mc(n(t.amount), a.currency || 'EUR')}${n(t.tax) ? ' · retido ' + IX.Mc(n(t.tax), a.currency || 'EUR') : ''}</small></div><span class="mono pos">${IX.Mc(netv, a.currency || 'EUR')}</span>${q && netv >= q.p ? `<button class="btn xs" data-act="invDrip" data-id="${t.id}">Reinvestir</button>` : ''}</div>`; }).join('')}</div></div>` : ''}
  <section><div class="sech"><h2>Por ativo</h2></div>${UI.table({ key: 'divs', rows: byA, empty: 'Regista proventos em Movimentos (Dividendo, JCP, Rendimento, Juros ou Aluguer).', cols: [
    { l: 'Ativo', v: x => `<b>${esc(x.a.ticker || x.a.name)}</b><div class="mut" style="font-size:12px">${esc(x.a.name)}</div>`, s: x => x.a.name }, { l: 'Recebido', cls: 'r', v: x => `<span class="mono">${M(x.tot)}</span>`, s: x => x.tot }, { l: '12 meses', cls: 'r', v: x => `<span class="mono">${M(x.d12)}</span>`, s: x => x.d12 },
    { l: 'Yield', cls: 'r', v: x => `<span class="mono">${U.pct(x.dy, 2)}</span>`, s: x => x.dy }, { l: 'Yield on cost', cls: 'r', v: x => `<span class="mono">${U.pct(x.yoc, 2)}</span>`, s: x => x.yoc }, { l: 'Cresc. dividendo/ano', cls: 'r', v: x => x.g == null ? '—' : `<span class="mono ${tone(x.g)}">${pctS(x.g, 1)}</span>`, s: x => x.g || 0 }, { l: 'Último', v: x => x.last ? U.fmtD(x.last.date) : '' },
    { l: 'Número mágico', cls: 'r', v: x => { const per = x.d12 && x.p.qty ? x.d12 / 12 / x.p.qty : 0, price = x.p.qty ? x.p.value / x.p.qty : 0; return per ? `<span class="mono" title="quantidade para os proventos de um mês comprarem mais uma unidade">${U.nf(Math.ceil(price / per))}</span>` : '—'; } }] })}</section>`; };
A.invDrip = b => { const t = OS.get('invtx', b.dataset.id); if (!t) return; const a = OS.get('assets', t.asset), q = IX.quoteFor(a); if (!q) return; const netv = n(t.amount) - n(t.tax) - n(t.fees), qty = Math.floor(netv / q.p * 1e4) / 1e4;
  UI.openForm('invtx', null, { asset: a.id, type: 'Compra', date: U.today(), qty: IX.isCrypto(a.sym) ? qty : Math.floor(netv / q.p), price: U.r2(q.p), note: 'Reinvestimento de ' + t.type.toLowerCase() }, { title: 'Reinvestir em ' + (a.ticker || a.sym) }); };
/* histórico do Yahoo (5 anos) para dividendos, desdobramentos, crescimento e projeção */
const DETC = {};
const histOf = a => { const h = DETC[a.sym]; if (h) return h; if (!DETC['_' + a.sym] && (IX.hasScript() || IX.isCrypto(a.sym))) { DETC['_' + a.sym] = 1; IX.hist(a.sym, '5y', '1d').then(x => { DETC[a.sym] = x || { div: [], spl: [] }; OS.request(); }).catch(() => { }); } return null; };
const isoTs = ts => U.iso(new Date(ts * 1000));
/* fator para converter dividendos ajustados em valor por ação na época */
const splitF = (h, date) => (h.spl || []).filter(z => isoTs(z[0]) > date).reduce((g, z) => g * (z[1] || 1), 1);
const qtyAt = (a, date) => { const st = IX.st0(); U.sortBy(OS.all('invtx').filter(t => t.asset === a.id && t.date < date), t => t.date).forEach(t => IX.step(st, t, IX.mult(a))); return st.qty; };
const detected = () => { const out = []; OS.all('assets').filter(a => a.sym && !IX.isRF(a) && !IX.isCrypto(a.sym)).forEach(a => { const h = histOf(a); if (!h) return;
  const T2 = OS.all('invtx').filter(t => t.asset === a.id), first = (U.sortBy(T2.filter(t => L.QTX.includes(t.type)), t => t.date)[0] || {}).date; if (!first) return; const gc = h.cur === 'GBp' ? .01 : 1;
  (h.spl || []).forEach(([ts, r]) => { const date = isoTs(ts); if (date <= first || date > U.today() || !r || r === 1) return; if (T2.some(t => t.type === 'Desdobramento/Grupamento' && Math.abs(U.diff(t.date, date)) <= 10)) return; out.push({ a, date, split: true, ratio: r }); });
  (h.div || []).forEach(([ts, per]) => { const date = isoTs(ts); if (date > U.today() || date <= first) return; const qty = qtyAt(a, date); if (qty <= 0) return; if (T2.some(t => IX.INC.has(t.type) && Math.abs(U.diff(t.date, date)) <= 45)) return; const p2 = per * gc * splitF(h, date); out.push({ a, date, qty, per: p2, amt: qty * p2, cur: h.cur === 'GBp' ? 'GBP' : h.cur }); }); });
  return [...U.sortBy(out.filter(x => x.split), x => x.date, -1), ...U.sortBy(out.filter(x => !x.split), x => x.date, -1)]; };
A.invDivAll = () => { const det = detected(); det.forEach(d => OS.add('invtx', d.split ? { asset: d.a.id, type: 'Desdobramento/Grupamento', date: d.date, ratio: d.ratio, note: 'Detetado automaticamente' } : { asset: d.a.id, type: d.a.cls === 'FII' || d.a.cls === 'REIT' ? 'Rendimento' : 'Dividendo', date: d.date, amount: U.r2(d.amt), note: 'Detetado automaticamente (bruto)' }, { silent: true })); OS.request(); UI.toast(det.length + ' evento(s) registado(s)', 'pos'); };
IX.detected = detected;
const divGrowth = h => { const by = {}; (h.div || []).forEach(([ts, per]) => { const y = isoTs(ts).slice(0, 4); by[y] = (by[y] || 0) + per; }); const ys = Object.keys(by).sort().filter(y => y < U.today().slice(0, 4)).slice(1); if (ys.length < 3) return null; const a0 = by[ys[0]], a1 = by[ys[ys.length - 1]]; return a0 > 0 ? Math.pow(a1 / a0, 1 / (ys.length - 1)) - 1 : null; };
const projection = () => { const months = Array.from({ length: 12 }, (_, i) => U.addMonths(U.ym(U.today()), i + 1)), data = months.map(() => 0);
  IX.positions().filter(p => p.qty > 0 && p.a.sym && !IX.isCrypto(p.a.sym)).forEach(p => { const h = histOf(p.a); if (!h) return; const gc = h.cur === 'GBp' ? .01 : 1, fx = Inv.fx(p.a.currency);
    (h.div || []).filter(([ts]) => ts * 1000 > Date.now() - 365 * 864e5).forEach(([ts, per]) => { const ym = U.addMonths(isoTs(ts).slice(0, 7), 12), i = months.indexOf(ym); if (i >= 0) data[i] += per * gc * p.qty * fx * (p.a.currency === 'BRL' && /JCP/i.test(p.a.notes || '') ? .85 : 1); }); });
  OS.all('assets').filter(a => IX.isRF(a) && a.idx && a.venc).forEach(() => { });
  return { labels: months.map(U.fmtYM), data, total: U.sum(data) }; };
let AG = null, AGat = 0;
const agenda = () => { const held = IX.positions().filter(p => p.qty > 0 && p.a.sym && !IX.isCrypto(p.a.sym) && !/^\^|=X$|=F$/.test(p.a.sym));
  if (!AG && IX.hasScript() && held.length && Date.now() - AGat > 6e4) { AGat = Date.now(); IX.agenda(held.map(p => p.a.sym)).then(c => { AG = c || {}; OS.request(); }).catch(() => { AG = {}; }); }
  if (!AG) return []; return U.sortBy(held.map(p => { const c = AG[p.a.sym] || {}; if (!c.ex && !c.pay) return null; const freq = (() => { const h = DETC[p.a.sym]; const k = h ? (h.div || []).filter(([ts]) => ts * 1000 > Date.now() - 365 * 864e5).length : 0; return k || 4; })();
    return { a: p.a, ex: c.ex ? isoTs(c.ex) : null, pay: c.pay ? isoTs(c.pay) : null, rate: c.rate, dy: c.dy, est: c.rate ? c.rate / freq * p.qty * Inv.fx(p.a.currency) : null }; }).filter(Boolean), x => x.ex || '0', -1); };

/* ================= ALOCAÇÃO ================= */
const KEYS = [['grp', 'Tipo'], ['cls', 'Classe'], ['sector', 'Setor'], ['country', 'País'], ['currency', 'Moeda'], ['broker', 'Corretora']];
T.alocacao = () => { const S = IX.summary(); if (!S.P.length) return onboarding(); const val = S.val || 1, tg = cfg().tgt || {}, H = IX.health(S);
  const by = k => { const o = {}; S.P.forEach(p => { const key = k === 'grp' ? GROUP(p.a.cls) : (p.a[k] || 'Sem dados'); o[key] = (o[key] || 0) + p.value; }); return Object.entries(o).map(([l, v]) => ({ l, v, c: k === 'grp' ? GC[l] : undefined })).sort((a, b) => b.v - a.v); };
  const grp = by('grp'), allG = [...new Set([...grp.map(g => g.l), ...Object.keys(tg).filter(k => n(tg[k]))])];
  const ap = n(OS.ui.invAporte), plan = ap > 0 ? rebalance(S, ap) : null, tgSum = U.sum(Object.values(tg), n);
  return `<div class="kpis">${UI.kpi('Diversificação efetiva', U.nf(H.eff, 1) + ' ativos', 'quantos ativos "iguais" equivalem à tua carteira')}${UI.kpi('Maior posição', U.pct(H.top, 1))}${UI.kpi('Top 5', U.pct(U.sum(U.sortBy(S.P, p => p.value, -1).slice(0, 5), p => p.value) / val, 1), 'peso dos 5 maiores')}${UI.kpi('Moeda de casa', U.pct(H.homeW, 0), cc() === 'BR' ? 'em BRL' : 'em EUR')}</div>
  <div class="g g2">${KEYS.map(([k, l]) => `<div class="pn"><div class="pn-h"><h3>Por ${l.toLowerCase()}</h3></div>${C.mount({ type: 'donut', data: by(k), label: 'Por ' + l, fmt: MK, max: 6 }, 200)}</div>`).join('')}</div>
  <div class="g g-main"><div class="pn"><div class="pn-h"><h3>Alocação alvo por tipo</h3><span class="mut" style="font-size:12px">${tgSum ? 'total ' + U.nf(tgSum) + '%' + (Math.abs(tgSum - 100) > .5 ? ' <span class="warn">(deve somar 100%)</span>' : '') : 'define as tuas metas'}</span></div>
    ${allG.map(g => { const cur = (grp.find(x => x.l === g) || { v: 0 }).v / val, t = n(tg[g]) / 100; return `<div class="bar-row inv-tg" style="grid-template-columns:160px 1fr 70px 90px"><span class="l"><span class="dot" style="background:${GC[g] || 'var(--mut)'}"></span>${esc(g)}</span>${UI.bar(cur, t && cur > t + .05 ? 'warn' : '', t || null)}<span class="v mono">${U.pct(cur, 1)}</span><div class="inp-wrap"><input type="number" step="1" min="0" max="100" data-bind="invcfg.tgt.${esc(g)}" data-fk="tg${esc(g)}" value="${tg[g] ?? ''}" aria-label="Alvo ${esc(g)}"><span>%</span></div></div>`; }).join('')}
    <div class="row gap6" style="margin-top:8px;flex-wrap:wrap"><span class="mut" style="font-size:12px">Modelos:</span>${Object.keys(MODELS).map(k => `<button class="chip" data-act="invModel" data-v="${k}">${k}</button>`).join('')}</div></div>
  <div class="pn"><div class="pn-h"><h3>${UI.ic('calc')}Onde aportar</h3></div><p class="mut" style="margin:0 0 8px;font-size:13px">Diz quanto vais investir: o Oceanum divide pelo que está mais abaixo da meta, sem vender nada.</p>
    <div class="inp-wrap" style="max-width:220px"><span>€</span><input type="number" step="any" data-uiv="invAporte" data-fk="invAp" value="${ap || ''}" placeholder="ex.: 500" aria-label="Valor a aportar"></div>
    ${plan ? `<div class="list" style="margin-top:10px">${plan.map(x => `<div class="li"><div class="li-t"><b>${esc(x.g)}</b><small>${U.pct(x.from, 1)} → ${U.pct(x.to, 1)} (alvo ${U.pct(x.t, 0)})${x.assets.length ? ' · ' + x.assets.map(esc).join(', ') : ''}</small></div><span class="mono pos">${M(x.v, { dec: 0 })}</span></div>`).join('')}</div>` : tgSum ? '' : '<p class="mut" style="font-size:12px">Define primeiro a alocação alvo (ou escolhe um modelo).</p>'}</div></div>`; };
const MODELS = { Conservador: { 'Renda fixa': 70, ETFs: 20, 'Ações': 5, 'Ouro e commodities': 5 }, Moderado: { 'Renda fixa': 40, ETFs: 40, 'Ações': 10, 'Fundos imobiliários': 5, Cripto: 5 }, Arrojado: { 'Renda fixa': 15, ETFs: 55, 'Ações': 20, 'Fundos imobiliários': 5, Cripto: 5 }, 'Só ETF global': { ETFs: 90, 'Renda fixa': 10 } };
A.invModel = b => { cfg().tgt = Object.assign({}, MODELS[b.dataset.v]); OS.touch('invcfg'); UI.toast('Modelo ' + b.dataset.v + ' aplicado. Ajusta à vontade.', 'pos'); };
const rebalance = (S, ap) => { const tg = cfg().tgt || {}, keys = Object.keys(tg).filter(k => n(tg[k]) > 0); if (!keys.length) return null; const tot = U.sum(keys, k => n(tg[k])), val = S.val, after = val + ap;
  const cur = {}; S.P.forEach(p => { const g = GROUP(p.a.cls); cur[g] = (cur[g] || 0) + p.value; });
  let need = keys.map(g => ({ g, t: n(tg[g]) / tot, have: cur[g] || 0 })).map(x => Object.assign(x, { gap: Math.max(0, x.t * after - x.have) })); const gapSum = U.sum(need, x => x.gap);
  need.forEach(x => x.v = gapSum ? ap * x.gap / gapSum : ap * x.t);
  return need.filter(x => x.v >= 1).map(x => ({ g: x.g, v: x.v, t: x.t, from: x.have / (val || 1), to: (x.have + x.v) / after, assets: U.sortBy(S.P.filter(p => GROUP(p.a.cls) === x.g), p => n(p.a.target) ? p.value / S.val - n(p.a.target) / 100 : 0).slice(0, 3).map(p => p.a.ticker || p.a.name) })).sort((a, b) => b.v - a.v); };

/* ================= MERCADO ================= */
let SR = { q: '', busy: false, res: null, err: '' };
T.mercado = () => { const ind = IX.INDICES(cc()); ind.forEach(([s]) => IX.extra.add(s)); const W = cfg().watch || []; W.forEach(s => IX.extra.add(s));
  const card = (s, l) => { const q = IX.q(s); return `<div class="mk-c click" data-act="invOpen" data-s="${esc(s)}"><div class="mk-h"><b>${esc(l || (q && q.nm) || s)}</b><small class="mut">${esc(s)}</small></div>${q ? `<div class="mk-p">${pxCell(s, q.p, q.p < 10 ? 4 : 2)} <small class="mut">${esc(q.cur || '')}</small></div>${q.pc ? chCell(s, q.p / q.pc - 1) : ''}${UI.spark(q.d || [], q.pc && q.p >= q.pc ? 'var(--pos)' : 'var(--neg)', 120, 30)}` : '<div class="mut" style="font-size:12px">sem cotação</div>'}</div>`; };
  return `<div class="pn"><div class="pn-h"><h3>${UI.ic('search')}Pesquisar ativos</h3><span class="mut" style="font-size:12px">ações, ETFs, FII, fundos, índices, cripto, câmbio de todas as bolsas</span></div>
    <form class="row gap8" data-form="invSearch"><input class="field grow" name="q" id="invQ" placeholder="ex.: VWCE, Apple, PETR4, EDP, Bitcoin, IWDA" value="${esc(SR.q)}" autocomplete="off" aria-label="Pesquisar"><button class="btn pri">${SR.busy ? 'A procurar…' : 'Procurar'}</button></form>
    ${SR.err ? `<p class="neg">${esc(SR.err)}</p>` : ''}${SR.res ? (SR.res.length ? `<div class="list" style="margin-top:8px">${SR.res.map(r => `<div class="li"><div class="li-t click" data-act="invOpen" data-s="${esc(r.s)}"><b>${esc(r.s)}</b><small>${esc(r.n)} · ${esc(r.ty || r.t || '')}${r.ex ? ' · ' + esc(r.ex) : ''}</small></div><button class="btn xs ghost" data-act="invWatch" data-s="${esc(r.s)}">${W.includes(r.s) ? '★ A acompanhar' : '☆ Acompanhar'}</button><button class="btn xs" data-act="invAddAsset" data-s="${esc(r.s)}" data-n="${esc(r.n)}" data-t="${esc(r.t || '')}" data-ex="${esc(r.ex || '')}">+ Carteira</button></div>`).join('')}</div>` : '<p class="mut">Nada encontrado.</p>') : ''}</div>
  ${IX.alertsPanel ? IX.alertsPanel() : ''}
  <div class="pn"><div class="pn-h"><h3>Índices, câmbio e ouro</h3>${liveBadge()}</div><div class="mk-g">${ind.map(([s, l]) => card(s, l)).join('')}</div></div>
  <div class="pn"><div class="pn-h"><h3>★ A acompanhar</h3><span class="mut" style="font-size:12px">${W.length} ativo(s)</span></div>${W.length ? `<div class="mk-g">${W.map(s => card(s)).join('')}</div>` : UI.empty('Pesquisa e toca em ☆ Acompanhar para seguires ativos sem os comprar.')}</div>
  <div class="pn"><div class="pn-h"><h3>Cripto · top 10</h3><span class="mut" style="font-size:12px">CoinGecko</span></div>${cryptoTop()}</div>`; };
OS.forms = OS.forms || {};
OS.forms.invSearch = async (f, v) => { const q = String(v('q') || '').trim(); if (!q) return; SR = { q, busy: true, res: null, err: '' }; OS.request();
  try { if (IX.hasScript()) { const j = await IX.search(q); SR.res = j.q || []; }
    else { const j = await (await fetch('https://api.coingecko.com/api/v3/search?query=' + encodeURIComponent(q))).json(); SR.res = (j.coins || []).slice(0, 8).map(c => ({ s: c.symbol.toUpperCase() + '-EUR', n: c.name, t: 'CRYPTOCURRENCY', ty: 'Cripto', ex: 'CoinGecko', cg: c.id })); if (!SR.res.length) SR.err = 'Sem o script ligado só consigo pesquisar cripto. Liga-o em Cotações para pesquisar ações, ETFs e fundos.'; }
  } catch (e) { SR.err = IX.st.script === 'old' ? 'O teu script é da versão antiga: atualiza-o em Cotações.' : 'A pesquisa falhou: ' + e.message; }
  SR.busy = false; OS.request(); };
let CT = null, CTat = 0;
const cryptoTop = () => { if (!CT && Date.now() - CTat > 6e4) { CTat = Date.now(); fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=' + (IX.view() === 'BRL' ? 'brl' : IX.view() === 'USD' ? 'usd' : 'eur') + '&order=market_cap_desc&per_page=10&sparkline=true&price_change_percentage=24h').then(r => r.json()).then(j => { if (Array.isArray(j)) { CT = j; setTimeout(() => CT = null, 120000); OS.request(); } }).catch(() => { }); }
  if (!CT) return '<p class="mut">A carregar…</p>'; const cur = IX.view();
  return `<div class="tblw"><table class="tbl"><thead><tr><th>#</th><th>Moeda</th><th class="r">Preço</th><th class="r">24h</th><th>7 dias</th><th class="r">Capitalização</th><th></th></tr></thead><tbody>${CT.map((c, i) => `<tr><td class="mut">${i + 1}</td><td><b>${esc(c.symbol.toUpperCase())}</b> <span class="mut">${esc(c.name)}</span></td><td class="r mono">${IX.Mc(c.current_price, cur, c.current_price < 10 ? 4 : 2)}</td><td class="r">${chCell('', (c.price_change_percentage_24h || 0) / 100)}</td><td>${UI.spark(((c.sparkline_in_7d || {}).price || []).filter((_, k) => k % 4 === 0), (c.price_change_percentage_24h || 0) >= 0 ? 'var(--pos)' : 'var(--neg)', 100, 26)}</td><td class="r mono">${IX.Mc(c.market_cap / 1e9, cur, 0)} mM</td><td><button class="btn xs ghost" data-act="invWatch" data-s="${esc(c.symbol.toUpperCase() + '-' + (cur === 'USD' ? 'USD' : cur))}">☆</button></td></tr>`).join('')}</tbody></table></div>`; };
A.invWatch = b => { const s = b.dataset.s, c = cfg(); c.watch = c.watch || []; c.watch = c.watch.includes(s) ? c.watch.filter(x => x !== s) : [...c.watch, s]; OS.touch('invcfg'); UI.toast(c.watch.includes(s) ? s + ' a acompanhar' : s + ' removido', 'pos'); IX.tick(true); };
const guessCls = (t, s, nm) => /CRYPTO/i.test(t) || IX.isCrypto(s) ? 'Cripto' : /ETF/i.test(t) ? 'ETF' : /MUTUALFUND/i.test(t) ? 'Fundo' : /FUTURE/i.test(t) && /GC=|SI=/.test(s) ? 'Ouro' : /11\.SA$/.test(s) && /FII|IMOB|REAL ESTATE|FUNDO/i.test(nm) ? 'FII' : /34\.SA$|35\.SA$/.test(s) ? 'BDR' : /INDEX/i.test(t) ? 'Outro' : 'Ação';
const SUF = { '.SA': ['BRL', 'Brasil'], '.LS': ['EUR', 'Portugal'], '.DE': ['EUR', 'Alemanha'], '.F': ['EUR', 'Alemanha'], '.AS': ['EUR', 'Países Baixos'], '.PA': ['EUR', 'França'], '.MC': ['EUR', 'Espanha'], '.MI': ['EUR', 'Itália'], '.L': ['GBP', 'Reino Unido'], '.SW': ['CHF', 'Suíça'], '.TO': ['CAD', 'Canadá'], '.IR': ['EUR', 'Irlanda'], '.BR': ['EUR', 'Bélgica'] };
const metaOf = s => { const k = Object.keys(SUF).find(x => s.endsWith(x)); if (k) return SUF[k]; if (IX.isCrypto(s)) return [s.split('-')[1].replace('USDT', 'USD'), '']; return ['USD', 'EUA']; };
A.invAddAsset = b => { const s = b.dataset.s, nm = b.dataset.n || s, t = b.dataset.t || '', q = IX.q(s), [cur, ctry] = metaOf(s), ex = OS.all('assets').find(a => a.sym === s);
  if (ex) { UI.openForm('invtx', null, { asset: ex.id, type: 'Compra', date: U.today(), price: q ? U.r2(q.p) : '' }, { title: 'Comprar ' + (ex.ticker || s) }); return; }
  UI.openForm('assets', null, { name: nm, ticker: s.replace(/\.[A-Z]{1,2}$/, '').replace(/-(EUR|USD|BRL)$/, ''), sym: s, cls: guessCls(t, s, nm), currency: q && q.cur ? (q.cur === 'GBp' ? 'GBP' : q.cur) : cur, country: ctry, price: q ? U.r2(q.p) : '', priceDate: U.today() },
    { title: 'Adicionar ' + s + ' à carteira', onSave: r => setTimeout(() => UI.openForm('invtx', null, { asset: r.id, type: 'Compra', date: U.today(), price: q ? U.r2(q.p) : '' }, { title: 'Registar a compra de ' + (r.ticker || s) }), 300) }); };

/* ================= PÁGINA DO ATIVO ================= */
const RNG = [['1d', '1D', '1d', '5m'], ['5d', '5D', '5d', '30m'], ['1mo', '1M', '1mo', '1d'], ['6mo', '6M', '6mo', '1d'], ['1y', '1A', '1y', '1d'], ['5y', '5A', '5y', '1wk'], ['max', 'Máx.', 'max', '1mo']];
const HC = {}; let NEWS = {};
A.invOpen = b => { const s = b.dataset.s; if (!s) return; OS.setUI('invSym', s); location.hash = 'investimentos.ativo'; };
T.ativo = () => { const s = OS.ui.invSym; if (!s) return T.mercado(); IX.extra.add(s); const q = IX.q(s), a = OS.all('assets').find(x => x.sym === s), p = a ? Inv.pos(a) : null, rg = OS.ui.invRg || '1y', R = RNG.find(r => r[0] === rg) || RNG[4];
  const hk = s + '|' + rg; if (rg !== '1d' && !HC[hk]) { HC[hk] = 'busy'; IX.hist(s, R[2], R[3]).then(h => { HC[hk] = h || 'none'; OS.request(); }).catch(() => { HC[hk] = 'none'; OS.request(); }); }
  const h = HC[hk]; let lab = [], dat = [];
  if (rg === '1d') { dat = q && q.d ? q.d : []; lab = dat.map((_, i) => ''); } else if (h && h !== 'busy' && h !== 'none') { const k = Math.max(1, Math.ceil(h.t.length / 220)); h.t.forEach((t, i) => { if (i % k === 0 || i === h.t.length - 1) { lab.push(U.fmtDS ? U.fmtDS(U.iso(new Date(t * 1000))) : ''); dat.push(h.c[i]); } }); }
  const ch = dat.length > 1 ? dat[dat.length - 1] / dat[0] - 1 : 0;
  const hy = HC[s + '|1y'] && typeof HC[s + '|1y'] === 'object' ? HC[s + '|1y'] : null, div12 = hy ? U.sum((hy.div || []).filter(d => d[0] * 1000 > Date.now() - 365 * 864e5), d => d[1]) : 0;
  if (!HC[s + '|1y']) { HC[s + '|1y'] = 'busy'; IX.hist(s, '1y', '1d').then(x => { HC[s + '|1y'] = x || 'none'; OS.request(); }).catch(() => { HC[s + '|1y'] = 'none'; }); }
  if (IX.hasScript() && !NEWS[s]) { NEWS[s] = 'busy'; IX.search((a && a.name) || (q && q.nm) || s.replace(/\..*$/, ''), 6).then(j => { NEWS[s] = j.news || []; OS.request(); }).catch(() => { NEWS[s] = []; }); }
  const news = Array.isArray(NEWS[s]) ? NEWS[s] : [], W = cfg().watch || [];
  return `<div class="row between gap12 inv-ah"><div><a class="acc" href="#investimentos.mercado" style="font-size:12px">← Mercado</a><h2 style="margin:4px 0 0">${esc((q && q.nm) || (a && a.name) || s)}</h2><span class="mut">${esc(s)}${q && q.ex ? ' · ' + esc(q.ex) : ''}${q && q.cur ? ' · ' + esc(q.cur) : ''}${q ? ' · ' + (q.open ? '<span class="pos">mercado aberto</span>' : 'mercado fechado') : ''}${q && q.src ? ' · ' + esc(q.src) : ''}</span></div>
    <div class="inv-ap"><div class="big-num">${q ? pxCell(s, q.p, q.p < 10 ? 4 : 2) : '—'}</div>${q && q.pc ? chCell(s, q.p / q.pc - 1) + ` <span class="mut" style="font-size:12px">hoje</span>` : ''}</div></div>
  <div class="row gap8" style="flex-wrap:wrap;margin:8px 0">${a ? `<button class="btn sm pri" data-act="invAddAsset" data-s="${esc(s)}">Registar compra</button><button class="btn sm" data-new="invtx" data-defs='${esc(JSON.stringify({ asset: a.id, type: 'Venda', date: U.today(), price: q ? U.r2(q.p) : '' }))}'>Registar venda</button><button class="btn sm ghost" data-edit="assets:${a.id}">Editar ativo</button>` : `<button class="btn sm pri" data-act="invAddAsset" data-s="${esc(s)}" data-n="${esc((q && q.nm) || s)}" data-t="${esc((q && q.ty) || '')}">+ Adicionar à carteira</button>`}<button class="btn sm ghost" data-act="invWatch" data-s="${esc(s)}">${W.includes(s) ? '★ A acompanhar' : '☆ Acompanhar'}</button><button class="btn sm ghost" data-act="invAlert" data-s="${esc(s)}" data-v="${q ? q.p : ''}">Alerta</button><button class="btn sm ghost" data-act="invCo" data-s="${esc(s)}">${UI.ic('building')}Análise da empresa</button><button class="btn sm ghost" data-act="invAskAsset" data-s="${esc(s)}">${UI.ic('zap')}Analisar com IA</button></div>
  <div class="pn"><div class="pn-h"><div class="row gap6">${RNG.map(r => `<button class="chip ${rg === r[0] ? 'on' : ''}" data-ui="invRg" data-v="${r[0]}">${r[1]}</button>`).join('')}</div>${dat.length > 1 ? `<span class="mono ${tone(ch)}">${pctS(ch)} no período</span>` : ''}</div>
    ${dat.length > 1 ? C.mount({ type: 'line', labels: lab, series: [{ name: s, data: dat, color: ch >= 0 ? 'var(--pos)' : 'var(--neg)' }], fmt: v => U.nf(v, v < 10 ? 2 : 0), min0: false }, 280) : `<div class="chart-empty" style="height:280px">${h === 'busy' ? 'A carregar…' : IX.hasScript() || IX.isCrypto(s) ? 'Sem dados para este período.' : 'Liga o script em Cotações para veres gráficos.'}</div>`}</div>
  <div class="g g-main"><div class="pn"><div class="pn-h"><h3>Estatísticas</h3></div><dl class="kv">${q ? `<dt>Mínimo / máximo do dia</dt><dd class="mono">${q.lo != null ? U.nf(q.lo, 2) + ' – ' + U.nf(q.hi, 2) : '—'}</dd><dt>Mínimo / máximo 52 semanas</dt><dd class="mono">${q.l52 != null ? U.nf(q.l52, 2) + ' – ' + U.nf(q.h52, 2) : '—'}</dd>${q.l52 != null && q.h52 ? `<dt>Posição no intervalo de 52 sem.</dt><dd>${UI.bar((q.p - q.l52) / ((q.h52 - q.l52) || 1), '')}</dd>` : ''}<dt>Fecho anterior</dt><dd class="mono">${q.pc != null ? U.nf(q.pc, 2) : '—'}</dd><dt>Volume</dt><dd class="mono">${q.v ? U.nf(q.v) : '—'}</dd>` : '<dt>Cotação</dt><dd>sem dados</dd>'}${div12 ? `<dt>Proventos 12 meses (por unidade)</dt><dd class="mono">${U.nf(div12, 4)}</dd><dt>Dividend yield</dt><dd class="mono">${q ? U.pct(div12 / q.p, 2) : '—'}</dd>` : ''}${hy && hy.c && hy.c.length > 20 ? `<dt>Volatilidade 1 ano</dt><dd class="mono">${U.pct(volOf(hy.c), 1)}</dd><dt>Variação 1 ano</dt><dd class="mono ${tone(hy.c[hy.c.length - 1] / hy.c[0] - 1)}">${pctS(hy.c[hy.c.length - 1] / hy.c[0] - 1, 1)}</dd>` : ''}</dl></div>
    <div class="pn"><div class="pn-h"><h3>A tua posição</h3></div>${p && p.qty ? `<dl class="kv"><dt>Quantidade</dt><dd class="mono">${U.nf(p.qty, p.qty % 1 ? 4 : 0)}</dd><dt>Preço médio</dt><dd class="mono">${IX.Mc(p.avg, a.currency || 'EUR')}</dd><dt>Valor</dt><dd class="mono">${M(p.value)}</dd><dt>Lucro / prejuízo</dt><dd class="mono ${tone(p.pl)}">${M(p.pl, { sign: 1 })} (${pctS(p.ret, 1)})</dd><dt>Proventos recebidos</dt><dd class="mono">${M(p.divs)}</dd><dt>Peso na carteira</dt><dd class="mono">${U.pct(p.value / (IX.summary().val || 1), 1)}</dd></dl>
      <div class="list" style="margin-top:8px">${U.sortBy(OS.all('invtx').filter(t => t.asset === a.id), t => t.date, -1).slice(0, 6).map(t => `<div class="li" data-edit="invtx:${t.id}" style="cursor:pointer"><span class="when">${U.fmtD(t.date)}</span><div class="li-t"><b>${t.type}</b><small>${['Compra', 'Venda'].includes(t.type) ? U.nf(n(t.qty), 4) + ' × ' + U.nf(n(t.price), 2) : U.nf(n(t.amount), 2)}</small></div></div>`).join('')}</div>` : UI.empty('Não tens este ativo.')}</div></div>
  <div class="pn"><div class="pn-h"><h3>Notícias</h3><span class="mut" style="font-size:12px">Yahoo Finance</span></div>${news.length ? `<div class="list">${news.map(x => `<a class="li" href="${esc(x.l)}" target="_blank" rel="noopener"><div class="li-t"><b>${esc(x.ti)}</b><small>${esc(x.pub || '')}${x.t ? ' · ' + new Date(x.t * 1000).toLocaleDateString('pt-PT') : ''}</small></div></a>`).join('')}</div>` : `<p class="mut">${NEWS[s] === 'busy' ? 'A carregar…' : IX.hasScript() ? 'Sem notícias recentes.' : 'Liga o script em Cotações para veres notícias.'}</p>`}</div>`; };
const volOf = c => { const r = []; for (let i = 1; i < c.length; i++) if (c[i - 1]) r.push(Math.log(c[i] / c[i - 1])); const m = U.avg(r); return Math.sqrt(U.avg(r, x => (x - m) * (x - m))) * Math.sqrt(252); };
A.invAskAsset = b => { OS.setUI('invAIq', 'Analisa o ativo ' + b.dataset.s + ' para mim: vale a pena ter na minha carteira, com que peso, e quais os riscos?'); location.hash = 'investimentos.ia'; };

/* ================= MOVIMENTOS + importação CSV ================= */
let IMP = null;
T.movimentos = () => `<div class="row gap8" style="flex-wrap:wrap;margin-bottom:10px">${UI.addBtn('invtx', 'Registar movimento', null, 'pri')}<button class="btn" data-act="invImp">${UI.ic('arrowUp')}Importar CSV / extrato</button><button class="btn ghost" data-act="invExp">Exportar CSV</button></div>
  ${IMP ? impPanel() : ''}
  ${UI.table({ key: 'invtx', coll: 'invtx', rows: U.sortBy(OS.all('invtx'), t => t.date, -1), limit: 100, empty: 'Sem movimentos.', emptyAct: UI.addBtn('invtx', 'Registar compra', null, ''), cols: [
  { l: 'Data', v: t => `<span class="mono">${U.fmtD(t.date)}</span>`, s: t => t.date }, { l: 'Ativo', v: t => { const a = OS.get('assets', t.asset) || {}; return esc(a.ticker || a.name || '—'); } },
  { l: 'Tipo', v: t => UI.badge(t.type, t.type === 'Compra' || t.type === 'Subscrição' ? 'acc' : t.type === 'Venda' ? 'vio' : t.type === 'Taxa' ? 'neg' : IX.INC.has(t.type) ? 'pos' : '') }, { l: 'Qtd.', cls: 'r', v: t => t.qty ? `<span class="mono">${U.nf(t.qty, 4)}</span>` : '' },
  { l: 'Preço', cls: 'r', v: t => t.price ? `<span class="mono">${U.nf(t.price, 2)}</span>` : t.ratio ? `<span class="mono">fator ${U.nf(t.ratio, 4)}</span>` : '' }, { l: 'Valor', cls: 'r', v: t => t.type === 'Desdobramento/Grupamento' ? '' : `<span class="mono">${U.nf(L.QTX.includes(t.type) ? n(t.qty) * n(t.price) * IX.mult(OS.get('assets', t.asset) || {}) : n(t.amount), 2)}</span>${n(t.tax) ? `<div class="mut" style="font-size:11px">retido ${U.nf(t.tax, 2)}</div>` : ''}` },
  { l: 'Comissões', cls: 'r', v: t => t.fees ? `<span class="mono">${U.nf(t.fees, 2)}</span>` : '' }, { l: 'Nota', v: t => esc(t.note || '') }] })}`;
A.invImp = () => { IMP = IMP ? null : { text: '', rows: null, err: '' }; OS.request(); };
const impPanel = () => `<div class="pn"><div class="pn-h"><h3>Importar movimentos</h3><button class="icon-btn" data-act="invImp" aria-label="Fechar">${UI.ic('x')}</button></div>
  <p class="mut" style="margin:0 0 8px;font-size:13px">Exporta o histórico da corretora (Degiro, Trading 212, XTB, Interactive Brokers, B3/CEI, Inter, XP, Rico, Clear…) em CSV e escolhe o ficheiro, ou cola o texto. Reconheço colunas como <i>data, ticker/ativo, tipo (compra/venda/dividendo), quantidade, preço, valor, taxas, moeda</i>.</p>
  <div class="row gap8" style="flex-wrap:wrap"><label class="btn sm" for="invFile">Escolher ficheiro</label><input id="invFile" type="file" accept=".csv,.txt,text/csv" hidden><button class="btn sm ghost" data-act="invImpParse">Ler texto colado</button></div>
  <textarea class="field" id="invImpTxt" rows="5" style="width:100%;margin-top:8px;font:12px var(--mono)" placeholder="data;ticker;tipo;quantidade;preço;taxas\n2025-03-10;VWCE.DE;compra;3;118,50;1">${esc(IMP.text)}</textarea>
  ${IMP.err ? `<p class="neg">${esc(IMP.err)}</p>` : ''}
  ${IMP.rows ? `<div class="note" style="margin-top:8px"><b>${IMP.rows.length}</b> movimento(s) reconhecido(s)${IMP.newA.length ? `, <b>${IMP.newA.length}</b> ativo(s) novo(s): ${IMP.newA.slice(0, 8).map(esc).join(', ')}` : ''}${IMP.dup ? ` · ${IMP.dup} já existiam (ignorados)` : ''}.</div>
    <div class="tblw" style="max-height:220px;overflow:auto"><table class="tbl"><thead><tr><th>Data</th><th>Ativo</th><th>Tipo</th><th class="r">Qtd.</th><th class="r">Preço</th><th class="r">Valor</th></tr></thead><tbody>${IMP.rows.slice(0, 50).map(r => `<tr><td>${U.fmtD(r.date)}</td><td>${esc(r.tk)}</td><td>${r.type}</td><td class="r mono">${r.qty ? U.nf(r.qty, 4) : ''}</td><td class="r mono">${r.price ? U.nf(r.price, 2) : ''}</td><td class="r mono">${r.amount ? U.nf(r.amount, 2) : ''}</td></tr>`).join('')}</tbody></table></div>
    <button class="btn pri" data-act="invImpGo" style="margin-top:8px">Importar ${IMP.rows.length} movimento(s)</button>` : ''}</div>`;
document.addEventListener('change', e => { if (e.target.id !== 'invFile') return; const f = e.target.files && e.target.files[0]; if (!f) return; const r = new FileReader(); r.onload = () => { IMP.text = String(r.result); impParse(); OS.request(); }; r.readAsText(f); });
document.addEventListener('input', e => { if (e.target.id === 'invImpTxt' && IMP) IMP.text = e.target.value; });
A.invImpParse = () => { impParse(); OS.request(); };
const numP = s => { s = String(s == null ? '' : s).replace(/[^\d,.\-]/g, ''); if (!s) return 0; if (s.includes(',') && s.includes('.')) s = s.lastIndexOf(',') > s.lastIndexOf('.') ? s.replace(/\./g, '').replace(',', '.') : s.replace(/,/g, ''); else if (s.includes(',')) s = s.replace(',', '.'); return Math.abs(+s) || 0; };
const dateP = s => { s = String(s || '').trim(); let m = s.match(/^(\d{4})-(\d{2})-(\d{2})/); if (m) return m[0]; m = s.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{2,4})/); if (m) { const y = m[3].length === 2 ? '20' + m[3] : m[3]; return `${y}-${U.pad(+m[2])}-${U.pad(+m[1])}`; } return ''; };
const typeP = s => { s = String(s || '').toLowerCase(); return /jcp|juros sobre/.test(s) ? 'JCP' : /rendiment/.test(s) ? 'Rendimento' : /bonifica|bonus/.test(s) ? 'Bonificação' : /amortiza/.test(s) ? 'Amortização' : /alugu|lending|empréstimo de/.test(s) ? 'Aluguer' : /subscri/.test(s) ? 'Subscrição' : /divid|provent|distrib/.test(s) ? 'Dividendo' : /juro|interest|cupão|cupom|coupon/.test(s) ? 'Juros' : /vend|sell|^v$|^s$|resgat/.test(s) ? 'Venda' : /taxa|fee|comiss|custódia/.test(s) ? 'Taxa' : /compr|buy|^c$|^b$|aplica|subscri/.test(s) ? 'Compra' : ''; };
const impParse = () => { IMP.err = ''; IMP.rows = null; const txt = (document.getElementById('invImpTxt') || {}).value || IMP.text; IMP.text = txt; const lines = txt.split(/\r?\n/).filter(l => l.trim()); if (lines.length < 2) { IMP.err = 'Preciso de uma linha de cabeçalho e pelo menos um movimento.'; return; }
  const sep = [';', '\t', ','].map(c => [c, lines[0].split(c).length]).sort((a, b) => b[1] - a[1])[0][0], split = l => { const out = []; let cur = '', q = false; for (const ch of l) { if (ch === '"') q = !q; else if (ch === sep && !q) { out.push(cur); cur = ''; } else cur += ch; } out.push(cur); return out.map(x => x.trim()); };
  const H = split(lines[0]).map(h => h.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '')), col = re => H.findIndex(h => re.test(h));
  const ci = { d: col(/^(data|date|dia)|data d|trade date|negocia/), tk: col(/ticker|simbolo|symbol|codigo|ativo|produto|instrument|isin|papel/), ty: col(/^tipo|type|operac|movimenta|side|c\/v|direction|acao$/), q: col(/quant|qty|shares|qtd|unidades|number/), p: col(/preco|price|cotacao|unit/), v: col(/valor|amount|total|montante|value|liquido/), f: col(/taxa|fee|comiss|custos|corretagem/), cur: col(/moeda|currency/) };
  if (ci.d < 0 || ci.tk < 0) { IMP.err = 'Não encontrei as colunas de data e de ativo/ticker no cabeçalho.'; return; }
  const rows = []; const ci2 = { tax: col(/imposto|withholding|retid|\btax\b/) }; lines.slice(1).forEach(l => { const c = split(l), date = dateP(c[ci.d]), tk = (c[ci.tk] || '').trim(); if (!date || !tk) return; let type = typeP(ci.ty >= 0 ? c[ci.ty] : ''); const qtyRaw = ci.q >= 0 ? String(c[ci.q]) : '', qty = numP(qtyRaw), price = ci.p >= 0 ? numP(c[ci.p]) : 0, amount = ci.v >= 0 ? numP(c[ci.v]) : 0;
    if (!type) type = /^-/.test(qtyRaw.trim()) ? 'Venda' : qty ? 'Compra' : amount ? 'Dividendo' : ''; if (!type) return;
    const amt0 = L.QTX.includes(type) ? qty : amount; if (!amt0) return;
    rows.push({ date, tk, type, qty, price: price || (qty && amount ? amount / qty : 0), amount: L.QTX.includes(type) ? qty * (price || (qty && amount ? amount / qty : 0)) : amount, fees: ci.f >= 0 ? numP(c[ci.f]) : 0, tax: ci2.tax >= 0 ? numP(c[ci2.tax]) : 0, cur: ci.cur >= 0 ? String(c[ci.cur] || '').toUpperCase().slice(0, 3) : '' }); });
  if (!rows.length) { IMP.err = 'Não reconheci nenhum movimento. Confirma que há colunas de data, ativo e tipo (ou quantidade).'; return; }
  const find = tk => OS.all('assets').find(a => [a.ticker, a.sym, a.name].some(x => x && x.toUpperCase() === tk.toUpperCase()));
  IMP.dup = 0; IMP.rows = rows.filter(r => { const a = find(r.tk); if (a && OS.all('invtx').some(t => t.asset === a.id && t.date === r.date && t.type === r.type && Math.abs(n(t.qty) - r.qty) < 1e-6 && Math.abs(n(t.price) - r.price) < .01)) { IMP.dup++; return false; } return true; });
  IMP.newA = [...new Set(IMP.rows.filter(r => !find(r.tk)).map(r => r.tk))]; };
A.invImpGo = () => { if (!IMP || !IMP.rows) return; const find = tk => OS.all('assets').find(a => [a.ticker, a.sym, a.name].some(x => x && x.toUpperCase() === tk.toUpperCase())); let nA = 0;
  IMP.rows.forEach(r => { let a = find(r.tk); if (!a) { const isS = /^[A-Z0-9.\-=^]{1,15}$/.test(r.tk) && !/^[A-Z]{2}[A-Z0-9]{9}\d$/.test(r.tk); a = OS.add('assets', { name: r.tk, ticker: r.tk.replace(/\.[A-Z]{1,2}$/, ''), sym: isS ? r.tk : '', cls: IX.isCrypto(r.tk) ? 'Cripto' : 'Ação', currency: r.cur && L.CUR.includes(r.cur) ? r.cur : metaOf(r.tk)[0] }, { silent: true }); nA++; }
    OS.add('invtx', Object.assign({ asset: a.id, type: r.type, date: r.date, fees: r.fees || '', note: 'Importado' }, L.QTX.includes(r.type) ? { qty: r.qty, price: U.r2(r.price * 1e4) / 1e4 } : { amount: U.r2(r.amount), tax: r.tax || '' }), { silent: true }); });
  UI.toast(`${IMP.rows.length} movimento(s) importado(s)${nA ? ', ' + nA + ' ativo(s) criado(s): confirma o símbolo de cotação de cada um' : ''}`, 'pos'); IMP = null; OS.request(); IX.tick(true); };
A.invExp = () => { const rows = [['data', 'ticker', 'simbolo', 'nome', 'classe', 'tipo', 'quantidade', 'preco', 'valor', 'taxas', 'moeda']].concat(U.sortBy(OS.all('invtx'), t => t.date).map(t => { const a = OS.get('assets', t.asset) || {}; return [t.date, a.ticker || '', a.sym || '', a.name || '', a.cls || '', t.type, t.qty || '', t.price || '', t.amount || '', t.fees || '', a.currency || 'EUR']; }));
  const blob = new Blob(['﻿' + rows.map(r => r.map(x => /[;"\n]/.test(String(x)) ? '"' + String(x).replace(/"/g, '""') + '"' : x).join(';')).join('\n')], { type: 'text/csv' }), u = URL.createObjectURL(blob), el = document.createElement('a'); el.href = u; el.download = 'oceanum-investimentos.csv'; el.click(); setTimeout(() => URL.revokeObjectURL(u), 2000); };

/* ================= IMPOSTOS ================= */
T.impostos = () => { const tx = U.sortBy(OS.all('invtx'), t => t.date), state = {}, sales = [];
  tx.forEach(t => { const a = OS.get('assets', t.asset); if (!a || IX.isRF(a)) return; const st = state[a.id] = state[a.id] || IX.st0(), fx = Inv.fx(a.currency), m = IX.mult(a), before = st.realized, wasShort = st.qty < 0, hadLong = st.qty > 0;
    IX.step(st, t, m); if ((t.type === 'Venda' && hadLong) || ((t.type === 'Compra' || t.type === 'Subscrição') && wasShort) || t.type === 'Amortização') { const gain = st.realized - before, gross = t.type === 'Amortização' ? n(t.amount) : n(t.qty) * n(t.price) * m; if (Math.abs(gain) > 1e-9 || t.type === 'Venda') sales.push({ dt: t.type === 'Venda' && tx.some(x => x.asset === a.id && x.date === t.date && x.type === 'Compra'), a, date: t.date, gross, gain, grossE: gross * fx, gainE: gain * fx, held: firstBuy(a, t.date), kind: t.type === 'Amortização' ? 'amortização' : wasShort ? 'fecho de venda a descoberto' : '' }); } });
  const yr = OS.ui.invTaxY || U.today().slice(0, 4), ys = [...new Set([U.today().slice(0, 4), ...sales.map(s => s.date.slice(0, 4))])].sort().reverse();
  const br = sales.filter(s => s.a.currency === 'BRL' && s.date.startsWith(yr)), pt = sales.filter(s => s.a.currency !== 'BRL' && s.date.startsWith(yr));
  const divs = OS.all('invtx').filter(t => IX.INC.has(t.type) && t.date.startsWith(yr)), divE = U.sum(divs, t => n(t.amount) * Inv.fx((OS.get('assets', t.asset) || {}).currency)), taxE = U.sum(divs, t => n(t.tax) * Inv.fx((OS.get('assets', t.asset) || {}).currency));
  const ptGain = U.sum(pt.filter(s => !(s.a.cls === 'Cripto' && s.held >= 365)), s => s.gainE), cryptoEx = pt.filter(s => s.a.cls === 'Cripto' && s.held >= 365);
  const brAll = sales.filter(s => s.a.currency === 'BRL'), carry = { ac: 0, dt: 0, fii: 0, out: 0 }, brMall = Object.entries(U.groupBy(brAll, s => s.date.slice(0, 7))).sort().map(([ym, arr]) => {
    const dt = arr.filter(s => s.dt), sw = arr.filter(s => !s.dt), acoes = sw.filter(s => s.a.cls === 'Ação'), fii = sw.filter(s => ['FII', 'REIT'].includes(s.a.cls)), outros = sw.filter(s => !acoes.includes(s) && !fii.includes(s));
    const vAc = U.sum(acoes, s => s.gross), gAc = U.sum(acoes, s => s.gain), isento = vAc <= 20000, gF = U.sum(fii, s => s.gain), gO = U.sum(outros, s => s.gain), gD = U.sum(dt, s => s.gain);
    const tax = (g, k, rate, exempt) => { if (g < 0) { carry[k] += -g; return 0; } if (exempt) return 0; const use = Math.min(carry[k], g); carry[k] -= use; return (g - use) * rate; };
    const irAc = tax(gAc, 'ac', .15, isento), irF = tax(gF, 'fii', .2, false), irO = tax(gO, 'out', .15, false), irD = tax(gD, 'dt', .2, false);
    const [y, m] = ym.split('-').map(Number), venc = U.iso(new Date(y, m + 1, 0)); return { ym, vAc, gAc, isento, irAc, irF, irO, irD, ir: irAc + irF + irO + irD, venc, gO, gF, gD, carry: Object.assign({}, carry) }; });
  const brM = brMall.filter(r => r.ym.startsWith(yr));
  return `<div class="row gap6 inv-per">${ys.map(y => `<button class="chip ${yr === y ? 'on' : ''}" data-ui="invTaxY" data-v="${y}">${y}</button>`).join('')}</div>
  <div class="pn"><div class="pn-h"><h3>🇵🇹 Portugal (IRS, anexo G e J)</h3><span class="mut" style="font-size:12px">ativos fora do Brasil</span></div>
    <div class="kpis">${UI.kpi('Mais-valias realizadas', M(U.sum(pt, s => s.gainE), { sign: 1 }), pt.length + ' venda(s)')}${UI.kpi('Imposto estimado (28%)', M(Math.max(0, ptGain) * .28), 'taxa autónoma; podes optar por englobar', { tone: ptGain > 0 ? 'warn' : '' })}${UI.kpi('Proventos brutos', M(divE), taxE ? 'imposto já retido: ' + M(taxE) + ' (dedutível em PT até ao limite da convenção)' : 'tributados a 28% (cá) ou retidos lá fora')}${UI.kpi('Cripto isenta (> 365 dias)', M(U.sum(cryptoEx, s => s.gainE), { sign: 1 }))}</div>
    ${pt.length ? UI.table({ key: 'taxpt', rows: pt, cols: [{ l: 'Data', v: s => U.fmtD(s.date) }, { l: 'Ativo', v: s => esc(s.a.ticker || s.a.name) }, { l: 'Detido', v: s => s.held + ' dias' + (s.kind ? ` <span class="bdg">${esc(s.kind)}</span>` : '') }, { l: 'Valor de venda', cls: 'r', v: s => `<span class="mono">${M(s.grossE)}</span>` }, { l: 'Mais/menos-valia', cls: 'r', v: s => `<span class="mono ${tone(s.gainE)}">${M(s.gainE, { sign: 1 })}</span>` }] }) : '<p class="mut">Sem vendas neste ano.</p>'}
    <p class="mut" style="font-size:12px">Estimativa com o preço médio. Menos-valias abatem às mais-valias do mesmo ano (e dos 5 seguintes se englobares). Ativos estrangeiros vão no anexo J. Confirma com o simulador do Portal das Finanças.</p></div>
  <div class="pn"><div class="pn-h"><h3>🇧🇷 Brasil (IR mensal, DARF 6015)</h3><span class="mut" style="font-size:12px">ativos em BRL</span></div>
    ${brM.length ? `<div class="tblw"><table class="tbl"><thead><tr><th>Mês</th><th class="r">Vendas de ações</th><th class="r">Ganho ações</th><th class="r">Ganho FII</th><th class="r">Ganho ETF/outros</th><th class="r">Day trade</th><th class="r">IR devido</th><th>DARF até</th></tr></thead><tbody>${brM.map(r => `<tr><td>${U.fmtYM(r.ym)}</td><td class="r mono">${IX.Mc(r.vAc, 'BRL')}${r.isento && r.vAc ? ' <span class="bdg pos">isento</span>' : ''}</td><td class="r mono ${tone(r.gAc)}">${IX.Mc(r.gAc, 'BRL')}</td><td class="r mono ${tone(r.gF)}">${IX.Mc(r.gF, 'BRL')}</td><td class="r mono ${tone(r.gO)}">${IX.Mc(r.gO, 'BRL')}</td><td class="r mono ${tone(r.gD)}">${r.gD ? IX.Mc(r.gD, 'BRL') : '—'}</td><td class="r mono ${r.ir ? 'warn' : ''}">${IX.Mc(r.ir, 'BRL')}</td><td>${r.ir >= 10 ? U.fmtD(r.venc) : r.ir ? 'acumula (< R$ 10)' : '—'}</td></tr>`).join('')}</tbody></table></div>` : '<p class="mut">Sem vendas em BRL neste ano.</p>'}
    ${brMall.length ? (() => { const c = brMall[brMall.length - 1].carry; return `<div class="note">Prejuízo acumulado a compensar: ações ${IX.Mc(c.ac, 'BRL')} · day trade ${IX.Mc(c.dt, 'BRL')} · FII ${IX.Mc(c.fii, 'BRL')} · ETF/outros ${IX.Mc(c.out, 'BRL')}</div>`; })() : ''}
    <p class="mut" style="font-size:12px">Ações: vendas até R$ 20 mil no mês são isentas; acima, 15% sobre o ganho (swing trade). FII: 20% sem isenção. ETF e BDR: 15% sem isenção. Day trade (compra e venda no mesmo dia) é detetado e paga 20%. Os prejuízos acumulam e abatem os ganhos seguintes da mesma categoria (já descontados no IR devido). Rendimentos de FII e dividendos são isentos; JCP tem 15% retido. Estimativa: confirma com um contador.</p></div>`; };
const firstBuy = (a, before) => { const t = U.sortBy(OS.all('invtx').filter(x => x.asset === a.id && L.QTX.includes(x.type) && x.date <= before), x => x.date)[0]; return t ? U.diff(before, t.date) : 0; };

/* ================= COTAÇÕES E LIGAÇÕES ================= */
T.cotacoes = () => { const c = OS.one('inbox'), st = IX.st, has = IX.hasScript(), v4 = (c.ver || 0) >= 6 && st.script !== 'old', fx = OS.one('profile').fx || {};
  return `<div class="pn"><div class="pn-h"><h3>${UI.ic('sync')}Cotações em tempo real</h3>${liveBadge()}</div>
  <div class="ib-w">
    <div class="ib-s ${has && v4 && st.script === 'ok' ? 'done' : ''}"><i>1</i><div><b>Ações, ETFs, fundos, FII, índices e câmbio de todas as bolsas (Yahoo Finance)</b>
      ${!has ? `<p>Usa o mesmo script Google do atalho de gastos e da sincronização (é grátis e fica na tua conta). Configura-o primeiro em <a class="acc" href="#definicoes">Definições → Atalho de gastos</a>.</p>`
      : v4 && st.script === 'ok' ? `<p class="pos">✓ Ligado. Atualiza a cada 20 s com esta página aberta (as bolsas da Europa e do Brasil podem ter até 15 min de atraso no Yahoo; EUA, câmbio e cripto são praticamente imediatos).</p>`
      : `<p>O teu script precisa da <b>versão nova</b> (uma vez só): 1) <button class="btn xs pri" data-act="ibCopy" data-t="code">Copiar código novo</button> 2) no <a class="acc" href="https://script.google.com" target="_blank" rel="noopener">Apps Script</a> apaga o código antigo e cola o novo → 💾 Guardar 3) <b>Implementar → Gerir implementações → ✏️ → Versão: Nova versão → Implementar</b>. O endereço não muda. 4) <button class="btn xs" data-act="invCheck">Verificar</button></p>${st.scriptErr ? `<div class="ib-st bad">✗ ${esc(st.scriptErr)}</div>` : ''}`}</div></div>
    <div class="ib-s ${st.ws === 'ok' ? 'done' : ''}"><i>2</i><div><b>Cripto ao segundo (Binance) e CoinGecko</b><p>${st.ws === 'ok' ? '<span class="pos">✓ Streaming ligado.</span>' : 'Liga-se sozinho quando tens cripto na carteira ou a acompanhar (símbolo tipo BTC-EUR).'} Não precisa de nada.</p></div></div>
    <div class="ib-s ${st.fh === 'ok' ? 'done' : ''}"><i>3</i><div><b>Opcional: ações dos EUA ao segundo (Finnhub)</b><p>Cria uma chave grátis em <a class="acc" href="https://finnhub.io/register" target="_blank" rel="noopener">finnhub.io</a> e cola aqui. Os preços dos EUA passam a chegar em streaming.</p><div class="inp-wrap" style="max-width:360px"><input type="text" data-bind="invcfg.fh" data-fk="invFh" value="${esc(cfg().fh || '')}" placeholder="chave Finnhub" autocomplete="off" aria-label="Chave Finnhub"></div></div></div>
    <div class="ib-s ${IX.fxRates ? 'done' : ''}"><i>4</i><div><b>Câmbio</b><p>${IX.fxRates ? `✓ Taxas do BCE de ${U.fmtD(IX.fxDate)}: 1 € = ${['USD', 'BRL', 'GBP'].map(k => IX.fxRates[k] ? U.nf(IX.fxRates[k], 4) + ' ' + k : '').filter(Boolean).join(' · ')}. Com o script, o câmbio também passa a ser ao vivo.` : 'A obter as taxas do BCE…'}</p></div></div>
    ${cc() === 'BR' || OS.all('assets').some(a => ['% do CDI', 'CDI +', 'IPCA +', 'Selic +', 'Poupança'].includes(a.idx)) ? `<div class="ib-s done"><i>5</i><div><b>Renda fixa brasileira</b><p>CDI, Selic, IPCA e poupança diários do Banco Central do Brasil: o valor de cada CDB, LCI, LCA, Tesouro e poupança é calculado dia a dia.</p></div></div>` : ''}
  </div></div>
  ${IX.hasScript() ? tdPanel() : ''}
  <div class="pn"><div class="pn-h"><h3>Preço manual</h3><span class="mut" style="font-size:12px">para ativos sem cotação (imóveis, PPR, fundos sem símbolo…)</span></div>${OS.all('assets').filter(a => !a.sym && !IX.isRF(a)).length ? `<div class="list">${OS.all('assets').filter(a => !a.sym && !IX.isRF(a)).map(a => `<form class="li" data-form="setPrice" data-id="${a.id}"><div class="li-t"><b>${esc(a.ticker || a.name)}</b><small>${esc(a.cls)} · ${a.priceDate ? 'preço de ' + U.fmtD(a.priceDate) : 'sem preço'}</small></div><div class="inp-wrap" style="width:150px"><input type="number" step="any" name="p" value="${a.price ?? ''}" aria-label="Preço de ${esc(a.ticker || a.name)}"><span>${a.currency || 'EUR'}</span></div><button class="btn sm">Guardar</button></form>`).join('')}</div>` : '<p class="mut">Todos os ativos têm cotação automática ou são renda fixa.</p>'}</div>
  <div class="pn"><div class="pn-h"><h3>Câmbio manual (sem internet)</h3><span class="mut" style="font-size:12px">quantos € vale 1 unidade</span></div><div class="row gap16" style="flex-wrap:wrap">${['USD', 'BRL', 'GBP'].map(k => `<label class="row gap8"><span class="mono">1 ${k} =</span><div class="inp-wrap" style="width:120px"><input type="number" step="any" data-bind="profile.fx.${k}" data-fk="fx${k}" value="${fx[k] || ''}" aria-label="Câmbio ${k}"><span>€</span></div></label>`).join('')}</div></div>`; };
let TDL = 0;
const tdPanel = () => { if (!IX.tdList.length && !TDL) { TDL = 1; IX.loadTD().then(() => OS.request()).catch(() => { }); }
  const L2 = IX.tdList; if (!L2.length) return '';
  return UI.toggle(`Tesouro Direto · preços e taxas de hoje (${L2.length} títulos)`, `<div class="tblw"><table class="tbl"><thead><tr><th>Título</th><th>Taxa de compra</th><th>Taxa de venda</th><th class="r">Preço de compra</th><th class="r">Preço de resgate (mercado)</th><th>Vencimento</th><th></th></tr></thead><tbody>${L2.map(x => `<tr><td><b>${esc(x.n)}</b></td><td>${esc(x.tc || '—')}</td><td>${esc(x.tv || '—')}</td><td class="r mono">${x.pc ? IX.Mc(x.pc, 'BRL') : '—'}</td><td class="r mono">${IX.Mc(x.pr, 'BRL')}</td><td>${x.v ? U.fmtD(x.v) : ''}</td><td><button class="btn xs" data-new="assets" data-defs='${esc(JSON.stringify({ name: x.n, ticker: x.n.replace(/^Tesouro /, 'TD '), cls: 'Tesouro Direto', td: x.n, currency: 'BRL', country: 'Brasil', venc: x.v, broker: 'Tesouro Direto' }))}'>+ Carteira</button></td></tr>`).join('')}</tbody></table></div><p class="mut" style="font-size:12px">Fonte: Tesouro Direto (oficial). Com o título na carteira, o valor segue o preço de resgate: é a marcação a mercado (o que recebias se vendesses hoje). Regista a compra com o número de títulos (pode ter decimais) e o preço unitário.</p>`, 'tdTab', 'bank'); };
A.invCheck = async () => { UI.toast('A verificar o script…'); IX.st.script = ''; try { if (OS.Inbox && OS.Inbox.check) await OS.Inbox.check(); await IX.tick(true); UI.toast(IX.st.script === 'ok' ? 'Cotações ao vivo ligadas ✓' : 'Ainda não: confirma que implementaste uma Nova versão.', IX.st.script === 'ok' ? 'pos' : 'warn'); } catch (e) { UI.toast('Falhou: ' + e.message, 'neg'); } OS.request(); };
T.ia = () => (OS.InvAI ? OS.InvAI.view() : UI.empty('A carregar…'));
})();
