/* OCEANUM — Biblioteca dos mestres: os princípios dos maiores investidores, pensadores e livros de investimento,
   resumidos por palavras nossas (sem citações longas). A IA de investimentos raciocina SEMPRE através destas lentes,
   diz que mestres sustentam cada recomendação e onde eles discordam. */
(() => {
'use strict';
const W = OS.InvWisdom = {};
W.MESTRES = [
  { id: 'buffett', nome: 'Warren Buffett', area: 'Valor e negócios', obras: 'Cartas aos acionistas da Berkshire Hathaway', ideias: ['Comprar uma ação é comprar parte de um negócio: entende o negócio antes do preço.', 'Preferir empresas excelentes com vantagem competitiva duradoura ("fosso") a preço justo, em vez de empresas medíocres baratas.', 'O horizonte certo é décadas; o tempo é amigo dos bons negócios.', 'Ser receoso quando os outros são gananciosos e ganancioso quando os outros têm medo.', 'Para a maioria das pessoas, um fundo de índice de baixo custo é a melhor escolha.', 'Regra 1: não perder dinheiro; regra 2: não esquecer a regra 1 (evitar perdas permanentes).'] },
  { id: 'munger', nome: 'Charlie Munger', area: 'Modelos mentais', obras: 'Poor Charlie\'s Almanack', ideias: ['Usar uma "grelha" de modelos mentais de várias disciplinas para decidir.', 'Inverter: pensa no que garantiria o fracasso e evita-o.', 'Paciência extrema e poucas decisões grandes e muito bem pensadas.', 'Evitar alavancagem, inveja e loucura: o que destrói gente inteligente.', 'Ficar dentro do círculo de competência.'] },
  { id: 'graham', nome: 'Benjamin Graham', area: 'Pai do value investing', obras: 'O Investidor Inteligente; Security Analysis', ideias: ['Margem de segurança: comprar bem abaixo do valor intrínseco estimado.', 'O "Sr. Mercado" oferece preços todos os dias; usa-os quando te servem, não deixes que te guiem.', 'Investimento é análise que promete segurança do capital e retorno adequado; o resto é especulação.', 'Investidor defensivo: carteira simples e diversificada, mistura de ações e obrigações (entre 25% e 75%) rebalanceada.'] },
  { id: 'bogle', nome: 'John Bogle', area: 'Fundos de índice', obras: 'The Little Book of Common Sense Investing', ideias: ['Os custos são o único fator que controlas: cada 1% de custos come uma fatia enorme do retorno a longo prazo.', 'Em média, os gestores ativos perdem para o índice depois de custos: compra o mercado inteiro.', 'Fica o curso: não tentes adivinhar o mercado.', 'A percentagem em obrigações deve crescer com a idade e com a necessidade de segurança.'] },
  { id: 'lynch', nome: 'Peter Lynch', area: 'Crescimento a preço razoável', obras: 'One Up on Wall Street', ideias: ['Investe no que conheces e consegues explicar em duas frases.', 'Faz o trabalho de casa: conhece o negócio, a dívida e o crescimento (PEG).', 'Correções acontecem; mais dinheiro se perdeu a tentar antecipá-las do que nas correções em si.', 'Os grandes vencedores precisam de tempo: não arranques as flores para regar as ervas daninhas.'] },
  { id: 'dalio', nome: 'Ray Dalio', area: 'Diversificação e ciclos', obras: 'Principles; Big Debt Crises', ideias: ['O "Santo Graal" é ter 10–15 fontes de retorno boas e pouco correlacionadas.', 'All Weather: equilibrar risco entre cenários de crescimento/inflação a subir ou a descer.', 'Os ciclos de dívida e de juros movem os mercados: não assumes que o passado recente continua.', 'Dor + reflexão = progresso: regista os erros e aprende com eles.'] },
  { id: 'marks', nome: 'Howard Marks', area: 'Risco e ciclos', obras: 'The Most Important Thing; Mastering the Market Cycle', ideias: ['Pensamento de segundo nível: o que o mercado já espera e onde pode estar errado.', 'Risco é a probabilidade de perda permanente, não só a volatilidade.', 'Sabe onde estás no ciclo: euforia pede prudência, pânico pede coragem.', 'Evitar os perdedores é mais importante do que apanhar todos os vencedores.'] },
  { id: 'fisher', nome: 'Philip Fisher', area: 'Qualidade e crescimento', obras: 'Common Stocks and Uncommon Profits', ideias: ['Procura empresas com gestão excelente, I&D e crescimento sustentável.', 'Investiga a fundo ("scuttlebutt"): clientes, concorrentes, fornecedores.', 'Se a compra foi bem feita, o momento de vender é quase nunca.'] },
  { id: 'templeton', nome: 'John Templeton', area: 'Contrarian global', obras: 'Templeton\'s Way with Money', ideias: ['Os mercados em alta nascem no pessimismo e morrem na euforia.', 'Diversifica globalmente: as oportunidades não respeitam fronteiras.', 'As quatro palavras mais perigosas: "desta vez é diferente".'] },
  { id: 'malkiel', nome: 'Burton Malkiel', area: 'Mercados eficientes', obras: 'A Random Walk Down Wall Street', ideias: ['É muito difícil bater o mercado de forma consistente; os índices vencem a maioria.', 'Diversificação, custos baixos e reequilíbrio são o "almoço grátis".', 'Aportes regulares (custo médio) reduzem o risco de entrar no pior momento.'] },
  { id: 'siegel', nome: 'Jeremy Siegel', area: 'Longo prazo', obras: 'Stocks for the Long Run', ideias: ['No longo prazo (20+ anos) as ações bateram obrigações, ouro e liquidez depois da inflação.', 'A curto prazo as ações são muito voláteis: o horizonte define a alocação.', 'Os dividendos reinvestidos são uma grande parte do retorno total.'] },
  { id: 'bernstein', nome: 'William Bernstein', area: 'Alocação de ativos', obras: 'The Four Pillars of Investing; The Intelligent Asset Allocator', ideias: ['Os quatro pilares: teoria, história, psicologia e o negócio da indústria financeira.', 'Já ganhaste o jogo quando tens o suficiente: para de correr riscos desnecessários.', 'A alocação de ativos explica a maior parte da diferença de resultados entre carteiras.'] },
  { id: 'taleb', nome: 'Nassim Taleb', area: 'Incerteza e cisnes negros', obras: 'O Cisne Negro; Antifrágil; Iludidos pelo Acaso', ideias: ['Eventos raros e extremos dominam os resultados: não confies em modelos que os ignoram.', 'Estratégia "barbell": maioria muito segura + pequena parte em apostas com ganho grande e perda limitada.', 'Evita a ruína a qualquer custo: sobreviver é a condição para ganhar.', 'Desconfia de previsões e de quem não tem pele em jogo.'] },
  { id: 'kahneman', nome: 'Daniel Kahneman', area: 'Psicologia das decisões', obras: 'Pensar, Depressa e Devagar', ideias: ['Aversão à perda: uma perda dói cerca do dobro de um ganho igual; isso leva a vender mal.', 'Excesso de confiança e viés de confirmação enganam até especialistas.', 'Decide com regras escritas antes da emoção (lista de verificação).'] },
  { id: 'housel', nome: 'Morgan Housel', area: 'Psicologia do dinheiro', obras: 'A Psicologia do Dinheiro', ideias: ['Riqueza é o que não vês: o dinheiro que não gastaste.', 'Juros compostos precisam de tempo e de não interromper o processo.', 'Margem de erro: planeia para estares errado; poupar sem objetivo também é proteção.', 'O "suficiente" é poderoso: não arrisques o que tens e precisas pelo que não precisas.'] },
  { id: 'shiller', nome: 'Robert Shiller', area: 'Avaliação e bolhas', obras: 'Exuberância Irracional', ideias: ['Mercados podem ficar caros por narrativas: avaliações elevadas (CAPE) baixam o retorno futuro esperado.', 'Bolhas alimentam-se de histórias contagiosas; desconfia de subidas explicadas só por narrativa.'] },
  { id: 'thorp', nome: 'Edward Thorp', area: 'Probabilidades e dimensionamento', obras: 'A Man for All Markets', ideias: ['Dimensiona cada aposta pela vantagem e pelo risco (critério de Kelly, usado com prudência: meia-Kelly ou menos).', 'Para quase todos, fundos de índice são a melhor opção.'] },
  { id: 'barsi', nome: 'Luiz Barsi Filho', curto: 'Barsi', area: 'Dividendos (Brasil)', obras: 'O Rei dos Dividendos (biografia)', ideias: ['"Carteira previdenciária": comprar empresas de setores perenes (energia, saneamento, bancos, seguros) que pagam dividendos.', 'Reinvestir os dividendos para aumentar a renda passiva ano após ano.', 'Comprar quando estão baratas e com foco no longo prazo, não na cotação diária.'] },
  { id: 'bazin', nome: 'Décio Bazin', area: 'Dividend yield (Brasil)', obras: 'Faça Fortuna com Ações, Antes que Seja Tarde', ideias: ['Preço-teto: só comprar quando o dividend yield esperado é de pelo menos ~6% ao ano.', 'Evitar empresas muito endividadas e desconfiar de lucros instáveis.'] },
  { id: 'cerbasi', nome: 'Gustavo Cerbasi', area: 'Finanças pessoais', obras: 'Casais Inteligentes Enriquecem Juntos; Como Organizar sua Vida Financeira', ideias: ['Primeiro organizar o orçamento, reserva de emergência e dívidas; depois investir.', 'Investir de forma automática e regular, alinhado com objetivos de vida.'] },
  { id: 'estoicos', nome: 'Sêneca, Epicteto e Marco Aurélio', area: 'Filosofia estoica', obras: 'Cartas a Lucílio; Manual; Meditações', ideias: ['Separa o que controlas (poupança, custos, comportamento, alocação) do que não controlas (o mercado).', 'Riqueza é ter poucas necessidades; a serenidade vale mais do que o ganho rápido.', 'Prepara-te para a adversidade antes de ela chegar (premeditatio malorum).'] },
  { id: 'pascal', nome: 'Blaise Pascal e a teoria da decisão', area: 'Probabilidade', obras: 'Pensées; trabalhos sobre probabilidade', ideias: ['Pesa probabilidades E consequências: um resultado improvável mas catastrófico merece proteção.', 'Muitos males vêm de não saber ficar quieto: a inação é muitas vezes a melhor decisão.'] },
  { id: 'keynes', nome: 'John Maynard Keynes', area: 'Economia e mercados', obras: 'Teoria Geral; gestão do fundo do King\'s College', ideias: ['O mercado pode manter-se irracional mais tempo do que tu solvente: evita alavancagem.', 'Concentra-te em poucos negócios que conheces bem, com paciência (fase final da sua carreira).'] }
];
/* versão compacta para o prompt da IA */
W.prompt = (ids) => { const L = ids && ids.length ? W.MESTRES.filter(m => ids.includes(m.id)) : W.MESTRES;
  return 'BIBLIOTECA DOS MESTRES (princípios resumidos; usa-os como lentes de raciocínio, não como citações):\n' + L.map(m => `• ${m.nome} (${m.area}; ${m.obras}): ${m.ideias.join(' ')}`).join('\n'); };
W.CONSENSO = 'CONSENSO DOS MESTRES (quando quase todos concordam, isto pesa mais): 1) proteger o capital e evitar a ruína; 2) custos baixos e diversificação; 3) horizonte longo e aportes regulares; 4) controlar o comportamento (medo, ganância, excesso de confiança); 5) conhecer o que se compra; 6) não usar alavancagem. DIVERGÊNCIAS conhecidas: índice passivo (Bogle, Malkiel, Buffett para a maioria) vs escolher ações (Buffett, Lynch, Fisher, Barsi) — para quem não tem tempo nem vantagem, prevalece o índice; dividendos (Barsi, Bazin) vs retorno total (Bogle, Siegel); concentração (Munger, Keynes) vs diversificação ampla (Dalio, Bogle, Templeton).';
W.view = (sel) => `<div class="iw-g">${W.MESTRES.map(m => `<div class="iw-c ${sel && sel.includes(m.id) ? 'on' : ''}" data-act="iaLens" data-id="${m.id}" role="button" tabindex="0"><b>${OS.U.esc(m.nome)}</b><small class="mut">${OS.U.esc(m.area)} · ${OS.U.esc(m.obras)}</small><ul>${m.ideias.slice(0, 3).map(i => `<li>${OS.U.esc(i)}</li>`).join('')}</ul></div>`).join('')}</div>`;
})();
