/* OCEANUM — Frases do dia: verdades que doem (para acordar) e motivação forte (para ir).
   Uma de cada por dia, iguais o dia todo; podes ver outra. Aparecem na Visão Geral (debaixo da saudação) e no Hoje. */
(() => {
'use strict';
const U = OS.U, V = OS.views, A = OS.act, esc = U.esc;
const TRUTH = [
  'Ninguém vai sentir pena de você daqui a dez anos por ter tido preguiça hoje. Vão só ver o resultado.',
  'Você não está cansado. Você está desacostumado a fazer o que é difícil.',
  'O seu "amanhã eu começo" já tem anos. E você sabe disso.',
  'As pessoas que você admira estavam a trabalhar enquanto você estava a deslizar o dedo no telemóvel.',
  'Você não tem falta de tempo. Tem falta de prioridade. O tempo para o que importa você arranja.',
  'A sua mãe não se sacrificou para você ser mediano.',
  'Se continuar a fazer o que está a fazer, vai continuar a ter o que tem. Sem surpresas.',
  'Ninguém lembra de quem quase conseguiu.',
  'O conforto de hoje é a dívida que você paga com juros amanhã.',
  'Você diz que quer, mas as suas ações dizem que não quer tanto assim.',
  'Talento sem disciplina é só potencial desperdiçado. E potencial desperdiçado é a coisa mais triste que existe.',
  'O mundo não deve nada a você. Nem o emprego, nem o sucesso, nem a atenção.',
  'Daqui a cinco anos você vai ser exatamente o resultado das escolhas pequenas que está a fazer hoje.',
  'Você está a trocar o que mais quer na vida pelo que quer agora.',
  'O tempo que você perde não volta. Cada dia desperdiçado é um dia a menos — para sempre.',
  'Ninguém veio salvar você. Se você não se levantar, ninguém levanta.',
  'Arrependimento é o peso mais pesado que existe. E ele cresce todos os dias que você adia.',
  'Você reclama do resultado mas ama o processo que te leva a ele: a cama, o sofá, o telemóvel.',
  'Os seus pais estão a envelhecer. O tempo para os orgulhar e cuidar deles não é infinito.',
  'Se a sua vida fosse um filme, você ia torcer pela personagem que está a ser hoje?',
  'Motivação é para amadores. Profissionais aparecem mesmo sem vontade.',
  'Você sabe exatamente o que tem de fazer. Só não está a fazer.',
  'Cada desculpa que você dá é uma pequena traição ao seu próprio futuro.',
  'Ninguém vai trabalhar por você. Ninguém vai estudar por você. Ninguém vai sofrer por você.',
  'Você saiu do Brasil, atravessou um oceano. Não foi para ficar parado no mesmo lugar.',
  'O que você faz quando ninguém está a ver define quem você realmente é.',
  'Você não falha por falta de capacidade. Falha por falta de constância.',
  'A sua zona de conforto é bonita. Mas nada cresce lá.',
  'Ninguém se importa com o seu potencial. Importam-se com o que você entrega.',
  'O "depois" é o lugar onde os sonhos vão morrer.',
  'Você tem as mesmas 24 horas de quem você admira. A diferença é o que faz com elas.',
  'Se você não construir o seu sonho, alguém vai contratar você para construir o dele.',
  'Pessoas medianas esperam pela vontade. Pessoas grandes fazem com ou sem ela.',
  'O seu corpo é o resultado de cada refeição e cada treino que você escolheu — ou não.',
  'Dinheiro mal gasto hoje é liberdade que você não vai ter amanhã.',
  'A dor de ficar igual vai ser maior do que a dor de mudar. Só que vem mais tarde.',
  'O telemóvel está a roubar a sua vida e você ainda agradece.',
  'Você não precisa de mais um vídeo motivacional. Precisa de fazer o que já sabe.',
  'Se hoje fosse o último dia da sua vida, você teria orgulho de como o gastou?',
  'Ninguém vai lembrar das suas desculpas. Só das suas conquistas — ou da falta delas.',
  'A distância entre quem você é e quem você quer ser chama-se disciplina.',
  'Você está a viver como se tivesse tempo de sobra. Não tem.',
  'Quem não se prepara está a preparar-se para falhar.',
  'O seu futuro "eu" está a olhar para você agora. Ele está orgulhoso ou envergonhado?',
  'Você pede a Deus que abra portas, mas não sai do sofá para bater nelas.',
  'Fé sem obras é morta. Oração sem esforço é preguiça com bons modos.',
  'Inveja de quem conseguiu é só a prova de que você podia ter feito mais.',
  'Estar ocupado não é o mesmo que ser produtivo. Você só está a fugir do que importa.',
  'Ninguém fica rico, forte ou sábio por acidente.',
  'Cada "só mais cinco minutos" é você a escolher perder.',
  'Você não é vítima das circunstâncias. É resultado das decisões.',
  'Se você não está a evoluir, está a ficar para trás. O mundo não espera.',
  'O sacrifício de agora é pequeno comparado com o arrependimento de nunca ter tentado.',
  'A vida não vai ficar mais fácil. Você é que tem de ficar mais forte.',
  'Quem quer, arranja um meio. Quem não quer, arranja uma desculpa.',
  'Você conhece o caminho. O problema é que ele é difícil e você está a escolher o fácil.',
  'Dormir tarde para ver séries e acordar sem energia: essa é a rotina de quem não chega a lado nenhum.',
  'Você quer resultados de campeão com esforço de amador.',
  'Ninguém vai bater palmas para o seu esforço mínimo.',
  'O seu salário, o seu corpo e as suas notas são o espelho dos seus hábitos.',
  'Se você soubesse o quanto o tempo é curto, não teria desperdiçado o dia de ontem.',
  'Promessas a si mesmo que você não cumpre destroem a sua autoconfiança, uma de cada vez.',
  'Você vai olhar para trás e desejar ter começado hoje.',
  'O mundo está cheio de pessoas inteligentes que nunca fizeram nada. Não seja mais uma.',
  'Disciplina é lembrar-se do que você quer quando o que você sente é preguiça.',
  'Você vai morrer. A pergunta é: vai ter vivido de verdade?',
  'Quem você vai ser quando ninguém acreditar em você? É aí que se vê.',
  'Cada dia sem treinar, sem estudar, sem poupar, é um voto contra a pessoa que você quer ser.',
  'Seja honesto: se continuar assim, onde vai estar daqui a um ano?',
  'Ninguém nasce pronto. Mas também ninguém fica pronto parado.',
  'O medo de falhar está a fazer você falhar sem nem tentar.',
  'As pessoas à sua volta estão a crescer. Você está a assistir.',
  'A preguiça cobra caro, e cobra sempre no pior momento.',
  'Você não precisa de um plano perfeito. Precisa de parar de se esconder atrás do planeamento.',
  'Um dia você vai ter filhos. Que exemplo é que está a construir?',
  'Você reza por uma vida diferente e vive igual todos os dias.',
  'Excelência não é um ato. É um hábito. E os seus hábitos hoje são medianos.',
  'O seu adversário não é ninguém lá fora. É você na cama às 7 da manhã.',
  'Sonhar é de graça. Realizar custa tudo. E você ainda não pagou.',
  'Se não for agora, quando? Se não for você, quem?',
  'Ninguém vai entregar a vida que você quer de bandeja. Ela tem de ser arrancada.',
  'O que te separa do sucesso é a quantidade de vezes que você se levanta depois de cair.',
  'A sua família merece a melhor versão de você. Você está a dar-lhes a mais cansada.',
  'Você tem medo de falhar, mas devia ter medo de nunca ter tentado.',
  'Hoje é um dos dias que você vai lembrar — ou um dos milhares que vai esquecer. Escolha.'
];
const PUSH = [
  'Hoje não é dia de negociar com a preguiça. É dia de ganhar dela.',
  'Levanta-te. Ninguém vai fazer isto por ti — e é exatamente por isso que vai ser teu.',
  'Um passo hoje vale mais do que cem planos para amanhã.',
  'Trabalha em silêncio. Deixa o resultado fazer barulho.',
  'Tu não vieste até aqui para chegar só até aqui.',
  'Disciplina hoje, liberdade amanhã.',
  'Faz hoje o que os outros não querem, para viveres amanhã como os outros não podem.',
  'O cansaço passa. O orgulho de ter feito fica.',
  'Sê o tipo de pessoa que cumpre o que promete a si mesma.',
  'Não precisas de te sentir pronto. Precisas de começar.',
  'Cada repetição, cada página, cada euro poupado: estás a construir o homem que vais ser.',
  'Hoje é mais um tijolo. Não deixes de o pôr.',
  'Tudo o que fizerem, façam de todo o coração — Colossenses 3:23. Hoje é para dar tudo.',
  'Grandes coisas nunca vêm de zonas de conforto.',
  'Não pares quando estiveres cansado. Para quando estiver feito.',
  'Dor temporária, orgulho permanente.',
  'O teu futuro está a ser decidido nas próximas 24 horas.',
  'Sê mais forte do que a tua melhor desculpa.',
  'Quem tu queres ser já está à tua espera do outro lado do esforço.',
  'Foco. Fé. Força. O resto é ruído.',
  'Hoje vence a versão de ti que não desiste.',
  'Não compares o teu capítulo 1 com o capítulo 20 de outra pessoa. Escreve o teu.',
  'Persistência transforma o impossível em inevitável.',
  'Acorda com determinação. Deita-te com satisfação.',
  'O Deus que te trouxe até aqui não te trouxe para pares agora.',
  'Fica desconfortável. É lá que tu cresces.',
  'Mais uma hora de foco hoje pode mudar o resto do teu ano.',
  'Ninguém se lembra de dias normais. Faz de hoje um dia que conta.',
  'Ganha a manhã e ganhas o dia.',
  'Não é sobre ter tempo. É sobre fazer tempo.',
  'Hoje vais fazer o difícil primeiro.',
  'Sê a prova de que é possível.',
  'O caminho é longo, mas cada passo conta. Dá o de hoje.',
  'A tua história ainda está a ser escrita — e hoje és tu a caneta.',
  'Faz com que o teu eu de daqui a 5 anos te agradeça.',
  'Pequenas vitórias todos os dias constroem uma vida grande.',
  'Não vieste ao mundo para seres mais um.',
  'Coragem não é não ter medo. É ir com medo.',
  'Começa onde estás, usa o que tens, faz o que podes.',
  'Hoje: menos desculpas, mais execução.'
];
const pick = (arr, salt) => arr[(U.hash(U.today() + salt) + (OS.ui['q_' + salt] || 0)) % arr.length];
A.qNext = b => { OS.setUI('q_' + b.dataset.k, (OS.ui['q_' + b.dataset.k] || 0) + 1); };
const truthCard = () => `<div class="pn q-truth"><div class="pn-h"><h3>Verdade do dia</h3><button class="icon-btn" data-act="qNext" data-k="t" aria-label="Outra verdade" title="Outra">${OS.UI.ic('right')}</button></div><p>${esc(pick(TRUTH, 't'))}</p></div>`;
const pushLine = () => `<p class="q-push">${esc(pick(PUSH, 'p'))} <button class="q-more" data-act="qNext" data-k="p" aria-label="Outra frase">↻</button></p>`;
OS.Quotes = { TRUTH, PUSH, truth: () => pick(TRUTH, 't'), push: () => pick(PUSH, 'p') };
const wrap = (k, fn) => { const o = V[k]; if (!o || o._q) return; V[k] = sub => fn(o(sub), sub); V[k]._q = 1; };
OS.on('ready', () => {
  wrap('visao', h => h.replace(/(<div class="dash-top"><div><div class="eyebrow">[^<]*<\/div><h1>[^<]*<\/h1>)/, '$1' + pushLine()));
  wrap('hoje', h => { let x = h.replace(/<p class="today-q"[^>]*>[\s\S]*?<\/p>/, pushLine()); const at = x.indexOf('</div>', x.indexOf('q-push')); return at > 0 ? x.slice(0, at + 6) + truthCard() + x.slice(at + 6) : truthCard() + x; });
});
// Visão Geral: cartão "Verdade do dia" logo a seguir ao topo
OS.on('ready', () => { const o = V.visao; if (!o || o._q2) return; V.visao = sub => { const h = o(sub), k = h.indexOf('<div class="dash-top"'); if (k < 0) return h; let depth = 0, i = k; const re = /<\/?div\b/g; re.lastIndex = k; let m; while ((m = re.exec(h))) { depth += m[0] === '<div' ? 1 : -1; if (!depth) { i = h.indexOf('>', m.index) + 1; break; } } return h.slice(0, i) + truthCard() + h.slice(i); }; V.visao._q2 = 1; });
})();
