/* OCEANUM — Corpo › Desporto: os desportos que praticas.
   Catálogo com informação de cada desporto (o que é, benefícios, músculos, gasto calórico, lesões e prevenção, equipamento, aquecimento),
   as tuas práticas (treinos, jogos, competições) com estatísticas específicas de cada desporto, resultados, gráficos,
   treinos específicos para melhorar (técnica, físico, tático, mental), plano semanal e treinador IA. */
(() => {
'use strict';
const U = OS.U, UI = OS.UI, C = OS.C, V = OS.views, A = OS.act, esc = U.esc, today = () => U.today();
const D = (f, t, m, d) => ({ f, t, m, d });
/* ---------- catálogo ---------- */
const SPORTS = {
  futebol: { n: 'Futebol', ic: 'ball', c: '#22c55e', met: 7, comp: 1, info: 'Desporto coletivo de 11 contra 11 em que se marca golo com os pés ou a cabeça. Exige resistência intermitente, velocidade, técnica de passe e leitura de jogo.', ben: ['Resistência cardiovascular e capacidade de repetir sprints', 'Coordenação, agilidade e equilíbrio', 'Trabalho de equipa e tomada de decisão'], mus: 'Quadríceps, isquiotibiais, glúteos, gémeos, adutores e core', inj: [['Entorse do tornozelo', 'propriocepção (apoio unipodal) e ligaduras/meias de compressão'], ['Rotura dos isquiotibiais', 'Nordic curls 2×/semana e aquecimento com sprints progressivos'], ['Lesões no joelho (LCA)', 'FIFA 11+ antes dos treinos, aterrar com joelho alinhado']], gear: 'Chuteiras adequadas ao piso (FG/AG/TF), caneleiras, meias de compressão', aq: ['Corrida leve 5 min', 'Mobilidade de anca (balanços de perna)', 'Skippings e calcanhares ao glúteo', 'Passes curtos em pares', '3 sprints progressivos de 20 m'],
    pos: ['Guarda-redes', 'Defesa central', 'Lateral', 'Médio defensivo', 'Médio centro', 'Médio ofensivo', 'Extremo', 'Ponta de lança'], st: [['golos', 'Golos'], ['assist', 'Assistências'], ['remates', 'Remates à baliza'], ['desarmes', 'Desarmes'], ['km', 'Km percorridos']],
    dr: [D('Técnica', 'Rondo 4×1', 15, 'Quatro à volta, um ao meio a pressionar: 2 toques no máximo, troca quem perder a bola.'), D('Técnica', 'Condução com mudanças de direção', 10, 'Slalom entre cones com as duas faces do pé; acelera depois de cada cone.'), D('Técnica', 'Finalização de primeira', 15, 'Recebe um passe lateral e remata de primeira, 10 de cada pé.'), D('Técnica', 'Pé fraco 100 toques', 10, 'Passes contra a parede só com o pé mais fraco, 100 repetições.'), D('Físico', 'RSA: sprints repetidos', 12, '6×30 m a fundo com 25 s de recuperação, 2 séries.'), D('Físico', 'Nordic curls + Copenhagen', 10, '3×6 nórdicos e 3×20 s prancha lateral de adutores — prevenção de lesões.'), D('Tático', 'Jogo reduzido 4×4', 20, 'Campo pequeno, 4 min de jogo, 2 de pausa: pressão alta e transições rápidas.'), D('Mental', 'Visualização pré-jogo', 5, 'Imagina 3 ações tuas a correr bem no próximo jogo, com detalhe.')] },
  futsal: { n: 'Futsal', ic: 'ball', c: '#10b981', met: 8, comp: 1, info: 'Futebol de 5 em pavilhão com bola mais pequena e pesada. Muita velocidade de decisão, receção com a sola e jogo em espaços curtos.', ben: ['Explosão e agilidade', 'Técnica em espaço reduzido', 'Decisão rápida'], mus: 'Pernas, glúteos, core', inj: [['Entorse do tornozelo', 'reforço de tornozelo e calçado de pavilhão'], ['Pubalgia', 'Copenhagen e fortalecimento do core']], gear: 'Sapatilhas de sola lisa (IC), caneleiras', aq: ['Corrida e deslocamentos laterais 5 min', 'Mobilidade de anca', 'Toques de sola e receções', 'Sprints curtos de 10 m'],
    pos: ['Guarda-redes', 'Fixo', 'Ala', 'Pivô'], st: [['golos', 'Golos'], ['assist', 'Assistências'], ['remates', 'Remates'], ['recup', 'Recuperações']],
    dr: [D('Técnica', 'Receção com a sola + orientação', 10, 'Recebe com a sola e roda para o espaço livre, alternando lados.'), D('Técnica', 'Pisadas e fintas', 10, 'Pisada, elástico, cueca entre cones: 5 de cada.'), D('Tático', 'Rotação 3-1', 20, 'Movimentos de rotação e paralela com finalização no pivô.'), D('Físico', 'Agilidade em escada', 10, '6 padrões de escada de coordenação, 3 voltas cada.'), D('Físico', 'Sprints 10 m com mudança', 10, '10×10 m ida e volta com toque no chão.'), D('Mental', 'Respiração entre jogadas', 5, 'Expira longo (4-7) para baixar o ritmo antes de livres e penáltis.')] },
  basquetebol: { n: 'Basquetebol', ic: 'ball', c: '#f97316', met: 6.5, comp: 1, info: 'Cinco contra cinco: marca-se no cesto. Mistura saltos, sprints curtos, drible e lançamento de precisão.', ben: ['Potência e salto vertical', 'Coordenação mão-olho', 'Resistência intermitente'], mus: 'Gémeos, quadríceps, glúteos, ombros, core', inj: [['Entorse do tornozelo', 'propriocepção e ténis de cano alto'], ['Tendinite rotuliana', 'agachamento excêntrico em plano inclinado'], ['Dedos', 'tape nos dedos e técnica de receção']], gear: 'Ténis de basquetebol, joelheiras opcionais', aq: ['Corrida e deslocamentos defensivos 5 min', 'Mobilidade de tornozelo e anca', 'Drible estático 2 min', 'Lançamentos próximos do cesto'],
    pos: ['Base', 'Extremo-base', 'Extremo', 'Extremo-poste', 'Poste'], st: [['pontos', 'Pontos'], ['ressaltos', 'Ressaltos'], ['assist', 'Assistências'], ['roubos', 'Roubos de bola'], ['triplos', 'Triplos']],
    dr: [D('Técnica', 'Mikan drill', 8, 'Bandejas alternadas com as duas mãos debaixo do cesto, 3×1 min.'), D('Técnica', 'Forma de lançamento (BEEF)', 10, 'Equilíbrio, olhos, cotovelo, finalização: 50 lançamentos a 2 m, depois recua.'), D('Técnica', 'Drible com 2 bolas', 10, 'Simultâneo e alternado, baixo e alto, 30 s cada.'), D('Técnica', '100 lances livres', 15, 'Regista a percentagem; rotina igual em todos.'), D('Físico', 'Pliometria', 10, 'Saltos de caixa 4×5 e saltos laterais 3×10.'), D('Tático', 'Pick and roll 2×0', 15, 'Bloqueio direto: leitura de passar, lançar ou penetrar.'), D('Mental', 'Rotina de lance livre', 5, 'Mesma sequência sempre: respiração, 3 dribles, olhar o aro.')] },
  voleibol: { n: 'Voleibol', ic: 'ball', c: '#eab308', met: 4, comp: 1, info: 'Seis contra seis separados por uma rede; três toques para devolver. Muito salto, reação e comunicação.', ben: ['Salto e potência de ombros', 'Reflexos', 'Comunicação de equipa'], mus: 'Ombros, core, pernas e gémeos', inj: [['Ombro (manguito rotador)', 'exercícios de rotação externa com elástico'], ['Joelho do saltador', 'excêntricos e aterragem suave'], ['Dedos', 'tape e técnica de bloco']], gear: 'Sapatilhas de pavilhão, joelheiras', aq: ['Mobilidade de ombros com elástico', 'Deslocamentos e saltos baixos', 'Toques de dedos e manchete em pares', 'Remates progressivos'],
    pos: ['Distribuidor', 'Oposto', 'Zona 4 (ponta)', 'Central', 'Líbero'], st: [['pontos', 'Pontos'], ['aces', 'Aces'], ['blocos', 'Blocos'], ['rececoes', 'Receções certas']],
    dr: [D('Técnica', 'Manchete contra a parede', 10, '100 toques seguidos de manchete com controlo.'), D('Técnica', 'Serviço por zonas', 15, 'Escolhe zona 1, 5 ou 6 e acerta 10 de cada.'), D('Técnica', 'Passada de ataque', 10, 'Passada 3 passos com braços, sem bola, depois com lançamento.'), D('Físico', 'Salto vertical', 10, 'Agachamento com salto 4×6 e saltos de bloco 3×10.'), D('Tático', 'Cobertura de ataque', 15, 'Posicionamento em W para receção e cobertura.'), D('Mental', 'Reset após erro', 3, 'Gesto-âncora (bater nas pernas) e foco no ponto seguinte.')] },
  tenis: { n: 'Ténis', ic: 'racket', c: '#84cc16', met: 7, comp: 1, info: 'Raquete e bola, individual ou pares. Golpes de direita, esquerda, serviço e volei; muita movimentação lateral.', ben: ['Agilidade e reação', 'Coordenação', 'Resistência anaeróbia'], mus: 'Ombro, antebraço, core rotacional, pernas', inj: [['Epicondilite (cotovelo de tenista)', 'excêntricos de punho, raquete com corda mais macia'], ['Ombro', 'rotadores externos com elástico'], ['Gémeos', 'alongar e reforçar gémeos']], gear: 'Raquete adequada ao nível, sapatilhas de ténis do piso certo', aq: ['Saltar à corda 3 min', 'Rotação de tronco e ombros', 'Mini-ténis junto à rede', 'Serviços progressivos'],
    pos: ['Singulares', 'Pares'], st: [['setsG', 'Sets ganhos'], ['setsP', 'Sets perdidos'], ['aces', 'Aces'], ['winners', 'Winners'], ['erros', 'Erros não forçados']],
    dr: [D('Técnica', 'Cesto de direitas cruzadas', 15, '50 direitas cruzadas a um alvo; depois 50 paralelas.'), D('Técnica', 'Serviço: lançamento consistente', 10, 'Lança a bola 20 vezes sem bater: deve cair no mesmo sítio.'), D('Técnica', 'Volei em rede', 10, 'Voleis curtos com parceiro, sem deixar cair.'), D('Físico', 'Spider drill', 8, 'Corre aos 5 pontos do campo a partir do centro, 4 séries.'), D('Tático', 'Pontos de 3 pancadas', 15, 'Serviço + 2 pancadas com objetivo de ganhar o ponto.'), D('Mental', 'Rotina entre pontos', 5, 'Responder (virar costas), relaxar, preparar, executar.')] },
  padel: { n: 'Padel', ic: 'racket', c: '#06b6d4', met: 6, comp: 1, info: 'Raquete em pares num campo fechado com paredes de vidro. Jogo de posicionamento, globos e defesa com as paredes.', ben: ['Reflexos e coordenação', 'Social e divertido', 'Cardio moderado'], mus: 'Ombro, antebraço, pernas, core', inj: [['Epicondilite', 'pega correta e excêntricos'], ['Gémeos e tendão de Aquiles', 'aquecer bem e reforçar']], gear: 'Pala adequada, sapatilhas de padel (sola espiga)', aq: ['Mobilidade de ombro e punho', 'Deslocamentos laterais', 'Bolas suaves em rede', 'Saídas de parede'],
    pos: ['Drive (direita)', 'Revés (esquerda)'], st: [['setsG', 'Sets ganhos'], ['setsP', 'Sets perdidos'], ['winners', 'Winners'], ['erros', 'Erros']],
    dr: [D('Técnica', 'Saída de parede de fundo', 15, 'Bola contra o vidro, deixa ressaltar e devolve cruzado; 30 de cada lado.'), D('Técnica', 'Bandeja', 10, 'Bandeja à malha lateral com controlo, não com força.'), D('Técnica', 'Globo defensivo', 10, 'Globos altos por cima do adversário a partir do fundo.'), D('Tático', 'Ganhar a rede', 15, 'Globo + subir juntos à rede em pares.'), D('Físico', 'Deslocamentos em L', 8, 'Rede-fundo-lateral, 6×30 s.'), D('Mental', 'Comunicação de pares', 5, 'Combinar "minha/tua/vai" antes de cada ponto.')] },
  natacao: { n: 'Natação', ic: 'wave', c: '#3b82f6', met: 8, info: 'Deslocamento na água em crol, costas, bruços ou mariposa. Corpo inteiro, baixo impacto nas articulações.', ben: ['Corpo inteiro e baixo impacto', 'Capacidade pulmonar', 'Ótima para recuperação ativa'], mus: 'Dorsais, ombros, peito, core, pernas', inj: [['Ombro de nadador', 'técnica de entrada da mão e reforço de rotadores'], ['Joelho de bruços', 'pernada correta e aquecimento']], gear: 'Óculos, touca, pull-buoy, prancha, barbatanas', aq: ['200 m suaves variados', 'Mobilidade de ombro', '4×25 m técnica', '2×50 m progressivos'],
    pos: ['Crol', 'Costas', 'Bruços', 'Mariposa', 'Estilos'], st: [['metros', 'Metros'], ['t100', 'Melhor 100 m (s)'], ['series', 'Séries']],
    dr: [D('Técnica', 'Catch-up', 10, 'Crol esperando que a mão da frente seja tocada antes da braçada seguinte.'), D('Técnica', 'Pernada com prancha', 10, '8×25 m pernada, ritmo constante.'), D('Técnica', 'Respiração bilateral 3-5', 10, 'Respira a cada 3 e depois a cada 5 braçadas.'), D('Físico', 'Intervalado 10×100', 25, '10×100 m com 20 s de descanso a ritmo forte e igual.'), D('Físico', 'Pull com pull-buoy', 15, '4×100 m só braços.'), D('Mental', 'Contar braçadas', 5, 'Conta braçadas por piscina e tenta reduzir sem perder ritmo.')] },
  corrida: { n: 'Corrida', ic: 'run', c: '#ef4444', met: 9.8, link: 'corrida', info: 'Corrida de estrada ou trilho. O módulo Corrida do Oceanum tem o registo detalhado de km e ritmo.', ben: ['Saúde cardiovascular', 'Gestão do peso', 'Clareza mental'], mus: 'Gémeos, quadríceps, isquiotibiais, glúteos', inj: [['Canelite', 'aumentar volume ≤10%/semana e reforço de tibial'], ['Fascite plantar', 'reforço do pé e alongar gémeos'], ['Joelho de corredor', 'reforço de glúteo médio']], gear: 'Ténis de corrida adequados à passada, relógio GPS', aq: ['Caminhada rápida 3 min', 'Skippings, calcanhares', 'Balanços de perna', '2×80 m progressivos'],
    pos: ['5 km', '10 km', 'Meia maratona', 'Maratona', 'Trail'], st: [['km', 'Km'], ['ritmo', 'Ritmo (min/km)'], ['desnivel', 'Desnível (m)']],
    dr: [D('Físico', 'Intervalado 6×800', 30, '6×800 m a ritmo de 5 km com 2 min de trote.'), D('Físico', 'Longão leve', 60, 'Corrida longa em ritmo de conversa.'), D('Técnica', 'Drills de técnica', 10, 'Skipping A/B, passo saltado, 2×20 m cada.'), D('Físico', 'Força para corredores', 20, 'Agachamento búlgaro, elevação de gémeos, ponte de glúteo.'), D('Mental', 'Dividir a prova em partes', 5, 'Planeia a prova em 3 blocos com objetivo para cada.')] },
  ciclismo: { n: 'Ciclismo', ic: 'bike', c: '#a855f7', met: 7.5, info: 'Estrada, BTT ou indoor. Resistência aeróbia com pouco impacto; potência de pernas nas subidas.', ben: ['Resistência sem impacto', 'Pernas fortes', 'Explorar lugares novos'], mus: 'Quadríceps, glúteos, gémeos', inj: [['Joelho', 'afinação correta do selim'], ['Lombar', 'core e posição na bicicleta']], gear: 'Capacete, luzes, sapatos de encaixe opcionais', aq: ['10 min a rolar leve', '3×1 min cadência alta'],
    pos: ['Estrada', 'BTT', 'Gravel', 'Indoor'], st: [['km', 'Km'], ['desnivel', 'Desnível (m)'], ['vel', 'Velocidade média']],
    dr: [D('Físico', 'Sweet spot 3×12', 50, '3×12 min a 88–93% do FTP com 5 min fáceis.'), D('Técnica', 'Cadência', 15, '5×1 min a 110 rpm, pedalar redondo.'), D('Físico', 'Repetições em subida', 40, '6×3 min em subida forte, desce a recuperar.'), D('Mental', 'Gestão de esforço', 5, 'Define a zona alvo antes de sair e respeita-a.')] },
  jiujitsu: { n: 'Jiu-Jitsu', ic: 'shield', c: '#64748b', met: 7, comp: 1, info: 'Arte marcial de solo focada em alavancas, raspagens, passagens de guarda e finalizações (estrangulamentos e chaves).', ben: ['Força funcional e resistência', 'Resolução de problemas sob pressão', 'Defesa pessoal e disciplina'], mus: 'Corpo inteiro: core, costas, pega, ancas', inj: [['Pescoço e ombro', 'reforço de pescoço e bater cedo'], ['Dedos', 'tape nos dedos'], ['Joelho', 'cuidado com chaves de calcanhar e técnica de guarda']], gear: 'Kimono (gi) ou rashguard (no-gi), protetor bucal', aq: ['Shrimp (fuga de anca) ida e volta', 'Rolamentos', 'Ponte e rotação', 'Solo drill de passagem'],
    pos: ['Branca', 'Azul', 'Roxa', 'Castanha', 'Preta'], st: [['fin', 'Finalizações'], ['rasp', 'Raspagens'], ['pass', 'Passagens'], ['rounds', 'Rounds de rola']],
    dr: [D('Técnica', 'Fuga de anca (shrimp) 50×', 8, 'Movimento base para recuperar guarda.'), D('Técnica', 'Raspagem de tesoura 20×', 10, 'Dos dois lados, devagar e com controlo.'), D('Técnica', 'Passagem toreando', 10, 'Drill com parceiro: controlo de calças e lado.'), D('Tático', 'Rolas posicionais', 20, 'Começa numa posição (montada, costas) e luta por 3 min.'), D('Físico', 'Pega e core', 10, 'Pendurar no kimono 3×30 s, prancha 3×45 s.'), D('Mental', 'Calma debaixo de pressão', 5, 'Respirar pelo nariz em posições ruins durante a rola.')] },
  boxe: { n: 'Boxe', ic: 'flame', c: '#dc2626', met: 9, comp: 1, info: 'Combate de pé só com os punhos. Treino de técnica, saco, manoplas e sparring.', ben: ['Condição física explosiva', 'Coordenação e reflexos', 'Alívio de stress e confiança'], mus: 'Ombros, core, pernas, costas', inj: [['Mãos e punhos', 'ligaduras sempre e luvas de peso certo'], ['Ombro', 'aquecer bem e reforço']], gear: 'Ligaduras, luvas (12–16 oz), protetor bucal, saltar à corda', aq: ['Corda 3 rounds', 'Sombra 2 rounds', 'Mobilidade de ombro e anca'],
    pos: ['Ortodoxo', 'Canhoto'], st: [['rounds', 'Rounds'], ['spar', 'Rounds de sparring'], ['combos', 'Combinações treinadas']],
    dr: [D('Técnica', 'Sombra com foco', 9, '3 rounds de 3 min: jab-direto-gancho com defesa após cada combinação.'), D('Técnica', 'Saco 1-2-3', 12, '4 rounds com combinações e saída lateral.'), D('Físico', 'Corda e burpees', 12, '3 min corda + 10 burpees, 4 séries.'), D('Tático', 'Defesa e contra-ataque', 15, 'Parceiro ataca jab, tu esquivas e contras.'), D('Mental', 'Respiração no round', 3, 'Expirar em cada golpe, controlar ritmo.')] },
  muaythai: { n: 'Muay Thai', ic: 'flame', c: '#b91c1c', met: 10, comp: 1, info: 'A "arte dos oito membros": punhos, cotovelos, joelhos e canelas, mais o clinch.', ben: ['Condição física total', 'Defesa pessoal', 'Disciplina'], mus: 'Pernas, core, ombros, ancas', inj: [['Canelas', 'progressão no saco e caneleiras no sparring'], ['Ancas', 'mobilidade de anca diária']], gear: 'Luvas, ligaduras, caneleiras, protetor bucal', aq: ['Corda 3 rounds', 'Sombra com chutes leves', 'Mobilidade de anca'],
    pos: ['Ortodoxo', 'Canhoto'], st: [['rounds', 'Rounds'], ['spar', 'Rounds de sparring'], ['chutes', 'Chutes no saco']],
    dr: [D('Técnica', 'Teep (pontapé frontal)', 8, '3×20 de cada perna com equilíbrio.'), D('Técnica', 'Chute circular no saco', 12, '4 rounds alternando lados.'), D('Tático', 'Clinch', 15, 'Controlo de pescoço e joelhadas com parceiro.'), D('Físico', 'Condicionamento', 12, 'Joelhadas rápidas 30 s × 8.'), D('Mental', 'Ritmo de luta', 5, 'Alterna 3 velocidades na sombra para controlar o ritmo.')] },
  surf: { n: 'Surf', ic: 'wave', c: '#0ea5e9', met: 5, info: 'Apanhar ondas numa prancha: remada, take-off e manobras. Portugal tem ondas incríveis o ano inteiro.', ben: ['Ombros e costas fortes', 'Equilíbrio', 'Contacto com a natureza'], mus: 'Dorsais, ombros, core, pernas', inj: [['Ombro', 'remada técnica e reforço'], ['Cortes e pancadas', 'leash e respeitar as regras de prioridade']], gear: 'Prancha adequada ao nível, fato isotérmico, leash, parafina', aq: ['Mobilidade de ombro e anca', 'Pop-ups na areia 10×', 'Corrida leve'],
    pos: ['Shortboard', 'Longboard', 'Bodyboard'], st: [['ondas', 'Ondas apanhadas'], ['melhor', 'Melhor onda (1–10)']],
    dr: [D('Técnica', 'Pop-up em terra', 10, '30 pop-ups rápidos e silenciosos.'), D('Físico', 'Remada em piscina', 20, 'Intervalos de 1 min forte, 30 s parado.'), D('Físico', 'Equilíbrio', 10, 'Balance board ou unipodal 3×1 min.'), D('Tático', 'Ler o mar', 10, 'Observa 10 min: séries, picos e correntes antes de entrar.'), D('Mental', 'Calma no inside', 5, 'Respiração lenta depois de levar uma série na cabeça.')] },
  escalada: { n: 'Escalada', ic: 'mountain', c: '#d97706', met: 8, info: 'Subir paredes em bloco (boulder), via desportiva ou ao ar livre. Força de dedos, técnica de pés e resolução de problemas.', ben: ['Força relativa e pega', 'Mobilidade', 'Concentração'], mus: 'Antebraços, dorsais, bíceps, core', inj: [['Polias dos dedos', 'progressão lenta e evitar crimp total'], ['Cotovelo', 'antagonistas (flexões)']], gear: 'Pés de gato, magnésio, arnês e corda (vias)', aq: ['Mobilidade de ombros', 'Travessias fáceis 5 min', 'Pendurar com pés no chão'],
    pos: ['Bloco', 'Desportiva', 'Clássica'], st: [['vias', 'Vias/blocos'], ['grau', 'Grau máximo']],
    dr: [D('Técnica', 'Pés silenciosos', 10, 'Escala vias fáceis sem fazer barulho com os pés.'), D('Físico', 'Hangboard', 15, '7 s pendurado / 3 s descanso × 6, 3 séries (só a partir de nível intermédio).'), D('Técnica', 'Repetir o projeto por secções', 20, 'Divide o bloco em movimentos e liga-os.'), D('Mental', 'Queda controlada', 5, 'Pratica quedas para perder o medo.')] },
  crossfit: { n: 'CrossFit', ic: 'dumbbell', c: '#f43f5e', met: 8, info: 'Treino funcional de alta intensidade: levantamentos olímpicos, ginástica e metcons.', ben: ['Condição física geral', 'Força e potência', 'Comunidade'], mus: 'Corpo inteiro', inj: [['Lombar', 'técnica antes de carga'], ['Ombro', 'escala os kipping']], gear: 'Sapatilhas planas, cinto opcional, corda', aq: ['Remo 5 min', 'Mobilidade', 'Barra vazia progressiva'],
    pos: ['Scaled', 'RX'], st: [['wod', 'WOD (tempo/reps)'], ['rpeW', 'Peso máximo (kg)']],
    dr: [D('Técnica', 'Snatch com barra vazia', 10, 'Posições: hang, power, full.'), D('Físico', 'EMOM 12', 12, 'Min ímpar: 10 burpees; par: 15 kettlebell swings.'), D('Técnica', 'Double unders', 10, 'Tentativas em blocos de 30 s.'), D('Mental', 'Dividir o WOD', 5, 'Parte em blocos pequenos antes de começar.')] },
  calistenia: { n: 'Calistenia', ic: 'dumbbell', c: '#14b8a6', met: 6, info: 'Treino com o peso do corpo: flexões, elevações, dips, pino, alavancas.', ben: ['Força relativa', 'Controlo do corpo', 'Treinar em qualquer lado'], mus: 'Peito, costas, ombros, core', inj: [['Punhos', 'aquecer e reforçar'], ['Cotovelo', 'progressão gradual']], gear: 'Barra, paralelas, elásticos', aq: ['Mobilidade de punhos e ombros', 'Scapula pulls', 'Flexões fáceis'],
    pos: ['Iniciante', 'Intermédio', 'Avançado'], st: [['flex', 'Máx. flexões'], ['elev', 'Máx. elevações'], ['dips', 'Máx. dips']],
    dr: [D('Técnica', 'Pino contra a parede', 10, '5×30 s de barriga para a parede.'), D('Físico', 'Elevações negativas', 10, '5×3 descidas de 5 s.'), D('Físico', 'Ladder de flexões', 10, '1-2-3-4-5-4-3-2-1 com 10 s.'), D('Técnica', 'Tuck front lever', 10, '6×10 s.')] }
};
const KEYS = Object.keys(SPORTS);
const OTHER = { n: 'Outro', ic: 'target', c: '#94a3b8', met: 6, info: 'Desporto personalizado.', ben: [], mus: '', inj: [], gear: '', aq: ['Aquecimento geral 5–10 min', 'Mobilidade das articulações usadas', 'Gestos do desporto a baixa intensidade'], pos: [], st: [['pontos', 'Pontos/estatística']], dr: [] };
const SPI = { ball: 'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zM12 7l3.8 2.8-1.5 4.5H9.7L8.2 9.8z', racket: 'M14.5 3.5a6 6 0 0 1 0 8.5 6 6 0 0 1-8.5 0 6 6 0 0 1 8.5-8.5zM6 12l-3 6 1 1 6-3', bike: 'M5.5 17.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7zM18.5 17.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7zM5.5 14l4-6h5l4 6M9.5 8 12 14h-6.5M14 5h3', shield: 'M12 3l7 3v6c0 4.5-3 7.5-7 9-4-1.5-7-4.5-7-9V6z', target: 'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zM12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8z' };
const ico = (k, cls = '') => SPI[k] ? `<svg class="ic ${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="${SPI[k]}"/></svg>` : UI.ic(k, cls);
const cat = s => (s && SPORTS[s.key]) || Object.assign({}, OTHER, { n: (s && s.name) || 'Outro' });
const LEV = ['Iniciante', 'Intermédio', 'Avançado', 'Competição'];
OS.S.sports = { label: 'Desporto', title: r => r.name || cat(r).n, fields: [
  { k: 'key', l: 'Desporto', t: 'sel', o: () => KEYS.map(k => [k, SPORTS[k].n]).concat([['outro', 'Outro']]) }, { k: 'name', l: 'Nome (se for outro)', t: 'text' },
  { k: 'level', l: 'Nível', t: 'sel', o: LEV }, { k: 'pos', l: 'Posição / estilo / faixa', t: 'text' }, { k: 'club', l: 'Clube / equipa / ginásio', t: 'text' }, { k: 'since', l: 'Pratico desde', t: 'date' },
  { k: 'freq', l: 'Vezes por semana (objetivo)', t: 'num' }, { k: 'goal', l: 'Objetivo', t: 'area', rows: 2 }, { k: 'notes', l: 'Notas', t: 'area', rows: 2 }], defaults: () => ({ level: 'Iniciante', freq: 2 }) };
OS.S.sportlog = { label: 'Prática', title: r => (OS.get('sports', r.sport) ? cat(OS.get('sports', r.sport)).n : 'Prática') + ' · ' + U.fmtD(r.date), fields: [
  { k: 'sport', l: 'Desporto', t: 'sel', o: () => OS.all('sports').map(s => [s.id, s.name || cat(s).n]), req: 1 }, { k: 'date', l: 'Data', t: 'date', req: 1 }, { k: 'kind', l: 'Tipo', t: 'sel', o: ['Treino', 'Jogo', 'Competição', 'Aula', 'Treino específico', 'Lazer'] },
  { k: 'mins', l: 'Minutos', t: 'num' }, { k: 'rpe', l: 'Esforço (RPE 1–10)', t: 'num' }, { k: 'res', l: 'Resultado', t: 'sel', o: ['', 'Vitória', 'Empate', 'Derrota'] }, { k: 'score', l: 'Marcador', t: 'text' }, { k: 'notes', l: 'Notas', t: 'area', rows: 2 }], defaults: () => ({ date: today(), kind: 'Treino', mins: 60, rpe: 6 }) };

const weightKg = () => { const r = U.sortBy(OS.all('body').filter(b => +b.weight), b => b.date).pop(); return r ? +r.weight : 75; };
// Corrida: as práticas vêm automaticamente da aba Corrida (coleção runs)
const runLogs = sid => OS.all('runs').map(r => { const sec = U.parseDur(r.time) || 0, km = U.num(r.km), pace = km && sec ? sec / km / 60 : 0; return { id: 'run_' + r.id, virtual: 1, edit: 'runs:' + r.id, sport: sid, date: r.date, kind: r.type || 'Corrida', mins: Math.round(sec / 60), rpe: r.feel ? Math.min(10, +r.feel * 2) : '', st: Object.assign({ km: U.r2(km) }, pace ? { ritmo: Math.round(pace * 100) / 100 } : {}, U.num(r.elev) ? { desnivel: U.num(r.elev) } : {}), notes: r.notes || '', _c: r._c }; });
const isRun = s => s && s.key === 'corrida';
const allLogs = () => OS.all('sportlog').concat(...OS.all('sports').filter(isRun).map(s => runLogs(s.id)));
const logs = id => { const s = OS.get('sports', id); return U.sortBy(OS.all('sportlog').filter(l => l.sport === id).concat(isRun(s) ? runLogs(id) : []), l => l.date + (l._c || 0), -1); };
const kcal = (s, mins) => Math.round(cat(s).met * weightKg() * (+mins || 0) / 60);
const weekOf = d => U.monday(d);

/* ---------- vistas ---------- */
V.desporto = sub => { const id = OS.ui.spId, s = sub === 'sp' && OS.get('sports', id);
  const head = UI.head('Desporto', 'Os desportos que praticas: informação, as tuas práticas e estatísticas, treinos específicos para melhorar e ajuda para evitar lesões.', `<button class="btn pri" data-act="spAddPick">${UI.ic('plus')}<span>Desporto</span></button>`, 'Corpo');
  if (sub === 'novo') return head + pickView();
  if (s) return head + sportView(s);
  return head + UI.tabs('desporto', [['', 'Os meus desportos'], ['stats', 'Estatísticas'], ['novo', 'Adicionar desporto']], sub || '') + (sub === 'stats' ? statsView() : homeView()); };
A.spAddPick = () => { location.hash = 'desporto.novo'; };
const pickView = () => { const mine = OS.all('sports').map(s => s.key);
  return `<a class="btn xs ghost" href="#desporto" style="margin-bottom:10px">← Os meus desportos</a><div class="sp-pick">${KEYS.map(k => { const c = SPORTS[k], has = mine.includes(k); return `<button class="sp-pc ${has ? 'has' : ''}" style="--sc:${c.c}" data-act="spAdd" data-k="${k}"><span class="sp-pi">${ico(c.ic)}</span><b>${c.n}</b><small>${has ? '✓ já praticas' : esc(c.info.split('.')[0])}</small></button>`; }).join('')}<button class="sp-pc" style="--sc:#94a3b8" data-act="spAdd" data-k="outro"><span class="sp-pi">${ico('target')}</span><b>Outro desporto</b><small>Escreve o nome do teu desporto</small></button></div>`; };
A.spAdd = b => { const k = b.dataset.k; if (k === 'outro') { const n = prompt('Qual é o desporto?', ''); if (!n) return; const s = OS.add('sports', { key: 'outro', name: n.trim(), level: 'Iniciante', freq: 2, since: today() }); return A.spOpen({ dataset: { id: s.id } }); }
  const ex = OS.all('sports').find(s => s.key === k); if (ex) return A.spOpen({ dataset: { id: ex.id } }); const s = OS.add('sports', { key: k, level: 'Iniciante', freq: 2, since: today() }); UI.toast(SPORTS[k].n + ' adicionado ✓', 'pos'); A.spOpen({ dataset: { id: s.id } }); };
A.spOpen = b => { OS.setUI('spId', b.dataset.id); OS.setUI('spTab', ''); location.hash = 'desporto.sp'; };
const homeView = () => { const S = OS.all('sports'), wk = weekOf(today());
  if (!S.length) return `<div class="pn sp-empty"><h3>Que desportos praticas?</h3><p class="mut">Futebol, padel, jiu-jitsu, natação… Adiciona os teus para registares treinos e jogos, veres estatísticas e teres treinos específicos para melhorar.</p><a class="btn pri" href="#desporto.novo">Escolher desportos</a></div>`;
  return `<div class="sp-grid">${S.map(s => { const c = cat(s), L = logs(s.id), w = L.filter(l => l.date >= wk).length, f = +s.freq || 0, last = L[0], h = U.sum(L, l => +l.mins || 0) / 60;
    return `<div class="sp-card" style="--sc:${c.c}" data-act="spOpen" data-id="${s.id}" role="button" tabindex="0"><div class="sp-ch"><span class="sp-pi">${ico(c.ic)}</span><div><b>${esc(s.name || c.n)}</b><small>${esc([s.level, s.pos, s.club].filter(Boolean).join(' · '))}</small></div></div>
      <div class="sp-cw"><span>Esta semana</span><b>${w}${f ? ' / ' + f : ''}</b></div>${f ? UI.bar(Math.min(1, w / f), w >= f ? 'pos' : '') : ''}<div class="sp-cs"><span><b>${L.length}</b> práticas</span><span><b>${U.nf(h, h < 10 ? 1 : 0)}</b> h</span><span>${last ? 'última ' + U.rel(last.date) : 'sem registos'}</span></div></div>`; }).join('')}
    <a class="sp-card sp-add" href="#desporto.novo">${UI.ic('plus')}<b>Adicionar desporto</b></a></div>
  <div class="pn"><div class="pn-h"><h3>Últimas práticas</h3>${UI.addBtn('sportlog', 'Registar prática', { sport: S[0].id }, 'sm')}</div>${(() => { const L = U.sortBy(allLogs(), l => l.date + (l._c || 0), -1).slice(0, 8); return L.length ? `<div class="list">${L.map(logRow).join('')}</div>` : UI.empty('Ainda sem práticas registadas.'); })()}</div>`; };
const logRow = l => { const s = OS.get('sports', l.sport), c = cat(s), st = Object.entries(l.st || {}).filter(([, v]) => v !== '' && v != null).map(([k, v]) => `${(c.st.find(x => x[0] === k) || [, k])[1]} ${v}`).slice(0, 3).join(' · ');
  return `<div class="li click" data-edit="${l.edit || 'sportlog:' + l.id}"><span class="sp-dot" style="--sc:${c.c}">${ico(c.ic)}</span><div class="li-t"><b>${esc((s && (s.name || c.n)) || 'Desporto')} · ${esc(l.kind || 'Treino')}${l.res ? ` · <span class="${l.res === 'Vitória' ? 'pos' : l.res === 'Derrota' ? 'neg' : ''}">${l.res}${l.score ? ' ' + esc(l.score) : ''}</span>` : ''}</b><small>${U.fmtD(l.date)} · ${l.mins || 0} min${l.rpe ? ' · RPE ' + l.rpe : ''}${st ? ' · ' + esc(st) : ''}</small></div><span class="mono mut">${kcal(s, l.mins)} kcal</span></div>`; };

const STABS = [['', 'Resumo'], ['registar', 'Registar prática'], ['treinos', 'Treinos para melhorar'], ['sobre', 'Sobre o desporto'], ['ajuda', 'Auxílios'], ['coach', 'Treinador IA']];
const sportView = s => { const c = cat(s), t = OS.ui.spTab || '';
  return `<a class="btn xs ghost" href="#desporto" style="margin-bottom:10px">← Os meus desportos</a>
  <div class="sp-hero" style="--sc:${c.c}"><span class="sp-pi lg">${ico(c.ic)}</span><div class="grow"><h2>${esc(s.name || c.n)}</h2><p>${esc([s.level, s.pos, s.club, s.since ? 'desde ' + U.fmtD(s.since) : ''].filter(Boolean).join(' · ') || 'Define o teu nível, posição e clube')}</p>${s.goal ? `<p class="sp-goal">${esc(s.goal)}</p>` : ''}</div><button class="btn sm ghost" data-edit="sports:${s.id}">Editar</button></div>
  <div class="tabs" role="tablist">${STABS.map(([k, l]) => `<a href="javascript:void 0" class="${t === k ? 'on' : ''}" data-act="spTab" data-v="${k}">${l}</a>`).join('')}</div>${(SV[t] || SV[''])(s, c)}`; };
A.spTab = b => OS.setUI('spTab', b.dataset.v);
const SV = {};
SV[''] = (s, c) => { const L = logs(s.id), t = today(), m30 = U.addDays(t, -29), L30 = L.filter(l => l.date >= m30), games = L.filter(l => l.res), wins = games.filter(l => l.res === 'Vitória').length, wks = Array.from({ length: 12 }, (_, i) => U.addDays(weekOf(t), -7 * (11 - i)));
  const tot = {}; L.forEach(l => Object.entries(l.st || {}).forEach(([k, v]) => { if (v === '' || v == null || isNaN(+v)) return; (tot[k] = tot[k] || []).push(+v); }));
  const sk = OS.ui.spStat && tot[OS.ui.spStat] ? OS.ui.spStat : Object.keys(tot)[0], series = sk ? L.filter(l => l.st && l.st[sk] !== '' && l.st[sk] != null && !isNaN(+l.st[sk])).slice(0, 20).reverse() : [];
  return `<div class="kpis">${UI.kpi('Práticas (30 dias)', L30.length, U.hours(U.sum(L30, l => +l.mins || 0)))}${UI.kpi('Total', L.length, U.nf(U.sum(L, l => +l.mins || 0) / 60, 1) + ' h')}${games.length ? UI.kpi('Vitórias', U.pct(wins / games.length), `${wins}V ${games.filter(l => l.res === 'Empate').length}E ${games.filter(l => l.res === 'Derrota').length}D`, { tone: wins / games.length >= .5 ? 'pos' : '' }) : UI.kpi('Esforço médio', L.length ? U.nf(U.avg(L.filter(l => l.rpe), l => +l.rpe), 1) : '—', 'RPE 1–10')}${UI.kpi('Calorias (30 dias)', U.nf(U.sum(L30, l => kcal(s, l.mins))), 'estimativa · ' + weightKg() + ' kg')}</div>
  ${Object.keys(tot).length ? `<div class="sp-tot">${c.st.filter(([k]) => tot[k]).map(([k, l]) => { const a = tot[k], sum = U.sum(a, x => x), avg = sum / a.length, isMax = /máx|melhor|grau|ritmo|vel|%|peso/i.test(l); const best = /ritmo/i.test(l) ? Math.min(...a) : Math.max(...a); return `<button class="sp-tv ${k === sk ? 'on' : ''}" data-act="spStat" data-k="${k}"><small>${esc(l)}</small><b>${isMax ? U.nf(best, /ritmo/i.test(l) ? 2 : 1) : U.nf(sum, k === 'km' ? 1 : 0)}</b><em>${isMax ? 'melhor' : 'total · ' + U.nf(avg, 1) + '/prática'}</em></button>`; }).join('')}</div>` : ''}
  <div class="g g2"><div class="pn"><div class="pn-h"><h3>Minutos por semana</h3></div>${C.mount({ type: 'bar', labels: wks.map(w => U.fmtDS(w)), series: [{ name: 'Minutos', data: wks.map(w => U.sum(L.filter(l => l.date >= w && l.date <= U.addDays(w, 6)), l => +l.mins || 0)), color: c.c }], target: (+s.freq || 0) * 60 || null, empty: 'Regista práticas para ver a evolução.' }, 190)}</div>
    <div class="pn"><div class="pn-h"><h3>${sk ? esc((c.st.find(x => x[0] === sk) || [, sk])[1]) + ' por prática' : 'Estatística'}</h3></div>${series.length ? C.mount({ type: 'line', labels: series.map(l => U.fmtDS(l.date)), series: [{ name: (c.st.find(x => x[0] === sk) || [, sk])[1], data: series.map(l => +l.st[sk]), color: c.c }] }, 190) : UI.empty('Regista as tuas estatísticas em "Registar prática".')}</div></div>
  <div class="pn"><div class="pn-h"><h3>Histórico</h3><button class="btn sm" data-act="spTab" data-v="registar">${UI.ic('plus')}Registar</button></div>${L.length ? `<div class="list">${L.slice(0, 30).map(logRow).join('')}</div>` : UI.empty('Ainda sem práticas.')}</div>`; };
A.spStat = b => OS.setUI('spStat', b.dataset.k);
SV.registar = (s, c) => isRun(s) ? `<div class="pn"><p class="sp-p">As tuas corridas entram aqui <b>automaticamente</b> a partir da aba <a href="#corrida">Corrida</a> — km, tempo, ritmo e desnível. Regista lá (ou aqui) e fica tudo junto.</p><div class="row gap8">${UI.addBtn('runs', 'Registar corrida')}<a class="btn ghost" href="#corrida">Abrir Corrida</a></div></div>` : `<form class="pn sp-form" data-form="spLog" data-id="${s.id}"><div class="sp-fg">
    <label>Data<input class="field" type="date" name="date" value="${today()}"></label><label>Tipo<select class="field" name="kind">${['Treino', 'Jogo', 'Competição', 'Aula', 'Treino específico', 'Lazer'].map(k => `<option>${k}</option>`).join('')}</select></label>
    <label>Minutos<input class="field" type="number" name="mins" value="60" min="1"></label><label>Esforço (RPE 1–10)<input class="field" type="number" name="rpe" value="6" min="1" max="10"></label>
    ${c.comp ? `<label>Resultado<select class="field" name="res"><option value="">—</option><option>Vitória</option><option>Empate</option><option>Derrota</option></select></label><label>Marcador<input class="field" name="score" placeholder="ex.: 3-1, 6-4 6-3"></label>` : ''}
    ${c.st.map(([k, l]) => `<label>${esc(l)}<input class="field" name="st_${k}" ${/grau|wod/i.test(l) ? '' : 'type="number" step="any"'}></label>`).join('')}
    <label>Como me senti<select class="field" name="feel">${['', 'Mal', 'Normal', 'Bem', 'Excelente'].map(x => `<option>${x}</option>`).join('')}</select></label></div>
    ${c.dr.length ? `<div class="eyebrow" style="margin-top:10px">Treinos específicos que fiz</div><div class="fe-chs">${c.dr.map((d, i) => `<label class="chip"><input type="checkbox" name="dr" value="${i}" style="margin-right:4px">${esc(d.t)}</label>`).join('')}</div>` : ''}
    <textarea class="field" name="notes" rows="2" placeholder="Notas: o que correu bem, o que melhorar…" style="width:100%;margin-top:10px"></textarea><button class="btn pri" style="margin-top:10px">Guardar prática</button></form>`;
OS.forms = OS.forms || {};
OS.forms.spLog = (f, v) => { const s = OS.get('sports', f.dataset.id); if (!s) return; const c = cat(s), st = {}; c.st.forEach(([k]) => { const x = v('st_' + k); if (x !== '') st[k] = isNaN(+x) ? x : +x; });
  OS.add('sportlog', { sport: s.id, date: v('date') || today(), kind: v('kind'), mins: +v('mins') || 0, rpe: +v('rpe') || '', res: v('res') || '', score: v('score') || '', st, feel: v('feel'), notes: v('notes'), drills: [...f.querySelectorAll('input[name=dr]:checked')].map(x => c.dr[+x.value].t) });
  UI.toast('Prática registada', 'pos'); OS.setUI('spTab', ''); };
SV.treinos = (s, c) => { const by = U.groupBy(c.dr, d => d.f), done = {}; logs(s.id).forEach(l => (l.drills || []).forEach(t => done[t] = (done[t] || 0) + 1)); const plan = weekPlan(s, c);
  return `${plan.length ? `<div class="pn"><div class="pn-h"><h3>Plano desta semana (${plan.length}×)</h3><button class="btn sm pri" data-act="spPlan" data-id="${s.id}">Pôr nas tarefas</button></div><div class="sp-plan">${plan.map((p, i) => `<div class="sp-pd"><b>Sessão ${i + 1} · ${p.title}</b><small>${U.WDS[U.parse(p.d).getDay()]} ${+p.d.slice(8)} · ${U.sum(p.items, d => d.m)} min</small>${p.items.map(d => `<div class="sp-pi2">• ${esc(d.t)} <span class="mut">${d.m} min</span></div>`).join('')}</div>`).join('')}</div></div>` : ''}
  ${Object.entries(by).map(([f, ds]) => `<section><div class="sech"><h2>${f}</h2></div><div class="g g2">${ds.map(d => `<div class="pn sp-dr"><div class="row between gap8"><b>${esc(d.t)}</b><span class="bdg out">${d.m} min</span></div><p>${esc(d.d)}</p><small class="mut">${done[d.t] ? `feito ${done[d.t]}×` : 'ainda não fizeste'}</small></div>`).join('')}</div></section>`).join('') || UI.empty('Para desportos personalizados, pergunta ao Treinador IA por treinos específicos.')}`; };
const weekPlan = (s, c) => { const n = Math.max(1, Math.min(5, +s.freq || 2)), byF = U.groupBy(c.dr, d => d.f), pickF = (f, k) => (byF[f] || []).slice(k % Math.max(1, (byF[f] || []).length)).concat(byF[f] || []).slice(0, 1), mon = weekOf(today()), days = [[0], [0, 3], [0, 2, 4], [0, 1, 3, 5], [0, 1, 2, 4, 5]][n - 1];
  if (!c.dr.length) return []; return days.map((dd, i) => { const items = i % 3 === 0 ? [...pickF('Técnica', i), ...pickF('Técnica', i + 1), ...pickF('Físico', i)] : i % 3 === 1 ? [...pickF('Tático', i), ...pickF('Físico', i + 1), ...pickF('Mental', i)] : [...pickF('Técnica', i + 2), ...pickF('Tático', i + 1)];
    return { d: U.addDays(mon, dd), title: i % 3 === 0 ? 'técnica + físico' : i % 3 === 1 ? 'tática + físico' : 'técnica + jogo', items: items.filter((x, j, a) => x && a.indexOf(x) === j) }; }); };
A.spPlan = b => { const s = OS.get('sports', b.dataset.id), c = cat(s); weekPlan(s, c).filter(p => p.d >= today()).forEach(p => OS.add('tasks', { title: `${s.name || c.n}: ${p.title}`, sched: p.d, status: 'Próxima', prio: '3', area: 'Saúde', notes: p.items.map(d => `${d.t} (${d.m} min) — ${d.d}`).join('\n'), effort: String(U.sum(p.items, d => d.m)), sportPlan: s.id }, { silent: true })); OS.request(); UI.toast('Plano posto nas tarefas desta semana', 'pos'); };
SV.sobre = (s, c) => `<div class="g g2"><div class="pn"><div class="pn-h"><h3>O que é</h3></div><p class="sp-p">${esc(c.info)}</p>${c.link ? `<a class="btn sm" href="#${c.link}">Abrir o módulo ${esc(c.n)}</a>` : ''}</div>
    <div class="pn"><div class="pn-h"><h3>Benefícios</h3></div><ul class="sp-ul">${c.ben.map(x => `<li>${esc(x)}</li>`).join('') || '<li>—</li>'}</ul></div>
    <div class="pn"><div class="pn-h"><h3>Músculos e gasto</h3></div><p class="sp-p">${esc(c.mus || '—')}</p><p class="sp-p">≈ <b>${kcal(s, 60)} kcal por hora</b> <span class="mut">(MET ${c.met} · ${weightKg()} kg)</span></p></div>
    <div class="pn"><div class="pn-h"><h3>Equipamento</h3></div><p class="sp-p">${esc(c.gear || '—')}</p>${c.pos.length ? `<div class="eyebrow" style="margin-top:8px">Posições / estilos</div><div class="fe-chs">${c.pos.map(p => `<span class="chip ${s.pos === p ? 'on' : ''}" data-act="spPos" data-id="${s.id}" data-v="${esc(p)}" role="button">${esc(p)}</span>`).join('')}</div>` : ''}</div></div>`;
A.spPos = b => { OS.upd('sports', b.dataset.id, { pos: b.dataset.v }); UI.toast('Posição: ' + b.dataset.v, 'pos'); };
SV.ajuda = (s, c) => `<div class="g g2"><div class="pn"><div class="pn-h"><h3>Aquecimento (10 min)</h3></div><ol class="sp-ul">${c.aq.map(x => `<li>${esc(x)}</li>`).join('')}</ol></div>
    <div class="pn"><div class="pn-h"><h3>Prevenir lesões</h3></div>${c.inj.length ? c.inj.map(([l, p]) => `<div class="sp-inj"><b>${esc(l)}</b><small>${esc(p)}</small></div>`).join('') : '<p class="mut">Reforço muscular 2×/semana, aquecimento e sono.</p>'}</div>
    <div class="pn"><div class="pn-h"><h3>Alimentação e hidratação</h3></div><ul class="sp-ul"><li><b>Antes (2–3 h):</b> refeição com hidratos (arroz, massa, pão) e pouca gordura.</li><li><b>Durante:</b> água; acima de 60–75 min, bebida com hidratos/eletrólitos.</li><li><b>Depois (até 2 h):</b> proteína (≈${Math.round(weightKg() * .3)} g) + hidratos para recuperar.</li><li>Bebe ~${Math.round(weightKg() * 35 / 100) / 10} L de água por dia, mais 500 ml por hora de treino.</li></ul></div>
    <div class="pn"><div class="pn-h"><h3>Recuperação e mente</h3></div><ul class="sp-ul"><li>Dorme 7–9 h: é quando o corpo se adapta ao treino.</li><li>Depois de um esforço RPE ≥ 8, faz um dia leve ou de descanso.</li><li>Alongamentos e mobilidade 10 min ao fim do dia.</li><li>Antes de jogos: rotina fixa, visualização e respiração 4-7.</li><li>Dor aguda, inchaço ou dor que piora → para e consulta um fisioterapeuta/médico.</li></ul></div></div>`;
let CO = { busy: false };
SV.coach = (s, c) => { const k = 'oc_spcoach_' + s.id, last = U.ls.get(k, null), hasAI = OS.AI && OS.AI.key && OS.AI.key();
  return `${hasAI ? '' : `<div class="pn">${OS.AI && OS.AI.setup ? OS.AI.setup('') : ''}</div>`}<form class="pn col gap8" data-form="spCoach" data-id="${s.id}"><b>O que queres melhorar?</b><textarea class="field" name="q" rows="3" placeholder="Ex.: quero marcar mais golos e ter mais resistência no 2.º tempo; tenho jogo daqui a 3 semanas">${esc((last && last.q) || '')}</textarea><button class="btn pri" ${CO.busy || !hasAI ? 'disabled' : ''}>${CO.busy ? 'O treinador está a analisar…' : 'Pedir plano ao treinador IA'}</button></form>
  ${last && last.o ? `<div class="pn sp-coach"><h3>${esc(last.o.titulo || 'Plano')}</h3>${last.o.analise ? `<p class="sp-p">${esc(last.o.analise)}</p>` : ''}${(last.o.semanas || []).map(w => `<div class="sp-w"><b>${esc(w.semana || '')} — ${esc(w.foco || '')}</b><ul class="sp-ul">${(w.sessoes || []).map(x => `<li>${esc(x)}</li>`).join('')}</ul></div>`).join('')}${(last.o.dicas || []).length ? `<div class="eyebrow">Dicas</div><ul class="sp-ul">${last.o.dicas.map(x => `<li>${esc(x)}</li>`).join('')}</ul>` : ''}<small class="mut">${new Date(last.at).toLocaleString('pt-PT')}</small></div>` : ''}${last && last.err ? `<p class="neg">${esc(last.err)}</p>` : ''}`; };
OS.forms.spCoach = async (f, v) => { if (CO.busy) return; const s = OS.get('sports', f.dataset.id), c = cat(s), q = f.elements.q.value.trim(), k = 'oc_spcoach_' + s.id; if (!q) return UI.toast('Escreve o que queres melhorar', 'neg'); CO.busy = true; OS.request();
  const L = logs(s.id).slice(0, 15).map(l => ({ data: l.date, tipo: l.kind, min: l.mins, rpe: l.rpe, res: l.res, stats: l.st, treinos: l.drills, notas: l.notes }));
  try { const o = await OS.AI.json([{ text: `És um treinador de ${c.n} experiente e cuidadoso com lesões. Atleta: Ryan, ${weightKg()} kg, nível ${s.level || '—'}, posição/estilo ${s.pos || '—'}, objetivo "${s.goal || ''}", treina ~${s.freq || 2}×/semana. Últimas práticas: ${JSON.stringify(L)}.
Pedido: "${q}". Cria um plano prático de 4 semanas em português de Portugal, específico deste desporto, com sessões concretas (exercícios, séries/tempo), progressão e uma análise curta do que os dados mostram. Não inventes dados. JSON: {"titulo":"…","analise":"…","semanas":[{"semana":"Semana 1","foco":"…","sessoes":["…"]}],"dicas":["…"]}` }], .5);
    U.ls.set(k, { q, o, at: Date.now() }); } catch (e) { U.ls.set(k, { q, err: e.message || 'Erro da IA', at: Date.now() }); } CO.busy = false; OS.request(); };

const statsView = () => { const S = OS.all('sports'), L = allLogs(), t = today(), wks = Array.from({ length: 12 }, (_, i) => U.addDays(weekOf(t), -7 * (11 - i)));
  if (!L.length) return UI.empty('As estatísticas aparecem quando registares práticas.');
  return `<div class="kpis">${UI.kpi('Práticas', L.length)}${UI.kpi('Horas', U.nf(U.sum(L, l => +l.mins || 0) / 60, 1))}${UI.kpi('Este mês', L.filter(l => l.date.slice(0, 7) === t.slice(0, 7)).length)}${UI.kpi('Calorias (estim.)', U.nf(U.sum(L, l => kcal(OS.get('sports', l.sport), l.mins))))}</div>
  <div class="g g2"><div class="pn"><div class="pn-h"><h3>Horas por desporto</h3></div>${C.mount({ type: 'donut', data: S.map(s => ({ l: s.name || cat(s).n, v: U.sum(L.filter(l => l.sport === s.id), l => +l.mins || 0) / 60, c: cat(s).c })).filter(x => x.v), fmt: v => U.nf(v, 1) + ' h', centerSub: 'horas' }, 210)}</div>
    <div class="pn"><div class="pn-h"><h3>Práticas por semana</h3></div>${C.mount({ type: 'bar', labels: wks.map(w => U.fmtDS(w)), series: [{ name: 'Práticas', data: wks.map(w => L.filter(l => l.date >= w && l.date <= U.addDays(w, 6)).length), color: 'var(--accent)' }] }, 210)}</div></div>`; };

/* práticas no calendário */
if (OS.Cal && OS.Cal.items) { const _it = OS.Cal.items; OS.Cal.items = (from, to) => { const out = _it(from, to); OS.all('sportlog').forEach(l => { if (l.date >= from && l.date <= to) { const s = OS.get('sports', l.sport); out.push({ date: l.date, title: (s ? s.name || cat(s).n : 'Desporto') + ' · ' + (l.kind || 'Treino'), src: 'workout', done: true, edit: 'sportlog:' + l.id, sub: (l.mins || 0) + ' min' }); } }); return out.sort((a, b) => (a.date + (a.start || '99')).localeCompare(b.date + (b.start || '99'))); }; }
OS.on('ready', () => { if (OS.all('runs').length && !OS.all('sports').some(isRun)) OS.add('sports', { key: 'corrida', level: 'Intermédio', freq: +(OS.one('profile').runKmTarget ? 3 : 2), since: U.sortBy(OS.all('runs'), r => r.date)[0].date, auto: 1 }, { silent: true }); });
OS.Sport = { SPORTS, weekPlan, kcal, logs };
})();
