/* OCEANUM — Estudos: Cursos · Certificações · Leituras.
   Leituras = estante virtual: pesquisa em todos os livros (Google Books + Open Library), Quero ler / A ler / Lido / Abandonado,
   progresso por página, nota, resenha, citações, categorias, a minha estante (físico, ebook, audiolivro; emprestar, doar, vender, trocar),
   desafios literários e estatísticas. */
(() => {
'use strict';
const U = OS.U, UI = OS.UI, C = OS.C, V = OS.views, A = OS.act, esc = U.esc, today = () => U.today();
const norm = s => String(s || '').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^a-z0-9 ]/g, ' ').replace(/\s+/g, ' ').trim();

/* ================= coleções ================= */
const BST = ['Quero ler', 'A ler', 'Lido', 'Abandonado'];
const BIC = { 'Quero ler': '', 'A ler': '', 'Lido': '', 'Abandonado': '' };
const GEN = ['Romance', 'Ficção', 'Fantasia', 'Ficção científica', 'Clássico', 'Literatura brasileira', 'Literatura portuguesa', 'Infantojuvenil', 'Poesia', 'Biografia', 'História', 'Filosofia', 'Cristão / Teologia', 'Autoajuda', 'Desenvolvimento pessoal', 'Negócios', 'Finanças', 'Economia', 'Psicologia', 'Ciência', 'Tecnologia', 'Policial / Suspense', 'Terror', 'Aventura', 'HQ / Mangá', 'Política', 'Educação', 'Saúde', 'Arte', 'Outro'];
const FMT = ['Físico', 'Ebook', 'Audiolivro'];
const OWN = ['Não tenho', 'Tenho', 'Emprestei', 'Pedi emprestado', 'Biblioteca', 'Para doar', 'Doado', 'Vendido', 'Trocado'];
const OWNED = o => ['Tenho', 'Emprestei', 'Para doar'].includes(o);
OS.S.books = { label: 'Livro', title: r => r.title, fields: [
  { k: 'title', l: 'Título', t: 'text', req: 1 }, { k: 'subtitle', l: 'Subtítulo', t: 'text' }, { k: 'author', l: 'Autor(es)', t: 'text' },
  { k: 'status', l: 'Estado', t: 'sel', o: BST }, { k: 'pages', l: 'Páginas', t: 'num' }, { k: 'curPage', l: 'Página atual', t: 'num', show: r => r.status === 'A ler' },
  { k: 'start', l: 'Comecei', t: 'date' }, { k: 'end', l: 'Terminei / parei', t: 'date', show: r => ['Lido', 'Abandonado'].includes(r.status) },
  { k: 'cats', l: 'Categorias', t: 'tags', h: GEN.join(', ') }, { k: 'rating', l: 'Nota (1–5 estrelas)', t: 'rating' },
  { k: 'own', l: 'Na minha estante?', t: 'sel', o: OWN }, { k: 'format', l: 'Formato', t: 'sel', o: FMT }, { k: 'where', l: 'Onde está / a quem', t: 'text', h: 'Ex.: estante do quarto, Kindle, emprestado ao João' },
  { k: 'publisher', l: 'Editora', t: 'text' }, { k: 'year', l: 'Ano', t: 'text' }, { k: 'isbn', l: 'ISBN', t: 'text' }, { k: 'cover', l: 'Capa (link da imagem)', t: 'text' },
  { k: 'desc', l: 'Sinopse', t: 'area', rows: 4 }, { k: 'review', l: 'Resenha', t: 'area', rows: 5 }],
  defaults: () => ({ status: 'Quero ler', own: 'Não tenho', format: 'Físico' }),
  after: r => { const p = {}; if (r.status === 'A ler' && !r.start) p.start = today(); if (['Lido', 'Abandonado'].includes(r.status) && !r.end) p.end = today(); if (r.status === 'Lido' && +r.pages) p.curPage = +r.pages; if (Object.keys(p).length) OS.upd('books', r.id, p, { silent: true }); } };
const CST = ['Obtida', 'Em preparação', 'Exame marcado', 'Expirada'];
const CCAT = ['Contabilidade', 'Finanças', 'Gestão', 'Dados & Programação', 'Tecnologia', 'Línguas', 'Marketing', 'Vendas', 'Saúde & Segurança', 'Desporto', 'Fé & Ministério', 'Académica', 'Outro'];
OS.S.certs = { label: 'Certificação', title: r => r.name, fields: [
  { k: 'name', l: 'Certificação', t: 'text', req: 1 }, { k: 'issuer', l: 'Entidade emissora', t: 'text', h: 'Ex.: Google, Cambridge, Microsoft, OCC, Coursera, Universidade' },
  { k: 'status', l: 'Estado', t: 'sel', o: CST }, { k: 'cat', l: 'Área', t: 'sel', o: CCAT }, { k: 'level', l: 'Nível / nota', t: 'text', h: 'Ex.: B2, 920/1000, Distinção' },
  { k: 'date', l: 'Obtida em', t: 'date', show: r => r.status !== 'Em preparação' && r.status !== 'Exame marcado' }, { k: 'examDate', l: 'Data do exame', t: 'date', show: r => r.status === 'Exame marcado' || r.status === 'Em preparação' },
  { k: 'expires', l: 'Válida até', t: 'date', h: 'Deixa vazio se não expira.' }, { k: 'hours', l: 'Carga horária (h)', t: 'num' },
  { k: 'credId', l: 'ID da credencial', t: 'text' }, { k: 'url', l: 'Link de verificação / certificado', t: 'text' }, { k: 'skills', l: 'Competências', t: 'tags' }, { k: 'notes', l: 'Notas', t: 'area', rows: 2 }],
  defaults: () => ({ status: 'Obtida', date: today(), cat: 'Outro' }) };
OS.S.rchal = { label: 'Desafio literário', title: r => r.title, fields: [
  { k: 'title', l: 'Desafio', t: 'text', req: 1 }, { k: 'kind', l: 'Tipo', t: 'sel', o: [['livros', 'Número de livros'], ['paginas', 'Número de páginas'], ['categoria', 'Livros de uma categoria'], ['lista', 'Lista de livros / tarefas']] },
  { k: 'target', l: 'Meta', t: 'num', show: r => r.kind !== 'lista' }, { k: 'cat', l: 'Categoria', t: 'sel', o: GEN, show: r => r.kind === 'categoria' },
  { k: 'start', l: 'Início', t: 'date', req: 1 }, { k: 'end', l: 'Fim', t: 'date', req: 1 }, { k: 'notes', l: 'Notas', t: 'area', rows: 2 }],
  defaults: () => ({ kind: 'livros', target: 12, start: today().slice(0, 4) + '-01-01', end: today().slice(0, 4) + '-12-31', items: [] }) };
// cursos continuam em "learn" (com mais tipos e campos)
if (OS.S.learn) { const f = OS.S.learn.fields, k = f.find(x => x.k === 'kind'); if (k) k.o = ['Curso', 'Formação', 'Bootcamp', 'Workshop', 'Pós-graduação', 'Mentoria', 'Vídeo / palestra', 'Artigo', 'Projeto prático', 'Livro', 'Certificação'];
  const i = f.findIndex(x => x.k === 'author'); if (i >= 0) f[i] = Object.assign({}, f[i], { l: 'Plataforma / escola / autor' });
  if (!f.some(x => x.k === 'hours')) f.splice(f.length - 1, 0, { k: 'hours', l: 'Carga horária (h)', t: 'num' }, { k: 'cat', l: 'Área', t: 'sel', o: CCAT }, { k: 'price', l: 'Preço', t: 'num' }, { k: 'certUrl', l: 'Certificado (link)', t: 'text', show: r => r.status === 'Concluído' }); }
const isCourse = l => !['Livro', 'Certificação'].includes(l.kind);

/* migração: livros e certificações antigos (em "learn") passam para as novas abas */
OS.on('ready', () => { try { const L = OS.all('learn').slice(); let n = 0;
  L.forEach(l => { if (l.kind === 'Livro' && !OS.all('books').some(b => b.src === l.id)) { OS.add('books', { src: l.id, title: l.title, author: l.author || '', status: { 'Na fila': 'Quero ler', 'Em curso': 'A ler', 'Concluído': 'Lido', 'Abandonado': 'Abandonado' }[l.status] || 'Quero ler', pages: l.unit === 'páginas' ? l.total : '', curPage: l.unit === 'páginas' ? l.done : '', start: l.start, end: l.end, rating: l.rating ? Math.max(1, Math.min(5, Math.round(+l.rating / 2))) : '', review: l.lesson || '', own: 'Não tenho', format: 'Físico', cats: [] }, { silent: true }); OS.del('learn', l.id); n++; }
    else if (l.kind === 'Certificação' && !OS.all('certs').some(c => c.src === l.id)) { OS.add('certs', { src: l.id, name: l.title, issuer: l.author || '', status: l.status === 'Concluído' ? 'Obtida' : 'Em preparação', date: l.end || '', url: l.url || '', notes: l.lesson || '', cat: 'Outro' }, { silent: true }); OS.del('learn', l.id); n++; } });
  if (n) OS.request(); } catch (e) { console.error(e); } });

/* ================= pesquisa de livros ================= */
const GMAP = [[/juvenile|children/i, 'Infantojuvenil'], [/biograph|autobiograph/i, 'Biografia'], [/business|management/i, 'Negócios'], [/econom/i, 'Economia'], [/financ|invest|money/i, 'Finanças'], [/religio|christian|bible|theolog/i, 'Cristão / Teologia'], [/philosoph/i, 'Filosofia'], [/histor/i, 'História'], [/self-help|self help/i, 'Autoajuda'], [/psycholog/i, 'Psicologia'], [/computer|technolog/i, 'Tecnologia'], [/science fiction/i, 'Ficção científica'], [/fantasy/i, 'Fantasia'], [/mystery|thriller|crime|detective|suspense/i, 'Policial / Suspense'], [/horror/i, 'Terror'], [/romance|love/i, 'Romance'], [/poetry/i, 'Poesia'], [/comics|graphic|manga/i, 'HQ / Mangá'], [/politic/i, 'Política'], [/educat/i, 'Educação'], [/health|medic/i, 'Saúde'], [/art|music|photograph/i, 'Arte'], [/adventure/i, 'Aventura'], [/^science|nature|physics|biology/i, 'Ciência'], [/classic/i, 'Clássico'], [/brazil/i, 'Literatura brasileira'], [/portug/i, 'Literatura portuguesa'], [/fiction|novel/i, 'Ficção']];
const mapCats = arr => { const out = []; (arr || []).forEach(c => { GMAP.forEach(([re, g]) => { if (re.test(c) && !out.includes(g)) out.push(g); }); }); return out.slice(0, 4); };
const strip = s => String(s || '').replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim();
const gb = async q => { const r = await fetch('https://www.googleapis.com/books/v1/volumes?q=' + encodeURIComponent(q) + '&maxResults=24&printType=books'); if (!r.ok) throw new Error('Google Books ' + r.status); const j = await r.json();
  return (j.items || []).map(it => { const v = it.volumeInfo || {}, ids = v.industryIdentifiers || [], isbn = (ids.find(x => x.type === 'ISBN_13') || ids.find(x => x.type === 'ISBN_10') || {}).identifier || '', im = v.imageLinks || {};
    return { gid: it.id, title: v.title || '', subtitle: v.subtitle || '', author: (v.authors || []).join(', '), publisher: v.publisher || '', year: (v.publishedDate || '').slice(0, 4), pages: v.pageCount || '', cats: mapCats(v.categories), rawCats: v.categories || [], desc: strip(v.description).slice(0, 2500), lang: v.language || '', isbn, cover: (im.thumbnail || im.smallThumbnail || '').replace(/^http:/, 'https:').replace('&edge=curl', ''), avg: v.averageRating || 0 }; }); };
const ol = async q => { const r = await fetch('https://openlibrary.org/search.json?q=' + encodeURIComponent(q) + '&limit=20&fields=key,title,subtitle,author_name,first_publish_year,number_of_pages_median,cover_i,isbn,subject,publisher,language'); if (!r.ok) throw new Error('Open Library ' + r.status); const j = await r.json();
  return (j.docs || []).map(d => ({ olid: d.key, title: d.title || '', subtitle: d.subtitle || '', author: (d.author_name || []).slice(0, 3).join(', '), publisher: (d.publisher || [])[0] || '', year: d.first_publish_year ? String(d.first_publish_year) : '', pages: d.number_of_pages_median || '', cats: mapCats(d.subject), desc: '', isbn: (d.isbn || [])[0] || '', cover: d.cover_i ? `https://covers.openlibrary.org/b/id/${d.cover_i}-M.jpg` : '', lang: (d.language || [])[0] || '' })); };
const BS = { q: '', res: null, busy: false, err: '' };
const bkey = b => norm(b.title).slice(0, 40) + '|' + norm((b.author || '').split(',')[0]).slice(0, 20);
const searchBooks = async q => { BS.q = q; BS.busy = true; BS.err = ''; BS.res = null; OS.request();
  const [g, o] = await Promise.allSettled([gb(q), ol(q)]); const seen = new Set(), out = [];
  [...(g.value || []), ...(o.value || [])].forEach(b => { if (!b.title) return; const k = bkey(b); if (seen.has(k)) { const ex = out.find(x => bkey(x) === k); if (ex) { if (!ex.cover && b.cover) ex.cover = b.cover; if (!ex.pages && b.pages) ex.pages = b.pages; if (!ex.desc && b.desc) ex.desc = b.desc; if (!ex.cats.length) ex.cats = b.cats; } return; } seen.add(k); out.push(b); });
  BS.res = out; BS.busy = false; if (!out.length) BS.err = g.status === 'rejected' && o.status === 'rejected' ? 'Sem ligação às bases de livros agora. Podes adicionar o livro à mão.' : 'Não encontrei esse livro. Tenta outro termo (título + autor) ou adiciona à mão.'; OS.request(); };
OS.forms = OS.forms || {};
OS.forms.bkSearch = (f, v) => { const q = v('q'); if (q) searchBooks(q); };
const mine = b => OS.all('books').find(x => (b.gid && x.gid === b.gid) || (b.olid && x.olid === b.olid) || bkey(x) === bkey(b));
A.bkAdd = b => { const r = (BS.res || [])[+b.dataset.i]; if (!r) return; const st = b.dataset.s || 'Quero ler', ex = mine(r);
  if (ex) { OS.upd('books', ex.id, Object.assign({ status: st }, b.dataset.own ? { own: 'Tenho' } : {})); OS.S.books.after(OS.get('books', ex.id)); UI.toast(`“${ex.title}” → ${st}`, 'pos'); return; }
  const o = OS.add('books', Object.assign({}, r, { avg: undefined, rawCats: undefined, status: st, own: b.dataset.own ? 'Tenho' : 'Não tenho', format: 'Físico', added: today() })); OS.S.books.after(o); UI.toast(`“${r.title}” adicionado — ${st}${b.dataset.own ? ' · na tua estante' : ''}`, 'pos'); };
A.bkOpenRes = b => { const r = (BS.res || [])[+b.dataset.i], ex = r && mine(r); if (ex) return A.bkOpen({ dataset: { id: ex.id } }); BS.peek = +b.dataset.i; OS.request(); };

/* ================= helpers ================= */
const cover = (b, cls = '') => b.cover ? `<img class="bk-cv ${cls}" src="${esc(b.cover)}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.replaceWith(Object.assign(document.createElement('div'),{className:'bk-cv bk-cv0 ${cls}',textContent:${esc(JSON.stringify((b.title || '?').slice(0, 40)))}}))">` : `<div class="bk-cv bk-cv0 ${cls}">${esc((b.title || '?').slice(0, 40))}</div>`;
const stars = (n, id) => `<span class="bk-st" role="group" aria-label="Nota">${[1, 2, 3, 4, 5].map(i => id ? `<button class="${i <= (+n || 0) ? 'on' : ''}" data-act="bkRate" data-id="${id}" data-v="${i}" aria-label="${i} estrela${i > 1 ? 's' : ''}"></button>` : `<i class="${i <= (+n || 0) ? 'on' : ''}"></i>`).join('')}</span>`;
const prog = b => +b.pages ? Math.min(1, (+b.curPage || 0) / +b.pages) : 0;
const yrOf = b => (b.end || '').slice(0, 4);
const readIn = (from, to) => OS.all('books').filter(b => b.status === 'Lido' && b.end && b.end >= from && b.end <= to);
OS.Books = { readIn, all: () => OS.all('books') };

/* ================= CURSOS ================= */
V.cursos = sub => { const L = OS.all('learn').filter(isCourse), f = OS.ui.cuf || '', st = ['Em curso', 'Na fila', 'Concluído', 'Abandonado'];
  const it = U.sortBy(L.filter(l => !f || l.status === f), l => (st.indexOf(l.status) + 1) + (l.start || ''));
  const hrs = U.sum(L.filter(l => l.status === 'Concluído'), l => +l.hours || 0);
  const card = l => { const p = +l.total ? Math.min(1, (+l.done || 0) / +l.total) : l.status === 'Concluído' ? 1 : 0;
    return `<div class="pn cu-c"><div class="row between gap8"><div class="click grow" data-edit="learn:${l.id}" style="cursor:pointer;min-width:0"><span class="eyebrow">${esc(l.kind || 'Curso')}${l.cat ? ' · ' + esc(l.cat) : ''}</span><b class="cu-t">${esc(l.title)}</b><small class="mut">${esc([l.author, l.hours ? l.hours + ' h' : '', l.start ? 'desde ' + U.fmtDS(l.start) : '', l.end && l.status === 'Concluído' ? 'concluído ' + U.fmtDS(l.end) : ''].filter(Boolean).join(' · '))}</small></div>${UI.badge(l.status || 'Na fila', l.status === 'Concluído' ? 'pos' : l.status === 'Em curso' ? 'acc' : '')}</div>
      ${UI.bar(p, p >= 1 ? 'pos' : '')}<div class="row between gap8" style="margin-top:6px"><small class="mut">${+l.total ? `${+l.done || 0} de ${l.total} ${esc(l.unit || 'aulas')} · ${U.pct(p)}` : 'Define o total de aulas/módulos para ver o progresso'}</small><span class="row gap6">${l.status !== 'Concluído' && +l.total ? `<button class="btn xs" data-act="cuStep" data-id="${l.id}">+1 ${esc((l.unit || 'aulas').replace(/s$/, ''))}</button>` : ''}${l.status === 'Na fila' ? `<button class="btn xs ghost" data-act="cuSet" data-id="${l.id}" data-v="Em curso">Começar</button>` : ''}${l.status === 'Em curso' ? `<button class="btn xs ghost" data-act="cuSet" data-id="${l.id}" data-v="Concluído">Concluir</button>` : ''}${l.url ? `<a class="btn xs ghost" href="${esc(l.url)}" target="_blank" rel="noopener">Abrir</a>` : ''}${l.certUrl ? `<a class="btn xs ghost" href="${esc(l.certUrl)}" target="_blank" rel="noopener">Certificado</a>` : ''}</span></div></div>`; };
  return UI.head('Cursos', 'Todos os cursos que estás a fazer ou queres fazer: progresso por aula ou módulo, carga horária, plataforma e certificado.', UI.addBtn('learn', 'Novo curso', { kind: 'Curso', status: 'Em curso', unit: 'aulas', start: today() }), 'Estudos') +
    `<div class="kpis">${UI.kpi('Em curso', L.filter(l => l.status === 'Em curso').length)}${UI.kpi('Na fila', L.filter(l => l.status === 'Na fila').length)}${UI.kpi('Concluídos', L.filter(l => l.status === 'Concluído').length, hrs ? U.nf(hrs) + ' h de formação' : '')}${UI.kpi('Este ano', L.filter(l => l.status === 'Concluído' && (l.end || '').startsWith(today().slice(0, 4))).length, 'cursos concluídos')}</div>
    <div class="row gap6" style="flex-wrap:wrap;margin-bottom:10px">${UI.chip('Todos', 'cuF', !f, 'data-v=""')}${st.map(s => UI.chip(`${s} (${L.filter(l => l.status === s).length})`, 'cuF', f === s, `data-v="${s}"`)).join('')}</div>
    ${it.length ? `<div class="g g2">${it.map(card).join('')}</div>` : UI.empty('Ainda não tens cursos aqui. Junta os cursos online, formações, bootcamps e workshops que estás a fazer.', UI.addBtn('learn', 'Adicionar curso', { kind: 'Curso', status: 'Em curso', unit: 'aulas', start: today() }, ''))}`; };
A.cuF = b => OS.setUI('cuf', b.dataset.v);
A.cuStep = b => { const l = OS.get('learn', b.dataset.id); if (!l) return; const d = Math.min(+l.total || 1e9, (+l.done || 0) + 1), p = { done: d }; if (+l.total && d >= +l.total) { p.status = 'Concluído'; p.end = today(); UI.toast('Curso concluído', 'pos'); } else if (l.status === 'Na fila') { p.status = 'Em curso'; p.start = l.start || today(); } OS.upd('learn', l.id, p); };
A.cuSet = b => { const v = b.dataset.v, p = { status: v }; if (v === 'Em curso') p.start = today(); if (v === 'Concluído') { p.end = today(); const l = OS.get('learn', b.dataset.id); if (+l.total) p.done = +l.total; } OS.upd('learn', b.dataset.id, p); };

/* ================= CERTIFICAÇÕES ================= */
V.certificacoes = () => { const Cs = OS.all('certs'), f = OS.ui.cef || {}, t = today(), soon = U.addDays(t, 90);
  const exp = c => c.expires && c.expires < t, warn = c => c.expires && c.expires >= t && c.expires <= soon;
  const it = U.sortBy(Cs.filter(c => (!f.s || (f.s === 'Expirada' ? exp(c) || c.status === 'Expirada' : c.status === f.s)) && (!f.c || c.cat === f.c) && (!f.q || norm(c.name + ' ' + c.issuer).includes(norm(f.q)))), c => c.date || c.examDate || '', -1);
  const cats = [...new Set(Cs.map(c => c.cat).filter(Boolean))];
  const card = c => `<div class="pn ce-c ${exp(c) ? 'exp' : ''}"><div class="ce-ic click" data-edit="certs:${c.id}">${c.status === 'Obtida' && !exp(c) ? UI.ic('shield') : c.status === 'Exame marcado' ? UI.ic('cal') : c.status === 'Em preparação' ? UI.ic('book') : UI.ic('hourglass')}</div><div class="grow click" data-edit="certs:${c.id}" style="min-width:0;cursor:pointer"><b>${esc(c.name)}</b><small class="mut">${esc([c.issuer, c.cat, c.level].filter(Boolean).join(' · '))}</small>
    <div class="ce-m">${c.status === 'Obtida' && c.date ? `<span>obtida ${U.fmtD(c.date)}</span>` : ''}${c.examDate && c.status !== 'Obtida' ? `<span class="${c.examDate >= t ? 'acc' : ''}">exame ${U.fmtD(c.examDate)}${c.examDate >= t ? ' · daqui a ' + U.diff(c.examDate, t) + ' d' : ''}</span>` : ''}${c.expires ? `<span class="${exp(c) ? 'neg' : warn(c) ? 'warn' : ''}">${exp(c) ? 'expirou' : 'válida até'} ${U.fmtD(c.expires)}</span>` : c.status === 'Obtida' ? '<span>sem validade</span>' : ''}${c.hours ? `<span>${c.hours} h</span>` : ''}${c.credId ? `<span class="mono">ID ${esc(c.credId)}</span>` : ''}</div>
    ${(c.skills || []).length ? `<div class="ce-sk">${c.skills.map(s => `<span>${esc(s)}</span>`).join('')}</div>` : ''}</div>${c.url ? `<a class="btn xs ghost" href="${esc(c.url)}" target="_blank" rel="noopener" >Ver</a>` : ''}</div>`;
  const ob = Cs.filter(c => c.status === 'Obtida' && !exp(c));
  return UI.head('Certificações', 'Todas as tuas certificações — línguas, tecnologia, finanças, cursos, académicas, desporto, igreja… Com validade, credencial e link para provar.', UI.addBtn('certs', 'Nova certificação'), 'Estudos') +
    `<div class="kpis">${UI.kpi('Obtidas', ob.length)}${UI.kpi('Em preparação', Cs.filter(c => ['Em preparação', 'Exame marcado'].includes(c.status)).length, (() => { const n = U.sortBy(Cs.filter(c => c.examDate && c.examDate >= t && c.status !== 'Obtida'), c => c.examDate)[0]; return n ? 'próximo exame ' + U.fmtDS(n.examDate) : ''; })())}${UI.kpi('A expirar (90 dias)', Cs.filter(warn).length, '', { tone: Cs.some(warn) ? 'warn' : '' })}${UI.kpi('Horas certificadas', U.nf(U.sum(ob, c => +c.hours || 0)))}</div>
    <div class="filters"><input type="search" placeholder="Procurar certificação…" value="${esc(f.q || '')}" data-uif="cef.q" aria-label="Procurar"><select data-uif="cef.s" aria-label="Estado"><option value="">Todos os estados</option>${CST.map(s => `<option${f.s === s ? ' selected' : ''}>${s}</option>`).join('')}</select><select data-uif="cef.c" aria-label="Área"><option value="">Todas as áreas</option>${cats.map(s => `<option${f.c === s ? ' selected' : ''}>${esc(s)}</option>`).join('')}</select></div>
    ${it.length ? `<div class="g g2">${it.map(card).join('')}</div>` : UI.empty(Cs.length ? 'Nenhuma certificação com estes filtros.' : 'Junta aqui todas as tuas certificações — qualquer uma conta.', UI.addBtn('certs', 'Adicionar certificação', null, ''))}`; };

/* ================= LEITURAS ================= */
const LT = [['', 'Estante'], ['minha', 'Minha estante'], ['buscar', 'Pesquisar livros'], ['desafios', 'Desafios'], ['estatisticas', 'Estatísticas'], ['resenhas', 'Resenhas & citações']];
V.leituras = sub => { const k = sub === 'livro' ? 'livro' : LT.some(t => t[0] === (sub || '')) ? (sub || '') : '';
  return UI.head('Leituras', 'A tua estante virtual: todos os livros do mundo, o que estás a ler, já leste ou abandonaste, resenhas, os livros que tens em casa e desafios literários.', `<a class="btn pri" href="#leituras.buscar">${UI.ic('search')}<span>Adicionar livro</span></a>`, 'Estudos') + UI.tabs('leituras', LT, k === 'livro' ? '' : k) + `<div class="bk">${LT_[k]()}</div>`; };
const LT_ = {};
const shelfCard = b => `<div class="bk-it" data-act="bkOpen" data-id="${b.id}" role="button" tabindex="0" aria-label="${esc(b.title)}">${cover(b)}${b.status === 'A ler' && +b.pages ? `<span class="bk-pg"><i style="width:${Math.round(prog(b) * 100)}%"></i></span>` : ''}<b>${esc(b.title)}</b><small>${esc((b.author || '').split(',')[0])}</small>${b.rating ? stars(b.rating) : ''}${OWNED(b.own) ? `<span class="bk-own" title="${esc(b.own + ' · ' + (b.format || ''))}">${UI.ic(b.format === 'Ebook' ? 'card' : b.format === 'Audiolivro' ? 'wave' : 'book')}</span>` : ''}</div>`;
LT_[''] = () => { const B = OS.all('books'), f = OS.ui.bkf || {}, yr = today().slice(0, 4), reading = B.filter(b => b.status === 'A ler');
  const it = B.filter(b => (f.s === 'fav' ? +b.rating >= 5 : !f.s || b.status === f.s) && (!f.c || (b.cats || []).includes(f.c)) && (!f.q || norm(b.title + ' ' + b.author).includes(norm(f.q))));
  const so = f.o || 'rec', sorted = so === 'tit' ? U.sortBy(it, b => norm(b.title)) : so === 'aut' ? U.sortBy(it, b => norm(b.author)) : so === 'nota' ? U.sortBy(it, b => -(+b.rating || 0)) : U.sortBy(it, b => b.end || b.start || b.added || U.iso(new Date(b._c || 0)), -1);
  const cats = [...new Set(B.flatMap(b => b.cats || []))].sort(), ch = OS.all('rchal').filter(c => c.start <= today() && c.end >= today());
  return `<div class="kpis">${UI.kpi('Lidos em ' + yr, readIn(yr + '-01-01', yr + '-12-31').length, U.nf(U.sum(readIn(yr + '-01-01', yr + '-12-31'), b => +b.pages || 0)) + ' páginas')}${UI.kpi('A ler', reading.length)}${UI.kpi('Quero ler', B.filter(b => b.status === 'Quero ler').length)}${UI.kpi('Na minha estante', B.filter(b => OWNED(b.own)).length, 'livros que tenho')}</div>
  ${reading.length ? `<div class="pn"><div class="pn-h"><h3>A ler agora</h3></div><div class="bk-now">${reading.map(b => `<div class="bk-nw">${cover(b, 'sm')}<div class="grow" style="min-width:0"><b class="click" data-act="bkOpen" data-id="${b.id}">${esc(b.title)}</b><small class="mut">${esc(b.author || '')}</small>${+b.pages ? UI.bar(prog(b)) : ''}<form class="row gap6" data-form="bkPage" data-id="${b.id}" style="margin-top:6px"><input class="field" name="p" type="number" min="0" ${+b.pages ? `max="${b.pages}"` : ''} value="${+b.curPage || ''}" placeholder="pág." style="width:90px" aria-label="Página atual"><small class="mut">${+b.pages ? 'de ' + b.pages + ' · ' + U.pct(prog(b)) : ''}</small><button class="btn xs">Atualizar</button><button type="button" class="btn xs ghost" data-act="bkSet" data-id="${b.id}" data-v="Lido">Terminei ✓</button></form></div></div>`).join('')}</div></div>` : ''}
  ${ch.length ? `<div class="bk-chs">${ch.map(c => { const P = chalProg(c); return `<a class="bk-chm" href="#leituras.desafios"><b>${esc(c.title)}</b>${UI.bar(P.p, P.p >= 1 ? 'pos' : '')}<small>${P.txt}</small></a>`; }).join('')}</div>` : ''}
  <div class="row gap6" style="flex-wrap:wrap;margin:6px 0 10px">${UI.chip(`Todos (${B.length})`, 'bkF', !f.s, 'data-k="s" data-v=""')}${BST.map(s => UI.chip(`${BIC[s]} ${s} (${B.filter(b => b.status === s).length})`, 'bkF', f.s === s, `data-k="s" data-v="${s}"`)).join('')}${UI.chip('Favoritos', 'bkF', f.s === 'fav', 'data-k="s" data-v="fav"')}</div>
  <div class="filters"><input type="search" placeholder="Procurar na minha estante…" value="${esc(f.q || '')}" data-uif="bkf.q" aria-label="Procurar"><select data-uif="bkf.c" aria-label="Categoria"><option value="">Todas as categorias</option>${cats.map(c => `<option${f.c === c ? ' selected' : ''}>${esc(c)}</option>`).join('')}</select><select data-uif="bkf.o" aria-label="Ordenar"><option value="rec"${so === 'rec' ? ' selected' : ''}>Mais recentes</option><option value="tit"${so === 'tit' ? ' selected' : ''}>Título</option><option value="aut"${so === 'aut' ? ' selected' : ''}>Autor</option><option value="nota"${so === 'nota' ? ' selected' : ''}>Nota</option></select></div>
  ${sorted.length ? `<div class="bk-grid">${sorted.map(shelfCard).join('')}</div>` : UI.empty(B.length ? 'Nenhum livro com estes filtros.' : 'A tua estante está vazia. Pesquisa um livro (ex.: O Pequeno Príncipe) e marca se queres ler, estás a ler ou já leste.', `<a class="btn" href="#leituras.buscar">Pesquisar livros</a>`)}`; };
A.bkF = b => OS.setUI('bkf', Object.assign({}, OS.ui.bkf || {}, { [b.dataset.k]: b.dataset.v }));
A.bkOpen = b => { OS.setUI('bk', b.dataset.id); location.hash = 'leituras.livro'; };
OS.forms.bkPage = (f, v) => { const b = OS.get('books', f.dataset.id); if (!b) return; let p = Math.max(0, +v('p') || 0); if (+b.pages) p = Math.min(+b.pages, p); const log = (b.log || []).filter(x => x.d !== today()); log.push({ d: today(), p }); OS.upd('books', b.id, { curPage: p, log: log.slice(-400), status: b.status === 'Quero ler' ? 'A ler' : b.status, start: b.start || today() });
  if (+b.pages && p >= +b.pages) { OS.upd('books', b.id, { status: 'Lido', end: today() }); UI.toast(`Terminaste “${b.title}” Escreve a tua resenha!`, 'pos'); OS.setUI('bk', b.id); location.hash = 'leituras.livro'; } else UI.toast('Página ' + p + ' ✓', 'pos'); };
A.bkSet = b => { const x = OS.get('books', b.dataset.id); if (!x) return; const v = b.dataset.v, p = { status: v }; if (v === 'A ler') { p.start = x.start && x.status !== 'Quero ler' ? x.start : today(); p.end = ''; } if (v === 'Lido' || v === 'Abandonado') p.end = today(); if (v === 'Lido' && +x.pages) p.curPage = +x.pages; OS.upd('books', x.id, p); if (v === 'Lido') UI.toast('Mais um lido', 'pos'); };
A.bkRate = b => { const x = OS.get('books', b.dataset.id); OS.upd('books', x.id, { rating: +x.rating === +b.dataset.v ? 0 : +b.dataset.v }); };

LT_.minha = () => { const B = OS.all('books'), g = OS.ui.bkOw || 'casa', out = B.filter(b => ['Doado', 'Vendido', 'Trocado'].includes(b.own)), have = B.filter(b => OWNED(b.own));
  const sets = { casa: have.filter(b => b.own === 'Tenho'), fis: have.filter(b => (b.format || 'Físico') === 'Físico'), dig: have.filter(b => ['Ebook', 'Audiolivro'].includes(b.format)), emp: B.filter(b => ['Emprestei', 'Pedi emprestado', 'Biblioteca'].includes(b.own)), doar: B.filter(b => b.own === 'Para doar'), sai: out, nl: have.filter(b => b.status !== 'Lido') };
  const L = [['casa', 'Tenho', sets.casa], ['fis', 'Físicos', sets.fis], ['dig', 'Digitais', sets.dig], ['nl', 'Tenho e ainda não li', sets.nl], ['emp', 'Emprestados', sets.emp], ['doar', 'Para doar', sets.doar], ['sai', 'Já saíram', sets.sai]];
  const cur = (L.find(x => x[0] === g) || L[0])[2];
  const row = b => `<div class="li bk-ow"><div class="click" data-act="bkOpen" data-id="${b.id}">${cover(b, 'xs')}</div><div class="li-t click" data-act="bkOpen" data-id="${b.id}"><b>${esc(b.title)}</b><small>${esc([b.author, b.format, b.own !== 'Tenho' ? b.own : '', b.where].filter(Boolean).join(' · '))}${b.ownDate ? ' · ' + U.fmtD(b.ownDate) : ''}</small></div>
    <div class="li-r bk-oa">${b.own === 'Tenho' || b.own === 'Para doar' ? `<button class="btn xs ghost" data-act="bkOwn" data-id="${b.id}" data-v="Emprestei">Emprestar</button>${b.own === 'Tenho' ? `<button class="btn xs ghost" data-act="bkOwn" data-id="${b.id}" data-v="Para doar">Quero doar</button>` : `<button class="btn xs pri" data-act="bkOwn" data-id="${b.id}" data-v="Doado">Doei ✓</button>`}<button class="btn xs ghost" data-act="bkOwn" data-id="${b.id}" data-v="Vendido">Vendi</button><button class="btn xs ghost" data-act="bkOwn" data-id="${b.id}" data-v="Trocado">Troquei</button>` : ['Emprestei', 'Pedi emprestado', 'Biblioteca'].includes(b.own) ? `<button class="btn xs" data-act="bkOwn" data-id="${b.id}" data-v="${b.own === 'Emprestei' ? 'Tenho' : 'Não tenho'}">${b.own === 'Emprestei' ? 'Devolveram-me' : 'Devolvi'}</button>` : ['Doado', 'Vendido', 'Trocado'].includes(b.own) ? `<button class="btn xs ghost" data-act="bkOwn" data-id="${b.id}" data-v="Tenho">Voltou a ser meu</button>` : ''}</div></div>`;
  return `<div class="kpis">${UI.kpi('Livros que tenho', have.length, `${sets.fis.length} físicos · ${sets.dig.length} digitais`)}${UI.kpi('Ainda por ler', sets.nl.length, 'tens em casa e não leste')}${UI.kpi('Emprestados', sets.emp.length)}${UI.kpi('Doados / vendidos / trocados', out.length)}</div>
    <div class="pn"><div class="row gap8" style="flex-wrap:wrap;align-items:center"><b>Juntar livros que já tenho:</b><a class="btn sm pri" href="#leituras.buscar">${UI.ic('search')}Pesquisar e marcar “Tenho”</a>${UI.addBtn('books', 'Adicionar à mão', { own: 'Tenho', status: 'Quero ler', format: 'Físico', added: today() }, 'sm')}</div><small class="mut">Na pesquisa, carrega em <b>“Tenho”</b> para pôr o livro na tua estante (físico, ebook ou audiolivro — muda no livro).</small></div>
    <div class="row gap6" style="flex-wrap:wrap;margin:6px 0 10px">${L.map(([k, l, a]) => UI.chip(`${l} (${a.length})`, 'bkOw', g === k, `data-v="${k}"`)).join('')}</div>
    ${cur.length ? `<div class="pn" style="padding:4px 14px">${U.sortBy(cur, b => norm(b.title)).map(row).join('')}</div>` : UI.empty(g === 'doar' ? 'Nenhum livro separado para doar. No livro (ou aqui em “Tenho”), carrega em “Quero doar”.' : 'Nada aqui ainda.')}`; };
A.bkOw = b => OS.setUI('bkOw', b.dataset.v);
A.bkOwn = b => { const x = OS.get('books', b.dataset.id); if (!x) return; const v = b.dataset.v; let who = '';
  if (['Emprestei', 'Doado', 'Vendido', 'Trocado'].includes(v)) { who = prompt({ Emprestei: 'Emprestaste a quem?', Doado: 'Doaste a quem / onde? (opcional)', Vendido: 'Vendeste a quem / onde? (opcional)', Trocado: 'Trocaste por qual livro? (opcional)' }[v], '') ; if (who === null) return; }
  const hist = (x.ownLog || []).concat([{ d: today(), v, who: who || '' }]).slice(-30);
  OS.upd('books', x.id, { own: v, ownDate: today(), where: who ? (v === 'Emprestei' ? 'emprestado a ' : v === 'Trocado' ? 'trocado por ' : v === 'Doado' ? 'doado a ' : 'vendido a ') + who : v === 'Tenho' ? (x.where && /emprestado|doado|vendido|trocado/.test(x.where) ? '' : x.where || '') : x.where || '', ownLog: hist });
  UI.toast({ Emprestei: 'Emprestado', 'Para doar': 'Separado para doar', Doado: 'Doado — que abençoe alguém', Vendido: 'Vendido', Trocado: 'Trocado', Tenho: 'De volta à tua estante', 'Não tenho': 'Devolvido' }[v] || v, 'pos'); };

LT_.buscar = () => { const r = BS.res, pk = BS.peek != null && r ? r[BS.peek] : null;
  return `<form class="pn row gap8" data-form="bkSearch"><input class="field grow" name="q" value="${esc(BS.q)}" placeholder="Título, autor ou ISBN — ex.: O Pequeno Príncipe, Machado de Assis, 9788595081512" aria-label="Pesquisar livros" autocomplete="off"><button class="btn pri">${UI.ic('search')}Pesquisar</button></form>
    <small class="mut" style="display:block;margin:-4px 2px 10px">Pesquisa em milhões de livros (Google Books + Open Library). Não encontras? ${UI.addBtn('books', 'Adiciona à mão', { added: today() }, 'xs ghost')}</small>
    ${BS.busy ? `<div class="pn"><div class="sai-busy"><div class="fd-spin"></div><span>A procurar “${esc(BS.q)}”…</span></div></div>` : ''}${BS.err ? `<p class="mut">${esc(BS.err)}</p>` : ''}
    ${pk ? `<div class="pn bk-peek"><div class="row between"><b>Detalhes</b><button class="icon-btn" data-act="bkPeekX" aria-label="Fechar">${UI.ic('x')}</button></div><div class="bk-dt">${cover(pk, 'lg')}<div><h3 style="margin:0">${esc(pk.title)}</h3>${pk.subtitle ? `<div class="mut">${esc(pk.subtitle)}</div>` : ''}<p class="mut" style="margin:4px 0">${esc([pk.author, pk.publisher, pk.year, pk.pages ? pk.pages + ' págs.' : '', pk.isbn ? 'ISBN ' + pk.isbn : ''].filter(Boolean).join(' · '))}</p><div class="ce-sk">${(pk.cats || []).map(c => `<span>${esc(c)}</span>`).join('')}</div><p class="bk-desc">${esc(pk.desc || 'Sem sinopse disponível.')}</p>${addBtns(BS.peek)}</div></div></div>` : ''}
    ${r && r.length ? `<div class="bk-res">${r.map((b, i) => { const ex = mine(b); return `<div class="bk-r">${`<div class="click" data-act="bkOpenRes" data-i="${i}">${cover(b, 'sm')}</div>`}<div class="grow" style="min-width:0"><b class="click" data-act="bkOpenRes" data-i="${i}">${esc(b.title)}</b>${b.subtitle ? `<small class="mut">${esc(b.subtitle)}</small>` : ''}<small>${esc([b.author, b.year, b.pages ? b.pages + ' págs.' : ''].filter(Boolean).join(' · '))}</small>${(b.cats || []).length ? `<div class="ce-sk">${b.cats.map(c => `<span>${esc(c)}</span>`).join('')}</div>` : ''}
      ${ex ? `<div class="bk-in">✓ Na tua estante · ${BIC[ex.status] || ''} ${esc(ex.status)}${OWNED(ex.own) ? ' · tenho' : ''} <button class="btn xs ghost" data-act="bkOpen" data-id="${ex.id}">Abrir</button></div>` : addBtns(i)}</div></div>`; }).join('')}</div>` : ''}`; };
const addBtns = i => `<div class="bk-ab">${BST.map(s => `<button class="btn xs ${s === 'Lido' ? 'pri' : ''}" data-act="bkAdd" data-i="${i}" data-s="${s}">${BIC[s]} ${s === 'Lido' ? 'Já li' : s === 'A ler' ? 'Estou a ler' : s === 'Abandonado' ? 'Desisti' : 'Quero ler'}</button>`).join('')}<button class="btn xs ghost" data-act="bkAdd" data-i="${i}" data-s="Quero ler" data-own="1" title="Tenho este livro (na estante)">Tenho</button></div>`;
A.bkPeekX = () => { BS.peek = null; OS.request(); };

LT_.livro = () => { const b = OS.get('books', OS.ui.bk); if (!b) return UI.empty('Livro não encontrado.', `<a class="btn" href="#leituras">Voltar à estante</a>`);
  const Q = b.quotes || [];
  return `<a class="btn xs ghost" href="#leituras" style="margin-bottom:10px">← Estante</a>
  <div class="pn"><div class="bk-dt">${cover(b, 'lg')}<div style="min-width:0">
    <h2 style="margin:0">${esc(b.title)}</h2>${b.subtitle ? `<div class="mut">${esc(b.subtitle)}</div>` : ''}<p style="margin:4px 0 8px">${esc(b.author || '')}</p>
    <p class="mut" style="margin:0 0 8px;font-size:13px">${esc([b.publisher, b.year, b.pages ? b.pages + ' páginas' : '', b.isbn ? 'ISBN ' + b.isbn : ''].filter(Boolean).join(' · '))}</p>
    <div class="seg bk-sseg" role="group" aria-label="Estado">${BST.map(s => `<button class="${b.status === s ? 'on' : ''}" data-act="bkSet" data-id="${b.id}" data-v="${s}">${BIC[s]} ${s === 'Lido' ? 'Já li' : s === 'A ler' ? 'A ler' : s === 'Abandonado' ? 'Desisti' : 'Quero ler'}</button>`).join('')}</div>
    <div style="margin:10px 0 4px">${stars(b.rating, b.id)} <small class="mut">${b.rating ? b.rating + '/5' : 'dá a tua nota'}</small></div>
    ${b.status === 'A ler' ? `<form class="row gap6" data-form="bkPage" data-id="${b.id}" style="margin:8px 0;flex-wrap:wrap"><input class="field" name="p" type="number" min="0" value="${+b.curPage || ''}" placeholder="página" style="width:100px" aria-label="Página atual"><small class="mut">${+b.pages ? 'de ' + b.pages + ' · ' + U.pct(prog(b)) : ''}</small><button class="btn sm">Atualizar página</button></form>${+b.pages ? UI.bar(prog(b)) : ''}` : ''}
    <small class="mut" style="display:block;margin-top:6px">${[b.start ? 'Comecei ' + U.fmtD(b.start) : '', b.end && b.status === 'Lido' ? 'terminei ' + U.fmtD(b.end) : '', b.end && b.status === 'Abandonado' ? 'parei ' + U.fmtD(b.end) + (+b.curPage ? ' na pág. ' + b.curPage : '') : '', b.start && b.end && b.status === 'Lido' ? '(' + Math.max(1, U.diff(b.end, b.start)) + ' dias)' : ''].filter(Boolean).join(' · ')}</small>
    <div class="bk-cats">${GEN.filter(g => (b.cats || []).includes(g)).concat((b.cats || []).filter(c => !GEN.includes(c))).map(c => `<button class="chip on" data-act="bkCat" data-id="${b.id}" data-c="${esc(c)}" title="Tirar">${esc(c)} ×</button>`).join('')}<select class="field" data-bkcat="${b.id}" aria-label="Acrescentar categoria" style="width:auto;padding:4px 8px;font-size:12.5px"><option value="">+ categoria</option>${GEN.filter(g => !(b.cats || []).includes(g)).map(g => `<option>${g}</option>`).join('')}</select></div>
    <div class="bk-ownbox"><b>Na minha estante:</b> <select class="field" data-bkf="own" data-id="${b.id}" style="width:auto">${OWN.map(o => `<option${(b.own || 'Não tenho') === o ? ' selected' : ''}>${o}</option>`).join('')}</select><select class="field" data-bkf="format" data-id="${b.id}" style="width:auto">${FMT.map(o => `<option${(b.format || 'Físico') === o ? ' selected' : ''}>${o}</option>`).join('')}</select><input class="field" data-bkf="where" data-id="${b.id}" value="${esc(b.where || '')}" placeholder="onde está / a quem" style="width:180px"></div>
    <div class="row gap6" style="margin-top:10px;flex-wrap:wrap"><button class="btn xs ghost" data-edit="books:${b.id}">Editar dados</button><button class="btn xs ghost" data-act="bkDel" data-id="${b.id}">Remover da estante</button></div></div></div>
    ${b.desc ? `<details class="tog" style="margin-top:12px"><summary><span>Sinopse</span>${UI.ic('down', 'chev')}</summary><div class="tog-b"><p class="bk-desc">${esc(b.desc)}</p></div></details>` : ''}</div>
  <div class="pn"><div class="pn-h"><h3>✍️ A minha resenha</h3>${b.reviewDate ? `<small class="mut">${U.fmtD(b.reviewDate)}</small>` : ''}</div>
    <textarea class="field bk-rev" id="bkRev" data-bkf="review" data-id="${b.id}" rows="8" placeholder="${b.status === 'Lido' ? 'O que achaste? O que aprendeste, o que te marcou, a quem recomendarias…' : 'Podes escrever já as tuas impressões — ou volta quando terminares.'}">${esc(b.review || '')}</textarea>
    <label class="row gap6 mut" style="font-size:13px;margin-top:6px"><input type="checkbox" data-bkf="spoiler" data-id="${b.id}" ${b.spoiler ? 'checked' : ''}> contém spoilers</label><small class="mut">Guarda sozinho ao sair do campo.</small></div>
  <div class="pn"><div class="pn-h"><h3>Citações</h3><span class="mut mono">${Q.length}</span></div>
    ${Q.map((q, i) => `<blockquote class="bk-q">“${esc(q.t)}”${q.p ? `<small> — pág. ${esc(q.p)}</small>` : ''}<button class="icon-btn" data-act="bkQDel" data-id="${b.id}" data-i="${i}" aria-label="Apagar">${UI.ic('x')}</button></blockquote>`).join('')}
    <form class="row gap6" data-form="bkQuote" data-id="${b.id}" style="flex-wrap:wrap"><input class="field grow" name="t" placeholder="Uma frase que te marcou…" aria-label="Citação" style="min-width:200px"><input class="field" name="p" placeholder="pág." style="width:80px" aria-label="Página"><button class="btn sm">Guardar</button></form></div>`; };
A.bkDel = b => { const x = OS.get('books', b.dataset.id); if (!x || !confirm(`Remover “${x.title}” da tua estante?`)) return; OS.del('books', x.id); location.hash = 'leituras'; };
A.bkCat = b => { const x = OS.get('books', b.dataset.id); OS.upd('books', x.id, { cats: (x.cats || []).filter(c => c !== b.dataset.c) }); };
A.bkQDel = b => { const x = OS.get('books', b.dataset.id); OS.upd('books', x.id, { quotes: (x.quotes || []).filter((_, i) => i !== +b.dataset.i) }); };
OS.forms.bkQuote = (f, v) => { const t = v('t'); if (!t) return; const x = OS.get('books', f.dataset.id); OS.upd('books', x.id, { quotes: (x.quotes || []).concat([{ t, p: v('p'), d: today() }]) }); };
document.addEventListener('change', e => { const el = e.target, d = el.dataset || {};
  if (d.bkcat && el.value) { const x = OS.get('books', d.bkcat); if (x) OS.upd('books', x.id, { cats: [...new Set((x.cats || []).concat(el.value))] }); return; }
  if (d.bkf && d.id) { const x = OS.get('books', d.id); if (!x) return; const v = el.type === 'checkbox' ? el.checked : el.value, p = { [d.bkf]: v }; if (d.bkf === 'review') p.reviewDate = today(); if (d.bkf === 'own') p.ownDate = today(); OS.upd('books', x.id, p); } });

/* ---------- desafios ---------- */
const PRE = [
  ['', 'Desafio anual', () => ({ title: 'Desafio de leitura ' + today().slice(0, 4), kind: 'livros', target: 24 })],
  ['', '52 livros num ano', () => ({ title: '52 livros em ' + today().slice(0, 4), kind: 'livros', target: 52 })],
  ['', '10 000 páginas', () => ({ title: '10 000 páginas em ' + today().slice(0, 4), kind: 'paginas', target: 10000 })],
  ['', 'Clássicos', () => ({ title: 'Clássicos que todos devem ler', kind: 'lista', items: ['O Pequeno Príncipe', 'Dom Casmurro', '1984', 'Orgulho e Preconceito', 'Cem Anos de Solidão', 'Crime e Castigo', 'Os Lusíadas', 'Memórias Póstumas de Brás Cubas', 'O Senhor dos Anéis', 'A Metamorfose', 'Dom Quixote', 'O Alquimista'] })],
  ['', 'Volta ao mundo', () => ({ title: 'Volta ao mundo em livros', kind: 'lista', items: ['Um autor brasileiro', 'Um autor português', 'Um autor africano', 'Um autor asiático', 'Um autor norte-americano', 'Um autor europeu (fora de Portugal)', 'Um autor latino-americano (fora do Brasil)', 'Um autor da Oceânia'] })],
  ['', 'Desafio de géneros', () => ({ title: 'Desafio de géneros ' + today().slice(0, 4), kind: 'lista', items: ['Uma biografia', 'Um clássico', 'Um livro de poesia', 'Um livro cristão', 'Um livro de finanças', 'Um de ficção científica ou fantasia', 'Um livro com mais de 500 páginas', 'Um livro publicado este ano', 'Um livro recomendado por um amigo', 'Um livro que virou filme', 'Um livro de um autor que nunca leste', 'Um livro que abandonaste e queres retomar'] })],
  ['✝️', 'Livros cristãos', () => ({ title: '6 livros cristãos este ano', kind: 'categoria', cat: 'Cristão / Teologia', target: 6 })],
  ['', 'Finanças & negócios', () => ({ title: '5 livros de finanças', kind: 'categoria', cat: 'Finanças', target: 5 })]];
const chalProg = c => { const R = readIn(c.start, c.end), t = today(), el = Math.max(0, Math.min(1, (U.diff(t < c.end ? t : c.end, c.start) + 1) / (U.diff(c.end, c.start) + 1)));
  if (c.kind === 'lista') { const it = c.items || [], dn = it.filter(i => i.done || (i.book && (OS.get('books', i.book) || {}).status === 'Lido')).length; return { n: dn, tg: it.length, p: it.length ? dn / it.length : 0, txt: `${dn} de ${it.length} cumpridos`, el }; }
  const n = c.kind === 'paginas' ? U.sum(R, b => +b.pages || 0) : c.kind === 'categoria' ? R.filter(b => (b.cats || []).includes(c.cat)).length : R.length, tg = +c.target || 1, exp = tg * el, d = n - exp, unit = c.kind === 'paginas' ? 'páginas' : 'livros';
  return { n, tg, p: n / tg, el, txt: `${U.nf(n)} de ${U.nf(tg)} ${unit}${t <= c.end && n < tg ? ` · ${Math.abs(d) < (c.kind === 'paginas' ? 50 : .5) ? 'no ritmo certo' : d > 0 ? U.nf(Math.round(d)) + ' à frente' : U.nf(Math.round(-d)) + ' atrás do ritmo'}` : n >= tg ? ' · cumprido' : ''}`, R }; };
LT_.desafios = () => { const Cs = U.sortBy(OS.all('rchal'), c => c.end, -1), t = today(), act = Cs.filter(c => c.end >= t), past = Cs.filter(c => c.end < t);
  const card = c => { const P = chalProg(c), left = U.diff(c.end, t);
    return `<div class="pn bk-ch"><div class="row between gap8"><div class="click" data-edit="rchal:${c.id}" style="cursor:pointer"><span class="eyebrow">${{ livros: 'Livros', paginas: 'Páginas', categoria: 'Categoria · ' + esc(c.cat || ''), lista: 'Lista' }[c.kind] || ''} · ${U.fmtDS(c.start)} → ${U.fmtDS(c.end)}</span><h3 style="margin:2px 0 0">${P.p >= 1 ? '' : ''}${esc(c.title)}</h3></div><span class="mono" style="font-size:20px">${U.pct(Math.min(1, P.p))}</span></div>
      ${UI.bar(Math.min(1, P.p), P.p >= 1 ? 'pos' : '', c.kind !== 'lista' && left >= 0 ? P.el : null)}<small class="mut">${P.txt}${left >= 0 && P.p < 1 ? ` · faltam ${left} dias${c.kind === 'livros' && P.tg > P.n ? ` · ~${U.nf(Math.max(1, (P.tg - P.n) / Math.max(1, left / 30)), 1)} por mês` : ''}` : ''}</small>
      ${c.kind === 'lista' ? `<div class="bk-cl">${(c.items || []).map((i, k) => { const bk = i.book && OS.get('books', i.book), dn = i.done || (bk && bk.status === 'Lido'); return `<div class="bk-cli ${dn ? 'dn' : ''}"><input type="checkbox" class="cbx" data-act="chItem" data-id="${c.id}" data-k="${k}" ${dn ? 'checked' : ''} aria-label="Cumprido"><span class="grow">${esc(i.t)}${bk ? ` <small class="mut">— ${esc(bk.title)}${bk.status !== 'Lido' ? ' (' + esc(bk.status) + ')' : ''}</small>` : ''}</span><select class="field" data-chbook="${c.id}" data-k="${k}" style="width:auto;max-width:180px;padding:3px 6px;font-size:12px" aria-label="Livro"><option value="">ligar livro…</option>${U.sortBy(OS.all('books'), b => norm(b.title)).map(b => `<option value="${b.id}"${i.book === b.id ? ' selected' : ''}>${esc(b.title.slice(0, 40))}</option>`).join('')}</select></div>`; }).join('')}<form class="row gap6" data-form="chAddItem" data-id="${c.id}" style="margin-top:6px"><input class="field grow" name="t" placeholder="+ item da lista" aria-label="Novo item"><button class="btn xs">+</button></form></div>`
      : P.R && P.R.length ? `<div class="bk-mini">${(c.kind === 'categoria' ? P.R.filter(b => (b.cats || []).includes(c.cat)) : P.R).slice(0, 14).map(b => `<span data-act="bkOpen" data-id="${b.id}" title="${esc(b.title)}">${cover(b, 'xs')}</span>`).join('')}</div>` : ''}</div>`; };
  return `<div class="pn"><div class="pn-h"><h3>Novo desafio</h3>${UI.addBtn('rchal', 'Personalizado', null, 'sm')}</div><div class="bk-pre">${PRE.map(([ic, l], i) => `<button class="bk-pr" data-act="chNew" data-i="${i}"><b>${l}</b></button>`).join('')}</div></div>
    ${act.length ? act.map(card).join('') : UI.empty('Sem desafios ativos. Escolhe um acima — por exemplo, o desafio anual — e o progresso conta sozinho com os livros que marcares como lidos.')}
    ${past.length ? UI.toggle(`Desafios terminados (${past.length})`, past.map(card).join(''), 'chPast', 'flag') : ''}`; };
A.chNew = b => { const o = PRE[+b.dataset.i][2](), y = today().slice(0, 4); if (o.kind === 'livros') { const n = prompt('Quantos livros queres ler?', o.target); if (n === null) return; o.target = Math.max(1, +n || o.target); if (o.title.startsWith('Desafio')) o.title = `Ler ${o.target} livros em ${y}`; }
  const r = OS.add('rchal', Object.assign({ start: y + '-01-01', end: y + '-12-31' }, o, { items: (o.items || []).map(t => ({ t, done: false, book: (OS.all('books').find(b => norm(b.title) === norm(t)) || {}).id || '' })) })); UI.toast('Desafio criado: ' + r.title, 'pos'); };
A.chItem = b => { const c = OS.get('rchal', b.dataset.id), it = (c.items || []).slice(), k = +b.dataset.k; it[k] = Object.assign({}, it[k], { done: !it[k].done }); OS.upd('rchal', c.id, { items: it }); };
OS.forms.chAddItem = (f, v) => { const t = v('t'); if (!t) return; const c = OS.get('rchal', f.dataset.id); OS.upd('rchal', c.id, { items: (c.items || []).concat([{ t, done: false, book: '' }]) }); };
document.addEventListener('change', e => { const d = e.target.dataset || {}; if (!d.chbook) return; const c = OS.get('rchal', d.chbook), it = (c.items || []).slice(), k = +d.k; it[k] = Object.assign({}, it[k], { book: e.target.value }); OS.upd('rchal', c.id, { items: it }); });

/* ---------- estatísticas ---------- */
LT_.estatisticas = () => { const B = OS.all('books'), R = B.filter(b => b.status === 'Lido' && b.end), y0 = today().slice(0, 4), ys = Array.from({ length: 6 }, (_, i) => String(+y0 - 5 + i));
  if (!R.length) return UI.empty('As estatísticas aparecem quando marcares livros como lidos.', `<a class="btn" href="#leituras.buscar">Adicionar livros</a>`);
  const mo = Array.from({ length: 12 }, (_, i) => y0 + '-' + String(i + 1).padStart(2, '0')), cats = {}; R.forEach(b => (b.cats && b.cats.length ? b.cats : ['Sem categoria']).forEach(c => cats[c] = (cats[c] || 0) + 1));
  const au = {}; R.forEach(b => (b.author || '').split(',').map(s => s.trim()).filter(Boolean).forEach(a => au[a] = (au[a] || 0) + 1));
  const days = R.filter(b => b.start).map(b => Math.max(1, U.diff(b.end, b.start))), rated = R.filter(b => +b.rating), pg = R.filter(b => +b.pages);
  const big = U.sortBy(pg, b => -b.pages)[0], best = U.sortBy(rated, b => -b.rating).slice(0, 5);
  return `<div class="kpis">${UI.kpi('Livros lidos', R.length, 'desde sempre')}${UI.kpi('Páginas lidas', U.nf(U.sum(pg, b => +b.pages)))}${UI.kpi('Nota média', rated.length ? U.nf(U.sum(rated, b => +b.rating) / rated.length, 1) + '' : '—')}${UI.kpi('Tempo médio por livro', days.length ? Math.round(U.sum(days, x => x) / days.length) + ' dias' : '—')}</div>
  <div class="g g2"><div class="pn"><div class="pn-h"><h3>Livros por ano</h3></div>${C.mount({ type: 'bar', labels: ys, series: [{ name: 'Livros', data: ys.map(y => R.filter(b => yrOf(b) === y).length), color: 'var(--accent)' }] }, 200)}</div>
    <div class="pn"><div class="pn-h"><h3>Páginas por mês · ${y0}</h3></div>${C.mount({ type: 'bar', labels: mo.map(m => U.MES ? U.MES[+m.slice(5) - 1] : m.slice(5)), series: [{ name: 'Páginas', data: mo.map(m => U.sum(R.filter(b => b.end.startsWith(m)), b => +b.pages || 0)), color: 'var(--c5)' }] }, 200)}</div></div>
  <div class="g g3"><div class="pn"><div class="pn-h"><h3>Categorias</h3></div>${C.mount({ type: 'donut', data: Object.entries(cats).sort((a, b) => b[1] - a[1]).map(([l, v]) => ({ l, v })), label: 'Lidos', max: 7, fmt: v => v }, 210)}</div>
    <div class="pn"><div class="pn-h"><h3>Autores mais lidos</h3></div>${Object.entries(au).sort((a, b) => b[1] - a[1]).slice(0, 8).map(([a, n]) => `<div class="li"><div class="li-t"><b>${esc(a)}</b></div><span class="mono">${n}</span></div>`).join('')}</div>
    <div class="pn"><div class="pn-h"><h3>Os melhores</h3></div>${best.map(b => `<div class="li click" data-act="bkOpen" data-id="${b.id}"><div class="li-t"><b>${esc(b.title)}</b><small>${stars(b.rating)}</small></div></div>`).join('') || '<p class="mut">Dá notas aos livros lidos.</p>'}${big ? `<div class="divider"></div><small class="mut">Maior livro lido: <b>${esc(big.title)}</b> (${big.pages} págs.)</small>` : ''}</div></div>`; };

LT_.resenhas = () => { const B = OS.all('books'), Rv = U.sortBy(B.filter(b => (b.review || '').trim()), b => b.reviewDate || b.end || '', -1), Q = B.flatMap(b => (b.quotes || []).map(q => Object.assign({ b }, q)));
  return `<div class="g g-main"><div><h3 style="margin:4px 0 10px">Resenhas (${Rv.length})</h3>${Rv.map(b => `<div class="pn bk-rv"><div class="row gap12">${cover(b, 'sm')}<div class="grow" style="min-width:0"><b class="click" data-act="bkOpen" data-id="${b.id}">${esc(b.title)}</b><small class="mut" style="display:block">${esc(b.author || '')}${b.reviewDate ? ' · ' + U.fmtD(b.reviewDate) : ''}</small>${b.rating ? stars(b.rating) : ''}${b.spoiler ? ' <span class="bdg warn">spoilers</span>' : ''}</div></div><p class="bk-desc" style="white-space:pre-wrap">${esc(b.review)}</p></div>`).join('') || UI.empty('Ainda sem resenhas. Abre um livro lido e escreve o que achaste.')}</div>
    <div><h3 style="margin:4px 0 10px">Citações (${Q.length})</h3>${Q.map(q => `<blockquote class="bk-q">“${esc(q.t)}”<small> — <span class="click" data-act="bkOpen" data-id="${q.b.id}">${esc(q.b.title)}</span>${q.p ? ', pág. ' + esc(q.p) : ''}</small></blockquote>`).join('') || '<p class="mut">Guarda frases dos livros na página de cada livro.</p>'}</div></div>`; };

/* links antigos (Aprendizagem → itens) */
OS.on('ready', () => { const _ap = V.aprendizagem; if (_ap && !_ap._st) { V.aprendizagem = sub => sub === 'itens' ? V.cursos() : _ap(sub); V.aprendizagem._st = 1; } });
})();
