/* OCEANUM — Universidade+: o que os melhores apps de estudo têm.
   Flashcards com repetição espaçada (SM-2, como o Anki) e criados pela IA · Simulados de escolha múltipla gerados pela IA ·
   Tutor IA (explicar, resumir, Feynman, mapa mental, exercícios) · Calculadora de notas ("quanto preciso no exame?") ·
   Plano de estudo até ao exame · Materiais por disciplina · Presenças/faltas · Contagem decrescente, mapa de calor e sequência. */
(() => {
'use strict';
const U = OS.U, UI = OS.UI, C = OS.C, V = OS.views, A = OS.act, esc = U.esc, today = () => U.today(), St = OS.St;
const UNI = OS.UNI, UT = OS.UT; if (!UNI || !UT) return;
const subjN = id => (OS.get('subjects', id) || {}).name || '—';
const cur = () => St.current();
const subjOpts = (v, all) => `${all ? `<option value="">${all}</option>` : ''}${cur().map(s => `<option value="${s.id}"${v === s.id ? ' selected' : ''}>${esc(s.name)}</option>`).join('')}`;
const hasAI = () => OS.AI && OS.AI.key && OS.AI.key();
const noAI = () => `<div class="pn">${OS.AI && OS.AI.setup ? OS.AI.setup('') : '<p class="mut">Liga a IA nas Definições.</p>'}</div>`;
const md = t => esc(String(t || '')).replace(/\*\*(.+?)\*\*/g, '<b>$1</b>').replace(/(^|\n)#{1,3} ?(.+)/g, '$1<b class="un-h">$2</b>').replace(/(^|\n)\s*[-•*] (.+)/g, '$1<span class="un-li">• $2</span>').replace(/\n/g, '<br>');

/* ---------- coleções e campos ---------- */
OS.S.cards = { label: 'Flashcard', title: r => r.front, fields: [
  { k: 'subject', l: 'Disciplina', t: 'sel', o: () => cur().map(s => [s.id, s.name]) }, { k: 'deck', l: 'Baralho / tema', t: 'text', h: 'Ex.: Capítulo 3, IVA, Balanço' },
  { k: 'front', l: 'Frente (pergunta)', t: 'area', rows: 2, req: 1 }, { k: 'back', l: 'Verso (resposta)', t: 'area', rows: 3, req: 1 }],
  defaults: () => ({ ef: 2.5, iv: 0, reps: 0, due: today(), lapses: 0 }) };
OS.S.quizzes = { label: 'Simulado', title: r => r.title || 'Simulado', fields: [{ k: 'title', l: 'Título', t: 'text' }, { k: 'date', l: 'Data', t: 'date' }, { k: 'score', l: 'Nota (0–20)', t: 'num' }] };
OS.S.materials = { label: 'Material', title: r => r.title, fields: [
  { k: 'subject', l: 'Disciplina', t: 'sel', o: () => OS.all('subjects').map(s => [s.id, s.name]), req: 1 }, { k: 'title', l: 'Título', t: 'text', req: 1 },
  { k: 'kind', l: 'Tipo', t: 'sel', o: ['Slides', 'Sebenta / apontamentos', 'Livro', 'Exercícios', 'Exames antigos', 'Vídeo', 'Artigo', 'Site / link', 'Outro'] }, { k: 'url', l: 'Link (Drive, Moodle, YouTube…)', t: 'text' }, { k: 'notes', l: 'Notas', t: 'area', rows: 2 }],
  defaults: () => ({ kind: 'Slides' }) };
if (OS.S.subjects && !OS.S.subjects.fields.some(f => f.k === 'absMax')) OS.S.subjects.fields.push({ k: 'absMax', l: 'Faltas permitidas', t: 'num', h: 'Limite de faltas (ex.: aulas práticas)' }, { k: 'abs', l: 'Faltas dadas', t: 'num' }, { k: 'moodle', l: 'Link da disciplina (Moodle / Teams)', t: 'text' });

/* ---------- novas abas ---------- */
const add = (after, k, l) => { if (UT.some(t => t[0] === k)) return; const i = UT.findIndex(t => t[0] === after); UT.splice(i + 1, 0, [k, l]); };
add('avaliacoes', 'notas', 'Calculadora de notas'); add('notas', 'exames', 'Plano para exames'); add('exames', 'flashcards', 'Flashcards'); add('flashcards', 'simulados', 'Simulados'); add('simulados', 'tutor', 'Tutor IA'); add('tutor', 'materiais', 'Materiais'); add('materiais', 'presencas', 'Presenças');

/* ================= VISÃO: extra no topo ================= */
const studyByDay = () => { const m = {}; OS.all('sessions').forEach(s => m[s.date] = (m[s.date] || 0) + (+s.minutes || 0)); return m; };
const streak = by => { let n = 0, d = today(); if (!(by[d] >= 25)) d = U.addDays(d, -1); while (by[d] >= 25) { n++; d = U.addDays(d, -1); } return n; };
const heat = by => { const end = today(), start = U.addDays(U.monday(end), -7 * 25), days = U.range(start, U.addDays(U.monday(end), 6)), lv = m => !m ? 0 : m < 30 ? 1 : m < 60 ? 2 : m < 120 ? 3 : 4;
  return `<div class="un-heat">${days.map(d => `<i class="l${d > end ? 'x' : lv(by[d])}" title="${U.fmtD(d)} · ${by[d] || 0} min"></i>`).join('')}</div><div class="un-heat-k"><span>menos</span>${[0, 1, 2, 3, 4].map(i => `<i class="l${i}"></i>`).join('')}<span>mais</span></div>`; };
const due = (sid) => OS.all('cards').filter(c => (!sid || c.subject === sid) && (c.due || today()) <= today());
const _visao = UNI.visao;
UNI.visao = () => { const t = today(), by = studyByDay(), st = streak(by), up = U.sortBy(OS.all('assessments').filter(a => a.date >= t && a.date <= U.addDays(t, 60) && a.prep !== 'Feito'), a => a.date).slice(0, 4), tr = OS.all('trees').filter(x => x.date === t && x.alive !== false);
  return `<div class="un-top"><div class="pn un-today"><div class="pn-h"><h3>${UI.ic('zap')}Hoje</h3></div>
      <div class="un-qs"><a class="un-q" href="#universidade.flashcards"><b>${due().length}</b><small>flashcards para rever</small></a><a class="un-q" href="#universidade.revisoes"><b>${St.revDue().length}</b><small>revisões</small></a><a class="un-q" href="#floresta"><b>${U.hours(by[t] || 0)}</b><small>estudo hoje${tr.length ? ' · ' + tr.length : ''}</small></a><div class="un-q"><b>${st}</b><small>${st === 1 ? 'dia seguido' : 'dias seguidos'} (≥25 min)</small></div></div>
      <div class="row gap8" style="flex-wrap:wrap;margin-top:10px"><a class="btn sm pri" href="#floresta">Focar agora</a><a class="btn sm" href="#universidade.flashcards" data-act="fcStart">🃏 Rever flashcards</a><a class="btn sm ghost" href="#universidade.tutor">Tutor IA</a><a class="btn sm ghost" href="#universidade.simulados">Simulado</a></div></div>
    <div class="pn"><div class="pn-h"><h3>${UI.ic('cal')}Contagem decrescente</h3><a class="more" href="#universidade.exames">${UI.ic('right')}</a></div>${up.length ? `<div class="un-cd">${up.map(a => { const d = U.diff(a.date, t); return `<div class="un-cdi ${d <= 7 ? 'hot' : d <= 14 ? 'warm' : ''}" data-act="unPlan" data-id="${a.id}" role="button" tabindex="0"><b>${d === 0 ? 'Hoje' : d}</b><small>${d === 0 ? '' : d === 1 ? 'dia' : 'dias'}</small><span>${esc(a.title)}</span><em>${esc(subjN(a.subject))} · ${esc(a.prep || 'Não comecei')}</em></div>`; }).join('')}</div>` : UI.empty('Sem avaliações nos próximos 60 dias.', UI.addBtn('assessments', 'Avaliação', null, 'sm'))}</div></div>
  <div class="pn"><div class="pn-h"><h3>Mapa de estudo · 6 meses</h3><span class="mut" style="font-size:12px">${U.hours(U.sum(Object.entries(by).filter(([d]) => d >= U.addDays(t, -29)), x => x[1]))} nos últimos 30 dias</span></div>${heat(by)}</div>` + _visao(); };
A.unPlan = b => { OS.setUI('uePick', b.dataset.id); location.hash = 'universidade.exames'; };

/* ================= CALCULADORA DE NOTAS ================= */
UNI.notas = () => { const S = cur(), wi = OS.ui.wi || {};
  if (!S.length) return UI.empty('Sem disciplinas em curso.', UI.addBtn('subjects', 'Nova disciplina', null, ''));
  return `<div class="note">Escala 0–20, aprovação com 9,5. Junta todas as avaliações de cada disciplina com o peso (%). Nas que ainda não fizeste, escreve uma nota "e se…" para simular a média final.</div>
  <div class="g g2">${S.map(s => { const As = U.sortBy(OS.all('assessments').filter(a => a.subject === s.id), a => a.date || ''), done = As.filter(a => a.grade !== '' && a.grade != null), pend = As.filter(a => !(a.grade !== '' && a.grade != null));
    const W = U.sum(done, a => +a.weight || 0), Sm = U.sum(done, a => (+a.grade || 0) * (+a.weight || 0)), Wall = U.sum(As, a => +a.weight || 0), R = Math.max(0, 100 - W), cur0 = W ? Sm / W : null;
    const need = T => R > 0 ? (T * 100 - Sm) / R : null, tgt = +s.target || 15;
    const sim = U.sum(pend, a => (wi[a.id] !== undefined && wi[a.id] !== '' ? +wi[a.id] : (cur0 || 0)) * (+a.weight || 0)), simF = Wall ? (Sm + sim + Math.max(0, 100 - Wall) * (cur0 || 0)) / 100 : null;
    const nd = (T, l) => { const n = need(T); return `<div class="un-need ${n == null ? '' : n > 20 ? 'neg' : n <= 0 ? 'pos' : n > 15 ? 'warn' : ''}"><small>${l}</small><b>${n == null ? (cur0 >= T ? '✓' : '✗') : n <= 0 ? '✓ já garantido' : n > 20 ? 'impossível' : U.nf(n, 1)}</b></div>`; };
    return `<div class="pn"><div class="pn-h"><h3 class="click" data-edit="subjects:${s.id}">${esc(s.name)}</h3>${UI.addBtn('assessments', 'Avaliação', { subject: s.id }, 'xs')}</div>
      <div class="row gap16" style="flex-wrap:wrap;margin-bottom:8px"><div><div class="big-num" style="font-size:28px">${cur0 == null ? '—' : U.nf(cur0, 1)}</div><small class="mut">média do que já fizeste (${U.nf(W)}% avaliado)</small></div><div><div class="big-num" style="font-size:28px">${simF == null ? '—' : U.nf(simF, 1)}</div><small class="mut">final simulada</small></div></div>
      ${Wall && Math.abs(Wall - 100) > .5 ? `<p class="warn" style="font-size:12.5px;margin:0 0 8px">Os pesos somam ${U.nf(Wall)}% (deviam somar 100%).</p>` : ''}
      ${R > 0 ? `<div class="eyebrow">Média que precisas nos ${U.nf(R)}% que faltam para…</div><div class="un-needs">${nd(9.5, 'Passar (9,5)')}${nd(tgt, 'Alvo (' + tgt + ')')}${nd(14, '14')}${nd(17, '17')}</div>` : ''}
      <div class="list" style="margin-top:8px">${As.map(a => { const g = a.grade !== '' && a.grade != null; return `<div class="li"><div class="li-t click" data-edit="assessments:${a.id}"><b>${esc(a.title)}</b><small>${esc(a.type || '')} · ${a.date ? U.fmtDS(a.date) : 'sem data'} · peso ${a.weight || 0}%</small></div><div class="li-r">${g ? `<span class="mono ${+a.grade >= 9.5 ? 'pos' : 'neg'}">${a.grade}</span>` : `<input class="field un-wi" type="number" min="0" max="20" step=".1" placeholder="e se…" value="${esc(wi[a.id] == null ? '' : wi[a.id])}" data-wi="${a.id}" aria-label="Nota simulada para ${esc(a.title)}">`}</div></div>`; }).join('') || '<p class="mut" style="font-size:13px">Sem avaliações. Junta os testes, trabalhos e exames com o peso de cada um.</p>'}</div></div>`; }).join('')}</div>`; };
document.addEventListener('change', e => { const k = e.target.dataset && e.target.dataset.wi; if (!k) return; OS.setUI('wi', Object.assign({}, OS.ui.wi || {}, { [k]: e.target.value })); });

/* ================= PLANO PARA EXAMES ================= */
const planFor = a => { const t = today(), days = Math.max(1, U.diff(a.date, t)), s = OS.get('subjects', a.subject) || {}, tops = OS.all('topics').filter(x => x.subject === a.subject && x.status !== 'Dominado'), out = [];
  const w = +a.weight || 30, diff = { Baixa: .8, Média: 1, Alta: 1.3 }[s.diff] || 1, mins = Math.round(Math.min(180, Math.max(30, (w / 100) * 600 * diff / Math.max(3, days) * 4)) / 5) * 5;
  const studyDays = Math.max(1, Math.floor((days - 1) * .7)), list = tops.length ? tops.map(x => x.title) : ['Matéria da avaliação (lista os conteúdos na aba Disciplinas)'];
  for (let i = 0; i < days; i++) { const d = U.addDays(t, i); let items;
    if (i === days - 1) items = ['Simulado completo em condições de exame', 'Rever o caderno de erros', 'Dormir cedo'];
    else if (i < studyDays) { const per = Math.ceil(list.length / studyDays), sl = list.slice(i * per, i * per + per); items = sl.length ? sl.map(x => 'Estudar: ' + x).concat(i % 3 === 2 ? ['Flashcards do que estudaste'] : []) : ['Exercícios práticos', 'Flashcards']; }
    else items = ['Revisão: ' + list.slice((i - studyDays) % list.length, (i - studyDays) % list.length + 2).join(', '), 'Exercícios de exames antigos', 'Flashcards'];
    out.push({ d, items, mins: i === days - 1 ? Math.round(mins * 1.2 / 5) * 5 : mins }); }
  return out; };
UNI.exames = () => { const t = today(), up = U.sortBy(OS.all('assessments').filter(a => a.date >= t && a.prep !== 'Feito'), a => a.date), pk = OS.get('assessments', OS.ui.uePick) || up[0];
  if (!up.length) return UI.empty('Sem avaliações futuras. Regista os testes e exames com a data e o peso.', UI.addBtn('assessments', 'Nova avaliação', null, ''));
  const P = pk ? planFor(pk) : [], d = pk ? U.diff(pk.date, t) : 0, made = pk && OS.all('tasks').some(x => x.examPlan === pk.id);
  return `<div class="row gap6" style="flex-wrap:wrap;margin-bottom:10px">${up.slice(0, 10).map(a => UI.chip(`${esc(a.title)} · ${U.diff(a.date, t)} d`, 'uePick', pk && pk.id === a.id, `data-id="${a.id}"`)).join('')}</div>
  ${pk ? `<div class="pn un-ex"><div class="row between gap8" style="flex-wrap:wrap"><div><div class="eyebrow">${esc(subjN(pk.subject))} · ${esc(pk.type || '')}${pk.weight ? ' · ' + pk.weight + '%' : ''}</div><h3 style="margin:2px 0">${esc(pk.title)}</h3><small class="mut">${U.longDate(pk.date)}${pk.time ? ' às ' + pk.time : ''} · ${d === 0 ? 'é hoje!' : 'faltam ' + d + (d === 1 ? ' dia' : ' dias')}</small></div>
      <div class="row gap6" style="flex-wrap:wrap"><select class="field" data-prep="${pk.id}" style="width:auto" aria-label="Preparação">${['Não comecei', 'A preparar', 'Pronto', 'Feito'].map(o => `<option${(pk.prep || 'Não comecei') === o ? ' selected' : ''}>${o}</option>`).join('')}</select><button class="btn sm ${made ? 'ghost' : 'pri'}" data-act="uePlanTasks" data-id="${pk.id}">${made ? '✓ Plano nas tarefas' : 'Pôr o plano nas tarefas'}</button><button class="btn sm" data-act="ueFocus" data-s="${pk.subject}">Focar</button></div></div>
      <div class="un-plan">${P.map((x, i) => `<div class="un-pd ${x.d === t ? 'today' : ''} ${i === P.length - 1 ? 'last' : ''}"><div class="un-pdd"><b>${x.d === t ? 'Hoje' : U.WDS[U.parse(x.d).getDay()] + ' ' + (+x.d.slice(8))}</b><small>${x.mins} min</small></div><div>${x.items.map(it => `<div class="un-pit">${esc(it)}</div>`).join('')}</div></div>`).join('')}<div class="un-pd exam"><div class="un-pdd"><b>${U.WDS[U.parse(pk.date).getDay()]} ${+pk.date.slice(8)}</b><small></small></div><div><div class="un-pit"><b>${esc(pk.title)}</b> — confia no que preparaste.</div></div></div></div></div>` : ''}`; };
A.uePick = b => OS.setUI('uePick', b.dataset.id);
A.ueFocus = b => { const c = OS.one('forest'); c.tag = 's:' + b.dataset.s; OS.touch('forest'); location.hash = 'floresta'; };
A.uePlanTasks = b => { const a = OS.get('assessments', b.dataset.id); if (!a) return; if (OS.all('tasks').some(x => x.examPlan === a.id)) return UI.toast('O plano já está nas tarefas', ''); planFor(a).forEach(x => OS.add('tasks', { title: `${subjN(a.subject)}: ${x.items[0]}`, sched: x.d, status: 'Próxima', prio: U.diff(a.date, x.d) <= 3 ? '1' : '2', area: 'Universidade', subject: a.subject, effort: String(x.mins), notes: x.items.join('\n'), examPlan: a.id, ctx: ['@Estudos'] }, { silent: true })); if (a.prep === 'Não comecei') OS.upd('assessments', a.id, { prep: 'A preparar' }); OS.request(); UI.toast('Plano de estudo posto nas tarefas e no calendário', 'pos'); };
document.addEventListener('change', e => { const k = e.target.dataset && e.target.dataset.prep; if (k) OS.upd('assessments', k, { prep: e.target.value }); });

/* ================= FLASHCARDS (SM-2) ================= */
const sm2 = (c, q) => { let ef = +c.ef || 2.5, iv = +c.iv || 0, reps = +c.reps || 0, lapses = +c.lapses || 0;
  if (q < 3) { reps = 0; iv = 0; lapses++; } else { reps++; iv = reps === 1 ? 1 : reps === 2 ? (q === 5 ? 4 : 3) : Math.round(iv * ef * (q === 3 ? .85 : q === 5 ? 1.3 : 1)); }
  ef = Math.max(1.3, ef + (.1 - (5 - q) * (.08 + (5 - q) * .02))); return { ef: U.r2 ? U.r2(ef) : Math.round(ef * 100) / 100, iv, reps, lapses, due: U.addDays(today(), iv), last: today() }; };
const ivLabel = n => n === 0 ? '<1 d' : n < 30 ? n + ' d' : n < 365 ? Math.round(n / 30) + ' m' : U.nf(n / 365, 1) + ' a';
let FC = null; // sessão: { ids, i, show, done, again }
A.fcStart = b => { const sid = (b && b.dataset && b.dataset.s) || OS.ui.fcS || '', ids = U.sortBy(due(sid), c => c.due || '').map(c => c.id).slice(0, 200); if (!ids.length) { UI.toast('Nada para rever agora', 'pos'); return; } FC = { ids, i: 0, show: false, done: 0, again: 0, sid }; if (location.hash !== '#universidade.flashcards') location.hash = 'universidade.flashcards'; else OS.request(); };
A.fcFlip = () => { if (FC) { FC.show = true; OS.request(); } };
A.fcRate = b => { if (!FC) return; const c = OS.get('cards', FC.ids[FC.i]), q = +b.dataset.q; if (c) { OS.upd('cards', c.id, sm2(c, q), { silent: true }); if (q < 3) { FC.ids.push(c.id); FC.again++; } } FC.done++; FC.i++; FC.show = false; if (FC.i >= FC.ids.length) { UI.toast(`Sessão feita: ${FC.done} cartões`, 'pos'); FC = null; } OS.request(); };
A.fcStop = () => { FC = null; OS.request(); };
document.addEventListener('keydown', e => { if (!FC || !/flashcards/.test(location.hash) || /INPUT|TEXTAREA|SELECT/.test((e.target || {}).tagName)) return; if (e.key === ' ' && !FC.show) { e.preventDefault(); A.fcFlip(); } else if (FC.show && '1234'.includes(e.key)) A.fcRate({ dataset: { q: [1, 3, 4, 5]['1234'.indexOf(e.key)] } }); });
let FCAI = { busy: false, res: null, err: '' };
UNI.flashcards = () => { const sid = OS.ui.fcS || '', all = OS.all('cards'), my = all.filter(c => !sid || c.subject === sid), dd = due(sid), mat = my.filter(c => (+c.iv || 0) >= 21).length, nw = my.filter(c => !+c.reps).length;
  if (FC) { const c = OS.get('cards', FC.ids[FC.i]); if (!c) { FC = null; return UNI.flashcards(); } const left = FC.ids.length - FC.i, p = sm2(c, 1), h = sm2(c, 3), g = sm2(c, 4), ez = sm2(c, 5);
    return `<div class="fc-run"><div class="row between gap8"><small class="mut">${esc(subjN(c.subject))}${c.deck ? ' · ' + esc(c.deck) : ''}</small><small class="mut">${left} por rever · ${FC.done} feitos</small><button class="icon-btn" data-act="fcStop" aria-label="Terminar">${UI.ic('x')}</button></div>${UI.bar(FC.i / FC.ids.length, 'pos')}
      <div class="fc-card ${FC.show ? 'flip' : ''}" data-act="${FC.show ? '' : 'fcFlip'}" role="button" tabindex="0"><div class="fc-f">${md(c.front)}</div>${FC.show ? `<div class="fc-sep"></div><div class="fc-b">${md(c.back)}</div>` : '<small class="mut fc-tap">toca (ou espaço) para ver a resposta</small>'}</div>
      ${FC.show ? `<div class="fc-rates"><button class="fc-r again" data-act="fcRate" data-q="1"><b>De novo</b><small>${ivLabel(p.iv)}</small></button><button class="fc-r hard" data-act="fcRate" data-q="3"><b>Difícil</b><small>${ivLabel(h.iv)}</small></button><button class="fc-r good" data-act="fcRate" data-q="4"><b>Bem</b><small>${ivLabel(g.iv)}</small></button><button class="fc-r easy" data-act="fcRate" data-q="5"><b>Fácil</b><small>${ivLabel(ez.iv)}</small></button></div>` : `<button class="btn pri fc-show" data-act="fcFlip">Mostrar resposta</button>`}</div>`; }
  const decks = U.groupBy(my, c => (c.subject || '') + '|' + (c.deck || ''));
  return `<div class="row gap8" style="flex-wrap:wrap;align-items:center;margin-bottom:10px"><select class="field" style="width:auto" data-uiv="fcS" aria-label="Disciplina">${subjOpts(sid, 'Todas as disciplinas')}</select><span class="grow"></span>${UI.addBtn('cards', 'Flashcard', { subject: sid || (cur()[0] || {}).id || '' }, 'sm')}</div>
  <div class="kpis">${UI.kpi('Para rever hoje', dd.length, '', { tone: dd.length ? 'warn' : 'pos' })}${UI.kpi('Cartões', my.length, nw + ' novos')}${UI.kpi('Dominados', mat, 'intervalo ≥ 21 dias')}${UI.kpi('Retenção', (() => { const r = my.filter(c => +c.reps || +c.lapses); return r.length ? U.pct(1 - U.sum(r, c => +c.lapses || 0) / Math.max(1, U.sum(r, c => (+c.reps || 0) + (+c.lapses || 0)))) : '—'; })())}</div>
  <div class="pn fc-cta"><div><b>${dd.length ? `${dd.length} cartões à tua espera` : 'Tudo revisto por hoje'}</b><small class="mut">Repetição espaçada (SM-2, como o Anki): o que sabes bem volta daqui a semanas; o que erras volta já.</small></div><button class="btn pri" data-act="fcStart" data-s="${sid}" ${dd.length ? '' : 'disabled'}>🃏 Rever agora</button></div>
  <div class="g g2"><div class="pn"><div class="pn-h"><h3>Criar cartões com IA</h3></div>${hasAI() ? `<form data-form="fcAI" class="col gap8"><div class="row gap8" style="flex-wrap:wrap"><select class="field" name="s" style="width:auto">${subjOpts(sid || (cur()[0] || {}).id)}</select><input class="field grow" name="deck" placeholder="Tema / baralho (ex.: IVA)"><select class="field" name="n" style="width:auto">${[8, 12, 20, 30].map(n => `<option>${n}</option>`).join('')}</select></div><textarea class="field" name="t" rows="5" placeholder="Cola aqui os teus apontamentos, um resumo ou só escreve o tema (ex.: 'Depreciações e amortizações — métodos')"></textarea><button class="btn pri" ${FCAI.busy ? 'disabled' : ''}>${FCAI.busy ? 'A criar…' : 'Criar flashcards'}</button></form>
      ${FCAI.err ? `<p class="neg">${esc(FCAI.err)}</p>` : ''}${FCAI.res ? `<div class="fc-prev">${FCAI.res.cards.map((c, i) => `<label class="fc-pi"><input type="checkbox" data-fcp="${i}" ${c.on !== false ? 'checked' : ''}><div><b>${esc(c.f)}</b><small>${esc(c.b)}</small></div></label>`).join('')}</div><div class="row gap8"><button class="btn pri" data-act="fcAIAdd">Guardar ${FCAI.res.cards.filter(c => c.on !== false).length} cartões</button><button class="btn ghost" data-act="fcAIX">Descartar</button></div>` : ''}` : noAI()}</div>
    <div class="pn"><div class="pn-h"><h3>Importar em lote</h3></div><form data-form="fcBulk" class="col gap8"><div class="row gap8" style="flex-wrap:wrap"><select class="field" name="s" style="width:auto">${subjOpts(sid || (cur()[0] || {}).id)}</select><input class="field grow" name="deck" placeholder="Baralho"></div><textarea class="field" name="t" rows="5" placeholder="Uma por linha:  pergunta ; resposta&#10;Ativo = ? ; Passivo + Capital Próprio&#10;(também aceita tabulação ou ' :: ', como no Anki/Quizlet)"></textarea><button class="btn">Importar</button></form></div></div>
  <section><div class="sech"><h2>Baralhos</h2></div>${Object.keys(decks).length ? `<div class="g g3">${Object.entries(decks).map(([k, cs]) => { const [s, dk] = k.split('|'), d2 = cs.filter(c => (c.due || today()) <= today()).length; return `<div class="pn fc-deck"><div class="eyebrow">${esc(subjN(s))}</div><b>${esc(dk || 'Geral')}</b><small class="mut">${cs.length} cartões · ${d2} para hoje · ${cs.filter(c => (+c.iv || 0) >= 21).length} dominados</small>${UI.bar(cs.filter(c => (+c.iv || 0) >= 21).length / cs.length, 'pos')}<details class="fc-list"><summary>ver cartões</summary>${cs.slice(0, 60).map(c => `<div class="li click" data-edit="cards:${c.id}"><div class="li-t"><b>${esc(c.front.slice(0, 90))}</b><small>${esc(c.back.slice(0, 90))} · próxima ${U.fmtDS(c.due || today())}</small></div></div>`).join('')}</details></div>`; }).join('')}</div>` : UI.empty('Ainda sem flashcards. Cria com a IA a partir dos teus apontamentos, importa em lote ou adiciona um a um.')}</section>`; };
OS.forms = OS.forms || {};
const parseBulk = t => String(t || '').split(/\n+/).map(l => l.trim()).filter(Boolean).map(l => { const m = l.split(/\t| :: |\s*;\s*|\s+—\s+/); return m.length >= 2 ? { f: m[0].trim(), b: m.slice(1).join('; ').trim() } : null; }).filter(x => x && x.f && x.b);
OS.forms.fcBulk = (f, v) => { const L = parseBulk(f.elements.t.value); if (!L.length) return UI.toast('Escreve uma por linha: pergunta ; resposta', 'neg'); L.forEach(c => OS.add('cards', { subject: v('s'), deck: v('deck'), front: c.f, back: c.b, ef: 2.5, iv: 0, reps: 0, lapses: 0, due: today() }, { silent: true })); OS.request(); UI.toast(L.length + ' flashcards importados', 'pos'); };
OS.forms.fcAI = async (f, v) => { if (FCAI.busy) return; const s = v('s'), deck = v('deck'), n = +v('n') || 12, t = f.elements.t.value.trim(); if (!t && !deck) return UI.toast('Escreve o tema ou cola os apontamentos', 'neg');
  FCAI = { busy: true, res: null, err: '' }; OS.request();
  try { const o = await OS.AI.json([{ text: `És um professor universitário em Portugal (curso: ${OS.one('profile').course || OS.one('profile').uni || 'universidade'}). Cria ${n} flashcards excelentes para estudar "${subjN(s)}"${deck ? ' — tema: ' + deck : ''}, em português de Portugal.
Regras: uma ideia por cartão; pergunta curta e precisa na frente; resposta correta, curta e completa no verso (pode ter fórmula ou exemplo); mistura definições, porquês, fórmulas, exemplos numéricos e armadilhas comuns de exame; não inventes normas/leis — se citares (ex.: SNC, CIVA, IRC), sê exato.
${t ? 'Baseia-te SOBRETUDO neste material:\n"""' + t.slice(0, 12000) + '"""' : ''}
Devolve JSON: {"cartoes":[{"frente":"…","verso":"…"}]}` }], .4);
    const cards = (o.cartoes || []).filter(c => c && c.frente && c.verso).map(c => ({ f: String(c.frente).trim(), b: String(c.verso).trim() }));
    FCAI = { busy: false, res: { s, deck, cards }, err: cards.length ? '' : 'A IA não devolveu cartões. Tenta outra vez.' }; } catch (e) { FCAI = { busy: false, res: null, err: e.message || 'Erro da IA' }; } OS.request(); };
document.addEventListener('change', e => { const i = e.target.dataset && e.target.dataset.fcp; if (i == null || !FCAI.res) return; FCAI.res.cards[+i].on = e.target.checked; });
A.fcAIAdd = () => { if (!FCAI.res) return; const { s, deck, cards } = FCAI.res, ok = cards.filter(c => c.on !== false); ok.forEach(c => OS.add('cards', { subject: s, deck, front: c.f, back: c.b, ef: 2.5, iv: 0, reps: 0, lapses: 0, due: today(), ai: true }, { silent: true })); FCAI = { busy: false, res: null, err: '' }; OS.request(); UI.toast(ok.length + ' flashcards guardados', 'pos'); };
A.fcAIX = () => { FCAI = { busy: false, res: null, err: '' }; OS.request(); };

/* ================= SIMULADOS ================= */
let QZ = null, QB = { busy: false, err: '' };
UNI.simulados = () => { const hist = U.sortBy(OS.all('quizzes'), q => q.date + (q._c || 0), -1);
  if (QZ) { const done = QZ.done, n = QZ.qs.length, ok = done ? QZ.qs.filter(q => q.mine === q.a).length : 0, nota = done ? U.nf(ok / n * 20, 1) : '';
    return `<div class="qz-wrap"><div class="pn"><div class="row between gap8"><div><div class="eyebrow">${esc(subjN(QZ.s))}</div><h3 style="margin:2px 0">${esc(QZ.title)}</h3></div>${done ? `<div class="un-score ${ok / n >= .5 ? 'pos' : 'neg'}"><b>${nota}</b><small>/20 · ${ok} de ${n}</small></div>` : `<small class="mut">${QZ.qs.filter(q => q.mine != null).length} de ${n} respondidas</small>`}</div></div>
      ${QZ.qs.map((q, i) => `<div class="pn qz-q ${done ? (q.mine === q.a ? 'ok' : 'bad') : ''}"><b>${i + 1}. ${md(q.q)}</b><div class="qz-os">${q.o.map((o, j) => `<button class="qz-o ${q.mine === j ? 'on' : ''} ${done && j === q.a ? 'right' : ''} ${done && q.mine === j && j !== q.a ? 'wrong' : ''}" data-act="qzPick" data-i="${i}" data-j="${j}" ${done ? 'disabled' : ''}><span>${'ABCD'[j]}</span>${esc(o)}</button>`).join('')}</div>${done && q.e ? `<div class="qz-exp">${md(q.e)}</div>` : ''}</div>`).join('')}
      <div class="row gap8" style="flex-wrap:wrap">${done ? `<button class="btn pri" data-act="qzErr">Enviar as erradas para o caderno de erros</button><button class="btn" data-act="qzX">Fechar</button>` : `<button class="btn pri" data-act="qzDone">Corrigir</button><button class="btn ghost" data-act="qzX">Cancelar</button>`}</div></div>`; }
  const sid = OS.ui.qzS || (cur()[0] || {}).id || '', tops = OS.all('topics').filter(t => t.subject === sid), nC = OS.all('cards').filter(c => c.subject === sid).length;
  return `<div class="g g2"><div class="pn"><div class="pn-h"><h3>Simulado com IA</h3></div>${hasAI() ? `<form data-form="qzAI" class="col gap8"><div class="row gap8" style="flex-wrap:wrap"><select class="field" name="s" data-uiv="qzS" style="width:auto">${subjOpts(sid)}</select><select class="field" name="n" style="width:auto">${[5, 10, 15, 20].map(n => `<option${n === 10 ? ' selected' : ''}>${n}</option>`).join('')}</select><select class="field" name="d" style="width:auto"><option>Médio</option><option>Fácil</option><option>Difícil (nível exame)</option></select></div>
      ${tops.length ? `<div class="fe-chs">${tops.map(t => `<label class="chip"><input type="checkbox" name="tp" value="${esc(t.title)}" style="margin-right:4px">${esc(t.title)}</label>`).join('')}</div>` : ''}<textarea class="field" name="t" rows="4" placeholder="Opcional: cola a matéria, um resumo ou escreve os temas a testar"></textarea><button class="btn pri" ${QB.busy ? 'disabled' : ''}>${QB.busy ? 'A preparar o simulado…' : 'Gerar simulado'}</button></form>${QB.err ? `<p class="neg">${esc(QB.err)}</p>` : ''}` : noAI()}</div>
    <div class="pn"><div class="pn-h"><h3>🃏 Simulado com os teus flashcards</h3></div><p class="mut" style="font-size:13px">Sem IA: escolha múltipla feita com as respostas dos teus cartões de ${esc(subjN(sid))} (${nC} cartões).</p><button class="btn" data-act="qzCards" data-s="${sid}" ${nC >= 4 ? '' : 'disabled'}>Começar (${Math.min(10, nC)} perguntas)</button>${nC < 4 ? '<small class="mut" style="display:block;margin-top:6px">Precisas de pelo menos 4 flashcards nesta disciplina.</small>' : ''}</div></div>
  ${hist.length ? `<div class="pn"><div class="pn-h"><h3>Evolução</h3></div>${C.mount({ type: 'line', labels: hist.slice(0, 20).reverse().map(q => U.fmtDS(q.date)), series: [{ name: 'Nota', data: hist.slice(0, 20).reverse().map(q => +q.score || 0), color: 'var(--accent)' }], target: 9.5, targetLabel: '9,5' }, 180)}<div class="list">${hist.slice(0, 12).map(q => `<div class="li"><span class="when">${U.fmtDS(q.date)}</span><div class="li-t"><b>${esc(q.title)}</b><small>${esc(subjN(q.subject))} · ${q.correct}/${q.n}</small></div><span class="mono ${+q.score >= 9.5 ? 'pos' : 'neg'}">${U.nf(+q.score, 1)}</span></div>`).join('')}</div></div>` : ''}`; };
OS.forms.qzAI = async (f, v) => { if (QB.busy) return; const s = v('s'), n = +v('n') || 10, dif = v('d'), tp = [...f.querySelectorAll('input[name=tp]:checked')].map(x => x.value), t = f.elements.t.value.trim(); QB = { busy: true, err: '' }; OS.request();
  try { const o = await OS.AI.json([{ text: `És um professor universitário exigente em Portugal. Cria um simulado de ${n} perguntas de escolha múltipla (4 opções, só UMA certa) de "${subjN(s)}", dificuldade: ${dif}, em português de Portugal.${tp.length ? ' Temas: ' + tp.join('; ') + '.' : ''}
Regras: perguntas claras, ao nível de exame universitário; distratores plausíveis (erros típicos); inclui cálculos curtos quando a disciplina for numérica; explicação curta de porque a certa é certa; não inventes normas — se citares legislação/normas, sê exato.
${t ? 'Material de base:\n"""' + t.slice(0, 12000) + '"""' : ''}
Em "tema" põe o conteúdo/tema da disciplina a que a pergunta pertence${tp.length ? ' (usa exatamente um destes nomes: ' + tp.join('; ') + ')' : ''}.
JSON: {"titulo":"…","perguntas":[{"tema":"…","pergunta":"…","opcoes":["…","…","…","…"],"certa":0,"explicacao":"…"}]}` }], .5);
    const qs = (o.perguntas || []).filter(q => q && q.pergunta && Array.isArray(q.opcoes) && q.opcoes.length >= 2).map(q => ({ q: q.pergunta, o: q.opcoes.slice(0, 4).map(String), a: Math.max(0, Math.min(q.opcoes.length - 1, +q.certa || 0)), e: q.explicacao || '', t: q.tema || '', mine: null }));
    if (!qs.length) throw new Error('A IA não devolveu perguntas. Tenta outra vez.'); QZ = { s, title: o.titulo || 'Simulado · ' + subjN(s), qs, done: false, ai: true }; QB = { busy: false, err: '' }; } catch (e) { QB = { busy: false, err: e.message || 'Erro' }; } OS.request(); };
A.qzCards = b => { return qzCards(b); };
const qzCards = b => { const s = b.dataset.s, cs = OS.all('cards').filter(c => c.subject === s); if (cs.length < 4) return; const pickN = U.sortBy(cs, () => Math.random()).slice(0, 10);
  QZ = { s, title: 'Simulado de flashcards · ' + subjN(s), done: false, qs: pickN.map(c => { const wrong = U.sortBy(cs.filter(x => x.id !== c.id && x.back !== c.back), () => Math.random()).slice(0, 3).map(x => x.back), o = U.sortBy([c.back, ...wrong], () => Math.random()); return { q: c.front, o, a: o.indexOf(c.back), e: '', t: c.deck || '', mine: null }; }) }; OS.request(); };
A.qzPick = b => { if (!QZ || QZ.done) return; QZ.qs[+b.dataset.i].mine = +b.dataset.j; OS.request(); };
A.qzDone = () => { if (!QZ) return; const un = QZ.qs.filter(q => q.mine == null).length; const go = () => { QZ.done = true; const ok = QZ.qs.filter(q => q.mine === q.a).length; OS.add('quizzes', { date: today(), subject: QZ.s, title: QZ.title, n: QZ.qs.length, correct: ok, score: Math.round(ok / QZ.qs.length * 200) / 10, qs: QZ.qs.map(q => ({ q: q.q, t: q.t || '', a: q.o[q.a], mine: q.mine == null ? '' : q.o[q.mine] })) }); logAnswers(QZ); OS.request(); window.scrollTo(0, 0); };
  if (un) UI.ask('Corrigir já?', `Tens ${un} pergunta(s) sem resposta — contam como erradas.`, 'Corrigir', go, 'pri'); else go(); };
A.qzErr = () => { if (!QZ) return; const w = QZ.qs.filter(q => q.mine !== q.a); w.forEach(q => OS.add('errors', { title: q.q.slice(0, 140), subject: QZ.s, date: today(), type: q.mine == null ? 'Falta de tempo' : 'Não sabia a matéria', why: q.mine == null ? 'Não respondi' : 'Respondi: ' + q.o[q.mine], right: q.o[q.a] + (q.e ? ' — ' + q.e : ''), rule: '', redone: false }, { silent: true })); OS.request(); UI.toast(w.length + ' erro(s) no caderno de erros', 'pos'); QZ = null; };
A.qzX = () => { QZ = null; OS.request(); };

/* ================= TUTOR IA ================= */
const TM = [['explicar', 'Explica-me simples'], ['passo', 'Passo a passo'], ['exemplos', 'Exemplos práticos'], ['resumo', 'Resumir texto'], ['feynman', 'Feynman: eu explico, tu corriges'], ['mapa', 'Mapa mental'], ['exercicios', 'Exercícios resolvidos'], ['duvida', 'Tirar uma dúvida']];
const TP = { explicar: 'Explica de forma muito simples (como a um amigo inteligente que nunca ouviu falar disto), com uma analogia do dia a dia e depois a versão técnica correta.', passo: 'Explica passo a passo, numerado, sem saltar passos, com um exemplo resolvido no fim.', exemplos: 'Dá 3 exemplos práticos e realistas (em Portugal, com euros quando fizer sentido), do mais simples ao mais exigente.', resumo: 'Faz um resumo de estudo do texto: ideias-chave em tópicos, conceitos a decorar, fórmulas e 3 perguntas de autoavaliação.', feynman: 'O aluno vai explicar o conceito por palavras dele. Avalia com honestidade: o que está certo, o que está errado ou vago, o que falta, e dá uma nota de 0 a 10 à explicação e a versão corrigida.', mapa: 'Cria um mapa mental em texto: tema central e ramos/sub-ramos em lista indentada com "-", com palavras-chave.', exercicios: 'Cria 3 exercícios ao nível de exame universitário e resolve cada um detalhadamente.', duvida: 'Responde à dúvida de forma direta e certa; se houver uma armadilha comum, avisa.' };
const TK = 'oc_tutor1'; let TU = U.ls.get(TK, { log: [] }), TB = false;
UNI.tutor = () => { const sid = OS.ui.tuS || (cur()[0] || {}).id || '', mode = OS.ui.tuM || 'explicar';
  return `${hasAI() ? '' : noAI()}<div class="pn"><form data-form="tutor" class="col gap8"><div class="row gap8" style="flex-wrap:wrap"><select class="field" name="s" data-uiv="tuS" style="width:auto">${subjOpts(sid, 'Geral')}</select><div class="row gap6" style="flex-wrap:wrap">${TM.map(([k, l]) => UI.chip(l, 'tuM', mode === k, `data-v="${k}" type="button"`)).join('')}</div></div>
    <textarea class="field" name="q" rows="${mode === 'resumo' || mode === 'feynman' ? 7 : 3}" placeholder="${mode === 'resumo' ? 'Cola aqui o texto, os slides ou os apontamentos…' : mode === 'feynman' ? 'Explica o conceito por palavras tuas (ex.: o que é o princípio do acréscimo e porque existe)…' : 'Ex.: O que é o método das quotas constantes nas depreciações?'}"></textarea>
    <div class="row gap8"><button class="btn pri" ${TB || !hasAI() ? 'disabled' : ''}>${TB ? 'A pensar…' : 'Perguntar ao tutor'}</button>${TU.log.length ? '<button type="button" class="btn ghost" data-act="tuClear">Limpar conversa</button>' : ''}</div></form></div>
  ${TB ? `<div class="pn"><div class="sai-busy"><div class="fd-spin"></div><span>O tutor está a preparar a resposta…</span></div></div>` : ''}
  ${TU.log.slice().reverse().map((m, i) => { const idx = TU.log.length - 1 - i; return `<div class="pn tu-m"><div class="tu-q"><span class="bdg out">${esc((TM.find(x => x[0] === m.mode) || [, ''])[1])}</span>${m.s ? ` <span class="mut" style="font-size:12px">${esc(subjN(m.s))}</span>` : ''}<p>${esc(m.q.length > 300 ? m.q.slice(0, 300) + '…' : m.q)}</p></div>${m.err ? `<p class="neg">${esc(m.err)}</p>` : `<div class="tu-a">${m.t ? `<b class="un-h">${esc(m.t)}</b><br>` : ''}${md(m.a)}</div><div class="row gap6" style="flex-wrap:wrap;margin-top:8px"><button class="btn xs ghost" data-act="tuNote" data-i="${idx}">Guardar na Knowledge Base</button><button class="btn xs ghost" data-act="tuCards" data-i="${idx}">Criar flashcards disto</button></div>`}</div>`; }).join('')}`; };
A.tuM = b => OS.setUI('tuM', b.dataset.v);
A.tuClear = () => { TU = { log: [] }; U.ls.set(TK, TU); OS.request(); };
OS.forms.tutor = async (f, v) => { const q = f.elements.q.value.trim(), s = v('s'), mode = OS.ui.tuM || 'explicar'; if (!q || TB) return; TB = true; OS.request(); const ent = { q, s, mode, d: today() };
  try { const ctx = TU.log.slice(-3).map(m => `Pergunta anterior: ${m.q.slice(0, 400)}\nResposta: ${(m.a || '').slice(0, 600)}`).join('\n\n');
    const o = await OS.AI.json([{ text: `És um tutor universitário excelente, paciente e rigoroso, a ajudar o Ryan (estudante em Portugal, ${OS.one('profile').uni || ''}${OS.one('profile').course ? ', curso de ' + OS.one('profile').course : ''}). Disciplina: ${s ? subjN(s) : 'geral'}. Responde em português de Portugal.
Tarefa: ${TP[mode]}
Regras: sê correto acima de tudo; se não tiveres a certeza, diz; se citares normas/leis portuguesas (SNC, CIRC, CIVA…), sê exato; usa **negrito** para conceitos-chave e listas com "- " quando ajudar; sem enchimento.
${ctx ? 'Contexto da conversa:\n' + ctx + '\n' : ''}
${mode === 'feynman' ? 'Explicação do aluno' : mode === 'resumo' ? 'Texto' : 'Pergunta'}:\n"""${q.slice(0, 14000)}"""
JSON: {"titulo":"título curto","resposta":"texto"}` }], .4);
    ent.t = o.titulo || ''; ent.a = o.resposta || ''; } catch (e) { ent.err = e.message || 'Erro da IA'; }
  TU.log.push(ent); TU.log = TU.log.slice(-20); U.ls.set(TK, TU); TB = false; OS.request(); };
A.tuNote = b => { const m = TU.log[+b.dataset.i]; if (!m) return; OS.add('notes', { title: m.t || m.q.slice(0, 80), body: m.a, type: m.mode === 'resumo' ? 'Resumo' : 'Conceito', subject: m.s || '', tags: ['tutor'] }); UI.toast('Guardado na Knowledge Base', 'pos'); };
A.tuCards = b => { const m = TU.log[+b.dataset.i]; if (!m) return; location.hash = 'universidade.flashcards'; setTimeout(() => { const f = document.querySelector('form[data-form=fcAI]'); if (!f) return; if (m.s) f.elements.s.value = m.s; f.elements.deck.value = m.t || ''; f.elements.t.value = m.a; f.scrollIntoView({ behavior: 'smooth', block: 'center' }); }, 150); };

/* ================= MATERIAIS ================= */
const KIC = { Slides: 'layers', 'Sebenta / apontamentos': 'note', Livro: 'book', Exercícios: 'edit', 'Exames antigos': 'checksq', Vídeo: 'play', Artigo: 'news', 'Site / link': 'link', Outro: 'link' };
UNI.materiais = () => { const S = OS.all('subjects').filter(s => s.status === 'Em curso' || OS.all('materials').some(m => m.subject === s.id)), M = OS.all('materials');
  return `<div class="row gap8" style="margin-bottom:10px">${UI.addBtn('materials', 'Material')}<span class="mut" style="font-size:12.5px">Slides, sebentas, exames antigos, vídeos e links do Moodle — tudo à mão, por disciplina.</span></div>
  ${S.length ? `<div class="g g2">${S.map(s => { const ms = M.filter(m => m.subject === s.id); return `<div class="pn"><div class="pn-h"><h3>${esc(s.name)}</h3>${s.moodle ? `<a class="btn xs ghost" href="${esc(s.moodle)}" target="_blank" rel="noopener">Moodle ↗</a>` : ''}${UI.addBtn('materials', '', { subject: s.id }, 'xs ghost')}</div>${ms.length ? `<div class="list">${ms.map(m => `<div class="li"><span class="un-mi">${UI.ic(KIC[m.kind] || 'link')}</span><div class="li-t click" data-edit="materials:${m.id}"><b>${esc(m.title)}</b><small>${esc(m.kind || '')}${m.notes ? ' · ' + esc(m.notes.slice(0, 60)) : ''}</small></div>${m.url ? `<a class="btn xs" href="${esc(m.url)}" target="_blank" rel="noopener">Abrir</a>` : ''}</div>`).join('')}</div>` : '<p class="mut" style="font-size:13px">Sem materiais.</p>'}</div>`; }).join('')}</div>` : UI.empty('Sem disciplinas em curso.')}`; };

/* ================= PRESENÇAS ================= */
UNI.presencas = () => { const S = cur();
  return `<div class="note">Conta as faltas de cada disciplina. Define o limite (ex.: aulas práticas com presença obrigatória) para seres avisado antes de chegar lá.</div>
  ${S.length ? `<div class="g g3">${S.map(s => { const n = +s.abs || 0, mx = +s.absMax || 0, p = mx ? n / mx : 0; return `<div class="pn un-abs"><div class="pn-h"><h3 class="click" data-edit="subjects:${s.id}">${esc(s.name)}</h3></div><div class="row between" style="align-items:center"><div><div class="big-num ${p >= 1 ? 'neg' : p >= .75 ? 'warn' : ''}" style="font-size:32px">${n}${mx ? `<span class="mut" style="font-size:16px"> / ${mx}</span>` : ''}</div><small class="mut">${mx ? (p >= 1 ? '<span class="neg">limite atingido!</span>' : `podes faltar mais ${mx - n}`) : 'sem limite definido'}</small></div><div class="row gap6"><button class="btn sm" data-act="absD" data-id="${s.id}" data-d="-1" aria-label="Menos uma falta">−</button><button class="btn sm pri" data-act="absD" data-id="${s.id}" data-d="1" aria-label="Mais uma falta">+ falta</button></div></div>${mx ? UI.bar(Math.min(1, p), p >= 1 ? 'neg' : p >= .75 ? 'warn' : 'pos') : `<button class="btn xs ghost" data-edit="subjects:${s.id}" style="margin-top:8px">Definir limite</button>`}</div>`; }).join('')}</div>` : UI.empty('Sem disciplinas em curso.')}`; };
A.absD = b => { const s = OS.get('subjects', b.dataset.id); if (!s) return; const n = Math.max(0, (+s.abs || 0) + +b.dataset.d); OS.upd('subjects', s.id, { abs: n }); if (+s.absMax && n >= +s.absMax * .75 && +b.dataset.d > 0) UI.toast(n >= +s.absMax ? `Atingiste o limite de faltas em ${s.name}!` : `Atenção: ${n} de ${s.absMax} faltas em ${s.name}`, n >= +s.absMax ? 'neg' : 'warn'); };

/* ================= BANCO DE QUESTÕES ================= */
OS.S.qbank = { label: 'Questão', title: r => r.q, fields: [
  { k: 'subject', l: 'Disciplina', t: 'sel', o: () => OS.all('subjects').map(s => [s.id, s.name]), req: 1 }, { k: 'topic', l: 'Conteúdo / tema', t: 'text' },
  { k: 'q', l: 'Pergunta', t: 'area', rows: 2, req: 1 }, { k: 'o1', l: 'Opção A (certa)', t: 'text', req: 1 }, { k: 'o2', l: 'Opção B', t: 'text', req: 1 }, { k: 'o3', l: 'Opção C', t: 'text' }, { k: 'o4', l: 'Opção D', t: 'text' },
  { k: 'exp', l: 'Explicação', t: 'area', rows: 2 }, { k: 'diff', l: 'Dificuldade', t: 'sel', o: ['Fácil', 'Médio', 'Difícil'] }], defaults: () => ({ diff: 'Médio', src: 'manual' }) };
OS.S.qlog = { label: 'Resposta', title: r => r.topic || 'Resposta', fields: [{ k: 'date', l: 'Data', t: 'date' }, { k: 'topic', l: 'Tema', t: 'text' }, { k: 'ok', l: 'Certa', t: 'bool' }] };
const qOpts = b => b.opts || [b.o1, b.o2, b.o3, b.o4].filter(Boolean);
const qAns = b => b.opts ? (+b.a || 0) : 0;
function logAnswers(Z) { Z.qs.forEach(q => { OS.add('qlog', { date: today(), subject: Z.s, topic: q.t || '', ok: q.mine === q.a, bid: q.bid || '', src: Z.src || (Z.ai ? 'simulado' : 'flashcards') }, { silent: true }); if (q.bid) { const b = OS.get('qbank', q.bid); if (b) OS.upd('qbank', b.id, { n: (+b.n || 0) + 1, ok: (+b.ok || 0) + (q.mine === q.a ? 1 : 0), last: today() }, { silent: true }); } }); }
add('simulados', 'questoes', 'Banco de questões'); add('questoes', 'desempenho', 'Desempenho');
let QG = { busy: false, err: '' };
UNI.questoes = () => { if (QZ) return UNI.simulados(); const sid = OS.ui.qbS || (cur()[0] || {}).id || '', B = OS.all('qbank').filter(b => b.subject === sid), tops = OS.all('topics').filter(t => t.subject === sid), byT = U.groupBy(B, b => b.topic || 'Geral');
  const acc = a => { const n = U.sum(a, b => +b.n || 0); return n ? U.sum(a, b => +b.ok || 0) / n : null; };
  return `<div class="row gap8" style="flex-wrap:wrap;align-items:center;margin-bottom:10px"><select class="field" style="width:auto" data-uiv="qbS" aria-label="Disciplina">${subjOpts(sid)}</select><span class="grow"></span>${UI.addBtn('qbank', 'Questão', { subject: sid }, 'sm')}</div>
  <div class="kpis">${UI.kpi('Questões no banco', B.length)}${UI.kpi('Respondidas', U.sum(B, b => +b.n || 0))}${UI.kpi('Acerto', acc(B) == null ? '—' : U.pct(acc(B)), '', { tone: acc(B) == null ? '' : acc(B) >= .7 ? 'pos' : acc(B) >= .5 ? 'warn' : 'neg' })}${UI.kpi('Temas', Object.keys(byT).length)}</div>
  <div class="g g2"><div class="pn"><div class="pn-h"><h3>Gerar questões com IA</h3></div>${hasAI() ? `<form data-form="qbAI" class="col gap8"><input type="hidden" name="s" value="${sid}"><div class="row gap8" style="flex-wrap:wrap"><select class="field" name="t" style="width:auto">${tops.map(t => `<option>${esc(t.title)}</option>`).join('')}<option value="">Outro tema (escreve abaixo)</option></select><select class="field" name="n" style="width:auto">${[5, 10, 20].map(n => `<option${n === 10 ? ' selected' : ''}>${n}</option>`).join('')}</select><select class="field" name="d" style="width:auto"><option>Médio</option><option>Fácil</option><option>Difícil</option></select></div><textarea class="field" name="x" rows="3" placeholder="Opcional: outro tema ou cola a matéria/exercícios do professor"></textarea><button class="btn pri" ${QG.busy ? 'disabled' : ''}>${QG.busy ? 'A gerar…' : 'Gerar e guardar no banco'}</button></form>${QG.err ? `<p class="neg">${esc(QG.err)}</p>` : ''}${tops.length ? '' : '<small class="mut">Dica: junta os conteúdos da disciplina (aba Disciplinas) para escolher por tema.</small>'}` : noAI()}</div>
    <div class="pn"><div class="pn-h"><h3>✍️ Praticar</h3></div><p class="mut" style="font-size:13px">Cada resposta conta para as estatísticas do tema.</p><div class="row gap8" style="flex-wrap:wrap"><button class="btn pri" data-act="qbPlay" data-m="weak" ${B.length ? '' : 'disabled'}>Treinar os meus pontos fracos</button><button class="btn" data-act="qbPlay" data-m="new" ${B.some(b => !+b.n) ? '' : 'disabled'}>Questões novas</button><button class="btn ghost" data-act="qbPlay" data-m="all" ${B.length ? '' : 'disabled'}>Aleatório</button></div></div></div>
  ${Object.keys(byT).length ? `<section><div class="sech"><h2>Por tema</h2></div><div class="g g3">${Object.entries(byT).map(([t, a]) => { const x = acc(a); return `<div class="pn qb-t"><b>${esc(t)}</b><small class="mut">${a.length} questões · ${U.sum(a, b => +b.n || 0)} respostas</small>${x == null ? '<small class="mut">ainda por praticar</small>' : UI.bar(x, x >= .7 ? 'pos' : x >= .5 ? 'warn' : 'neg')}<div class="row between" style="margin-top:6px"><span class="mono ${x == null ? '' : x >= .7 ? 'pos' : x >= .5 ? 'warn' : 'neg'}">${x == null ? '—' : U.pct(x)}</span><button class="btn xs" data-act="qbPlay" data-m="topic" data-t="${esc(t)}">Praticar</button></div></div>`; }).join('')}</div></section>` : UI.empty('O banco está vazio. Gera questões com a IA por tema ou adiciona as tuas (de exames antigos, fichas do professor…).')}`; };
OS.forms.qbAI = async (f, v) => { if (QG.busy) return; const s = v('s'), t = v('t') || v('x').slice(0, 80) || 'Geral', n = +v('n') || 10, d = v('d'), x = f.elements.x.value.trim(); QG = { busy: true, err: '' }; OS.request();
  try { const o = await OS.AI.json([{ text: `És um professor universitário em Portugal. Cria ${n} questões de escolha múltipla (4 opções, uma certa) de "${subjN(s)}", tema "${t}", dificuldade ${d}, ao nível de exame, em português de Portugal. Varia: conceitos, aplicação, cálculo (se fizer sentido), casos práticos e armadilhas comuns. Explicação curta. Não inventes normas.${x ? '\nMaterial:\n"""' + x.slice(0, 10000) + '"""' : ''}
JSON: {"questoes":[{"pergunta":"…","opcoes":["…","…","…","…"],"certa":0,"explicacao":"…"}]}` }], .5);
    const L = (o.questoes || []).filter(q => q && q.pergunta && Array.isArray(q.opcoes) && q.opcoes.length >= 2); if (!L.length) throw new Error('A IA não devolveu questões. Tenta outra vez.');
    L.forEach(q => OS.add('qbank', { subject: s, topic: t, q: q.pergunta, opts: q.opcoes.slice(0, 4).map(String), a: Math.max(0, Math.min(q.opcoes.length - 1, +q.certa || 0)), exp: q.explicacao || '', diff: d, src: 'IA', n: 0, ok: 0 }, { silent: true })); QG = { busy: false, err: '' }; UI.toast(L.length + ' questões no banco de "' + t + '"', 'pos'); } catch (e) { QG = { busy: false, err: e.message || 'Erro' }; } OS.request(); };
A.qbPlay = b => { const sid = OS.ui.qbS || (cur()[0] || {}).id || '', m = b.dataset.m; let B = OS.all('qbank').filter(x => x.subject === sid); const accq = x => +x.n ? (+x.ok || 0) / +x.n : .5;
  if (m === 'topic') B = B.filter(x => (x.topic || 'Geral') === b.dataset.t); if (m === 'new') B = B.filter(x => !+x.n); if (m === 'weak') B = U.sortBy(B, x => accq(x) + Math.random() * .15);
  else B = U.sortBy(B, () => Math.random()); B = B.slice(0, 10); if (!B.length) return UI.toast('Sem questões para isto', 'neg');
  QZ = { s: sid, src: 'banco', title: (m === 'weak' ? 'Pontos fracos' : m === 'topic' ? b.dataset.t : 'Prática') + ' · ' + subjN(sid), done: false, qs: B.map(x => { const o = qOpts(x), a = qAns(x), idx = U.sortBy(o.map((_, i) => i), () => Math.random()); return { q: x.q, o: idx.map(i => o[i]), a: idx.indexOf(a), e: x.exp || '', t: x.topic || 'Geral', bid: x.id, mine: null }; }) }; OS.request(); window.scrollTo(0, 0); };

/* ================= DESEMPENHO ================= */
const perf = sid => { const t = today(), T = {}, key = x => (x || 'Geral').trim(), get = k => T[k] || (T[k] = { t: k, n: 0, ok: 0, rec: 0, recOk: 0, err: 0, status: '', flash: 0, lapses: 0 });
  OS.all('topics').filter(x => x.subject === sid).forEach(x => get(key(x.title)).status = x.status);
  OS.all('qlog').filter(l => l.subject === sid).forEach(l => { const o = get(key(l.topic)); o.n++; if (l.ok) o.ok++; if (l.date >= U.addDays(t, -14)) { o.rec++; if (l.ok) o.recOk++; } });
  OS.all('errors').filter(e => e.subject === sid && !e.redone).forEach(e => { const m = Object.keys(T).find(k => k !== 'Geral' && (e.title + ' ' + (e.why || '')).toLowerCase().includes(k.toLowerCase())); get(m || 'Geral').err++; });
  OS.all('cards').filter(c => c.subject === sid).forEach(c => { const o = get(key(c.deck)); o.flash++; o.lapses += +c.lapses || 0; });
  const next = U.sortBy(OS.all('assessments').filter(a => a.subject === sid && a.date >= t && a.prep !== 'Feito'), a => a.date)[0], days = next ? U.diff(next.date, t) : 99;
  const L = Object.values(T).map(o => { const acc = o.n ? o.ok / o.n : null, why = [];
    let sc = 0; if (acc != null) { sc += (1 - acc) * 60; if (acc < .6) why.push(`acertas só ${U.pct(acc)} das questões`); } else { sc += 25; why.push('ainda não praticaste questões'); }
    if (o.status === 'Por estudar') { sc += 25; why.push('conteúdo por estudar'); } if (o.err) { sc += o.err * 6; why.push(`${o.err} erro(s) por refazer`); } if (o.lapses > 2) { sc += o.lapses * 2; why.push(`esqueces flashcards (${o.lapses}×)`); }
    if (o.rec >= 3 && o.recOk / o.rec < (acc || 0) - .1) { sc += 10; why.push('pioraste nas últimas 2 semanas'); } if (days <= 14) sc *= 1.3;
    return Object.assign(o, { acc, sc: Math.round(sc), why }); });
  return { L: U.sortBy(L, o => -o.sc), next, days }; };
UNI.desempenho = () => { const sid = OS.ui.dpS || (cur()[0] || {}).id || ''; if (!sid) return UI.empty('Sem disciplinas em curso.'); const s = OS.get('subjects', sid), x = St.stats(s), P = perf(sid), Q = OS.all('quizzes').filter(q => q.subject === sid), G = OS.all('assessments').filter(a => a.subject === sid && a.grade !== '' && a.grade != null), lg = OS.all('qlog').filter(l => l.subject === sid), rec = U.ls.get('oc_dprec_' + sid, null);
  const wks = Array.from({ length: 8 }, (_, i) => U.addDays(U.monday(today()), -7 * (7 - i))), wAcc = wks.map(w => { const a = lg.filter(l => l.date >= w && l.date <= U.addDays(w, 6)); return a.length ? Math.round(a.filter(l => l.ok).length / a.length * 100) : null; });
  const top = P.L.filter(o => o.sc > 0).slice(0, 6);
  return `<div class="row gap8" style="flex-wrap:wrap;align-items:center;margin-bottom:10px"><select class="field" style="width:auto" data-uiv="dpS" aria-label="Disciplina">${subjOpts(sid)}</select>${P.next ? `<span class="bdg ${P.days <= 7 ? 'neg' : 'warn'}">${esc(P.next.title)} daqui a ${P.days} dias</span>` : ''}</div>
  <div class="kpis">${UI.kpi('Média nas provas', x.avg || '—', 'alvo ' + x.tgt, { tone: x.avg ? (x.avg >= x.tgt ? 'pos' : x.avg >= 9.5 ? 'warn' : 'neg') : '' })}${UI.kpi('Acerto nas questões', lg.length ? U.pct(lg.filter(l => l.ok).length / lg.length) : '—', lg.length + ' respostas')}${UI.kpi('Simulados', Q.length ? U.nf(U.avg(Q, q => +q.score || 0), 1) : '—', Q.length + ' feitos · média /20')}${UI.kpi('Erros por refazer', x.errors, '', { tone: x.errors ? 'warn' : '' })}</div>
  <div class="pn"><div class="pn-h"><h3>Onde tens de melhorar</h3><span class="mut" style="font-size:12px">ordenado por prioridade</span></div>${top.length ? top.map((o, i) => `<div class="dp-w"><div class="dp-r">${i + 1}</div><div class="grow" style="min-width:0"><b>${esc(o.t)}</b>${o.acc != null ? ` <span class="mono ${o.acc >= .7 ? 'pos' : o.acc >= .5 ? 'warn' : 'neg'}">${U.pct(o.acc)}</span>` : ''}<small>${esc(o.why.join(' · ') || 'manter o ritmo')}</small>${o.acc != null ? UI.bar(o.acc, o.acc >= .7 ? 'pos' : o.acc >= .5 ? 'warn' : 'neg') : ''}</div><div class="dp-a"><button class="btn xs pri" data-act="dpPractice" data-s="${sid}" data-t="${esc(o.t)}">Praticar</button><button class="btn xs" data-act="dpTutor" data-s="${sid}" data-t="${esc(o.t)}">Explicar</button><a class="btn xs ghost" href="https://www.youtube.com/results?search_query=${encodeURIComponent(o.t + ' ' + s.name + ' aula')}" target="_blank" rel="noopener">Aulas ↗</a></div></div>`).join('') : UI.empty('Faz questões do banco, simulados e regista as notas das provas para veres onde melhorar.', `<a class="btn sm" href="#universidade.questoes">Banco de questões</a>`)}</div>
  <div class="g g2"><div class="pn"><div class="pn-h"><h3>Acerto por tema</h3></div>${P.L.filter(o => o.acc != null).length ? P.L.filter(o => o.acc != null).sort((a, b) => a.acc - b.acc).map(o => `<div class="bar-row" style="grid-template-columns:minmax(90px,170px) 1fr 46px"><span class="l">${esc(o.t)}</span>${UI.bar(o.acc, o.acc >= .7 ? 'pos' : o.acc >= .5 ? 'warn' : 'neg')}<span class="v">${U.pct(o.acc)}</span></div>`).join('') : '<p class="mut">Sem respostas ainda.</p>'}</div>
    <div class="pn"><div class="pn-h"><h3>Evolução</h3></div>${C.mount({ type: 'line', labels: wks.map(w => U.fmtDS(w)), series: [{ name: 'Acerto %', data: wAcc.map(v => v == null ? 0 : v), color: 'var(--accent)' }], target: 70, targetLabel: '70%', empty: 'Pratica para ver a evolução.' }, 170)}${G.length ? `<div class="eyebrow" style="margin-top:8px">Notas das provas</div>${U.sortBy(G, a => a.date).map(a => `<div class="li"><span class="when">${U.fmtDS(a.date)}</span><div class="li-t"><b>${esc(a.title)}</b></div><span class="mono ${+a.grade >= 9.5 ? 'pos' : 'neg'}">${a.grade}</span></div>`).join('')}` : ''}</div></div>
  <div class="pn"><div class="pn-h"><h3>Análise e recomendações da IA</h3><button class="btn sm pri" data-act="dpAI" data-s="${sid}" ${hasAI() && !DPB ? '' : 'disabled'}>${DPB ? 'A analisar…' : rec ? 'Atualizar análise' : 'Analisar o meu desempenho'}</button></div>${hasAI() ? '' : '<p class="mut">Liga a IA para teres análise personalizada.</p>'}
    ${rec && rec.o ? `<p class="sp-p">${md(rec.o.diagnostico || '')}</p>${(rec.o.focos || []).map(fc => `<div class="dp-f"><b>${esc(fc.tema || '')}</b><p>${md(fc.porque || '')}</p>${(fc.exercicios || []).length ? `<div class="eyebrow">Exercícios</div><ul class="sp-ul">${fc.exercicios.map(e => `<li>${esc(e)}</li>`).join('')}</ul>` : ''}${(fc.aulas || []).length ? `<div class="eyebrow">Aulas a ver</div><div class="fe-chs">${fc.aulas.map(q => `<a class="chip" href="https://www.youtube.com/results?search_query=${encodeURIComponent(q)}" target="_blank" rel="noopener">▶ ${esc(q)}</a>`).join('')}</div>` : ''}</div>`).join('')}${(rec.o.dicas || []).length ? `<div class="eyebrow">Dicas</div><ul class="sp-ul">${rec.o.dicas.map(d => `<li>${esc(d)}</li>`).join('')}</ul>` : ''}${rec.o.plano ? `<div class="eyebrow">Plano para esta semana</div><p class="sp-p">${md(rec.o.plano)}</p>` : ''}<small class="mut">${new Date(rec.at).toLocaleString('pt-PT')}</small>` : rec && rec.err ? `<p class="neg">${esc(rec.err)}</p>` : ''}</div>`; };
let DPB = false;
A.dpPractice = b => { OS.setUI('qbS', b.dataset.s); const has = OS.all('qbank').some(x => x.subject === b.dataset.s && (x.topic || 'Geral') === b.dataset.t); location.hash = 'universidade.questoes'; if (has) setTimeout(() => A.qbPlay({ dataset: { m: 'topic', t: b.dataset.t } }), 50); else UI.toast('Gera questões deste tema no banco primeiro', ''); };
A.dpTutor = b => { OS.setUI('tuS', b.dataset.s); OS.setUI('tuM', 'explicar'); location.hash = 'universidade.tutor'; setTimeout(() => { const t = document.querySelector('form[data-form=tutor] textarea'); if (t) { t.value = 'Explica-me "' + b.dataset.t + '" do início, com exemplos e os erros mais comuns em exame.'; t.focus(); } }, 120); };
A.dpAI = async b => { if (DPB) return; const sid = b.dataset.s, s = OS.get('subjects', sid), P = perf(sid); DPB = true; OS.request();
  const data = { disciplina: s.name, notas: OS.all('assessments').filter(a => a.subject === sid).map(a => ({ prova: a.title, data: a.date, peso: a.weight, nota: a.grade })), alvo: s.target, temas: P.L.map(o => ({ tema: o.t, acerto: o.acc == null ? null : Math.round(o.acc * 100), respostas: o.n, estado: o.status, erros: o.err })), simulados: OS.all('quizzes').filter(q => q.subject === sid).slice(-6).map(q => ({ data: q.date, nota: q.score })), erros: OS.all('errors').filter(e => e.subject === sid).slice(-10).map(e => ({ erro: e.title, tipo: e.type })), proximaProva: P.next ? { prova: P.next.title, dias: P.days } : null };
  try { const o = await OS.AI.json([{ text: `És um orientador de estudo universitário exigente e prático. Analisa os dados reais do Ryan em "${s.name}" e diz-lhe onde tem de melhorar, em português de Portugal. Baseia-te SÓ nos dados.
Dados: ${JSON.stringify(data)}
Para cada foco: porque é prioritário (com números dos dados), exercícios específicos e concretos que deve fazer (tipo de exercício, quantidade), e 2-3 pesquisas curtas de aulas para o YouTube (só o texto da pesquisa, não inventes links).
JSON: {"diagnostico":"…","focos":[{"tema":"…","porque":"…","exercicios":["…"],"aulas":["…"]}],"dicas":["…"],"plano":"plano curto dia a dia para esta semana"}` }], .4);
    U.ls.set('oc_dprec_' + sid, { o, at: Date.now() }); } catch (e) { U.ls.set('oc_dprec_' + sid, { err: e.message || 'Erro', at: Date.now() }); } DPB = false; OS.request(); };
OS.UniPlus = { sm2, planFor, parseBulk };
})();
