/* OCEANUM — Universidade, Aprendizagem, Conhecimento, Treino (com mapa corporal), Corrida. */
(() => {
'use strict';
const U = OS.U, UI = OS.UI, C = OS.C, V = OS.views, L = OS.L, esc = U.esc, A = OS.act;
const St = OS.St, Fit = OS.Fit, Run = OS.Run;
const subjN = id => (OS.get('subjects', id) || {}).name || '—';

/* ================= UNIVERSIDADE ================= */
const UT = [['', 'Visão'], ['disciplinas', 'Disciplinas'], ['horario', 'Horário'], ['avaliacoes', 'Avaliações'], ['sessoes', 'Sessões'], ['revisoes', 'Revisões'], ['erros', 'Caderno de erros'], ['plano', 'Plano do curso']];
V.universidade = sub => {
  const p = OS.one('profile');
  return UI.head('Universidade', `${esc(p.uni || '')}${p.course ? ' · ' + esc(p.course) : ''} · ${esc(p.year || '')} · ${esc(p.semester || '')}`, `${UI.addBtn('sessions', 'Sessão')}${UI.addBtn('assessments', 'Avaliação', null, '')}`, 'Estudos') + UI.tabs('universidade', UT, sub) + (UNI[sub || 'visao'] || UNI.visao)();
};
const UNI = {};
OS.UNI = UNI; OS.UT = UT;
UNI.visao = () => {
  const t = U.today(), p = OS.one('profile'), cur = St.current(), wk = U.monday(t), wm = St.weekMins(wk), tgt = St.targetWeek();
  const todo = St.today(), up = U.sortBy(OS.all('assessments').filter(a => a.date >= t && a.prep !== 'Feito'), a => a.date);
  const days = U.range(t, U.addDays(t, 34)), acad = OS.Cal.items(t, U.addDays(t, 34)).filter(x => x.src === 'exam' || (x.src === 'task' && OS.all('tasks').some(k => 'tasks:' + k.id === x.edit && k.area === 'Universidade')));
  const byD = U.groupBy(acad, x => x.date);
  const semDays = p.semStart && p.semEnd ? U.diff(p.semEnd, p.semStart) : 0, semPassed = semDays ? U.clamp(U.diff(t, p.semStart) / semDays, 0, 1) : null;
  return `<div class="kpis">${UI.kpi('Estudo esta semana', U.hours(wm), tgt ? 'alvo ' + tgt + ' h · ' + U.pct(wm / 60 / tgt) : 'define horas-alvo nas disciplinas', { tone: tgt && wm / 60 >= tgt ? 'pos' : '' })}${UI.kpi('Média ponderada', St.gpa() || '—', 'escala 0–20')}${UI.kpi('ECTS concluídos', U.nf(St.ectsDone()) + ' / ' + (p.ectsTotal || 180), U.pct(St.ectsDone() / (p.ectsTotal || 180)))}${UI.kpi('Revisões para hoje', St.revDue().length, St.revDue().filter(r => St.revNext(r) < t).length + ' atrasadas', { tone: St.revDue().some(r => St.revNext(r) < t) ? 'warn' : '' })}${UI.kpi('Semestre', semPassed == null ? '—' : U.pct(semPassed), p.semEnd ? 'termina ' + U.fmtD(p.semEnd) : '')}</div>
  <div class="g g-main">
    <div class="pn"><div class="pn-h"><h3>${UI.ic('zap')}O que estudar hoje</h3><span class="mut" style="font-size:12px">revisões → provas → ritmo semanal → conteúdos</span></div>
      ${todo.length ? `<div class="list">${todo.slice(0, 7).map(x => `<div class="li"><span class="bdg out" style="min-width:74px;justify-content:center">${esc(x.kind)}</span><div class="li-t"><b>${esc(x.title)}</b><small>${esc((x.subject ? subjN(x.subject) + ' · ' : '') + x.why)}</small></div><div class="li-r">${x.act ? `<button class="btn xs" ${x.act}>${x.actL}</button>` : ''}<button class="btn xs ghost" data-act="focusStart" data-subject="${x.subject || ''}" data-label="${esc(x.title)}">${UI.ic('play')}${x.mins || 50} min</button></div></div>`).join('')}</div>` : UI.empty('Tudo em dia. Avança matéria nova ou faz exercícios.')}</div>
    <div class="pn"><div class="pn-h"><h3>${UI.ic('cal')}Próximas avaliações e entregas</h3><a class="more" href="#universidade.avaliacoes">${UI.ic('right')}</a></div>${up.length ? `<div class="list">${up.slice(0, 6).map(a => { const al = St.assessAlert(a); return `<div class="li" data-edit="assessments:${a.id}" style="cursor:pointer"><span class="when">${U.fmtDS(a.date)}</span><div class="li-t"><b>${esc(a.title)}</b><small>${esc(subjN(a.subject))} · ${a.type}${a.weight ? ' · ' + a.weight + '%' : ''} · ${a.prep}</small></div>${al ? UI.badge(al[0], al[1]) : ''}</div>`; }).join('')}</div>` : UI.empty('Sem avaliações marcadas. Regista testes, exames e trabalhos com o peso de cada um.', UI.addBtn('assessments', 'Registar avaliação', null, ''))}</div>
  </div>
  <section><div class="sech"><h2>Esta semana por disciplina</h2><span class="mut" style="font-size:12.5px">a marca é o ritmo esperado até hoje</span></div><div class="pn">${cur.map(s => { const x = St.stats(s); return `<div class="bar-row" style="grid-template-columns:minmax(120px,240px) 1fr 150px;cursor:pointer" data-edit="subjects:${s.id}"><span class="l">${esc(s.name)}</span>${UI.bar(x.targetWk ? x.hWk / x.targetWk : 0, x.targetWk && x.hWk >= x.targetWk ? 'pos' : '', ((new Date().getDay() + 6) % 7 + 1) / 7)}<span class="v">${x.hWk} / ${x.targetWk || '—'} h</span></div>`; }).join('') || UI.empty('Sem disciplinas em curso.')}</div></section>
  <section><div class="sech"><h2>Desempenho</h2></div><div class="g g3">${cur.map(s => { const x = St.stats(s); return `<div class="pn click" data-edit="subjects:${s.id}" style="cursor:pointer"><div class="row between gap8"><b style="font-weight:560">${esc(s.name)}</b>${UI.badge(x.sit[0], x.sit[1])}</div><div class="row gap16" style="margin:12px 0"><div><div class="big-num" style="font-size:26px">${x.avg || '—'}</div><div class="mut" style="font-size:12px">média · alvo ${x.tgt}</div></div><div><div class="big-num" style="font-size:26px">${x.hours}</div><div class="mut" style="font-size:12px">horas totais</div></div></div>
    <dl class="kv"><dt>Peso já avaliado</dt><dd>${x.w}%</dd><dt>Conteúdos dominados</dt><dd>${x.topicsDone}/${x.topics}</dd><dt>Erros por refazer</dt><dd>${x.errors}</dd><dt>Próxima avaliação</dt><dd>${x.next ? U.fmtDS(x.next.date) : '—'}</dd></dl></div>`; }).join('')}</div></section>
  <section><div class="sech"><h2>Calendário acadêmico · 5 semanas</h2></div><div class="pn flush" style="overflow:hidden"><div class="cal-m">${U.range(U.monday(t), U.addDays(U.monday(t), 34)).map(d => `<div class="cal-d ${d < t ? 'out' : ''} ${d === t ? 'today' : ''}" style="min-height:74px;cursor:default"><span class="n">${+d.slice(8)} ${+d.slice(8) === 1 || d === U.monday(t) ? U.MES[+d.slice(5, 7) - 1] : ''}</span>${(byD[d] || []).map(x => `<span class="cev" ${x.edit ? `data-edit="${x.edit}" style="cursor:pointer"` : ''}><i style="background:${OS.srcColor(x.src)}"></i><span>${esc(x.title)}</span></span>`).join('')}</div>`).join('')}</div></div></section>`;
};
UNI.disciplinas = () => {
  const all = OS.all('subjects'), cur = all.filter(s => s.status === 'Em curso');
  return `<div class="row gap8">${UI.addBtn('subjects', 'Nova disciplina')}${UI.addBtn('topics', 'Novo conteúdo', null, '')}</div>
  <div class="g g2">${cur.map(s => { const x = St.stats(s), tops = OS.all('topics').filter(tp => tp.subject === s.id); return `<div class="pn"><div class="pn-h"><h3 class="click" data-edit="subjects:${s.id}" style="cursor:pointer">${esc(s.name)}</h3>${UI.badge(x.sit[0], x.sit[1])}</div>
    <div class="kpis" style="margin-bottom:12px">${UI.kpi('Média', x.avg || '—', 'alvo ' + x.tgt)}${UI.kpi('Horas', x.hours, 'semana ' + x.hWk + '/' + (x.targetWk || '—'))}${UI.kpi('Avaliado', x.w + '%')}</div>
    <div class="eyebrow" style="margin-bottom:4px">Conteúdos · ${x.topicsDone}/${x.topics} revistos ou dominados</div>
    ${tops.length ? `<div class="list">${tops.map(tp => `<div class="li"><div class="li-t click" data-edit="topics:${tp.id}"><b>${esc(tp.title)}</b><small>${tp.studiedAt ? 'estudado ' + U.fmtDS(tp.studiedAt) : ''}</small></div><select class="field" style="width:auto;padding:3px 26px 3px 8px;font-size:12.5px" data-topic="${tp.id}" aria-label="Estado de ${esc(tp.title)}">${['Por estudar', 'Estudado', 'Revisto', 'Dominado'].map(o => `<option${tp.status === o ? ' selected' : ''}>${o}</option>`).join('')}</select></div>`).join('')}</div>` : '<div class="mut" style="font-size:13px;padding:6px 0">Lista a matéria da disciplina. Ao marcar "Estudado", as revisões R1/R2/R3 ficam agendadas.</div>'}
    <form class="row gap8" data-form="topicAdd" data-subject="${s.id}" style="margin-top:8px"><input class="field grow" name="t" placeholder="Novo conteúdo…" aria-label="Novo conteúdo"><button class="btn sm">${UI.ic('plus')}</button></form></div>`; }).join('') || UI.empty('Sem disciplinas em curso.')}</div>
  <section><div class="sech"><h2>Todas as disciplinas</h2></div>${UI.table({ key: 'subj', coll: 'subjects', rows: all, cols: [{ l: 'Disciplina', v: s => esc(s.name), s: s => s.name, cls: 'wrap' }, { l: 'Semestre', v: s => esc(s.sem || ''), s: s => s.sem || '' }, { l: 'Estado', v: s => UI.badge(s.status, s.status === 'Aprovada' ? 'pos' : s.status === 'Em curso' ? 'acc' : s.status === 'Reprovada' || s.status === 'Em atraso' ? 'neg' : ''), s: s => s.status }, { l: 'ECTS', cls: 'r', v: s => `<span class="mono">${s.ects || '—'}</span>` }, { l: 'Média / final', cls: 'r', v: s => `<span class="mono">${s.final || St.stats(s).avg || '—'}</span>` }] })}</section>`;
};
UNI.horario = () => {
  const cls = OS.all('classes'), days = L.WEEK.slice(0, 6);
  return `<div class="row gap8">${UI.addBtn('classes', 'Nova aula')}<span class="mut" style="font-size:12.5px">As aulas aparecem no calendário entre ${U.fmtD(OS.one('profile').semStart)} e ${U.fmtD(OS.one('profile').semEnd)} (muda em Definições).</span></div>
  ${cls.length ? `<div class="pn flush" style="overflow-x:auto"><div style="display:grid;grid-template-columns:repeat(6,minmax(140px,1fr));min-width:840px">${days.map(([d, l]) => `<div style="border-right:1px solid var(--line);padding:10px"><div class="eyebrow" style="margin-bottom:8px">${l}</div>${U.sortBy(cls.filter(c => String(c.wday) === d), c => c.start).map(c => `<div class="kcard" data-edit="classes:${c.id}" style="margin-bottom:6px;border-left:3px solid var(--c3)"><span class="mono mut" style="font-size:11.5px">${c.start}–${c.end}</span><b>${esc(subjN(c.subject))}</b><span class="mut" style="font-size:12px">${esc([c.kind, c.room].filter(Boolean).join(' · '))}</span></div>`).join('')}</div>`).join('')}</div></div>` : UI.empty('Regista o horário das aulas do semestre.', UI.addBtn('classes', 'Adicionar aula', null, ''))}`;
};
UNI.avaliacoes = () => {
  const all = U.sortBy(OS.all('assessments'), a => a.date || '9');
  return `<div class="kan">${['Não comecei', 'A preparar', 'Pronto', 'Feito'].map(p => { const it = all.filter(a => (a.prep || 'Não comecei') === p && (p !== 'Feito' || a.date >= U.addDays(U.today(), -60))); return `<div class="kcol"><h4>${p}<span class="mono">${it.length}</span></h4>${it.map(a => { const al = St.assessAlert(a); return `<div class="kcard" data-edit="assessments:${a.id}"><b>${esc(a.title)}</b><div class="meta"><span>${esc(subjN(a.subject))}</span><span>${U.fmtDS(a.date)}</span>${a.weight ? `<span>${a.weight}%</span>` : ''}${al ? UI.badge(al[0], al[1]) : ''}${a.grade !== '' && a.grade != null ? UI.badge('nota ' + a.grade, U.num(a.grade) >= 10 ? 'pos' : 'neg') : ''}</div></div>`; }).join('')}</div>`; }).join('')}</div>
  ${UI.table({ key: 'ass', coll: 'assessments', rows: all, cols: [{ l: 'Data', v: a => `<span class="mono">${U.fmtD(a.date)}</span>`, s: a => a.date }, { l: 'Avaliação', v: a => esc(a.title), cls: 'wrap' }, { l: 'Disciplina', v: a => esc(subjN(a.subject)) }, { l: 'Tipo', v: a => a.type }, { l: 'Peso', cls: 'r', v: a => a.weight ? a.weight + '%' : '—' }, { l: 'Nota', cls: 'r', v: a => `<span class="mono">${a.grade !== '' && a.grade != null ? a.grade : '—'}</span>` }, { l: 'Contributo', cls: 'r', v: a => `<span class="mono">${U.r1(St.contrib(a)) || '—'}</span>` }, { l: 'Alerta', v: a => { const al = St.assessAlert(a); return al ? UI.badge(al[0], al[1]) : ''; } }] })}`;
};
UNI.sessoes = () => {
  const S = OS.all('sessions'), days = U.lastN(30), byD = U.groupBy(S, s => s.date), tot = U.sum(S, s => s.minutes);
  const bySubj = St.current().concat(OS.all('subjects').filter(s => s.status !== 'Em curso' && S.some(x => x.subject === s.id))).map(s => ({ l: s.name, v: U.sum(S.filter(x => x.subject === s.id), x => x.minutes) / 60 })).filter(x => x.v);
  const skillH = U.sum(S.filter(x => x.skill), x => x.minutes) / 60; if (skillH) bySubj.push({ l: 'Aprendizagem', v: skillH });
  const verdict = s => U.num(s.minutes) >= 100 && s.phone ? ['Guerreiro', 'pos'] : U.num(s.minutes) >= 50 ? ['Válida', ''] : ['Curta', 'warn'];
  return `<div class="kpis">${UI.kpi('Total acumulado', U.hours(tot), 'minutos totais na caverna: ' + U.nf(tot))}${UI.kpi('Últimos 30 dias', U.hours(U.sum(S.filter(s => s.date >= days[0]), s => s.minutes)))}${UI.kpi('Blocos de 50 min (30d)', U.nf(Math.floor(U.sum(S.filter(s => s.date >= days[0]), s => s.minutes) / 50)))}${UI.kpi('Foco médio', S.length ? U.nf(U.avg(S.filter(s => s.focus), s => s.focus), 1) + '/5' : '—')}${UI.kpi('Telemóvel longe', S.length ? U.pct(S.filter(s => s.phone).length / S.length) : '—', 'das sessões')}</div>
  <div class="g g-main"><div class="pn"><div class="pn-h"><h3>Ritmo diário (min)</h3></div>${C.mount({ type: 'bar', labels: days.map(d => U.fmtDS(d)), series: [{ name: 'Minutos', data: days.map(d => U.sum(byD[d] || [], s => s.minutes)), color: v => v >= 100 ? 'var(--pos)' : 'var(--accent)' }], target: 100, targetLabel: '2 blocos' }, 200)}</div>
  <div class="pn"><div class="pn-h"><h3>Horas por disciplina</h3></div>${C.mount({ type: 'donut', data: bySubj, fmt: v => U.nf(v, 1) + ' h', center: U.nf(tot / 60, 0) + ' h', centerSub: 'total' }, 200)}</div></div>
  ${UI.table({ key: 'ses', coll: 'sessions', rows: U.sortBy(S, s => s.date + s._c, -1), limit: 40, empty: 'Sem sessões. Usa o Modo Foco: no fim, a sessão regista-se sozinha.', cols: [{ l: 'Data', v: s => `<span class="mono">${U.fmtD(s.date)}</span>`, s: s => s.date }, { l: 'Disciplina / competência', v: s => esc(s.subject ? subjN(s.subject) : (OS.get('skills', s.skill) || {}).name || '—') }, { l: 'Tipo', v: s => s.type }, { l: 'Minutos', cls: 'r', v: s => `<span class="mono">${s.minutes}</span>`, s: s => U.num(s.minutes) }, { l: 'Foco', cls: 'r', v: s => s.focus ? s.focus + '/5' : '—' }, { l: 'Veredito', v: s => UI.badge(...verdict(s)) }] })}`;
};
UNI.revisoes = () => {
  const R = OS.all('reviews'), t = U.today(), q = U.sortBy(R.filter(r => St.revNext(r)), r => St.revNext(r)), strip = U.range(t, U.addDays(t, 13));
  return `<div class="note">Curva do esquecimento: R1 a 24 h, R2 a 7 dias, R3 a 30 dias do estudo. Ao marcar um conteúdo como "Estudado" as revisões criam-se sozinhas.</div>
  <div class="pn flush" style="overflow-x:auto"><div style="display:grid;grid-template-columns:repeat(14,minmax(96px,1fr));min-width:1300px">${strip.map(d => { const it = q.filter(r => St.revNext(r) === d || (d === t && St.revNext(r) < t)); return `<div style="border-right:1px solid var(--line);padding:8px;min-height:96px"><div class="eyebrow" style="${d === t ? 'color:var(--accent)' : ''}">${d === t ? 'Hoje' : U.WDS[U.parse(d).getDay()] + ' ' + (+d.slice(8))}</div>${it.map(r => `<div class="cev ${St.revNext(r) < t ? 'late' : ''}" title="${esc(r.topic)}"><i style="background:var(--c3)"></i><span>${esc(r.topic)}</span></div>`).join('')}</div>`; }).join('')}</div></div>
  <div class="pn"><div class="pn-h"><h3>Fila de revisão</h3>${UI.addBtn('reviews', 'Novo tópico', null, 'sm')}</div>${q.length ? `<div class="list">${q.map(r => { const s = St.revState(r); return `<div class="li"><span class="when">${U.fmtDS(St.revNext(r))}</span><div class="li-t click" data-edit="reviews:${r.id}"><b>${esc(r.topic)}</b><small>${esc(subjN(r.subject))} · ${!r.r1 ? 'R1' : !r.r2 ? 'R2' : 'R3'} · domínio ${esc(r.mastery || '—')}</small></div>${UI.badge(s[0], s[1])}${St.revNext(r) <= t ? `<button class="btn xs" data-act="revDone" data-id="${r.id}">Feita</button>` : ''}</div>`; }).join('')}</div>` : UI.empty('Fila vazia.')}</div>`;
};
UNI.erros = () => {
  const E = OS.all('errors'), types = ['Não sabia a matéria', 'Distração', 'Interpretação', 'Cálculo', 'Falta de tempo'];
  return `<div class="g g-side"><div class="pn"><div class="pn-h"><h3>Por tipo de erro</h3></div>${C.mount({ type: 'donut', data: types.map(k => ({ l: k, v: E.filter(e => e.type === k).length })), fmt: v => v, center: String(E.length), centerSub: 'erros' }, 190)}</div>
  <div class="pn"><div class="pn-h"><h3>Regras aprendidas</h3>${UI.addBtn('errors', 'Novo erro', null, 'sm')}</div>${E.filter(e => e.rule).slice(-6).reverse().map(e => `<div class="ins">${UI.ic('check', 'pos')}<div><b style="font-weight:520">${esc(e.rule)}</b><div class="mut" style="font-size:12.5px">${esc(subjN(e.subject))} · ${esc(e.title)}</div></div></div>`).join('') || UI.empty('Cada erro deve terminar numa regra para não repetir.')}</div></div>
  ${UI.table({ key: 'err', coll: 'errors', rows: U.sortBy(E, e => e.date || '', -1), cols: [{ l: 'Data', v: e => `<span class="mono">${U.fmtD(e.date)}</span>`, s: e => e.date }, { l: 'Erro', v: e => esc(e.title), cls: 'wrap' }, { l: 'Disciplina', v: e => esc(subjN(e.subject)) }, { l: 'Tipo', v: e => esc(e.type || '') }, { l: 'Refeito', v: e => e.redone ? UI.badge('sim', 'pos') : UI.badge('por refazer', 'warn') }] })}`;
};
UNI.plano = () => {
  const all = OS.all('subjects'), by = U.groupBy(all, s => s.sem || 'Por definir'), p = OS.one('profile');
  return `<div class="kpis">${UI.kpi('ECTS concluídos', St.ectsDone() + ' / ' + (p.ectsTotal || 180))}${UI.kpi('Aprovadas', all.filter(s => s.status === 'Aprovada').length + ' / ' + all.length)}${UI.kpi('Em curso', all.filter(s => s.status === 'Em curso').length)}${UI.kpi('Média final (aprovadas)', (() => { const a = all.filter(s => U.num(s.final)); return a.length ? U.nf(U.avg(a, s => s.final), 1) : '—'; })())}</div>
  <div class="pn">${UI.bar(St.ectsDone() / (p.ectsTotal || 180), 'pos')}</div>
  ${[...L.SEM].filter(s => by[s]).map(s => `<section><div class="sech"><h2>${s}</h2><span class="mut mono">${U.sum(by[s], x => x.ects)} ECTS</span></div><div class="pn" style="padding-block:4px">${by[s].map(x => `<div class="li" data-edit="subjects:${x.id}" style="cursor:pointer"><div class="li-t"><b>${esc(x.name)}</b><small>${x.ects || 6} ECTS${x.final ? ' · nota ' + x.final : ''}</small></div>${UI.badge(x.status, x.status === 'Aprovada' ? 'pos' : x.status === 'Em curso' ? 'acc' : '')}</div>`).join('')}</div></section>`).join('')}
  <div class="note">O plano foi importado do teu Notion (Disciplinas Acadêmicas). Ajusta o semestre de cada cadeira para o calendário e as metas ficarem certos.</div>`;
};
A.revDone = b => { St.revDone(b.dataset.id); UI.toast('Revisão registada', 'pos'); };
A.topicDone = b => { OS.upd('topics', b.dataset.id, { status: 'Estudado' }); St.topicAfter(OS.get('topics', b.dataset.id)); };
OS.forms = OS.forms || {};
OS.forms.topicAdd = (f, v) => { const t = v('t'); if (!t) return; OS.add('topics', { subject: f.dataset.subject, title: t, status: 'Por estudar' }); };
document.addEventListener('change', e => { const s = e.target.closest('[data-topic]'); if (!s) return; OS.upd('topics', s.dataset.topic, { status: s.value }); St.topicAfter(OS.get('topics', s.dataset.topic)); });
OS.S.subjects.detail = s => { const x = St.stats(s); const ses = U.sortBy(OS.all('sessions').filter(z => z.subject === s.id), z => z.date, -1).slice(0, 5); return `<div class="pn tint"><dl class="kv"><dt>Média atual</dt><dd>${x.avg || '—'}</dd><dt>Horas totais</dt><dd>${x.hours}</dd><dt>Esta semana</dt><dd>${x.hWk} h</dd><dt>Conteúdos dominados</dt><dd>${x.topicsDone}/${x.topics}</dd></dl>${ses.length ? `<div class="divider"></div><div class="eyebrow">Últimas sessões</div>${ses.map(z => `<div class="li"><span class="when">${U.fmtDS(z.date)}</span><div class="li-t"><b>${z.minutes} min · ${z.type}</b></div></div>`).join('')}` : ''}</div>`; };

/* ================= APRENDIZAGEM ================= */
V.aprendizagem = sub => {
  const head = UI.head('Trilhas & competências', 'As competências que queres dominar (Excel, Inglês, Python…), do nível atual ao nível alvo, etapa a etapa: conteúdos → estudo → exercícios → projeto → avaliação → domínio. Cursos, livros e certificações ligados a cada competência aparecem aqui.', UI.addBtn('skills', 'Nova competência'), 'Estudos');
  if (sub === 'itens') {
    const Lr = OS.all('learn'), yr = U.today().slice(0, 4);
    return head + `<div class="kpis">${UI.kpi('Livros concluídos ' + yr, Lr.filter(l => l.kind === 'Livro' && l.status === 'Concluído' && (l.end || '').startsWith(yr)).length, 'meta: 12 por ano')}${UI.kpi('Cursos concluídos', Lr.filter(l => l.kind === 'Curso' && l.status === 'Concluído').length)}${UI.kpi('Certificações', Lr.filter(l => l.kind === 'Certificação' && l.status === 'Concluído').length)}${UI.kpi('Em curso', Lr.filter(l => l.status === 'Em curso').length)}</div>
    <div class="kan">${['Na fila', 'Em curso', 'Concluído', 'Abandonado'].map(st => { const it = Lr.filter(l => l.status === st); return `<div class="kcol"><h4>${st}<span class="mono">${it.length}</span></h4>${it.map(l => `<div class="kcard" data-edit="learn:${l.id}"><span class="eyebrow">${esc(l.kind)}</span><b>${esc(l.title)}</b>${l.author ? `<span class="mut" style="font-size:12px">${esc(l.author)}</span>` : ''}${U.num(l.total) ? `${UI.bar(U.num(l.done) / U.num(l.total), st === 'Concluído' ? 'pos' : '')}<span class="mono mut" style="font-size:11.5px">${l.done || 0}/${l.total} ${l.unit || ''}</span>` : ''}</div>`).join('')}</div>`; }).join('')}</div>`;
  }
  const S = OS.all('skills');
  return head + (S.length ? `<div class="col gap12">${S.map(s => { const h = U.sum(OS.all('sessions').filter(x => x.skill === s.id), x => x.minutes) / 60, items = OS.all('learn').filter(l => l.skill === s.id), si = L.TRACK.indexOf(s.stage || 'Conteúdos'), plan = s.plan || [];
    return `<div class="pn"><div class="row between gap12"><div class="click" data-edit="skills:${s.id}" style="cursor:pointer"><span class="eyebrow">${esc(s.area || '')}</span><div style="font-size:16px;font-weight:600">${esc(s.name)}</div></div><div class="row gap12"><span class="mono tx2">${U.nf(h, 1)} h</span><span class="mono">nível ${s.level || 1} → ${s.targetLevel || 5}</span><button class="btn sm" data-act="skillStage" data-id="${s.id}" ${si >= L.TRACK.length - 1 ? 'disabled' : ''}>Avançar etapa</button><button class="btn sm ghost" data-act="focusStart" data-label="${esc(s.name)}" aria-label="Estudar ${esc(s.name)}">${UI.ic('play')}</button></div></div>
      <div style="display:grid;grid-template-columns:repeat(6,1fr);gap:4px;margin:14px 0 8px">${L.TRACK.map((st, i) => `<div style="text-align:center"><div style="height:6px;border-radius:9px;background:${i < si ? 'var(--pos)' : i === si ? 'var(--accent)' : 'rgba(255,255,255,.07)'}"></div><div style="font-size:11.5px;margin-top:6px;color:${i === si ? 'var(--tx)' : 'var(--mut)'}">${st}</div></div>`).join('')}</div>
      ${plan.length || items.length ? `<div class="row gap16" style="font-size:12.5px;color:var(--tx2)">${plan.length ? `<span>Conteúdos da trilha: ${plan.filter(p => p.done).length}/${plan.length}</span>` : ''}${items.map(l => `<span class="bdg out" data-edit="learn:${l.id}" style="cursor:pointer">${esc(l.kind)} · ${esc(l.title)}</span>`).join('')}</div>` : ''}</div>`; }).join('')}</div>` : UI.empty('Cria uma competência para começar uma trilha.', UI.addBtn('skills', 'Criar competência', null, '')));
};
A.skillStage = b => { const s = OS.get('skills', b.dataset.id); const i = L.TRACK.indexOf(s.stage || 'Conteúdos'); if (i < L.TRACK.length - 1) { OS.upd('skills', s.id, { stage: L.TRACK[i + 1], level: i + 1 >= L.TRACK.length - 1 ? Math.max(U.num(s.level), U.num(s.targetLevel) || 4) : s.level }); UI.toast(s.name + ': ' + L.TRACK[i + 1], 'pos'); } };

/* ================= CONHECIMENTO ================= */
V.conhecimento = () => {
  const f = OS.ui.kf || {}, q = (f.q || '').toLowerCase();
  const N = U.sortBy(OS.all('notes').filter(n => (!f.type || n.type === f.type) && (!f.rel || n.subject === f.rel || n.project === f.rel || n.goal === f.rel || n.skill === f.rel) && (!q || (n.title + ' ' + (n.body || '') + ' ' + (n.tags || []).join(' ')).toLowerCase().includes(q))), n => n._u, -1);
  const rels = [...OS.all('subjects').filter(s => s.status === 'Em curso').map(s => [s.id, 'Disciplina · ' + s.name]), ...OS.all('projects').map(p => [p.id, 'Projeto · ' + p.name]), ...OS.all('goals').filter(g => g.status === 'Ativa').map(g => [g.id, 'Meta · ' + g.title]), ...OS.all('skills').map(s => [s.id, 'Competência · ' + s.name])];
  const relTxt = n => [n.subject && subjN(n.subject), (OS.get('projects', n.project) || {}).name, (OS.get('goals', n.goal) || {}).title, (OS.get('skills', n.skill) || {}).name].filter(Boolean);
  return UI.head('Knowledge Base', 'Conceitos, fórmulas, insights, resumos e links, ligados à disciplina, projeto, meta ou competência a que pertencem.', UI.addBtn('notes', 'Nova nota'), 'Estudos') +
  `<form class="pn col gap8" data-form="noteQuick"><input class="field" name="t" placeholder="Título (ex.: Equação fundamental da contabilidade)" aria-label="Título"><textarea class="field" name="b" rows="2" placeholder="Ativo = Passivo + Capital Próprio" aria-label="Conteúdo"></textarea><div class="row between gap8"><select class="field" style="width:auto" name="type" aria-label="Tipo">${['Conceito', 'Fórmula', 'Ideia', 'Insight', 'Resumo', 'Anotação', 'Referência', 'Link'].map(x => `<option>${x}</option>`).join('')}</select><button class="btn pri sm">${UI.ic('plus')}Guardar nota</button></div></form>
  <div class="filters"><input type="search" placeholder="Procurar no conhecimento…" value="${esc(f.q || '')}" data-uif="kf.q" aria-label="Procurar"><select data-uif="kf.type" aria-label="Tipo"><option value="">Todos os tipos</option>${['Conceito', 'Fórmula', 'Ideia', 'Insight', 'Resumo', 'Anotação', 'Referência', 'Link'].map(x => `<option${f.type === x ? ' selected' : ''}>${x}</option>`).join('')}</select><select data-uif="kf.rel" aria-label="Relação"><option value="">Qualquer ligação</option>${rels.map(([id, l]) => `<option value="${id}"${f.rel === id ? ' selected' : ''}>${esc(l)}</option>`).join('')}</select></div>
  ${N.length ? `<div class="g g3">${N.map(n => `<div class="pn click" data-edit="notes:${n.id}" style="cursor:pointer;display:flex;flex-direction:column;gap:8px"><div class="row between gap8"><span class="eyebrow">${esc(n.type || 'Nota')}</span><span class="mut" style="font-size:11.5px">${U.fmtDS(U.iso(new Date(n._u)))}</span></div><b style="font-weight:560">${esc(n.title)}</b>${n.body ? `<div class="tx2" style="font-size:13px;${n.type === 'Fórmula' ? 'font-family:var(--mono)' : ''};display:-webkit-box;-webkit-line-clamp:4;-webkit-box-orient:vertical;overflow:hidden;white-space:pre-wrap">${esc(n.body)}</div>` : ''}${n.url ? `<a class="acc" style="font-size:12.5px" href="${esc(n.url)}" target="_blank" rel="noopener">${esc(n.url.replace(/^https?:\/\//, '').slice(0, 40))}</a>` : ''}<div class="row gap4">${relTxt(n).map(r => UI.badge(r, 'acc')).join('')}${(n.tags || []).map(t => UI.badge('#' + t, 'out')).join('')}</div></div>`).join('')}</div>` : UI.empty('Sem notas com estes filtros.')}`;
};
OS.forms.noteQuick = (f, v) => { const t = v('t'); if (!t) return; OS.add('notes', { title: t, body: v('b'), type: f.elements.type.value, tags: [] }); UI.toast('Nota guardada', 'pos'); };

/* ================= TREINO ================= */
const TT = [['', 'Treinar'], ['resumo', 'Resumo'], ['historico', 'Histórico'], ['exercicios', 'Exercícios'], ['divisao', 'Divisão semanal']];
V.treino = sub => UI.head('Treino', 'Rotinas, treino em curso com cargas da última vez, descanso cronometrado, recordes e evolução por exercício e por músculo.', `${UI.addBtn('workouts', 'Registo manual', null, 'ghost')}<button class="btn pri" data-act="wkStart">${UI.ic('play')}<span>Começar treino</span></button>`, 'Corpo') + UI.tabs('treino', TT, sub === 'visao' ? 'resumo' : sub) + (TR[sub || 'inicio'] || TR.inicio)();
const TR = {};
TR.inicio = () => V.treinoHome();
TR.resumo = TR.visao = () => {
  const t = U.today(), p = OS.one('profile'), W = OS.all('workouts'), wk = U.monday(t), w7 = U.addDays(t, -6), m30 = U.addDays(t, -29);
  const weeks = Array.from({ length: 12 }, (_, i) => U.addDays(wk, -7 * (11 - i)));
  const ms = Fit.muscleSets(w7, t), prs = Fit.prs().filter(x => x.date >= m30);
  const bw = U.sortBy(OS.all('body').filter(b => U.num(b.weight)), b => b.date).pop();
  return `<div class="kpis">${UI.kpi('Treinos esta semana', W.filter(w => w.date >= wk).length + ' / ' + (p.trainTarget || 4), '', { tone: W.filter(w => w.date >= wk).length >= (p.trainTarget || 4) ? 'pos' : '' })}${UI.kpi('Este mês', W.filter(w => U.ym(w.date) === U.ym(t)).length)}${UI.kpi('Volume (7 dias)', U.nf(U.sum(W.filter(w => w.date >= w7), Fit.volume) / 1000, 1) + ' t', 'kg × repetições')}${UI.kpi('Séries (7 dias)', U.nf(U.sum(W.filter(w => w.date >= w7), Fit.sets)))}${UI.kpi('Recordes (30 dias)', prs.length, '', { tone: prs.length ? 'pos' : '' })}${UI.kpi('Peso corporal', bw ? U.nf(bw.weight, 1) + ' kg' : '—', bw ? U.fmtD(bw.date) : '')}</div>
  <div class="g g-main"><div class="pn"><div class="pn-h"><h3>Volume por semana (t)</h3></div>${C.mount({ type: 'bar', labels: weeks.map(w => U.fmtDS(w)), series: [{ name: 'Volume', data: weeks.map(w => U.sum(W.filter(x => x.date >= w && x.date <= U.addDays(w, 6)), Fit.volume) / 1000), color: 'var(--c5)' }], fmt: v => U.nf(v, 1), empty: 'Regista treinos com séries para ver o volume.' }, 210)}</div>
  <div class="pn"><div class="pn-h"><h3>Frequência semanal</h3></div>${C.mount({ type: 'bar', labels: weeks.map(w => U.fmtDS(w)), series: [{ name: 'Treinos', data: weeks.map(w => W.filter(x => x.date >= w && x.date <= U.addDays(w, 6)).length), color: v => v >= (p.trainTarget || 4) ? 'var(--pos)' : 'var(--c5)' }], target: p.trainTarget || 4, targetLabel: 'meta' }, 210)}</div></div>
  <div class="g g2"><div class="pn"><div class="pn-h"><h3>Séries por grupo muscular · 7 dias</h3><a class="more" href="#corpo.mapa">Mapa ${UI.ic('right')}</a></div>${L.MUSCLES.map(m => `<div class="bar-row" style="grid-template-columns:110px 1fr 50px"><span class="l">${m}</span>${UI.bar(ms[m] / 16, ms[m] >= 10 ? 'pos' : '')}<span class="v">${U.nf(ms[m], ms[m] % 1 ? 1 : 0)}</span></div>`).join('')}<div class="note" style="margin-top:8px">Referência comum para hipertrofia: 10–20 séries por grupo por semana. Músculos secundários contam meia série.</div></div>
  <div class="pn"><div class="pn-h"><h3>Recordes recentes</h3></div>${prs.length ? prs.slice(0, 8).map(x => `<div class="li"><span class="when">${U.fmtDS(x.date)}</span><div class="li-t"><b>${esc(x.ex.name)}</b><small>${x.ex.muscle}</small></div><span class="mono pos">${x.kg} kg</span></div>`).join('') : UI.empty('Sem recordes nos últimos 30 dias.')}
    <div class="divider"></div><div class="eyebrow" style="margin-bottom:4px">Últimos treinos</div>${U.sortBy(W, w => w.date, -1).slice(0, 5).map(w => `<div class="li" data-edit="workouts:${w.id}" style="cursor:pointer"><span class="when">${U.fmtDS(w.date)}</span><div class="li-t"><b>${esc(w.title || 'Treino')}</b><small>${Fit.sets(w)} séries · ${U.nf(Fit.volume(w))} kg${w.dur ? ' · ' + w.dur + ' min' : ''}</small></div></div>`).join('') || UI.empty('Sem treinos.')}</div></div>`;
};
/* ---- Mapa corporal: ver bodymap.js ---- */
TR.mapa = () => OS.BodyMap.view();
A.muscle = b => OS.setUI('bmSel', b.dataset.m);
TR.historico = () => V.treinoHist();
TR.historicoTabela = () => UI.table({ key: 'wk', coll: 'workouts', rows: U.sortBy(OS.all('workouts'), w => w.date, -1), limit: 40, empty: 'Sem treinos registados.', emptyAct: UI.addBtn('workouts', 'Registar treino', null, ''), cols: [
  { l: 'Data', v: w => `<span class="mono">${U.fmtD(w.date)}</span>`, s: w => w.date }, { l: 'Treino', v: w => esc(w.title || '—') }, { l: 'Exercícios', v: w => (w.items || []).map(it => esc((OS.get('exercises', it.ex) || {}).name || '')).filter(Boolean).join(', '), cls: 'wrap' },
  { l: 'Séries', cls: 'r', v: w => Fit.sets(w) }, { l: 'Volume', cls: 'r', v: w => `<span class="mono">${U.nf(Fit.volume(w))} kg</span>`, s: w => Fit.volume(w) }, { l: 'Duração', cls: 'r', v: w => w.dur ? w.dur + ' min' : '—' }, { l: 'RPE', cls: 'r', v: w => w.rpe || '—' }] });
TR.exercicios = () => V.treinoEx();
TR.exerciciosAntigo = () => {
  const sel = OS.ui.exSel, ex = OS.get('exercises', sel), h = ex ? Fit.exHistory(ex.id) : [];
  return `<div class="row gap8">${UI.addBtn('exercises', 'Novo exercício')}</div>${ex ? `<div class="pn"><div class="pn-h"><h3>${esc(ex.name)} · ${ex.muscle}</h3><button class="btn sm ghost" data-act="exOpen" data-id="">Fechar</button></div>${h.length ? `<div class="kpis" style="margin-bottom:12px">${UI.kpi('Melhor 1RM estimado', Math.max(...h.map(x => x.e1rm)) + ' kg')}${UI.kpi('Carga máxima', Math.max(...h.map(x => x.top)) + ' kg')}${UI.kpi('Sessões', h.length)}${UI.kpi('Volume total', U.nf(U.sum(h, x => x.vol)) + ' kg')}</div>${C.mount({ type: 'line', labels: h.map(x => U.fmtDS(x.date)), series: [{ name: '1RM estimado', data: h.map(x => x.e1rm) }, { name: 'Carga máxima', data: h.map(x => x.top), color: 'var(--c2)' }], min0: false, fmt: v => U.nf(v) + ' kg' }, 220)}<div class="note">1RM estimado pela fórmula de Epley a partir da melhor série de cada sessão.</div>` : UI.empty('Ainda sem registos deste exercício.')}</div>` : ''}
  ${UI.table({ key: 'ex', rows: U.sortBy(OS.all('exercises'), e => e.muscle + e.name), rowAttr: e => `data-act="exOpen" data-id="${e.id}" tabindex="0" style="cursor:pointer"`, cols: [{ l: 'Exercício', v: e => `<b style="font-weight:520">${esc(e.name)}</b>`, s: e => e.name }, { l: 'Principal', v: e => e.muscle, s: e => e.muscle }, { l: 'Secundários', v: e => (e.secondary || []).join(', ') }, { l: 'Equipamento', v: e => esc(e.equip || '') }, { l: 'Sessões', cls: 'r', v: e => Fit.exHistory(e.id).length }, { l: '', v: e => `<button class="icon-btn" data-edit="exercises:${e.id}" aria-label="Editar">${UI.ic('edit')}</button>` }] })}`;
};
A.exOpen = (b, e) => { if (e.target.closest('[data-edit]')) return; OS.ui.exSel = b.dataset.id; OS.go('treino.exercicios'); OS.setUI('exSel', b.dataset.id); };
TR.peso = () => V.treinoPeso();
TR.pesoAntigo = () => {
  const B = U.sortBy(OS.all('body'), b => b.date), last = B[B.length - 1], first30 = B.filter(b => b.date >= U.addDays(U.today(), -30))[0];
  return `<div class="row gap8">${UI.addBtn('body', 'Registar peso')}</div><div class="kpis">${UI.kpi('Peso atual', last ? U.nf(last.weight, 1) + ' kg' : '—')}${UI.kpi('Variação 30 dias', last && first30 ? U.nf(last.weight - first30.weight, 1) + ' kg' : '—')}${UI.kpi('Cintura', last && last.waist ? last.waist + ' cm' : '—')}${UI.kpi('Gordura corporal', last && last.bf ? last.bf + '%' : '—')}</div>
  <div class="pn"><div class="pn-h"><h3>Evolução do peso</h3></div>${C.mount({ type: 'line', labels: B.map(b => U.fmtDS(b.date)), series: [{ name: 'Peso (kg)', data: B.map(b => U.num(b.weight)) }], min0: false, fmt: v => U.nf(v, 1), empty: 'Regista o peso para ver a curva.' }, 240)}</div>
  ${UI.table({ key: 'body', coll: 'body', rows: B.slice().reverse(), cols: [{ l: 'Data', v: b => U.fmtD(b.date) }, { l: 'Peso', cls: 'r', v: b => b.weight + ' kg' }, { l: 'Cintura', cls: 'r', v: b => b.waist ? b.waist + ' cm' : '—' }, { l: 'Gordura', cls: 'r', v: b => b.bf ? b.bf + '%' : '—' }] })}`;
};
TR.divisao = () => {
  const sp = OS.one('fit').split;
  return `<div class="pn"><div class="pn-h"><h3>Divisão semanal</h3><span class="mut" style="font-size:12.5px">aparece no Hoje e no Calendário como treino planeado</span></div>${L.WEEK.map(([d, l]) => `<div class="row gap12" style="padding:6px 0"><span style="width:90px" class="tx2">${l}</span><input class="field grow" data-bind="fit.split.${d}" data-fk="sp${d}" value="${esc(sp[d] || '')}" list="splits" aria-label="Treino de ${l}"></div>`).join('')}<datalist id="splits">${['Peito & Tríceps', 'Costas & Bíceps', 'Pernas', 'Ombros & Core', 'Full Body', 'Upper', 'Lower', 'Push', 'Pull', 'Corrida', 'Mobilidade', 'Descanso'].map(x => `<option value="${x}">`).join('')}</datalist></div>
  <div class="pn"><div class="pn-h"><h3>Leis do treino</h3></div><ul style="margin:0;padding-left:18px;display:flex;flex-direction:column;gap:5px;color:var(--tx2)"><li>Treino marcado é compromisso.</li><li>Sobrecarga progressiva semanal: regista cargas para a veres.</li><li>Sono de 7–8 h e 2,5–3 L de água fazem parte do treino.</li><li>Dor articular aguda = parar.</li></ul></div>`;
};

/* ================= CORRIDA ================= */
V.corrida = sub => UI.head('Corrida', 'Distância, tempo, ritmo, velocidade e frequência cardíaca. Recordes e evolução calculados sozinhos.', UI.addBtn('runs', 'Registar corrida'), 'Corpo') + UI.tabs('corrida', [['', 'Visão'], ['alongamentos', 'Alongamentos'], ['plano', 'Plano'], ['historico', 'Histórico']], sub) + (RN[sub || 'visao'] || RN.visao)();
const RN = {};
RN.alongamentos = () => V.corridaAlong();
RN.visao = () => {
  const R = OS.all('runs'), t = U.today(), p = OS.one('profile'), wk = U.monday(t), weeks = Run.weeks(12), last20 = U.sortBy(R, r => r.date).slice(-20);
  const r30 = R.filter(r => r.date >= U.addDays(t, -29)), km30 = U.sum(r30, r => r.km), pace30 = km30 ? U.sum(r30, r => U.parseDur(r.time)) / km30 : 0;
  const b5 = Run.best(5), b10 = Run.best(10), b21 = Run.best(21.1), lg = Run.longest(), fastest = R.filter(r => U.num(r.km) >= 3).reduce((a, r) => !a || Run.pace(r) < Run.pace(a) ? r : a, null);
  const planKm = U.sum(OS.all('runplan').filter(r => r.active), r => r.km) || U.num(p.runKmTarget);
  const hrs = r30.filter(r => U.num(r.hr));
  const rec = (l, x, v) => `<div class="li"><div class="li-t"><b>${l}</b><small>${x ? U.fmtD(x.date) + ' · ' + U.nf(x.km, 2) + ' km' : 'sem registo'}</small></div><span class="mono">${v}</span></div>`;
  return `${OS.BodyX ? OS.BodyX.strip() : ''}<div class="kpis">${UI.kpi('Esta semana', U.nf(Run.kmIn(wk, t), 1) + ' km', planKm ? 'plano ' + planKm + ' km' : '', { tone: planKm && Run.kmIn(wk, t) >= planKm ? 'pos' : '' })}${UI.kpi('Este mês', U.nf(Run.kmIn(U.ym(t) + '-01', t), 1) + ' km', R.filter(r => U.ym(r.date) === U.ym(t)).length + ' corridas')}${UI.kpi('Ritmo médio (30d)', pace30 ? U.mmss(pace30) + '/km' : '—', pace30 ? U.nf(3600 / pace30, 1) + ' km/h' : '')}${UI.kpi('Melhor 5 km', b5 ? U.mmss(b5.est) : '—', b5 ? (b5.exact ? 'tempo real' : 'estimado pelo ritmo') : '')}${UI.kpi('Maior distância', lg ? U.nf(lg.km, 1) + ' km' : '—')}${UI.kpi('FC média (30d)', hrs.length ? Math.round(U.avg(hrs, r => r.hr)) + ' bpm' : '—')}</div>
  <div class="g g-main"><div class="pn"><div class="pn-h"><h3>Distância semanal (km)</h3></div>${C.mount({ type: 'bar', labels: weeks.map(w => U.fmtDS(w)), series: [{ name: 'km', data: weeks.map(w => Run.kmIn(w, U.addDays(w, 6))), color: 'var(--c6)' }], target: planKm || null, targetLabel: 'plano', fmt: v => U.nf(v, v % 1 ? 1 : 0), empty: 'Regista corridas para ver a distância semanal.' }, 220)}</div>
  <div class="pn"><div class="pn-h"><h3>Recordes</h3></div>${rec('Melhor ritmo (≥ 3 km)', fastest, fastest ? U.mmss(Run.pace(fastest)) + '/km' : '—')}${rec('5 km', b5 && b5.run, b5 ? U.mmss(b5.est) + (b5.exact ? '' : ' est.') : '—')}${rec('10 km', b10 && b10.run, b10 ? U.mmss(b10.est) + (b10.exact ? '' : ' est.') : '—')}${rec('Meia maratona', b21 && b21.run, b21 ? U.mmss(b21.est) : '—')}${rec('Maior distância', lg, lg ? U.nf(lg.km, 2) + ' km' : '—')}<div class="note" style="margin-top:8px">"est." = tempo projetado a partir do ritmo de uma corrida igual ou mais longa.</div></div></div>
  <div class="g g2"><div class="pn"><div class="pn-h"><h3>Ritmo por corrida (min/km)</h3><span class="mut" style="font-size:12px">mais baixo = mais rápido</span></div>${C.mount({ type: 'line', labels: last20.map(r => U.fmtDS(r.date)), series: [{ name: 'Ritmo', data: last20.map(r => Run.pace(r) ? U.r2(Run.pace(r) / 60) : null) }], min0: false, fmt: v => U.mmss(v * 60), empty: 'Sem corridas.' }, 200)}</div>
  <div class="pn"><div class="pn-h"><h3>Frequência · 13 semanas</h3></div>${UI.heat(U.lastN(91), d => U.r1(U.sum(R.filter(r => r.date === d), r => r.km)), 10)}<div class="mut" style="font-size:12px;margin-top:10px">${R.filter(r => r.date >= U.addDays(t, -90)).length} corridas em 90 dias · ${U.nf(Run.kmIn(U.addDays(t, -90), t), 1)} km</div></div></div>`;
};
RN.plano = () => {
  const P = OS.all('runplan'), t = U.today(), wk = U.monday(t), days = U.range(wk, U.addDays(wk, 6));
  return `<div class="pn"><div class="pn-h"><h3>Esta semana: planeado vs feito</h3></div><div style="display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:8px">${days.map(d => { const wd = String(U.parse(d).getDay()), pl = P.filter(r => r.active && String(r.wday) === wd), dn = OS.all('runs').filter(r => r.date === d); return `<div class="kcol" style="min-height:110px"><h4>${U.WDS[U.parse(d).getDay()]} ${+d.slice(8)}</h4>${pl.map(r => `<div class="kcard" style="cursor:default;${dn.length ? 'border-color:rgba(63,207,142,.4)' : d < t ? 'border-color:rgba(242,109,109,.35)' : ''}"><b>${esc(r.type)}</b><span class="mut" style="font-size:12px">${U.num(r.km) ? r.km + ' km' : U.num(r.mins) ? r.mins + ' min' : ''}</span></div>`).join('')}${dn.map(r => `<div class="kcard" data-edit="runs:${r.id}"><span class="bdg pos">feito</span><span class="mono" style="font-size:12px">${U.nf(r.km, 1)} km · ${Run.paceStr(Run.pace(r))}</span></div>`).join('')}</div>`; }).join('')}</div></div>
  <div class="g g-main"><div class="pn"><div class="pn-h"><h3>Cronograma semanal</h3>${UI.addBtn('runplan', 'Treino', null, 'sm')}</div>${L.WEEK.map(([d, l]) => { const it = P.filter(r => String(r.wday) === d); return it.length ? it.map(r => `<div class="li" data-edit="runplan:${r.id}" style="cursor:pointer"><span style="width:80px" class="tx2">${l}</span><div class="li-t"><b>${esc(r.type)} ${U.num(r.km) ? r.km + ' km' : U.num(r.mins) ? r.mins + ' min' : ''}</b><small>${esc(r.desc || '')}</small></div>${r.active ? '' : UI.badge('inativo')}</div>`).join('') : ''; }).join('') || UI.empty('Sem cronograma. Gera um a partir de um objetivo.')}</div>
  <div class="pn"><div class="pn-h"><h3>Gerar cronograma</h3></div><form class="col gap12" data-form="runGen"><div class="fld"><label for="rg-goal">Objetivo</label><select id="rg-goal" name="goal">${[['5k25', '5 km em menos de 25 min'], ['5k22', '5 km em menos de 22 min'], ['10k', '10 km contínuos / < 50 min'], ['21k', 'Meia maratona (21,1 km)']].map(([v, l]) => `<option value="${v}">${l}</option>`).join('')}</select></div><div class="fld"><label for="rg-days">Dias por semana</label><select id="rg-days" name="days"><option>3</option><option selected>4</option><option>5</option></select></div><div class="note">Substitui o cronograma ativo. Estrutura: um treino de qualidade (intervalado ou fartlek), um de ritmo, rodagens fáceis e uma longa ao fim de semana. Aumenta o volume no máximo 10% por semana.</div><button class="btn pri">Gerar</button></form></div></div>`;
};
OS.forms.runGen = (f) => {
  const g = f.elements.goal.value, n = +f.elements.days.value;
  const T = { '5k25': [['2', 'Intervalado', '', 35, '8 × 400 m a ritmo de 4:50/km, 90 s a trote'], ['4', 'Rodagem', 4, '', 'Ritmo confortável, conversa possível'], ['6', 'Longa', 6, '', 'Contínua, ritmo fácil'], ['0', 'Regenerativa', 3, '', 'Muito leve'], ['5', 'Fartlek', '', 30, '6 × 1 min forte / 2 min leve']],
    '5k22': [['2', 'Intervalado', '', 40, '5 × 1000 m a 4:20/km, 2 min de recuperação'], ['4', 'Tempo / Limiar', 6, '', '3 km a ritmo de limiar no meio'], ['6', 'Longa', 9, '', 'Contínua, ritmo fácil'], ['0', 'Regenerativa', 4, '', 'Muito leve'], ['5', 'Rodagem', 5, '', 'Ritmo confortável']],
    '10k': [['2', 'Intervalado', '', 45, '6 × 800 m a ritmo de 5 km, 2 min de recuperação'], ['4', 'Tempo / Limiar', 7, '', '4 km a ritmo de 10 km no meio'], ['6', 'Longa', 12, '', 'Contínua, ritmo fácil'], ['0', 'Regenerativa', 5, '', 'Muito leve'], ['5', 'Rodagem', 6, '', 'Ritmo confortável']],
    '21k': [['2', 'Intervalado', '', 50, '4 × 2 km a ritmo de meia, 3 min de recuperação'], ['4', 'Tempo / Limiar', 10, '', '6 km a ritmo de limiar'], ['6', 'Longa', 16, '', 'Aumentar 1–2 km por semana até 18–20 km'], ['0', 'Regenerativa', 6, '', 'Muito leve'], ['5', 'Rodagem', 8, '', 'Ritmo confortável']] }[g];
  OS.all('runplan').filter(r => r.active).forEach(r => OS.upd('runplan', r.id, { active: false }, { silent: true }));
  T.slice(0, n).forEach(([wday, type, km, mins, desc]) => OS.add('runplan', { wday, type, km, mins, desc, active: true }, { silent: true }));
  UI.toast('Cronograma gerado', 'pos');
};
RN.historico = () => UI.table({ key: 'runs', coll: 'runs', rows: U.sortBy(OS.all('runs'), r => r.date, -1), limit: 60, empty: 'Sem corridas.', emptyAct: UI.addBtn('runs', 'Registar corrida', null, ''), cols: [
  { l: 'Data', v: r => `<span class="mono">${U.fmtD(r.date)}</span>`, s: r => r.date }, { l: 'Tipo', v: r => esc(r.type) }, { l: 'Distância', cls: 'r', v: r => `<span class="mono">${U.nf(r.km, 2)} km</span>`, s: r => U.num(r.km) },
  { l: 'Tempo', cls: 'r', v: r => `<span class="mono">${U.mmss(U.parseDur(r.time))}</span>` }, { l: 'Ritmo', cls: 'r', v: r => `<span class="mono">${Run.paceStr(Run.pace(r))}</span>`, s: r => Run.pace(r) },
  { l: 'Velocidade', cls: 'r', v: r => `<span class="mono">${U.nf(Run.speed(r), 1)} km/h</span>` }, { l: 'FC', cls: 'r', v: r => r.hr ? r.hr + (r.hrMax ? '/' + r.hrMax : '') : '—' }, { l: 'Sensação', cls: 'r', v: r => r.feel ? r.feel + '/5' : '—' }] });
})();
