/* OCEANUM — Trabalho, Carreira & Networking, Capital Profissional, Opportunity Center, Mova. */
(() => {
'use strict';
const U = OS.U, UI = OS.UI, C = OS.C, V = OS.views, L = OS.L, esc = U.esc, A = OS.act, Car = OS.Car, Mv = OS.Mv;

/* ================= TRABALHO ================= */
V.trabalho = () => {
  const p = OS.one('profile'), S = OS.all('shifts'), t = U.today(), wk = U.monday(t), ym = U.ym(t);
  const weeks = Array.from({ length: 10 }, (_, i) => U.addDays(wk, -7 * (9 - i)));
  const hW = U.sum(S.filter(s => s.date >= wk && s.date <= U.addDays(wk, 6)), Car.shiftHours), hM = U.sum(S.filter(s => U.ym(s.date) === ym), Car.shiftHours), payM = U.sum(S.filter(s => U.ym(s.date) === ym), Car.shiftPay);
  const next = U.sortBy(S.filter(s => s.date >= t), s => s.date + s.start).slice(0, 8);
  const tasks = OS.Tasks.open().filter(x => (x.ctx || []).includes('@Trabalho') || x.area === 'Trabalho');
  return UI.head('Trabalho', `${p.employer ? esc(p.employer) + (p.jobRole ? ' · ' + esc(p.jobRole) : '') : 'Define o teu trabalho atual em Definições'}${U.num(p.hourly) ? ' · ' + U.eur(p.hourly) + '/h' : ''}`, `${UI.addBtn('shifts', 'Turno')}${UI.addBtn('tasks', 'Tarefa', { ctx: ['@Trabalho'], area: 'Trabalho', status: 'Próxima' }, '')}`, 'Carreira') +
  `<div class="kpis">${UI.kpi('Horas esta semana', U.nf(hW, 1) + ' h')}${UI.kpi('Horas este mês', U.nf(hM, 1) + ' h')}${UI.kpi('Ganhos estimados (mês)', U.eur(payM), U.num(p.hourly) || S.some(s => U.num(s.rate)) ? 'horas × valor/hora' : 'define o valor/hora', { tone: 'pos' })}${UI.kpi('Próximo turno', next[0] ? U.rel(next[0].date) + ' ' + next[0].start : '—')}</div>
  ${payM ? `<div class="row gap8"><button class="btn sm" data-new="transactions" data-defs='${esc(JSON.stringify({ type: 'Receita', amount: U.r2(payM), cat: 'Salário', sub: 'Salário', desc: 'Salário ' + U.fmtYML(ym) + ' (turnos)' }))}'>${UI.ic('wallet')}Lançar salário do mês em Finanças</button><span class="mut" style="font-size:12.5px">Confirma o valor com o recibo antes de guardar.</span></div>` : ''}
  <div class="g g-main"><div class="pn"><div class="pn-h"><h3>Horas por semana</h3></div>${C.mount({ type: 'bar', labels: weeks.map(w => U.fmtDS(w)), series: [{ name: 'Horas', data: weeks.map(w => U.sum(S.filter(s => s.date >= w && s.date <= U.addDays(w, 6)), Car.shiftHours)), color: 'var(--c4)' }], fmt: v => U.nf(v, 0), empty: 'Regista turnos para ver as horas.' }, 200)}</div>
  <div class="pn"><div class="pn-h"><h3>Próximos turnos</h3></div>${next.length ? next.map(s => `<div class="li" data-edit="shifts:${s.id}" style="cursor:pointer"><span class="when">${U.fmtDS(s.date)}</span><div class="li-t"><b>${s.start}–${s.end}</b><small>${esc([s.place, s.role].filter(Boolean).join(' · '))} · ${U.nf(Car.shiftHours(s), 1)} h</small></div></div>`).join('') : UI.empty('Sem turnos marcados.')}</div></div>
  <section><div class="sech"><h2>Tarefas de trabalho</h2></div><div class="pn" style="padding:4px 16px">${tasks.map(x => OS.taskRow(x)).join('') || UI.empty('Nenhuma.')}</div></section>
  ${UI.table({ key: 'sh', coll: 'shifts', rows: U.sortBy(S, s => s.date, -1), limit: 30, cols: [{ l: 'Data', v: s => `<span class="mono">${U.fmtD(s.date)}</span>`, s: s => s.date }, { l: 'Horário', v: s => s.start + '–' + s.end }, { l: 'Local', v: s => esc(s.place || '') }, { l: 'Horas', cls: 'r', v: s => U.nf(Car.shiftHours(s), 1) }, { l: 'Valor', cls: 'r', v: s => `<span class="mono">${U.eur(Car.shiftPay(s))}</span>` }] })}`;
};

/* ================= CARREIRA ================= */
V.carreira = sub => {
  const head = UI.head('Carreira & Networking', 'Candidaturas, entrevistas, rede de contactos, experiências e metas profissionais.', `${UI.addBtn('applications', 'Candidatura')}${UI.addBtn('contacts', 'Contacto', null, '')}`, 'Carreira') + UI.tabs('carreira', [['', 'Candidaturas'], ['rede', 'Networking'], ['experiencias', 'Experiências'], ['metas', 'Metas profissionais']], sub);
  const t = U.today();
  if (sub === 'rede') {
    const Cn = OS.all('contacts'), act = Cn.filter(c => c.last && U.diff(t, c.last) <= 90), due = Cn.filter(c => c.next && c.next <= t);
    return head + `<div class="kpis">${UI.kpi('Contactos', Cn.length)}${UI.kpi('Ativos (90 dias)', act.length, Cn.length ? U.pct(act.length / Cn.length) : '')}${UI.kpi('Follow-ups pendentes', due.length, '', { tone: due.length ? 'warn' : '' })}${UI.kpi('Relações fortes', Cn.filter(c => U.num(c.strength) >= 4).length, 'força 4–5')}</div>
    ${due.length ? `<div class="pn"><div class="pn-h"><h3>Contactar agora</h3></div>${due.map(c => `<div class="li"><div class="li-t click" data-edit="contacts:${c.id}"><b>${esc(c.name)}</b><small>${esc([c.role, c.org].filter(Boolean).join(' · '))} · último contacto ${c.last ? U.rel(c.last) : '—'}</small></div><button class="btn sm" data-act="contactDone" data-id="${c.id}">Contactado hoje</button></div>`).join('')}</div>` : ''}
    ${UI.table({ key: 'ct', coll: 'contacts', rows: U.sortBy(Cn, c => c.last || '', -1), cols: [{ l: 'Nome', v: c => `<b style="font-weight:520">${esc(c.name)}</b>`, s: c => c.name }, { l: 'Descrição', v: c => esc([c.role, c.org].filter(Boolean).join(' · ')), cls: 'wrap' }, { l: 'Contacto', v: c => esc(c.contact || '') }, { l: 'Força', cls: 'r', v: c => c.strength ? '●'.repeat(c.strength) : '—', s: c => U.num(c.strength) }, { l: 'Último contacto', v: c => c.last ? `<span class="${U.diff(t, c.last) > 90 ? 'warn' : ''}">${U.fmtD(c.last)}</span>` : '—', s: c => c.last || '' }, { l: 'Follow-up', v: c => c.next ? `<span class="${c.next <= t ? 'neg' : ''}">${U.fmtD(c.next)}</span>` : '—', s: c => c.next || '9' }, { l: '', v: c => `<button class="btn xs ghost" data-act="contactDone" data-id="${c.id}">Contactado</button>` }] })}`;
  }
  if (sub === 'experiencias') {
    const E = U.sortBy(OS.all('experiences'), e => e.start || '', -1);
    return head + `<div class="row gap8">${UI.addBtn('experiences', 'Nova experiência')}</div>${E.length ? `<div class="pn">${E.map(e => `<div class="gcard" style="grid-template-columns:1fr auto"><div class="click" data-edit="experiences:${e.id}" style="cursor:pointer"><b>${esc(e.title)}</b><div class="gmeta">${UI.badge(e.kind, 'out')}${e.org ? `<span>${esc(e.org)}</span>` : ''}${(e.skills || []).map(s => UI.badge(s, 'acc')).join('')}</div>${e.desc ? `<div class="tx2" style="font-size:13px;margin-top:6px;white-space:pre-wrap">${esc(e.desc)}</div>` : ''}</div><span class="mono mut" style="font-size:12px">${e.start ? U.fmtYM(U.ym(e.start)) : ''}${e.end ? ' – ' + U.fmtYM(U.ym(e.end)) : e.start ? ' – atual' : ''}</span></div>`).join('')}</div>` : UI.empty('Regista empregos, voluntariado, eventos, palestras e competições. Tudo conta para o capital profissional.')}`;
  }
  if (sub === 'metas') {
    const G = OS.all('goals').filter(g => g.cat === 'Trabalho' || g.cat === 'Empresa');
    return head + `<div class="row gap8">${UI.addBtn('goals', 'Meta profissional', { cat: 'Trabalho' })}</div><div class="pn">${G.map(g => { const i = OS.Goal.info(g); return `<div class="gcard"><div class="click" data-edit="goals:${g.id}" style="cursor:pointer"><b>${esc(g.title)}</b><div class="gmeta">${UI.badge(i.st[0], i.st[1])}${g.due ? `<span>prazo ${U.fmtD(g.due)}</span>` : ''}</div></div><div class="gp">${UI.bar(i.p, '', i.exp)}</div></div>`; }).join('') || UI.empty('Sem metas profissionais.')}</div>
    <section><div class="sech"><h2>Competências e certificações</h2><a class="btn ghost sm" href="#aprendizagem">Aprendizagem ${UI.ic('right')}</a></div><div class="pn">${OS.all('skills').map(s => `<div class="bar-row"><span class="l">${esc(s.name)}</span>${UI.bar((U.num(s.level) || 0) / 5, '', (U.num(s.targetLevel) || 5) / 5)}<span class="v">${s.level || 0}/5 → ${s.targetLevel || 5}</span></div>`).join('') || UI.empty('Sem competências.')}</div></section>`;
  }
  const Ap = OS.all('applications'), sent = Ap.filter(a => a.status !== 'Por enviar'), resp = sent.filter(a => !['Enviada', 'Sem resposta'].includes(a.status)), iv = Ap.filter(a => ['Entrevista', 'Proposta', 'Aceite'].includes(a.status));
  const ST = ['Por enviar', 'Enviada', 'Entrevista', 'Proposta', 'Aceite', 'Recusada', 'Sem resposta'];
  return head + `<div class="kpis">${UI.kpi('Enviadas', sent.length)}${UI.kpi('Taxa de resposta', sent.length ? U.pct(resp.length / sent.length) : '—')}${UI.kpi('Entrevistas', iv.length)}${UI.kpi('Próxima entrevista', (() => { const n = U.sortBy(Ap.filter(a => a.interview && a.interview >= t), a => a.interview)[0]; return n ? U.fmtDS(n.interview) + ' · ' + esc(n.company) : '—'; })())}</div>
  <div class="kan">${ST.map(s => { const it = Ap.filter(a => (a.status || 'Por enviar') === s); return `<div class="kcol"><h4>${s}<span class="mono">${it.length}</span></h4>${it.map(a => `<div class="kcard" data-edit="applications:${a.id}"><b>${esc(a.company)}</b><div class="meta">${a.role ? `<span>${esc(a.role)}</span>` : ''}${a.date ? `<span>${U.fmtDS(a.date)}</span>` : ''}${a.interview ? UI.badge('entrevista ' + U.fmtDS(a.interview), 'warn') : ''}</div>${a.next ? `<span class="tx2" style="font-size:12px">→ ${esc(a.next)}</span>` : ''}</div>`).join('')}</div>`; }).join('')}</div>`;
};
A.contactDone = b => { const c = OS.get('contacts', b.dataset.id); if (!c) return; OS.upd('contacts', c.id, { last: U.today(), next: c.next && c.next <= U.today() ? U.addDays(U.today(), 30) : c.next }); UI.toast('Contacto registado · próximo follow-up em 30 dias', 'pos'); };

/* ================= CAPITAL PROFISSIONAL ================= */
V.capital = () => {
  const c = Car.capital(), t = U.today(), months = Array.from({ length: 12 }, (_, i) => U.addMonths(U.ym(t), i - 11));
  const series = months.map(m => { const end = m === U.ym(t) ? t : m + '-' + U.dim(m); return Car.capital(end).score; });
  const prev = Car.capital(U.addDays(t, -90));
  const dims = Object.entries(c.dims), weakest = U.sortBy(dims, d => d[1]).slice(0, 3);
  const tips = { 'Competências': 'Sobe um nível numa competência: completa a etapa seguinte da trilha em Aprendizagem.', 'Certificações': 'Escolhe uma certificação e cria-a como item "Certificação" com prazo.', 'Experiência': 'Regista a experiência atual (emprego, voluntariado) com data de início.', 'Rede': 'Contacta 2 pessoas esta semana e marca follow-ups.', 'Projetos & eventos': 'Vai a um evento ou palestra este mês e regista-o em Experiências.', 'Aprendizagem': 'Sessões ligadas a competências contam aqui: usa o Modo Foco com a competência.', 'Mercado': 'Envia uma candidatura ou submete uma oportunidade do Opportunity Center.' };
  return UI.head('Capital Profissional', 'Tudo o que aumenta a tua capacidade profissional ao longo do tempo, num só indicador de 0 a 1000. Cada dimensão satura num alvo realista para a tua fase (estudante do 1.º ano).', '', 'Carreira') +
  `<div class="g g-side"><div class="pn"><div class="eyebrow">Capital atual</div><div class="big-num" style="font-size:52px;margin:6px 0">${U.nf(c.score)}</div><div class="row gap8">${UI.trend(c.score, prev.score)}<span class="mut" style="font-size:12.5px">em 90 dias (${U.nf(prev.score)} → ${U.nf(c.score)})</span></div>
    <div class="divider"></div><dl class="kv"><dt>Competências</dt><dd>${c.skills}</dd><dt>Certificações</dt><dd>${c.certs}</dd><dt>Meses de experiência</dt><dd>${U.nf(c.months, 1)}</dd><dt>Contactos (ativos)</dt><dd>${c.contacts} (${c.active})</dd><dt>Candidaturas / entrevistas</dt><dd>${c.apps} / ${c.interviews}</dd><dt>Projetos concluídos</dt><dd>${c.projects}</dd><dt>Eventos e palestras</dt><dd>${c.events}</dd><dt>Horas de aprendizagem</dt><dd>${U.nf(c.learnH, 1)}</dd></dl></div>
  <div class="pn"><div class="pn-h"><h3>Perfil por dimensão</h3><span class="mut" style="font-size:12px">agora vs há 90 dias</span></div>${C.mount({ type: 'radar', axes: dims.map(d => d[0]), series: [{ name: 'Agora', data: dims.map(d => d[1]) }, { name: 'Há 90 dias', data: Object.values(prev.dims), color: 'var(--mut)' }] }, 320)}</div></div>
  <div class="g g-main"><div class="pn"><div class="pn-h"><h3>Evolução · 12 meses</h3></div>${C.mount({ type: 'line', labels: months.map(U.fmtYM), series: [{ name: 'Capital', data: series }], fmt: v => U.nf(v) }, 220)}</div>
  <div class="pn"><div class="pn-h"><h3>Para subir mais depressa</h3></div>${weakest.map(([k, v]) => `<div class="ins">${UI.ic('arrowUp', 'acc')}<div><b style="font-weight:540">${k} · ${U.pct(v)}</b><div class="tx2" style="font-size:13px">${tips[k]}</div></div></div>`).join('')}</div></div>
  <div class="pn">${dims.map(([k, v]) => `<div class="bar-row" style="grid-template-columns:160px 1fr 60px"><span class="l">${k}</span>${UI.bar(v, v >= .66 ? 'pos' : '')}<span class="v">${U.pct(v)}</span></div>`).join('')}</div>`;
};

/* ================= OPORTUNIDADES ================= */
V.oportunidades = () => {
  const O = OS.all('opps'), t = U.today(), f = OS.ui.oppK || '', vis = O.filter(o => !f || o.kind === f);
  const open = O.filter(o => !['Aceite', 'Recusada', 'Perdida'].includes(o.status)), soon = open.filter(o => o.deadline && o.deadline >= t && U.diff(o.deadline, t) <= 14 && !['Submetida', 'Em avaliação'].includes(o.status));
  const ST = ['Identificada', 'A preparar', 'Submetida', 'Em avaliação', 'Aceite', 'Recusada', 'Perdida'];
  const kinds = [...new Set(O.map(o => o.kind).filter(Boolean))];
  return UI.head('Opportunity Center', 'Cursos, certificações, eventos, palestras, programas da UA, estágios, empregos, competições, bolsas e oportunidades de negócio. Cada uma com prazo e próxima ação.', UI.addBtn('opps', 'Nova oportunidade'), 'Carreira') +
  `<div class="kpis">${UI.kpi('Abertas', open.length)}${UI.kpi('Prazo em 14 dias', soon.length, '', { tone: soon.length ? 'warn' : '' })}${UI.kpi('Submetidas', O.filter(o => ['Submetida', 'Em avaliação'].includes(o.status)).length)}${UI.kpi('Aceites', O.filter(o => o.status === 'Aceite').length, '', { tone: 'pos' })}${UI.kpi('Perdidas por prazo', O.filter(o => o.status === 'Perdida').length)}</div>
  ${kinds.length > 1 ? `<div class="row gap8">${UI.chip('Todas', 'oppK', !f, 'data-v=""')}${kinds.map(k => UI.chip(k, 'oppK', f === k, `data-v="${k}"`)).join('')}</div>` : ''}
  ${O.length ? `<div class="kan">${ST.map(s => { const it = U.sortBy(vis.filter(o => (o.status || 'Identificada') === s), o => o.deadline || '9'); return `<div class="kcol"><h4>${s}<span class="mono">${it.length}</span></h4>${it.map(o => { const d = o.deadline ? U.diff(o.deadline, t) : null; return `<div class="kcard" data-edit="opps:${o.id}"><span class="eyebrow">${esc(o.kind || '')}</span><b>${esc(o.name)}</b>${o.inst ? `<span class="mut" style="font-size:12px">${esc(o.inst)}</span>` : ''}<div class="meta">${o.deadline ? UI.badge(d < 0 ? 'prazo passou' : 'prazo ' + U.fmtDS(o.deadline), d != null && d >= 0 && d <= 7 ? 'neg' : d != null && d <= 21 && d >= 0 ? 'warn' : '') : ''}</div>${o.next ? `<span class="tx2" style="font-size:12px">→ ${esc(o.next)}</span>` : ''}${o.link ? `<a class="acc" style="font-size:12px" href="${esc(o.link)}" target="_blank" rel="noopener">abrir link</a>` : ''}</div>`; }).join('')}</div>`; }).join('')}</div>` : UI.empty('Regista a primeira oportunidade: programa de voluntariado da UA, estágio de verão, curso de Excel, bolsa, evento de networking em Aveiro…', UI.addBtn('opps', 'Adicionar oportunidade', null, ''))}`;
};
A.oppK = b => OS.setUI('oppK', b.dataset.v);

/* ================= MOVA ================= */
const MT = [['', 'Visão'], ['vendas', 'Vendas'], ['despesas', 'Despesas'], ['clientes', 'Clientes'], ['produtos', 'Produtos'], ['marketing', 'Marketing'], ['operacoes', 'Operações'], ['perfil', 'Perfil']];
V.mova = sub => {
  const mv = OS.one('mova');
  return UI.head(esc(mv.name || 'Mova'), mv.what ? esc(mv.what) : 'Sistema da empresa: receitas, custos, margens, clientes, produtos, marketing e operações.', `${UI.addBtn('mvsales', 'Venda')}${UI.addBtn('mvexp', 'Despesa', null, '')}`, 'Empresa') + UI.tabs('mova', MT, sub) + (MV[sub || 'visao'] || MV.visao)();
};
const MV = {};
MV.visao = () => {
  const mv = OS.one('mova'), t = U.today(), ym = U.ym(t), m = Mv.month(ym), pm = Mv.month(U.addMonths(ym, -1)), months = Array.from({ length: 12 }, (_, i) => U.addMonths(ym, i - 11)), md = months.map(Mv.month);
  const cl = OS.all('mvclients'), act = cl.filter(c => c.status === 'Ativo');
  const byProd = Object.entries(U.groupBy(OS.all('mvsales').filter(s => s.status !== 'Cancelado' && s.date >= U.addMonths(ym, -2) + '-01'), s => (OS.get('mvproducts', s.product) || {}).name || s.desc || 'Sem produto')).map(([l, a]) => ({ l, v: U.sum(a, Mv.rev) })).sort((a, b) => b.v - a.v);
  const byCl = Object.entries(U.groupBy(OS.all('mvsales').filter(s => s.status !== 'Cancelado'), s => s.client)).map(([id, a]) => ({ c: OS.get('mvclients', id), v: U.sum(a, Mv.rev), n: a.length })).filter(x => x.c).sort((a, b) => b.v - a.v).slice(0, 5);
  const tgt = U.num(mv.revenueTarget), day = +t.slice(8);
  const tasks = OS.Tasks.open().filter(x => (x.ctx || []).includes('@Mova') || x.area === 'Mova');
  return `${!mv.what ? `<div class="pn tint"><div class="row between gap12"><div><b>Define o que é a Mova</b><div class="tx2" style="font-size:13px;margin-top:2px">Não encontrei informação sobre a Mova no teu Notion nem nesta conversa, por isso não inventei nada. Preenche o perfil (o que vende, a quem, fase) e as metas: os alertas e o dashboard adaptam-se.</div></div><a class="btn pri" href="#mova.perfil">Preencher perfil</a></div></div>` : ''}
  <div class="kpis">${UI.kpi('Receita do mês', U.eur(m.rev), tgt ? U.pct(m.rev / tgt) + ' da meta de ' + U.eur(tgt, { dec: 0 }) : UI.trend(m.rev, pm.rev) + ' vs mês anterior')}${UI.kpi('Custos', U.eur(m.cogs + m.opex), 'produto ' + U.eurK(m.cogs) + ' · operação ' + U.eurK(m.opex))}${UI.kpi('Lucro', U.eur(m.profit), m.rev ? 'margem ' + U.pct(m.margin) : '', { tone: m.profit >= 0 ? 'pos' : 'neg' })}${UI.kpi('Clientes ativos', act.length, cl.filter(c => c.status === 'Lead' || c.status === 'Proposta').length + ' em pipeline')}${UI.kpi('Ticket médio', m.n ? U.eur(m.ticket) : '—', m.n + ' vendas')}${UI.kpi('CAC', m.cac != null ? U.eur(m.cac) : '—', 'marketing ÷ novos clientes')}${UI.kpi('A receber', U.eur(m.pending), '', { tone: m.pending ? 'warn' : '' })}</div>
  ${tgt ? `<div class="pn"><div class="row between" style="margin-bottom:8px;font-size:13px"><span>Meta de receita de ${U.fmtYML(ym)}</span><span class="mono">${U.eur(m.rev, { dec: 0 })} / ${U.eur(tgt, { dec: 0 })}</span></div>${UI.bar(m.rev / tgt, m.rev >= tgt ? 'pos' : '', day / U.dim(ym))}</div>` : ''}
  <div class="g g-main"><div class="pn"><div class="pn-h"><h3>Receita e custos · 12 meses</h3></div>${C.mount({ type: 'bar', labels: months.map(U.fmtYM), series: [{ name: 'Receita', data: md.map(x => x.rev), color: 'var(--pos)' }, { name: 'Custos', data: md.map(x => x.cogs + x.opex), color: 'var(--c4)' }], fmt: U.eurK, empty: 'Regista vendas e despesas da Mova.' }, 220)}</div>
  <div class="pn"><div class="pn-h"><h3>Lucro mensal</h3></div>${C.mount({ type: 'bar', labels: months.map(U.fmtYM), series: [{ name: 'Lucro', data: md.map(x => x.rev || x.opex ? x.profit : null), color: v => v >= 0 ? 'var(--pos)' : 'var(--neg)' }], fmt: U.eurK }, 220)}</div></div>
  <div class="g g3"><div class="pn"><div class="pn-h"><h3>Produtos (3 meses)</h3></div>${C.mount({ type: 'donut', data: byProd, max: 5 }, 170)}</div>
  <div class="pn"><div class="pn-h"><h3>Melhores clientes</h3></div>${byCl.length ? byCl.map(x => `<div class="li" data-edit="mvclients:${x.c.id}" style="cursor:pointer"><div class="li-t"><b>${esc(x.c.name)}</b><small>${x.n} compra(s)</small></div><span class="mono">${U.eur(x.v, { dec: 0 })}</span></div>`).join('') : UI.empty('Sem vendas com cliente.')}</div>
  <div class="pn"><div class="pn-h"><h3>Operações</h3><a class="more" href="#mova.operacoes">${UI.ic('right')}</a></div>${tasks.slice(0, 5).map(x => OS.taskRow(x, { focus: false })).join('') || UI.empty('Sem tarefas @Mova.')}</div></div>
  ${m.profit > 0 ? `<div class="row gap8"><button class="btn sm" data-new="transactions" data-defs='${esc(JSON.stringify({ type: 'Receita', cat: 'Mova', sub: 'Distribuição de lucro', desc: 'Mova · distribuição ' + U.fmtYML(ym) }))}'>${UI.ic('wallet')}Distribuir lucro para as finanças pessoais</button><span class="mut" style="font-size:12.5px">Mantém separadas as contas da empresa e as pessoais: só o que distribuis entra no teu orçamento.</span></div>` : ''}`;
};
MV.vendas = () => { const S = U.sortBy(OS.all('mvsales'), s => s.date, -1); return UI.table({ key: 'mvs', coll: 'mvsales', rows: S, limit: 50, empty: 'Sem vendas.', emptyAct: UI.addBtn('mvsales', 'Registar venda', null, ''), cols: [{ l: 'Data', v: s => `<span class="mono">${U.fmtD(s.date)}</span>`, s: s => s.date }, { l: 'Cliente', v: s => esc((OS.get('mvclients', s.client) || {}).name || '—') }, { l: 'Produto', v: s => esc((OS.get('mvproducts', s.product) || {}).name || s.desc || '—'), cls: 'wrap' }, { l: 'Qtd.', cls: 'r', v: s => s.qty || 1 }, { l: 'Receita', cls: 'r', v: s => `<span class="mono">${U.eur(Mv.rev(s))}</span>`, s: Mv.rev }, { l: 'Margem', cls: 'r', v: s => { const r = Mv.rev(s); return r ? `<span class="mono">${U.pct((r - Mv.cost(s)) / r)}</span>` : '—'; } }, { l: 'Pagamento', v: s => UI.badge(s.status, s.status === 'Pago' ? 'pos' : s.status === 'Pendente' ? (s.dueDate && s.dueDate < U.today() ? 'neg' : 'warn') : '') }] }); };
MV.despesas = () => UI.table({ key: 'mve', coll: 'mvexp', rows: U.sortBy(OS.all('mvexp'), e => e.date, -1), limit: 50, empty: 'Sem despesas.', emptyAct: UI.addBtn('mvexp', 'Registar despesa', null, ''), cols: [{ l: 'Data', v: e => `<span class="mono">${U.fmtD(e.date)}</span>`, s: e => e.date }, { l: 'Descrição', v: e => esc(e.desc || '—'), cls: 'wrap' }, { l: 'Categoria', v: e => esc(e.cat) }, { l: 'Recorrente', v: e => e.recurring ? UI.badge('sim', 'out') : '' }, { l: 'Valor', cls: 'r', v: e => `<span class="mono">${U.eur(e.amount)}</span>`, s: e => U.num(e.amount) }] });
MV.clientes = () => { const CL = OS.all('mvclients'); const ST = ['Lead', 'Proposta', 'Ativo', 'Inativo', 'Perdido']; return `<div class="row gap8">${UI.addBtn('mvclients', 'Novo cliente')}</div><div class="kan">${ST.map(s => { const it = CL.filter(c => (c.status || 'Lead') === s); return `<div class="kcol"><h4>${s}<span class="mono">${it.length}</span></h4>${it.map(c => { const tot = U.sum(OS.all('mvsales').filter(x => x.client === c.id && x.status !== 'Cancelado'), Mv.rev); return `<div class="kcard" data-edit="mvclients:${c.id}"><b>${esc(c.name)}</b><div class="meta">${c.source ? `<span>${esc(c.source)}</span>` : ''}${tot ? `<span class="mono">${U.eur(tot, { dec: 0 })}</span>` : ''}${c.next ? UI.badge('contactar ' + U.fmtDS(c.next), c.next <= U.today() ? 'warn' : '') : ''}</div></div>`; }).join('')}</div>`; }).join('')}</div>`; };
MV.produtos = () => UI.table({ key: 'mvp', coll: 'mvproducts', rows: OS.all('mvproducts'), empty: 'Sem produtos ou serviços.', emptyAct: UI.addBtn('mvproducts', 'Adicionar produto', null, ''), cols: [{ l: 'Produto / serviço', v: p => `<b style="font-weight:520">${esc(p.name)}</b>${p.active === false ? ' ' + UI.badge('inativo') : ''}`, s: p => p.name }, { l: 'Preço', cls: 'r', v: p => `<span class="mono">${U.eur(p.price)}</span>` }, { l: 'Custo', cls: 'r', v: p => `<span class="mono">${U.eur(p.cost)}</span>` }, { l: 'Margem', cls: 'r', v: p => U.num(p.price) ? `<span class="mono">${U.pct((U.num(p.price) - U.num(p.cost)) / U.num(p.price))}</span>` : '—' }, { l: 'Vendido (total)', cls: 'r', v: p => `<span class="mono">${U.eur(U.sum(OS.all('mvsales').filter(s => s.product === p.id), Mv.rev), { dec: 0 })}</span>` }] });
MV.marketing = () => { const M = OS.all('mvmkt'); const by = Object.entries(U.groupBy(M, m => m.channel || 'Outro')).map(([l, a]) => ({ l, cost: U.sum(a, x => x.cost), leads: U.sum(a, x => x.leads), conv: U.sum(a, x => x.conv) })); return `<div class="row gap8">${UI.addBtn('mvmkt', 'Nova ação')}</div>${by.length ? `<div class="pn"><div class="pn-h"><h3>Desempenho por canal</h3></div><table class="cmp"><thead><tr><th>Canal</th><th>Custo</th><th>Leads</th><th>Conversões</th><th>Conversão</th><th>Custo por cliente</th></tr></thead><tbody>${by.map(b => `<tr><td>${esc(b.l)}</td><td class="mono">${U.eur(b.cost)}</td><td class="mono">${b.leads}</td><td class="mono">${b.conv}</td><td class="mono">${b.leads ? U.pct(b.conv / b.leads) : '—'}</td><td class="mono">${b.conv ? U.eur(b.cost / b.conv) : '—'}</td></tr>`).join('')}</tbody></table></div>` : ''}${UI.table({ key: 'mvm', coll: 'mvmkt', rows: U.sortBy(M, m => m.date, -1), empty: 'Sem ações de marketing.', cols: [{ l: 'Data', v: m => U.fmtD(m.date), s: m => m.date }, { l: 'Canal', v: m => esc(m.channel || '') }, { l: 'Ação', v: m => esc(m.action), cls: 'wrap' }, { l: 'Custo', cls: 'r', v: m => U.eur(m.cost) }, { l: 'Leads', cls: 'r', v: m => m.leads || 0 }, { l: 'Conversões', cls: 'r', v: m => m.conv || 0 }] })}`; };
MV.operacoes = () => { const T = OS.all('tasks').filter(x => (x.ctx || []).includes('@Mova') || x.area === 'Mova'), P = OS.all('projects').filter(p => p.type === 'Empresarial'); return `<div class="row gap8">${UI.addBtn('tasks', 'Tarefa', { ctx: ['@Mova'], area: 'Mova', status: 'Próxima' })}${UI.addBtn('projects', 'Projeto empresarial', { type: 'Empresarial' }, '')}</div><div class="g g2"><div class="pn"><div class="pn-h"><h3>Tarefas</h3></div>${T.filter(x => x.status !== 'Feita').map(x => OS.taskRow(x)).join('') || UI.empty('Sem tarefas abertas.')}</div><div class="pn"><div class="pn-h"><h3>Projetos empresariais</h3></div>${P.map(p => { const i = OS.Proj.info(p); return `<div class="li" data-edit="projects:${p.id}" style="cursor:pointer"><div class="li-t"><b>${esc(p.name)}</b><small>${p.status} · ${i.done.length}/${i.tasks.length} tarefas</small></div><span class="mono">${Math.round(i.prog * 100)}%</span></div>`; }).join('') || UI.empty('Sem projetos.')}</div></div>`; };
MV.perfil = () => { const mv = OS.one('mova'); const F = [['name', 'Nome', 'text'], ['stage', 'Fase', 'sel', ['Ideia', 'Validação', 'Primeiros clientes', 'Operação', 'Crescimento']], ['what', 'O que é', 'area'], ['offer', 'O que vende', 'area'], ['customer', 'Cliente ideal', 'area'], ['founded', 'Início de atividade', 'date'], ['revenueTarget', 'Meta de receita mensal (€)', 'num'], ['clientsTarget', 'Meta de clientes ativos', 'num'], ['marginTarget', 'Margem alvo (%)', 'num'], ['notes', 'Notas estratégicas', 'area']];
  return `<div class="pn"><div class="fgrid">${F.map(([k, l, t, o]) => `<div class="fld ${t === 'area' ? 'wide' : ''}"><label for="mv_${k}">${l}</label>${t === 'area' ? `<textarea id="mv_${k}" rows="3" data-bind="mova.${k}" data-fk="mv${k}">${esc(mv[k])}</textarea>` : t === 'sel' ? `<select id="mv_${k}" data-bind="mova.${k}">${o.map(x => `<option${mv[k] === x ? ' selected' : ''}>${x}</option>`).join('')}</select>` : `<input id="mv_${k}" type="${t === 'num' ? 'number' : t}" value="${esc(mv[k])}" data-bind="mova.${k}" data-fk="mv${k}">`}</div>`).join('')}</div></div>
  <div class="note">Contexto do teu Notion: tinhas a meta "Abrir minha Empresa" (Crumbel Royal Co.) e, no Dominus, marcos para estruturar e lançar a Crumbel Royal. Se a Mova for essa empresa ou outra, escreve-o aqui.</div>`; };
})();
