/* OCEANUM — Trabalho+: folgas, horário semanal, horário a partir de FOTO (IA lê a escala e atualiza só os dias futuros
   do período indicado) e projetos de trabalho (ligados aos Projetos e Tarefas do Oceanum). */
(() => {
'use strict';
const U = OS.U, UI = OS.UI, V = OS.views, A = OS.act, esc = U.esc, today = () => U.today();
const OFFK = ['Folga', 'Férias', 'Feriado', 'Baixa', 'Falta justificada'];
OS.S.dayoffs = { label: 'Folga', title: r => (r.kind || 'Folga') + ' · ' + U.fmtD(r.date), fields: [
  { k: 'date', l: 'Dia', t: 'date', req: 1 }, { k: 'kind', l: 'Tipo', t: 'sel', o: OFFK }, { k: 'note', l: 'Nota', t: 'text' }], defaults: () => ({ date: today(), kind: 'Folga' }) };
// folgas no calendário
if (OS.Cal && OS.Cal.items) { OS.Cal.src.off = ['Folgas', '#22c55e']; const _it = OS.Cal.items; OS.Cal.items = (from, to) => { const out = _it(from, to); OS.all('dayoffs').forEach(o => { if (o.date >= from && o.date <= to) out.push({ date: o.date, title: '' + (o.kind || 'Folga'), src: 'off', edit: 'dayoffs:' + o.id }); }); return out.sort((a, b) => (a.date + (a.start || '99')).localeCompare(b.date + (b.start || '99'))); }; }
const dayInfo = d => ({ sh: U.sortBy(OS.all('shifts').filter(s => s.date === d), s => s.start || ''), off: OS.all('dayoffs').find(o => o.date === d) });
const hrs = s => OS.Car && OS.Car.shiftHours ? OS.Car.shiftHours(s) : 0;

/* abas do Trabalho */
const TT = [['', 'Resumo'], ['horario', 'Horário & folgas'], ['foto', 'Importar escala (foto)'], ['projetos', 'Projetos de trabalho']];
OS.on('ready', () => { const o = V.trabalho; if (!o || o._ws) return; V.trabalho = sub => { const k = TT.some(t => t[0] === (sub || '')) ? (sub || '') : '', base = o(), i = base.indexOf('</header>') + 9, head = base.slice(0, i), tabs = UI.tabs('trabalho', TT, k);
  return k ? head + tabs + W[k]() : head + tabs + weekStrip() + base.slice(i); }; V.trabalho._ws = 1; });
const W = {};
const weekStrip = () => { const t = today(), days = U.range(t, U.addDays(t, 6));
  return `<div class="ws-strip">${days.map(d => { const { sh, off } = dayInfo(d); return `<a class="ws-d ${off ? 'off' : sh.length ? 'work' : ''} ${d === t ? 'today' : ''}" href="#trabalho.horario"><small>${d === t ? 'Hoje' : U.WDS[U.parse(d).getDay()]} ${+d.slice(8)}</small><b>${off ? esc(off.kind || 'Folga') : sh.length ? sh.map(s => s.start + '–' + s.end).join('<br>') : '—'}</b></a>`; }).join('')}</div>`; };
W.horario = () => { const wk0 = U.addDays(U.monday(today()), 7 * (+OS.ui.wsW || 0)), days = U.range(wk0, U.addDays(wk0, 13)), t = today();
  const offN = OS.all('dayoffs').filter(o => o.date >= t.slice(0, 4) + '-01-01' && o.date <= t.slice(0, 4) + '-12-31');
  return `<div class="row gap8" style="flex-wrap:wrap;align-items:center;margin-bottom:10px"><button class="icon-btn" data-act="wsW" data-d="-1" aria-label="Anterior">${UI.ic('left')}</button><b>${U.fmtDS(days[0])} – ${U.fmtDS(days[13])}</b><button class="icon-btn" data-act="wsW" data-d="1" aria-label="Seguinte">${UI.ic('right')}</button><span class="grow"></span>${UI.addBtn('shifts', 'Turno', null, 'sm')}${UI.addBtn('dayoffs', 'Folga', null, 'sm')}<a class="btn sm pri" href="#trabalho.foto">Importar escala</a></div>
  <div class="kpis">${UI.kpi('Folgas este ano', offN.filter(o => (o.kind || 'Folga') === 'Folga').length)}${UI.kpi('Férias', offN.filter(o => o.kind === 'Férias').length + ' dias')}${UI.kpi('Horas nestas 2 semanas', U.nf(U.sum(OS.all('shifts').filter(s => s.date >= days[0] && s.date <= days[13]), hrs), 1) + ' h')}${UI.kpi('Próxima folga', (() => { const n = U.sortBy(OS.all('dayoffs').filter(o => o.date >= t), o => o.date)[0]; return n ? U.fmtDS(n.date) : '—'; })())}</div>
  <div class="ws-cal">${days.map(d => { const { sh, off } = dayInfo(d), past = d < t; return `<div class="ws-c ${off ? 'off' : sh.length ? 'work' : 'free'} ${d === t ? 'today' : ''} ${past ? 'past' : ''}"><div class="ws-h"><b>${U.WDS[U.parse(d).getDay()]} ${+d.slice(8)}</b>${d === t ? '<span class="bdg acc">hoje</span>' : ''}</div>
    ${off ? `<div class="ws-off click" data-edit="dayoffs:${off.id}">${esc(off.kind || 'Folga')}${off.note ? `<small>${esc(off.note)}</small>` : ''}</div>` : ''}${sh.map(s => `<div class="ws-sh click" data-edit="shifts:${s.id}"><b>${s.start}–${s.end}</b><small>${esc([s.place, s.role, s.src === 'foto' ? 'da escala' : ''].filter(Boolean).join(' · '))}</small></div>`).join('')}
    ${!off && !sh.length ? `<small class="mut">${past ? '—' : 'sem turno'}</small>` : ''}${past ? '' : `<div class="ws-a">${off ? '' : `<button class="btn xs ghost" data-act="wsOff" data-d="${d}">Folga</button>`}<button class="btn xs ghost" data-new="shifts" data-defs='${esc(JSON.stringify({ date: d }))}'>+ Turno</button></div>`}</div>`; }).join('')}</div>`; };
A.wsW = b => OS.setUI('wsW', (+OS.ui.wsW || 0) + +b.dataset.d * 2);
A.wsOff = b => { const d = b.dataset.d; OS.add('dayoffs', { date: d, kind: 'Folga' }); OS.all('shifts').filter(s => s.date === d).forEach(s => OS.del('shifts', s.id)); UI.toast('Folga marcada em ' + U.fmtD(d), 'pos'); };

/* ---------- importar escala por foto ---------- */
let IM = { files: [], busy: false, err: '', res: null };
const shrink = f => new Promise((res, rej) => { const r = new FileReader(); r.onload = () => { const im = new Image(); im.onload = () => { const k = Math.min(1, 1800 / Math.max(im.width, im.height)), c = document.createElement('canvas'); c.width = Math.round(im.width * k); c.height = Math.round(im.height * k); c.getContext('2d').drawImage(im, 0, 0, c.width, c.height); res({ mime: 'image/jpeg', data: c.toDataURL('image/jpeg', .86).split(',')[1], url: c.toDataURL('image/jpeg', .5) }); }; im.onerror = rej; im.src = r.result; }; r.onerror = rej; r.readAsDataURL(f); });
W.foto = () => { const p = OS.one('profile'), hasAI = OS.AI && OS.AI.key && OS.AI.key(), t = today(), from = OS.ui.wsFrom || t, to = OS.ui.wsTo || U.addDays(t, 13);
  return `${hasAI ? '' : `<div class="pn">${OS.AI && OS.AI.setup ? OS.AI.setup('') : ''}</div>`}<div class="pn"><div class="pn-h"><h3>Importar a escala a partir de foto</h3></div>
    <p class="mut" style="margin:0 0 10px">Tira foto (ou print) da escala que o teu trabalho envia. A IA lê os teus turnos e folgas e atualiza a tua semana — <b>só os dias de hoje em diante</b> e só dentro do período que escolheres. O que já passou nunca é alterado.</p>
    <div class="ws-form"><label>O teu nome na escala<input class="field" data-bind="profile.schedName" value="${esc(p.schedName || p.short || 'Ryan')}" placeholder="ex.: Ryan M."></label><label>De<input class="field" type="date" data-uiv="wsFrom" value="${from}" min="${t}"></label><label>Até<input class="field" type="date" data-uiv="wsTo" value="${to}" min="${from}"></label>
      <label>Local (opcional)<input class="field" data-bind="profile.schedPlace" value="${esc(p.schedPlace || '')}" placeholder="ex.: Loja Aveiro"></label></div>
    <div class="row gap8" style="flex-wrap:wrap;margin-top:10px"><label class="btn">Escolher foto(s)<input type="file" accept="image/*" multiple id="wsFile" hidden></label><label class="btn ghost">Tirar foto<input type="file" accept="image/*" capture="environment" id="wsCam" hidden></label>${IM.files.length ? `<button class="btn pri" data-act="wsRead" ${IM.busy || !hasAI ? 'disabled' : ''}>${IM.busy ? 'A ler a escala…' : 'Ler escala com IA'}</button><button class="btn ghost" data-act="wsClear">Limpar</button>` : ''}</div>
    ${IM.files.length ? `<div class="ws-thumbs">${IM.files.map(f => `<img src="${f.url}" alt="escala">`).join('')}</div>` : ''}${IM.err ? `<p class="neg">${esc(IM.err)}</p>` : ''}</div>
  ${IM.res ? (() => { const R = IM.res.filter(x => x.date >= from && x.date <= to && x.date >= t); return `<div class="pn"><div class="pn-h"><h3>Confirma o que a IA leu (${R.length} dias)</h3></div>${R.length ? `<div class="list">${R.map((x, i) => `<div class="li"><span class="when">${U.WDS[U.parse(x.date).getDay()]} ${U.fmtDS(x.date)}</span><div class="li-t"><b>${x.off ? '' + esc(x.kind || 'Folga') : esc(x.start + '–' + x.end)}</b><small>${esc([x.place, x.note].filter(Boolean).join(' · '))}${dayInfo(x.date).sh.length || dayInfo(x.date).off ? ' · substitui o que lá está' : ''}</small></div></div>`).join('')}</div><div class="row gap8" style="margin-top:10px"><button class="btn pri" data-act="wsApply">Atualizar a minha semana</button><button class="btn ghost" data-act="wsClear">Cancelar</button></div>` : '<p class="mut">Nada dentro do período escolhido (ou só dias que já passaram).</p>'}${IM.skipped ? `<small class="mut">${IM.skipped} dia(s) fora do período ou já passados foram ignorados.</small>` : ''}</div>`; })() : ''}`; };
document.addEventListener('change', async e => { if (e.target.id !== 'wsFile' && e.target.id !== 'wsCam') return; const fs = [...e.target.files].slice(0, 4); try { IM.files = IM.files.concat(await Promise.all(fs.map(shrink))).slice(0, 4); IM.err = ''; IM.res = null; } catch (er) { IM.err = 'Não consegui abrir a imagem.'; } OS.request(); });
A.wsClear = () => { IM = { files: [], busy: false, err: '', res: null }; OS.request(); };
A.wsRead = async () => { if (IM.busy || !IM.files.length) return; const p = OS.one('profile'), t = today(), from = OS.ui.wsFrom || t, to = OS.ui.wsTo || U.addDays(t, 13); IM.busy = true; IM.err = ''; OS.request();
  try { const o = await OS.AI.json([{ text: `Isto é a escala/horário de trabalho de uma equipa (foto). Lê APENAS a linha/coluna da pessoa "${p.schedName || p.short || 'Ryan'}". Hoje é ${t} (${U.WDS[U.parse(t).getDay()]}). O período pedido é de ${from} a ${to}. Converte cada dia em data completa AAAA-MM-DD (usa o mês/ano mais provável perto de hoje; se a escala só tiver dias da semana, assume a semana que contém essas datas no período pedido).
Para cada dia: se for folga/descanso/F/D/off → {"data","folga":true,"tipo":"Folga"|"Férias"|"Feriado"}; se trabalhar → {"data","entrada":"HH:MM","saida":"HH:MM","pausa_min":número ou 0}. Turnos que passam da meia-noite: saída depois da entrada no dia seguinte, mantém a data de início. Se não conseguires ler um dia, não o inventes.
JSON: {"pessoa_encontrada":true,"dias":[...],"observacoes":"…"}` }].concat(IM.files.map(f => ({ inline_data: { mime_type: f.mime, data: f.data } }))), .1);
    if (o.pessoa_encontrada === false) throw new Error(`Não encontrei "${p.schedName || p.short}" na escala. Confirma o teu nome como aparece na foto.`);
    const all = (o.dias || []).filter(x => /^\d{4}-\d{2}-\d{2}$/.test(x.data || '')).map(x => x.folga ? { date: x.data, off: true, kind: OFFK.includes(x.tipo) ? x.tipo : 'Folga' } : { date: x.data, start: (x.entrada || '').slice(0, 5), end: (x.saida || '').slice(0, 5), breakMin: +x.pausa_min || 0, place: p.schedPlace || '' }).filter(x => x.off || (/^\d\d:\d\d$/.test(x.start) && /^\d\d:\d\d$/.test(x.end)));
    if (!all.length) throw new Error('A IA não conseguiu ler dias da escala. Tenta uma foto mais nítida e direita.');
    IM.res = all; IM.skipped = all.filter(x => !(x.date >= from && x.date <= to && x.date >= t)).length; } catch (er) { IM.err = er.message || 'Erro da IA'; } IM.busy = false; OS.request(); };
A.wsApply = () => { const t = today(), from = OS.ui.wsFrom || t, to = OS.ui.wsTo || U.addDays(t, 13), R = (IM.res || []).filter(x => x.date >= from && x.date <= to && x.date >= t); if (!R.length) return;
  const dates = new Set(R.map(x => x.date)); OS.all('shifts').filter(s => dates.has(s.date) && s.date >= t).forEach(s => OS.del('shifts', s.id)); OS.all('dayoffs').filter(o => dates.has(o.date) && o.date >= t).forEach(o => OS.del('dayoffs', o.id));
  R.forEach(x => x.off ? OS.add('dayoffs', { date: x.date, kind: x.kind, src: 'foto' }, { silent: true }) : OS.add('shifts', { date: x.date, start: x.start, end: x.end, breakMin: x.breakMin, place: x.place, src: 'foto' }, { silent: true }));
  UI.toast(`Semana atualizada: ${R.filter(x => !x.off).length} turnos e ${R.filter(x => x.off).length} folgas`, 'pos'); IM = { files: [], busy: false, err: '', res: null }; OS.setUI('wsW', 0); location.hash = 'trabalho.horario'; };

/* ---------- projetos de trabalho (são Projetos do Oceanum do tipo Profissional) ---------- */
const isWork = p => ['Profissional', 'Empresarial'].includes(p.type) || p.area === 'Trabalho';
W.projetos = () => { const P = OS.all('projects').filter(isWork), act = P.filter(p => !['Concluído', 'Cancelado'].includes(p.status)), Proj = OS.Proj;
  return `<div class="row gap8" style="flex-wrap:wrap;margin-bottom:10px">${UI.addBtn('projects', 'Projeto de trabalho', { type: 'Profissional', status: 'Em andamento', area: 'Trabalho' })}<a class="btn ghost" href="#projetos">Todos os projetos</a><span class="mut" style="font-size:12.5px;align-self:center">São os mesmos projetos da aba Projetos e Tarefas — mudar aqui muda lá.</span></div>
  <div class="kpis">${UI.kpi('Em andamento', act.filter(p => p.status === 'Em andamento').length)}${UI.kpi('Tarefas abertas', U.sum(act, p => Proj.info(p).open.length))}${UI.kpi('Atrasados', act.filter(p => Proj.info(p).late).length, '', { tone: act.some(p => Proj.info(p).late) ? 'neg' : '' })}${UI.kpi('Concluídos', P.filter(p => p.status === 'Concluído').length)}</div>
  ${act.length ? `<div class="g g2">${U.sortBy(act, p => (p.due || '9') + (p.prio || '3')).map(p => { const i = Proj.info(p); return `<div class="pn wp"><div class="row between gap8"><div class="click grow" data-edit="projects:${p.id}" style="min-width:0"><span class="eyebrow">${esc(p.status)}${p.due ? ' · prazo ' + U.fmtDS(p.due) : ''}</span><b class="wp-t">${esc(p.name)}</b>${p.objective ? `<small class="mut">${esc(p.objective)}</small>` : ''}</div><span class="mono">${U.pct(i.prog)}</span></div>${UI.bar(i.prog, i.late ? 'neg' : i.prog >= 1 ? 'pos' : '')}
    <div class="list" style="margin-top:6px">${i.open.slice(0, 5).map(x => OS.taskRow ? OS.taskRow(x) : esc(x.title)).join('')}</div><form class="row gap6" data-form="quickTask" data-project="${p.id}" style="margin-top:6px"><input class="field grow" name="t" placeholder="+ tarefa neste projeto" aria-label="Nova tarefa"><button class="btn sm">${UI.ic('plus')}</button></form>${i.late ? '<small class="neg">Prazo ultrapassado</small>' : i.stalled ? `<small class="warn">Parado há ${i.idle} dias</small>` : ''}</div>`; }).join('')}</div>` : UI.empty('Sem projetos de trabalho. Cria um para separar as tarefas de cada projeto.', UI.addBtn('projects', 'Criar projeto de trabalho', { type: 'Profissional', status: 'Em andamento', area: 'Trabalho' }, ''))}`; };
OS.WorkSched = { dayInfo };
})();
